Repository elastic/elasticsearch-net, pull requests merged in 2018-05, with the labels that each got.

#3229 [DOCS] Fixes certutil command name
  src/Tests/ClientConcepts/Certificates/WorkingWithCertificates.doc.cs
Labels: Docs, Port to 6.x, v7.0.0

#3232 Change RequestConfiguration.ThrowExceptions to bool? (#3231)
  src/Elasticsearch.Net/Configuration/RequestConfiguration.cs
  src/Tests/Reproduce/GithubIssue3231.cs
Labels: Port to 5.x, Port to 6.x

#3264 Closes #3251. Rename levenstein to levenshtein.
  src/Nest/Search/Suggesters/TermSuggester/StringDistance.cs
Labels: Port to 6.x, v6.2.0

#3263 Rename jarowinkler to jaro_winkler.
  src/Nest/Search/Suggesters/TermSuggester/StringDistance.cs
Labels: Port to 6.x, v6.2.0
