Repository elastic/elasticsearch-net, pull requests merged in 2018-11, with the labels that each got.

#3461 Add missing enum values for UnassignedInformationReason
  src/Nest/Cluster/ClusterAllocationExplain/ClusterAllocationExplainResponse.cs
Labels: Bug, Port to 5.x, Port to 6.x, v5.6.5, v6.5.0

#3462 Add application privileges to Put Role API
  src/Nest/XPack/Security/Role/PutRole/IApplicationPrivileges.cs
  src/Nest/XPack/Security/Role/PutRole/IndicesPrivileges.cs
  src/Nest/XPack/Security/Role/PutRole/PutRoleRequest.cs
  src/Tests/Tests/XPack/Security/Role/PutRole/PutRoleApiTests.cs
Labels: Feature, Port to 6.x, v6.5.0

#3465 Allow null refresh_interval to be passed
  src/Nest/IndexModules/IndexSettings/Settings/DynamicIndexSettings.cs
  src/Nest/IndexModules/IndexSettings/Settings/IndexSettingsConverter.cs
  src/Tests/Tests/Document/Multiple/Bulk/BulkApiTests.cs
  src/Tests/Tests/Indices/IndexSettings/UpdateIndicesSettings/UpdateIndexSettingsApiTests.cs
Labels: Bug, Port to 5.x, Port to 6.x, v5.6.5, v6.5.0

#3486 Fix #3485
  src/Elasticsearch.Net/Responses/ResponseStatics.cs
  src/Tests/Tests/ClientConcepts/Troubleshooting/DebugInformation.doc.cs
Labels: Bug, Port to 5.x, Port to 6.x
