Repository elastic/elasticsearch-net, pull requests merged in 2018-04, with the labels that each got.

#3192 Add multiple documents to percolate query
  src/Nest/QueryDsl/Specialized/Percolate/PercolateQuery.cs
  src/Tests/QueryDsl/Specialized/Percolate/PercolateQueryUsageTests.cs
Labels: Port to 6.x

#3190 Add support for Daitch-Mokotoff algorithm
  src/Nest/Analysis/Plugins/Phonetic/PhoneticEncoder.cs
  src/Nest/Analysis/Plugins/Phonetic/PhoneticLanguage.cs
  src/Nest/Analysis/Plugins/Phonetic/PhoneticNameType.cs
  src/Nest/Analysis/Plugins/Phonetic/PhoneticRuleType.cs
  src/Nest/Analysis/Plugins/Phonetic/PhoneticTokenFilter.cs
  src/Tests/Analysis/TokenFilters/TokenFilterUsageTests.cs
  src/Tests/Framework/ManagedElasticsearch/Clusters/WritableCluster.cs
  src/Tests/Framework/ManagedElasticsearch/Plugins/ElasticsearchPlugin.cs
Labels: Port to 5.x, Port to 6.x, v5.6.2, v6.0.3

#3195 Change Fields to be optional on MultiMatchQuery
  src/Nest/QueryDsl/FullText/MultiMatch/MultiMatchQuery.cs
  src/Tests/QueryDsl/FullText/MultiMatch/MultiMatchUsageTests.cs
Labels: Port to 6.x

#3196 Add segment attributes to the _segments API
  src/Nest/Indices/Monitoring/IndicesSegments/Segment.cs
  src/Tests/Indices/Monitoring/IndicesSegments/SegmentsApiTests.cs
Labels: Port to 6.x

#3191 Add ignore_malformed to GeoShapeProperty
  src/Nest/Mapping/Types/Geo/GeoShape/GeoShapeAttribute.cs
  src/Nest/Mapping/Types/Geo/GeoShape/GeoShapeProperty.cs
Labels: Port to 6.x

#3198 Add response mime type to response
  src/Elasticsearch.Net/Connection/HttpConnection-CoreFx.cs
  src/Elasticsearch.Net/Responses/ElasticsearchResponse.cs
  src/Elasticsearch.Net/Transport/Pipeline/ResponseBuilder.cs
Labels: v5.6.2

#3203 Update settings available for s3 repository plugin
  src/Nest/Modules/SnapshotAndRestore/Repositories/S3Repository.cs
  src/Tests/Modules/SnapshotAndRestore/Repositories/CreateRepository/CreateRepositoryApiTests.cs
Labels: Port to 5.x, Port to 6.x

#3200 Add Significant Text Aggregation
  src/Nest/Aggregations/AggregateDictionary.cs
  src/Nest/Aggregations/AggregationContainer.cs
  src/Nest/Aggregations/Bucket/SignificantTerms/IncludeExclude.cs
  src/Nest/Aggregations/Bucket/SignificantTerms/SignificantTermsAggregation.cs
  src/Nest/Aggregations/Bucket/SignificantText/SignificantTextAggregation.cs
  src/Nest/Aggregations/Visitor/AggregationVisitor.cs
  src/Nest/Aggregations/Visitor/AggregationWalker.cs
  src/Tests/Aggregations/Bucket/SignificantTerms/SignificantTermsAggregationUsageTests.cs
  src/Tests/Aggregations/Bucket/SignificantText/SignificantTextAggregationUsageTests.cs
Labels: Port to 6.x

#3199 Feature/indices shard stats
  src/Nest/Indices/Monitoring/IndicesStats/IndicesStats.cs
  src/Nest/Indices/Monitoring/IndicesStats/ShardCommit.cs
  src/Nest/Indices/Monitoring/IndicesStats/ShardCompletion.cs
  src/Nest/Indices/Monitoring/IndicesStats/ShardDocs.cs
  src/Nest/Indices/Monitoring/IndicesStats/ShardFieldData.cs
  src/Nest/Indices/Monitoring/IndicesStats/ShardFileSizeInfo.cs
  src/Nest/Indices/Monitoring/IndicesStats/ShardFlush.cs
  src/Nest/Indices/Monitoring/IndicesStats/ShardGet.cs
  src/Nest/Indices/Monitoring/IndicesStats/ShardIndexing.cs
  src/Nest/Indices/Monitoring/IndicesStats/ShardMerges.cs
  src/Nest/Indices/Monitoring/IndicesStats/ShardPath.cs
  src/Nest/Indices/Monitoring/IndicesStats/ShardQueryCache.cs
  src/Nest/Indices/Monitoring/IndicesStats/ShardRefresh.cs
  src/Nest/Indices/Monitoring/IndicesStats/ShardRequestCache.cs
  src/Nest/Indices/Monitoring/IndicesStats/ShardRouting.cs
  src/Nest/Indices/Monitoring/IndicesStats/ShardRoutingState.cs
  src/Nest/Indices/Monitoring/IndicesStats/ShardSearch.cs
  src/Nest/Indices/Monitoring/IndicesStats/ShardSegments.cs
  src/Nest/Indices/Monitoring/IndicesStats/ShardSequenceNumber.cs
  src/Nest/Indices/Monitoring/IndicesStats/ShardStats.cs
  src/Nest/Indices/Monitoring/IndicesStats/ShardStatsRecovery.cs
  src/Nest/Indices/Monitoring/IndicesStats/ShardStatsStore.cs
  src/Nest/Indices/Monitoring/IndicesStats/ShardTransactionLog.cs
  src/Nest/Indices/Monitoring/IndicesStats/ShardWarmer.cs
  src/Tests/Indices/Monitoring/IndicesStats/IndicesStatsWithShardsInformationApiTests.cs
Labels: Port to 6.x

#3202 Add support for ip_range datatype
  src/Nest/Aggregations/Bucket/IpRange/IpRange.cs
  src/Nest/Aggregations/Bucket/IpRange/IpRangeAggregation.cs
  src/Nest/Aggregations/Bucket/IpRange/IpRangeAggregationRange.cs
  src/Nest/CommonOptions/Range/Ranges.cs
  src/Nest/Mapping/DynamicTemplate/SingleMapping.cs
  src/Nest/Mapping/Types/Core/Range/Ip/IpRangeAttribute.cs
  src/Nest/Mapping/Types/Core/Range/Ip/IpRangeProperty.cs
  src/Nest/Mapping/Types/Core/Range/RangePropertyBase.cs
  src/Nest/Mapping/Types/Core/Range/RangeType.cs
  src/Nest/Mapping/Types/FieldType.cs
  src/Nest/Mapping/Types/Properties-Scalar.cs
  src/Nest/Mapping/Types/Properties.cs
  src/Nest/Mapping/Types/PropertiesJsonConverter.cs
  src/Nest/Mapping/Types/PropertyJsonConverter.cs
  src/Nest/Mapping/Visitor/PropertyWalker.cs
  src/Tests/Aggregations/Bucket/IpRange/IpRangeAggregationUsageTests.cs
  src/Tests/Framework/MockData/Ranges.cs
  src/Tests/Indices/MappingManagement/PutMapping/PutMappingApiTest.cs
  src/Tests/Mapping/Types/Core/Range/IpRange/IpRangeAttributeTests.cs
  src/Tests/Mapping/Types/Core/Range/IpRange/IpRangePropertyTests.cs
Labels: Port to 5.x, Port to 6.x

#3208 Support serialization of geo shapes on documents
  build/scripts/Commandline.fsx
  src/Nest/QueryDsl/Geo/GeoLocation.cs
  src/Nest/QueryDsl/Geo/Shape/Envelope/EnvelopeGeoShape.cs
  src/Nest/QueryDsl/Geo/Shape/GeoShapeBase.cs
  src/Nest/QueryDsl/Geo/Shape/GeoShapeQueryJsonConverter.cs
  src/Nest/QueryDsl/Geo/Shape/GeometryCollection/GeometryCollection.cs
  src/Serializers/Nest.JsonNetSerializer/Converters/HandleNestTypesOnSourceJsonConverter.cs
  src/Tests/Framework/MockData/Developer.cs
  src/Tests/Framework/MockData/Person.cs
  src/Tests/Framework/MockData/Shape.cs
  src/Tests/Framework/SerializationTests/GeoShapeSerializationTests.cs
  src/Tests/Framework/TestClient.cs
  src/Tests/QueryDsl/Geo/GeoShapeQueryUsageTests.cs
Labels: Port to 6.x

#3214 Obsolete IgnoreUnmapped on IGeoShape
  src/Nest/QueryDsl/Geo/Shape/Circle/GeoShapeCircleQuery.cs
  src/Nest/QueryDsl/Geo/Shape/Envelope/GeoShapeEnvelopeQuery.cs
  src/Nest/QueryDsl/Geo/Shape/GeoShapeBase.cs
  src/Nest/QueryDsl/Geo/Shape/GeoShapeQueryJsonConverter.cs
  src/Nest/QueryDsl/Geo/Shape/GeometryCollection/GeometryCollection.cs
  src/Nest/QueryDsl/Geo/Shape/IGeoShapeQuery.cs
  src/Nest/QueryDsl/Geo/Shape/LineString/GeoShapeLineStringQuery.cs
  src/Nest/QueryDsl/Geo/Shape/MultiLineString/GeoShapeMultiLineStringQuery.cs
  src/Nest/QueryDsl/Geo/Shape/MultiPoint/GeoShapeMultiPointQuery.cs
  src/Nest/QueryDsl/Geo/Shape/MultiPolygon/GeoShapeMultiPolygonQuery.cs
  src/Nest/QueryDsl/Geo/Shape/Point/GeoShapePointQuery.cs
  src/Nest/QueryDsl/Geo/Shape/Polygon/GeoShapePolygonQuery.cs
  src/Tests/QueryDsl/Geo/GeoShapeQueryUsageTests.cs
  src/Tests/QueryDsl/Geo/Shape/GeoShapeQueryUsageTestsBase.cs
  src/Tests/QueryDsl/Geo/Shape/Polygon/GeoShapePolygonQueryUsageTests.cs
Labels: Port to 5.x, Port to master, v5.6.2, v6.1.0

#3218 Add Visit methods for *_range properties
  src/Nest/Mapping/Visitor/IMappingVisitor.cs
  src/Nest/Mapping/Visitor/IPropertyVisitor.cs
  src/Nest/Mapping/Visitor/MappingWalker.cs
  src/Nest/Mapping/Visitor/NoopPropertyVisitor.cs
  src/Nest/Mapping/Visitor/PropertyWalker.cs
  src/Tests/Indices/MappingManagement/GetMapping/GetMappingApiTest.cs
Labels: Port to 5.x, Port to 6.x, v5.6.2, v6.1.0
