Repository elastic/elasticsearch-net, pull requests merged in 2018-09, with the labels that each got.

#3393 Update TypeNameResolver.cs
  src/Nest/CommonAbstractions/Infer/TypeName/TypeNameResolver.cs
Labels: Port to 5.x, Port to 6.x, v6.3.0

#3396 Previous commits removed parent_node which needs to be obsoleted for …
  src/CodeGeneration/ApiGenerator/RestSpecification/Core/tasks.cancel.patch.json
  src/Elasticsearch.Net/Domain/RequestParameters/RequestParameters.Generated.cs
  src/Nest/_Generated/_Descriptors.generated.cs
  src/Nest/_Generated/_Requests.generated.cs
Labels: v6.3.0

#3389 SeedNode() on DefaultSeeder parallelizes where possible
  src/Tests/Tests.Core/ManagedElasticsearch/NodeSeeders/DefaultSeeder.cs
  src/Tests/Tests.Profiling/Framework/ProfilingCluster.cs
  src/Tests/Tests/Document/Multiple/Reindex/ReindexApiTests.cs
Labels: Feature, Port to 5.x, Port to master

#3408 Use AssertionScope to always include response.DebugInformation
  src/Tests/Tests/Framework/EndpointTests/ApiIntegrationTestBase.cs
  src/Tests/Tests/Search/Request/FieldsUsageTests.cs
Labels: Feature

#3405 Fix #3404 bulk all improvements
  src/Elasticsearch.Net/Auditing/Audit.cs
  src/Elasticsearch.Net/Auditing/AuditEvent.cs
  src/Elasticsearch.Net/Transport/Pipeline/RequestPipeline.cs
  src/Nest/Document/Multiple/BulkAll/BulkAllObservable.cs
  src/Nest/Document/Multiple/BulkAll/BulkAllRequest.cs
  src/Nest/Document/Multiple/BulkAll/BulkAllResponse.cs
  src/Tests/Tests/ClientConcepts/ConnectionPooling/MaxRetries/RespectsMaxRetry.doc.cs
  src/Tests/Tests/ClientConcepts/ConnectionPooling/RoundRobin/SkipDeadNodes.doc.cs
  src/Tests/Tests/ClientConcepts/ConnectionPooling/Sticky/SkipDeadNodes.doc.cs
  src/Tests/Tests/ClientConcepts/ConnectionPooling/Sticky/StickySniffingConnectionPool.doc.cs
  src/Tests/Tests/CodeStandards/Descriptors.doc.cs
  src/Tests/Tests/Document/Multiple/BulkAll/BulkAllApiTestsBase.cs
  src/Tests/Tests/Document/Multiple/BulkAll/BulkOnErrorApiTests.cs
  src/Tests/Tests/Tests.csproj
Labels: Bug, Feature, v6.3.1
