Repository elastic/elasticsearch-net, pull requests merged in 2018-03, with the labels that each got.

#3112 Add token_limit and force_unigrams to phrase suggest
  src/Nest/Search/Suggesters/PhraseSuggester/PhraseSuggester.cs
  src/Tests/Search/Request/SuggestUsageTests.cs
Labels: Port to 2.x, Port to 5.x, Port to 6.x

#3127 Fix #3115 bump json.net to version 11
  build/NEST.JsonNetSerializer.nuspec
  src/CodeGeneration/DocGenerator/DocGenerator.csproj
  src/Nest/Nest.csproj
  src/Serializers/Nest.JsonNetSerializer/Nest.JsonNetSerializer.csproj
Labels: Port to 6.x

#3135 Add ignore_unmapped to inner_hits
  src/Nest/Search/Search/InnerHits/InnerHits.cs
  src/Tests/Search/Request/InnerHitsUsageTests.cs
Labels: Port to 5.x, Port to 6.x

#3140 Add skip_duplicates to completion suggester
  src/Nest/Search/Suggesters/BaseSuggest.cs
  src/Nest/Search/Suggesters/CompletionSuggester/CompletionSuggester.cs
  src/Tests/Search/Request/SuggestUsageTests.cs
Labels: Port to 6.x

#3139 Remove multiple types per index from documentation
  .paket/Paket.Restore.targets
  src/Nest/Mapping/AttributeBased/ElasticsearchCorePropertyAttributeBase.cs
  src/Nest/Mapping/DynamicMapping.cs
  src/Nest/Mapping/Types/Complex/Object/ObjectProperty.cs
  src/Nest/Mapping/Types/CorePropertyBase.cs
  src/Nest/Mapping/Types/PropertyBase.cs
  src/Tests/ClientConcepts/HighLevel/Mapping/AttributeMapping.doc.cs
  src/Tests/ClientConcepts/HighLevel/Mapping/FluentMapping.doc.cs
  src/Tests/ClientConcepts/HighLevel/Mapping/VisitorPatternMapping.doc.cs
Labels: Port to master

#3162 Honour JsonConverters added in JsonSerializerSettings
  docs/client-concepts/high-level/serialization/custom-serialization.asciidoc
  src/Serializers/Nest.JsonNetSerializer/ConnectionSettingsAwareSerializerBase.Serializer.cs
  src/Tests/ClientConcepts/HighLevel/Serialization/CustomSerialization.doc.cs
  src/Tests/Reproduce/JsonNetSerializerConverters.cs
Labels: Port to master

#3165 Add bucket_sort aggregation
  src/Nest/Aggregations/AggregationContainer.cs
  src/Nest/Aggregations/Pipeline/BucketSort/BucketSortAggregation.cs
  src/Nest/Aggregations/Visitor/AggregationVisitor.cs
  src/Nest/Aggregations/Visitor/AggregationWalker.cs
  src/Tests/Aggregations/Pipeline/BucketSort/BucketSortAggregationUsageTests.cs
Labels: Port to master

#3166 Add urldecode ingest processor
  src/Nest/Ingest/PipelineJsonConverter.cs
  src/Nest/Ingest/Processors/UrlDecodeProcessor.cs
  src/Nest/Ingest/ProcessorsDescriptor.cs
  src/Tests/Ingest/PutPipeline/PutPipelineApiTests.cs
Labels: Port to master

#3168 Add terms_set query
  src/Nest/QueryDsl/Abstractions/Container/IQueryContainer.cs
  src/Nest/QueryDsl/Abstractions/Container/QueryContainer-Assignments.cs
  src/Nest/QueryDsl/Abstractions/Container/QueryContainer-Dsl.cs
  src/Nest/QueryDsl/Abstractions/Container/QueryContainerDescriptor.cs
  src/Nest/QueryDsl/Abstractions/Container/QueryContainerJsonConverter.cs
  src/Nest/QueryDsl/Query.cs
  src/Nest/QueryDsl/TermLevel/TermsSet/TermsSetQuery.cs
  src/Nest/QueryDsl/Visitor/DslPrettyPrintVisitor.cs
  src/Nest/QueryDsl/Visitor/QueryVisitor.cs
  src/Nest/QueryDsl/Visitor/QueryWalker.cs
  src/Tests/Framework/MockData/Project.cs
  src/Tests/Indices/MappingManagement/PutMapping/PutMappingApiTest.cs
  src/Tests/QueryDsl/TermLevel/TermsSet/TermsSetQueryUsageTests.cs
Labels: Port to master

#3169 Add auto_generate_synonyms_phrase_query to match, multi_match, query_…
  src/Nest/QueryDsl/FullText/Match/MatchQuery.cs
  src/Nest/QueryDsl/FullText/MultiMatch/MultiMatchQuery.cs
  src/Nest/QueryDsl/FullText/QueryString/QueryStringQuery.cs
  src/Nest/QueryDsl/FullText/SimpleQueryString/SimpleQueryStringQuery.cs
  src/Tests/QueryDsl/FullText/Match/MatchUsageTests.cs
  src/Tests/QueryDsl/FullText/MultiMatch/MultiMatchUsageTests.cs
  src/Tests/QueryDsl/FullText/QueryString/QueryStringUsageTests.cs
  src/Tests/QueryDsl/FullText/SimpleQueryString/SimpleQueryStringUsageTests.cs
Labels: Port to master

#3172 Add Max Token Length to Whitespace Tokenizer
  src/Nest/Analysis/Tokenizers/WhitespaceTokenizer.cs
Labels: Port to master
