Repository elastic/elasticsearch-net, pull requests merged in 2018-06, with the labels that each got.

#3278 Respect JSON Dates from Elasticsearch when passing to SourceSerializer
  src/Nest/CommonAbstractions/SerializationBehavior/SourceConverter.cs
  src/Tests/Reproduce/GithubIssue3164.cs
Labels: Port to 6.x

#3233 Add CompositeAggregation
  docs/aggregations.asciidoc
  docs/aggregations/bucket/composite/composite-aggregation-usage.asciidoc
  docs/aggregations/bucket/date-histogram/date-histogram-aggregation-usage.asciidoc
  src/Nest/Aggregations/AggregateDictionary.cs
  src/Nest/Aggregations/AggregateDictionaryConverter.cs
  src/Nest/Aggregations/AggregateJsonConverter.cs
  src/Nest/Aggregations/AggregationContainer.cs
  src/Nest/Aggregations/Bucket/Composite/CompositeAggregation.cs
  src/Nest/Aggregations/Bucket/Composite/CompositeAggregationSource.cs
  src/Nest/Aggregations/Bucket/Composite/CompositeBucket.cs
  src/Nest/Aggregations/Bucket/Composite/DateHistogramCompositeAggregationSource.cs
  src/Nest/Aggregations/Bucket/Composite/HistogramCompositeAggregationSource.cs
  src/Nest/Aggregations/Bucket/Composite/TermsCompositeAggregationSource.cs
  src/Nest/Aggregations/Visitor/AggregationVisitor.cs
  src/Nest/Aggregations/Visitor/AggregationWalker.cs
  src/Nest/CommonAbstractions/LazyDocument/LazyDocument.cs
  src/Nest/CommonAbstractions/LazyDocument/LazyDocumentJsonConverter.cs
  src/Tests/Aggregations/Bucket/Composite/CompositeAggregationUsageTests.cs
  src/Tests/Aggregations/Bucket/DateHistogram/DateHistogramAggregationUsageTests.cs
Labels: Port to 6.x

#3276 Include include_global_state in Snapshot status API. Closes #3258.
  src/Nest/Modules/SnapshotAndRestore/Snapshot/SnapshotStatus/SnapshotStatusResponse.cs
Labels: Port to 6.x, v6.2.0

#3289 Add scroll parameter to reindex. Closes #3253
  src/CodeGeneration/ApiGenerator/RestSpecification/Core/reindex.patch.json
  src/Elasticsearch.Net/Domain/RequestParameters/RequestParameters.Generated.cs
  src/Nest/_Generated/_Descriptors.generated.cs
  src/Nest/_Generated/_Requests.generated.cs
Labels: Port to 6.x, v6.2.0

#3277 Associate an external id with a task, so that it can be cancelled later.
  src/Elasticsearch.Net/Configuration/RequestConfiguration.cs
  src/Elasticsearch.Net/Transport/Pipeline/RequestData.cs
  src/Nest/Cluster/TaskManagement/GetTask/TaskInfo.cs
  src/Nest/Cluster/TaskManagement/ListTasks/ListTasksResponse.cs
  src/Tests/Search/Search/SearchApiTests.cs
Labels: Port to 6.x, v6.2.0

#3287 Assign instance to Aggregations property
  src/Nest/Aggregations/Bucket/BucketAggregate.cs
  src/Tests/Reproduce/GithubIssue3286.cs
  src/Tests/tests.default.yaml
Labels: Port to master, v6.2.0

#3292 Add DocValueFields to TopHits Aggregation
  docs/aggregations/metric/top-hits/top-hits-aggregation-usage.asciidoc
  src/CodeGeneration/DocGenerator/StringExtensions.cs
  src/Nest/Aggregations/Metric/TopHits/TopHitsAggregation.cs
  src/Tests/Aggregations/Metric/TopHits/TopHitsAggregationUsageTests.cs
Labels: Port to master, v5.6.3, v6.2.0

#3293 Add _ScriptedUpsert to BulkUpdateOperation
  src/Nest/Document/Multiple/Bulk/BulkOperation/BulkUpdate.cs
Labels: Port to master, v5.6.3, v6.2.0

#3294 Support single or array of char filters and token filters
  src/Nest/Analysis/Analyzers/CustomAnalyzer.cs
  src/Nest/Analysis/Normalizers/CustomNormalizer.cs
  src/Nest/CommonAbstractions/SerializationBehavior/GenericJsonConverters/ReadSingleOrEnumerableJsonConverter.cs
  src/Tests/Reproduce/GithubIssue3262.cs
Labels: Port to master, v5.6.3, v6.2.0
