Repository elastic/elasticsearch-net, pull requests merged in 2019-05, with the labels that each got.

#3683 Fix TODOs
  src/Elasticsearch.Net/Responses/ElasticsearchResponse.cs
  src/Elasticsearch.Net/Responses/HttpDetails/IApiCallDetails.cs
  src/Elasticsearch.Net/Transport/Pipeline/RequestPipeline.cs
  src/Nest/Aggregations/Bucket/Filters/FiltersAggregation.cs
  src/Nest/Aggregations/Visitor/AggregationVisitor.cs
  src/Nest/Analysis/TokenFilters/TokenFilterFormatter.cs
  src/Nest/Analysis/Tokenizers/TokenizerFormatter.cs
  src/Nest/Cluster/ClusterState/NodeState.cs
  src/Nest/Cluster/NodesInfo/NodeInfo.cs
  src/Nest/Cluster/NodesStats/NodeStats.cs
  src/Nest/CommonAbstractions/Fields/FieldValuesFormatter.cs
  src/Nest/CommonAbstractions/Infer/Field/FieldFormatter.cs
  src/Nest/CommonAbstractions/Infer/Id/IdResolver.cs
  src/Nest/CommonAbstractions/Infer/IndexName/IndexName.cs
  src/Nest/CommonOptions/Fuzziness/FuzzinessFormatter.cs
  src/Nest/Document/Multiple/MultiTermVectors/MultiTermVectorOperation.cs
  src/Nest/Document/Multiple/MultiTermVectors/MultiTermVectorsRequest.cs
  src/Nest/IndexModules/IndexSettings/Settings/DynamicIndexSettings.cs
  src/Nest/IndexModules/IndexSettings/Store/FileSystemStorageImplementation.cs
  src/Nest/Mapping/Types/PropertiesFormatter.cs
  src/Nest/QueryDsl/Compound/ConstantScore/ConstantScoreQuery.cs
  src/Nest/QueryDsl/Compound/FunctionScore/Functions/ScoreFunctionJsonFormatter.cs
  src/Nest/Search/Search/SearchRequest.cs
  src/Nest/XPack/Security/RoleMapping/Rules/Role/RoleMappingRulesDescriptor.cs
  src/Nest/XPack/Watcher/Action/ActionBase.cs
  src/Tests/Tests/ClientConcepts/HighLevel/Serialization/SendsUsingSourceSerializer.cs
  src/Tests/Tests/Cluster/NodesInfo/NodesInfoApiTests.cs
  src/Tests/Tests/Cluster/NodesStats/NodesStatsApiTests.cs
  src/Tests/Tests/Document/Multiple/MultiTermVectors/MultiTermVectorsApiTests.cs
  src/Tests/Tests/IndexModules/IndexSettings/Settings/TypedIndexSettings.cs
Labels: Cleanup, Port to master, v7.0.0

#3711 Implement Intervals query
  src/Nest/QueryDsl/Abstractions/Container/IQueryContainer.cs
  src/Nest/QueryDsl/Abstractions/Container/QueryContainer-Assignments.cs
  src/Nest/QueryDsl/Abstractions/Container/QueryContainerDescriptor.cs
  src/Nest/QueryDsl/FullText/Intervals/IntervalsAllOf.cs
  src/Nest/QueryDsl/FullText/Intervals/IntervalsAnyOf.cs
  src/Nest/QueryDsl/FullText/Intervals/IntervalsFilter.cs
  src/Nest/QueryDsl/FullText/Intervals/IntervalsMatch.cs
  src/Nest/QueryDsl/FullText/Intervals/IntervalsQuery.cs
  src/Nest/QueryDsl/Query.cs
  src/Nest/QueryDsl/Visitor/DslPrettyPrintVisitor.cs
  src/Nest/QueryDsl/Visitor/QueryVisitor.cs
  src/Nest/QueryDsl/Visitor/QueryWalker.cs
  src/Tests/Tests.Configuration/tests.default.yaml
  src/Tests/Tests/CodeStandards/Descriptors.doc.cs
  src/Tests/Tests/QueryDsl/FullText/Intervals/IntervalsUsageTests.cs
Labels: Feature, Port to master, v7.0.0

#3677 Refactor ServerError, Error and ErrorCause
  src/Elasticsearch.Net/Responses/ServerException/Error.cs
  src/Elasticsearch.Net/Responses/ServerException/ErrorCause.cs
  src/Elasticsearch.Net/Responses/ServerException/ErrorCauseExtensions.cs
  src/Elasticsearch.Net/Responses/ServerException/ServerError.cs
  src/Elasticsearch.Net/Responses/ServerException/ShardFailure.cs
  src/Elasticsearch.Net/Serialization/Extensions/ArraySegmentBytesExtensions.cs
  src/Elasticsearch.Net/Serialization/Formatters/InterfaceReadOnlyCollectionSingleOrEnumerableFormatter.cs
  src/Elasticsearch.Net/Serialization/Formatters/NullableStringIntFormatter.cs
  src/Nest/CommonAbstractions/Extensions/Extensions.cs
  src/Nest/CommonAbstractions/SerializationBehavior/JsonFormatters/ErrorCauseFormatter.cs
  src/Nest/CommonAbstractions/SerializationBehavior/JsonFormatters/ErrorFormatter.cs
  src/Nest/CommonOptions/Failures/BulkError.cs
  src/Nest/Document/Multiple/Bulk/BulkResponseItem/BulkResponseItemBase.cs
  src/Nest/Document/Multiple/BulkIndexByScrollFailure.cs
  src/Nest/Indices/MappingManagement/GetFieldMapping/FieldMappingFormatter.cs
  src/Tests/Tests/ClientConcepts/ServerError/ComplexErrorTests.cs
  src/Tests/Tests/ClientConcepts/ServerError/StringErrrorTests.cs
  src/Tests/Tests/Cluster/TaskManagement/TasksList/TasksListApiTests.cs
  src/Tests/Tests/Document/Multiple/DeleteByQuery/DeleteByQueryApiTests.cs
  src/Tests/Tests/Document/Multiple/UpdateByQuery/UpdateByQueryApiTests.cs
Labels: Refactoring, v7.0.0

#3684 Security Api Key functionality
  src/CodeGeneration/ApiGenerator/ApiGenerator.cs
  src/Elasticsearch.Net/Domain/RequestParameters/RequestParameters.Generated.cs
  src/Elasticsearch.Net/ElasticLowLevelClient.Generated.cs
  src/Elasticsearch.Net/IElasticLowLevelClient.Generated.cs
  src/Nest/XPack/Security/ApiKey/CreateApiKey/ApiKeyPrivileges.cs
  src/Nest/XPack/Security/ApiKey/CreateApiKey/ApiKeyRole.cs
  src/Nest/XPack/Security/ApiKey/CreateApiKey/ApiKeyRoles.cs
  src/Nest/XPack/Security/ApiKey/CreateApiKey/CreateApiKeyRequest.cs
  src/Nest/XPack/Security/ApiKey/CreateApiKey/CreateApiKeyResponse.cs
  src/Nest/XPack/Security/ApiKey/CreateApiKey/ElasticClient-CreateApiKey.cs
  src/Nest/XPack/Security/ApiKey/GetApiKey/ElasticClient-GetApiKey.cs
  src/Nest/XPack/Security/ApiKey/GetApiKey/GetApiKeyRequest.cs
  src/Nest/XPack/Security/ApiKey/GetApiKey/GetApiKeyResponse.cs
  src/Nest/XPack/Security/ApiKey/InvalidateApiKey/ElasticClient-InvalidateApiKey.cs
  src/Nest/XPack/Security/ApiKey/InvalidateApiKey/InvalidateApiKeyRequest.cs
  src/Nest/XPack/Security/ApiKey/InvalidateApiKey/InvalidateApiKeyResponse.cs
  src/Nest/_Generated/_Descriptors.generated.cs
  src/Nest/_Generated/_LowLevelDispatch.generated.cs
  src/Nest/_Generated/_Requests.generated.cs
  src/Tests/Tests/XPack/Security/ApiKey/SecurityApiKeyTests.cs
  src/Tests/Tests/XPack/Security/ApiKey/SecurityApiKeyUrlTests.cs
Labels: Port to 7.x, Port to master

#3714 Add SequenceNumber and PrimaryTerm to Hits, Get and MulitGetHit
  src/CodeGeneration/ApiGenerator/Overrides/GlobalOverrides.cs
  src/Elasticsearch.Net/Domain/RequestParameters/RequestParameters.Generated.cs
  src/Nest/Document/Multiple/Bulk/BulkOperation/BulkDelete.cs
  src/Nest/Document/Multiple/Bulk/BulkOperation/BulkIndex.cs
  src/Nest/Document/Multiple/MultiGet/Response/MultiGetHit.cs
  src/Nest/Document/Single/Get/GetResponse.cs
  src/Nest/Search/Search/Hits/Hit.cs
  src/Nest/_Generated/_Descriptors.generated.cs
  src/Nest/_Generated/_Requests.generated.cs
  src/Tests/Tests/Aggregations/Metric/TopHits/TopHitsAggregationUsageTests.cs
  src/Tests/Tests/Document/Multiple/Bulk/BulkInvalidVersionApiTests.cs
  src/Tests/Tests/Document/Multiple/MultiGet/MultiGetApiTests.cs
  src/Tests/Tests/Document/Single/Get/GetApiTests.cs
  src/Tests/Tests/Search/Request/InnerHitsUsageTests.cs
  src/Tests/Tests/Search/Search/SearchApiTests.cs
Labels: Feature, v7.0.0

#3718 Allow geo_shape types to be coerced into valid shapes.
  src/Nest/Mapping/Types/Geo/GeoShape/GeoShapeAttribute.cs
  src/Nest/Mapping/Types/Geo/GeoShape/GeoShapeProperty.cs
  src/Tests/Tests/Mapping/Types/Geo/GeoShape/GeoShapeAttributeTests.cs
  src/Tests/Tests/Mapping/Types/Geo/GeoShape/GeoShapePropertyTests.cs
Labels: Port to 7.x, Port to master

#3723 Add password_hash parameter to PutUser
  src/Nest/XPack/Security/User/PutUser/ElasticClient-PutUser.cs
  src/Nest/XPack/Security/User/PutUser/PutUserRequest.cs
Labels: Port to 7.x, Port to master

#3727 Add time since last auto follow fetch to auto follow stats
  src/Nest/XPack/CrossClusterReplication/Stats/CcrStatsResponse.cs
Labels: Port to 7.x, Port to master

#3725 Add realm information for Authenticate API
  src/Nest/XPack/Security/Authenticate/AuthenticateResponse.cs
Labels: Port to 7.x, Port to master

#3734 Fix CCR Tests.
  src/Tests/Tests.Core/ManagedElasticsearch/Clusters/IntrusiveOperationSeededCluster.cs
  src/Tests/Tests/Cluster/ClusterReroute/ClusterRerouteApiTests.cs
  src/Tests/Tests/XPack/CrossClusterReplication/CrossClusterReplicationFollowTests.cs
Labels: Port to 7.x, Port to master

#3740 [DOCS] Fix broken cross-ref links
  src/Tests/Tests/high-level.asciidoc
Labels: Docs

#3741 [DOCS] Fix broken cross-ref links (6.x backport of #3740)
  src/Tests/Tests/high-level.asciidoc
Labels: Docs, Port to 6.x

#3742 [DOCS] Fix includes and broken links
  docs/high-level.asciidoc
Labels: Docs, Port to 6.x

#3757 Include stored_scripts response in cluster metadata response.
  src/Nest/Cluster/ClusterState/MetadataState.cs
  src/Nest/Cluster/ClusterState/StoredScriptMapping.cs
  src/Tests/Tests/Cluster/ClusterState/ClusterStateApiTests.cs
Labels: Port to 7.x, Port to master, v6.8.0

#3758 Add buckets to AutoDateHistogramAggregation.
  src/Nest/Aggregations/Bucket/AutoDateHistogram/AutoDateHistogramAggregation.cs
  src/Tests/Tests/Aggregations/Bucket/AutoDateHistogram/AutoDateHistogramAggregationUsageTests.cs
Labels: Port to 7.x, Port to master, v6.8.0

#3759 Additional Rollup Stats
  src/Nest/XPack/RollUp/GetRollupJob/RollupJobStats.cs
Labels: Port to 7.x, Port to master, v6.8.0

#3764 XPack info and usage improvements.
  src/Nest/XPack/Info/XPackInfo/XPackInfoResponse.cs
  src/Nest/XPack/Info/XPackUsage/XPackUsageResponse.cs
  src/Tests/Tests/XPack/Info/XPackInfoApiTests.cs
  src/Tests/Tests/XPack/Info/XPackInfoUrlTests.cs
Labels: Port to 7.x, Port to master, v6.8.0

#3763 Attribute SuggestBucket for serialization
  src/Nest/Search/Suggesters/SuggestBucket.cs
  src/Tests/Tests.Reproduce/Discuss179634.cs
Labels: v6.8.0

#3766 Add pretty names (and other properties) to the cluster stats response.
  src/Nest/Cluster/ClusterStats/ClusterNodesStats.cs
  src/Nest/Cluster/ClusterStats/ClusterStatsResponse.cs
  src/Nest/Cluster/NodesInfo/NodeInfo.cs
  src/Nest/CommonOptions/Stats/PluginStats.cs
  src/Nest/CommonOptions/Stats/SegmentsStats.cs
  src/Tests/Tests/Cluster/ClusterStats/ClusterStatsApiTests.cs
Labels: v6.8.0

#3770 Set obsolete warning on GeoShape properties.
  src/Nest/Mapping/Types/Geo/GeoShape/GeoShapeProperty.cs
Labels: Port to 7.x, Port to master, v6.8.0

#3767 Add doc’s sequence number + primary term to get responses
  src/Nest/Document/Multiple/MultiGet/Response/MultiGetHit.cs
  src/Nest/Document/Single/Get/GetResponse.cs
  src/Tests/Tests/Document/Multiple/MultiGet/MultiGetApiTests.cs
  src/Tests/Tests/Document/Single/DocumentCrudTests.cs
  src/Tests/Tests/Document/Single/Get/GetApiTests.cs
Labels: Port to 7.x, Port to master, v6.8.0

#3775 Convert rollover lifecycle action to accept max size as a string and not long?
  src/Nest/XPack/Ilm/Actions/RolloverAction.cs
  src/Tests/Tests/XPack/Ilm/BytesValueConverterTests.cs
  src/Tests/Tests/XPack/Ilm/IlmApiTests.cs
Labels: Port to 7.x, Port to master, v6.8.0

#3776 Use a custom convertor for GeoOrientation to tolerate alternative options in Elasticsearch
  src/Nest/Mapping/Types/Geo/GeoShape/GeoOrientation.cs
  src/Tests/Tests/Mapping/Types/Geo/GeoShape/GeoShapeClusterMetadataApiTests.cs
Labels: Port to 7.x, Port to master, v6.8.0

#3783 Some event do not carry timings information but DebugInformation stil…
  src/Elasticsearch.Net/Responses/ResponseStatics.cs
Labels: Port to 5.x, Port to 6.x, Port to master, v7.0.0
