Repository elastic/elasticsearch-net, pull requests merged in 2019-12, with the labels that each got.

#4263 Static property for formatter instance returned new instance everytime
  src/Elasticsearch.Net/Serialization/Resolvers/ElasticsearchNetFormatterResolver.cs
Labels: Bug, Port to 7.x, v7.4.2

#4253 [DOCS] Added older release notice.
  docs/page_header.html
Labels: Docs, v6.8.4

#4255 [DOCS] Add EOL notice.
  docs/page_header.html
Labels: Docs, v1.9.3, v2.5.8, v5.6.7

#4212 normalize ifdefs in our source included UTF8Json
  src/Elasticsearch.Net/Elasticsearch.Net.csproj
  src/Elasticsearch.Net/Utf8Json/Formatters/CollectionFormatters.cs
  src/Elasticsearch.Net/Utf8Json/Formatters/DateTimeFormatter.cs
  src/Elasticsearch.Net/Utf8Json/Formatters/DictionaryFormatter.cs
  src/Elasticsearch.Net/Utf8Json/Formatters/EnumFormatter.cs
  src/Elasticsearch.Net/Utf8Json/Formatters/StandardClassLibraryFormatters.cs
  src/Elasticsearch.Net/Utf8Json/Formatters/TupleFormatter.cs
  src/Elasticsearch.Net/Utf8Json/Formatters/TupleFormatter.tt
  src/Elasticsearch.Net/Utf8Json/Formatters/ValueTupleFormatter.cs
  src/Elasticsearch.Net/Utf8Json/Formatters/ValueTupleFormatter.tt
  src/Elasticsearch.Net/Utf8Json/Internal/AutomataDictionary.cs
  src/Elasticsearch.Net/Utf8Json/Internal/BinaryUtil.cs
  src/Elasticsearch.Net/Utf8Json/Internal/ByteArrayComparer.cs
  src/Elasticsearch.Net/Utf8Json/Internal/ByteArrayStringHashTable.cs
  src/Elasticsearch.Net/Utf8Json/Internal/Emit/DynamicAssembly.cs
  src/Elasticsearch.Net/Utf8Json/Internal/Emit/ILViewer.cs
  src/Elasticsearch.Net/Utf8Json/Internal/FarmHash.cs
  src/Elasticsearch.Net/Utf8Json/Internal/FuncExtensions.cs
  src/Elasticsearch.Net/Utf8Json/Internal/GuidBits.cs
  src/Elasticsearch.Net/Utf8Json/Internal/NumberConverter.cs
  src/Elasticsearch.Net/Utf8Json/Internal/ReflectionExtensions.cs
  src/Elasticsearch.Net/Utf8Json/Internal/ThreadsafeTypeKeyHashTable.cs
  src/Elasticsearch.Net/Utf8Json/Internal/UnsafeMemory.Low.cs
  src/Elasticsearch.Net/Utf8Json/Internal/UnsafeMemory.cs
  src/Elasticsearch.Net/Utf8Json/Internal/UnsafeMemory.tt
  src/Elasticsearch.Net/Utf8Json/JsonReader.cs
  src/Elasticsearch.Net/Utf8Json/JsonSerializer.NonGeneric.cs
  src/Elasticsearch.Net/Utf8Json/JsonSerializer.cs
  src/Elasticsearch.Net/Utf8Json/JsonWriter.cs
  src/Elasticsearch.Net/Utf8Json/Resolvers/AttributeFormatterResolver.cs
  src/Elasticsearch.Net/Utf8Json/Resolvers/BuiltinResolver.cs
  src/Elasticsearch.Net/Utf8Json/Resolvers/CompositeResolver.cs
  src/Elasticsearch.Net/Utf8Json/Resolvers/DynamicGenericResolver.cs
  src/Elasticsearch.Net/Utf8Json/Resolvers/DynamicObjectResolver.cs
  src/Elasticsearch.Net/Utf8Json/Resolvers/StandardResolver.cs
Labels: Infra, Port to master

#4256 Add MatchBoolPrefix query
  docs/client-concepts/connection-pooling/request-overrides/disable-sniff-ping-per-request.asciidoc
  docs/client-concepts/connection/configuration-options.asciidoc
  docs/client-concepts/connection/modifying-default-connection.asciidoc
  docs/client-concepts/low-level/low-level-response-types.asciidoc
  docs/query-dsl.asciidoc
  docs/query-dsl/full-text/match-bool-prefix/match-bool-prefix-usage.asciidoc
  src/Nest/QueryDsl/Abstractions/Container/IQueryContainer.cs
  src/Nest/QueryDsl/Abstractions/Container/QueryContainer-Assignments.cs
  src/Nest/QueryDsl/Abstractions/Container/QueryContainerDescriptor.cs
  src/Nest/QueryDsl/Abstractions/Query/QueryDescriptorBase.cs
  src/Nest/QueryDsl/FullText/MatchBoolPrefix/MatchBoolPrefixQuery.cs
  src/Nest/QueryDsl/Query.cs
  src/Nest/QueryDsl/Visitor/DslPrettyPrintVisitor.cs
  src/Nest/QueryDsl/Visitor/QueryVisitor.cs
  src/Nest/QueryDsl/Visitor/QueryWalker.cs
  src/Tests/Tests/QueryDsl/FullText/MatchBoolPrefix/MatchBoolPrefixUsageTests.cs
Labels: Feature, v7.5.0

#4257 Add updateable property to Synonym token filters
  src/Nest/Analysis/TokenFilters/Synonym/SynonymGraphTokenFilter.cs
  src/Nest/Analysis/TokenFilters/Synonym/SynonymTokenFilter.cs
  src/Tests/Tests/Analysis/TokenFilters/TokenFilterTests.cs
Labels: Feature, v7.5.0

#4259 Add Search as you type to dynamic templates
  src/Nest/Mapping/DynamicTemplate/SingleMapping.cs
  src/Nest/Mapping/Types/Properties.cs
  src/Tests/Tests/Mapping/Types/Core/SearchAsYouType/SearchAsYouTypeSingleMappingPropertyTests.cs
  src/Tests/Tests/Mapping/Types/SingleMappingPropertyTestsBase.cs
  src/Tests/Tests/Mapping/Types/Specialized/Generic/GenericPropertyTests.cs
Labels: Feature, v7.5.0

#4262 Serialize IProperty types based on derived interface type
  src/Nest/Mapping/Types/PropertyFormatter.cs
Labels: Bug, v7.5.0

#4266 Fix Elasticsearch.Net.VirtualCluster lower bound version reference
  build/Elasticsearch.Net.VirtualizedCluster.nuspec
Labels: Infra, Port to 7.x

#4264 Implement Get SLM Stats API
  src/CodeGeneration/ApiGenerator/Configuration/CodeConfiguration.cs
  src/Elasticsearch.Net/Api/RequestParameters/RequestParameters.SnapshotLifecycleManagement.cs
  src/Elasticsearch.Net/ElasticLowLevelClient.SnapshotLifecycleManagement.cs
  src/Nest/Descriptors.SnapshotLifecycleManagement.cs
  src/Nest/ElasticClient.SnapshotLifecycleManagement.cs
  src/Nest/Requests.SnapshotLifecycleManagement.cs
  src/Nest/XPack/Info/XPackInfo/XPackInfoResponse.cs
  src/Nest/XPack/Info/XPackUsage/XPackUsageResponse.cs
  src/Nest/XPack/Slm/GetStats/GetSnapshotLifecycleStatsRequest.cs
  src/Nest/XPack/Slm/GetStats/GetSnapshotLifecycleStatsResponse.cs
  src/Nest/_Generated/ApiUrlsLookup.generated.cs
  src/Tests/Tests/XPack/Slm/SlmApiTests.cs
Labels: Port to master, v7.5.0

#4261 Implement setting snapshot retention configuration on SLM lifecycles.
  src/Nest/XPack/Slm/PutLifecycle/PutSnapshotLifecycleRequest.cs
  src/Nest/XPack/Slm/SnapshotLifecycleConfig.cs
  src/Nest/XPack/Slm/SnapshotLifecyclePolicy.cs
  src/Nest/XPack/Slm/SnapshotRetentionConfig.cs
  src/Tests/Tests/XPack/Slm/SlmApiTests.cs
Labels: Port to master, v7.5.0

#4265 Ensure missing SLM policy is handled by client correctly
  src/Tests/Tests/XPack/Slm/SlmApiTests.cs
Labels: Port to master, v7.5.0

#4246 Modify SLM execute lifecycle to use POST method as opposed to PUT.
  src/CodeGeneration/ApiGenerator/Generator/ApiEndpointFactory.cs
  src/CodeGeneration/ApiGenerator/RestSpecification/_Patches/slm.execute_lifecycle.patch.json
  src/Elasticsearch.Net/Api/RequestParameters/RequestParameters.SnapshotLifecycleManagement.cs
  src/Elasticsearch.Net/ElasticLowLevelClient.SnapshotLifecycleManagement.cs
  src/Nest/ElasticClient.SnapshotLifecycleManagement.cs
  src/Tests/Tests/XPack/Slm/ExecuteLifecycle/ExecuteLifecycleUrlTests.cs
Labels: Port to master, v7.5.0

#4245 Add SLM Start/Stop/Status APIs
  src/CodeGeneration/ApiGenerator/Domain/Code/CsharpNames.cs
  src/CodeGeneration/ApiGenerator/RestSpecification/XPack/slm.get_status.json
  src/CodeGeneration/ApiGenerator/RestSpecification/XPack/slm.start.json
  src/CodeGeneration/ApiGenerator/RestSpecification/XPack/slm.stop.json
  src/Elasticsearch.Net/Api/RequestParameters/RequestParameters.SnapshotLifecycleManagement.cs
  src/Elasticsearch.Net/ElasticLowLevelClient.SnapshotLifecycleManagement.cs
  src/Nest/Descriptors.SnapshotLifecycleManagement.cs
  src/Nest/ElasticClient.SnapshotLifecycleManagement.cs
  src/Nest/Requests.SnapshotLifecycleManagement.cs
  src/Nest/XPack/Slm/GetStatus/GetSnapshotLifecycleManagementStatusRequest.cs
  src/Nest/XPack/Slm/GetStatus/GetSnapshotLifecycleManagementStatusResponse.cs
  src/Nest/XPack/Slm/Start/StartSnapshotLifecycleManagementRequest.cs
  src/Nest/XPack/Slm/Start/StartSnapshotLifecycleManagementResponse.cs
  src/Nest/XPack/Slm/Stop/StopSnapshotLifecycleManagementRequest.cs
  src/Nest/XPack/Slm/Stop/StopSnapshotLifecycleManagementResponse.cs
  src/Nest/_Generated/ApiUrlsLookup.generated.cs
  src/Tests/Tests/XPack/Slm/GetLifecycleStats/GetLifecycleStatsUrlTests.cs
  src/Tests/Tests/XPack/Slm/GetStatusLifecycle/GetLifecycleStatusUrlTests.cs
  src/Tests/Tests/XPack/Slm/SlmApiTests.cs
  src/Tests/Tests/XPack/Slm/StartLifecycle/StartLifecycleUrlTests.cs
  src/Tests/Tests/XPack/Slm/StopLifecycle/StopLifecycleUrlTests.cs
Labels: Port to master, v7.5.0

#4258 Implement SLM Execute Retention API
  src/CodeGeneration/ApiGenerator/Configuration/CodeConfiguration.cs
  src/Elasticsearch.Net/Api/RequestParameters/RequestParameters.SnapshotLifecycleManagement.cs
  src/Elasticsearch.Net/ElasticLowLevelClient.SnapshotLifecycleManagement.cs
  src/Nest/Descriptors.SnapshotLifecycleManagement.cs
  src/Nest/ElasticClient.SnapshotLifecycleManagement.cs
  src/Nest/Requests.SnapshotLifecycleManagement.cs
  src/Nest/XPack/Slm/ExecuteRetention/ExecuteRetentionRequest.cs
  src/Nest/XPack/Slm/ExecuteRetention/ExecuteRetentionResponse.cs
  src/Nest/_Generated/ApiUrlsLookup.generated.cs
  src/Tests/Tests/XPack/Slm/SlmApiTests.cs
Labels: Port to master, v7.5.0

#4270 Get highest AssemblyFileVersionAttribute version
  src/Elasticsearch.Net/Api/RuntimeInformation.cs
  src/Nest/CrossPlatform/RuntimeInformation.cs
Labels: Bug, v7.5.0

#4268 Support MemberExpression and specific MethodCallExpression
  src/Nest/CommonAbstractions/Extensions/ExpressionExtensions.cs
  src/Nest/CommonAbstractions/Infer/Field/Field.cs
  src/Tests/Tests/ClientConcepts/HighLevel/Caching/FieldResolverCacheTests.cs
  src/Tests/Tests/Tests.csproj
Labels: Bug, v7.5.0

#4271 Support geotile_grid aggregation in composite agg sources.
  src/Nest/Aggregations/Bucket/Composite/CompositeAggregationSource.cs
  src/Nest/Aggregations/Bucket/Composite/GeoTileGridCompositeAggregationSource.cs
  src/Tests/Tests/Aggregations/Bucket/Composite/CompositeAggregationUsageTests.cs
Labels: Port to master, v7.5.0

#4274 Add the ability to require an ingest pipeline.
  src/Nest/IndexModules/IndexSettings/Settings/DynamicIndexSettings.cs
  src/Nest/IndexModules/IndexSettings/Settings/IndexSettingsFormatter.cs
  src/Nest/IndexModules/IndexSettings/Settings/UpdatableIndexSettings.cs
  src/Tests/Tests/IndexModules/IndexSettings/Settings/TypedIndexSettings.cs
Labels: Port to master, v7.5.0

#4275 Add enrich processor and APIs
  src/CodeGeneration/ApiGenerator/Configuration/CodeConfiguration.cs
  src/CodeGeneration/ApiGenerator/RestSpecification/_Patches/enrich.get_policy.patch.json
  src/Elasticsearch.Net/Api/RequestParameters/RequestParameters.Enrich.cs
  src/Elasticsearch.Net/ElasticLowLevelClient.Enrich.cs
  src/Elasticsearch.Net/ElasticLowLevelClient.NoNamespace.cs
  src/Elasticsearch.Net/IElasticLowLevelClient.Generated.cs
  src/Nest/Descriptors.Enrich.cs
  src/Nest/ElasticClient.Enrich.cs
  src/Nest/ElasticClient.NoNamespace.cs
  src/Nest/IElasticClient.Generated.cs
  src/Nest/Ingest/ProcessorFormatter.cs
  src/Nest/Ingest/Processors/EnrichProcessor.cs
  src/Nest/Ingest/ProcessorsDescriptor.cs
  src/Nest/Requests.Enrich.cs
  src/Nest/Requests.cs
  src/Nest/XPack/Enrich/DeletePolicy/DeleteEnrichPolicyRequest.cs
  src/Nest/XPack/Enrich/DeletePolicy/DeleteEnrichPolicyResponse.cs
  src/Nest/XPack/Enrich/EnrichPolicy.cs
  src/Nest/XPack/Enrich/ExecutePolicy/ExecuteEnrichPolicyRequest.cs
  src/Nest/XPack/Enrich/ExecutePolicy/ExecuteEnrichPolicyResponse.cs
  src/Nest/XPack/Enrich/GetPolicy/GetEnrichPolicyRequest.cs
  src/Nest/XPack/Enrich/GetPolicy/GetEnrichPolicyResponse.cs
  src/Nest/XPack/Enrich/NamedPolicy.cs
  src/Nest/XPack/Enrich/PutPolicy/PutEnrichPolicyRequest.cs
  src/Nest/XPack/Enrich/PutPolicy/PutEnrichPolicyResponse.cs
  src/Nest/XPack/Enrich/Stats/EnrichStatsRequest.cs
  src/Nest/XPack/Enrich/Stats/EnrichStatsResponse.cs
  src/Nest/XPack/Info/XPackInfo/XPackInfoResponse.cs
  src/Nest/XPack/Info/XPackUsage/XPackUsageResponse.cs
  src/Nest/_Generated/ApiUrlsLookup.generated.cs
  src/Tests/Tests/Ingest/ProcessorAssertions.cs
  src/Tests/Tests/Ingest/PutPipeline/PutPipelineApiTests.cs
  src/Tests/Tests/XPack/Enrich/DeletePolicy/DeletePolicyApiTests.cs
  src/Tests/Tests/XPack/Enrich/DeletePolicy/DeletePolicyUrlTests.cs
  src/Tests/Tests/XPack/Enrich/ExecutePolicy/ExecutePolicyApiTests.cs
  src/Tests/Tests/XPack/Enrich/ExecutePolicy/ExecutePolicyUrlTests.cs
  src/Tests/Tests/XPack/Enrich/GetPolicy/GetPolicyApiTests.cs
  src/Tests/Tests/XPack/Enrich/GetPolicy/GetPolicyUrlTests.cs
  src/Tests/Tests/XPack/Enrich/PutPolicy/PutPolicyApiTests.cs
  src/Tests/Tests/XPack/Enrich/PutPolicy/PutPolicyUrlTests.cs
  src/Tests/Tests/XPack/Enrich/Stats/StatsApiTests.cs
  src/Tests/Tests/XPack/Enrich/Stats/StatsUrlTests.cs
  src/Tests/Tests/XPack/Ilm/IlmApiTests.cs
  src/Tests/Tests/XPack/Info/XPackInfoApiTests.cs
Labels: Feature, Port to master, v7.5.0

#4276 Add VotingOnly node role
  src/Nest/Cluster/NodesInfo/NodeRole.cs
Labels: Bug, v7.5.0

#4278 DateMath has ToString() value for DateTime.MinValue
  src/Nest/CommonOptions/DateMath/DateMath.cs
  src/Tests/Tests.Reproduce/GithubIssue4228.cs
  src/Tests/Tests/CommonOptions/DateMath/DateMathTests.cs
Labels: Bug, v7.5.0

#4269 Set Accept header when format set on Cat APIs
  src/CodeGeneration/ApiGenerator/Domain/Specification/QueryParameters.cs
  src/CodeGeneration/ApiGenerator/Generator/CodeGenerator.cs
  src/CodeGeneration/ApiGenerator/Views/HighLevel/Requests/PlainRequestBase.cshtml
  src/CodeGeneration/ApiGenerator/Views/HighLevel/Requests/RequestImplementations.cshtml
  src/CodeGeneration/ApiGenerator/Views/LowLevel/RequestParameters/RequestParameters.cshtml
  src/Elasticsearch.Net/Api/RequestParameters/IRequestParameters.cs
  src/Elasticsearch.Net/Api/RequestParameters/RequestParameters.Cat.cs
  src/Elasticsearch.Net/Api/RequestParameters/RequestParameters.cs
  src/Elasticsearch.Net/Transport/Pipeline/RequestData.cs
  src/Elasticsearch.Net/Transport/Pipeline/ResponseBuilder.cs
  src/Nest/CommonAbstractions/Request/RequestBase.cs
  src/Nest/Requests.Cat.cs
  src/Tests/Tests.Reproduce/GithubIssue3907.cs
  src/Tests/Tests.Reproduce/GithubIssue4243.cs
  src/Tests/Tests/Cat/CatIndices/CatIndicesApiTests.cs
Labels: Bug, v7.5.0

#4282 add more 7 minors to CI test matrix
  azure-pipelines.yml
Labels: Infra, v7.5.0

#4283 enrich was forward ported but needed a regen as well
  src/Elasticsearch.Net/Api/RequestParameters/RequestParameters.Enrich.cs
  src/Elasticsearch.Net/ElasticLowLevelClient.Enrich.cs
  src/Nest/Descriptors.Enrich.cs
  src/Nest/Requests.Enrich.cs
  src/Nest/_Generated/ApiUrlsLookup.generated.cs
  src/Tests/Tests/XPack/Enrich/GetPolicy/GetPolicyUrlTests.cs
Labels: Infra

#4281 Fix breaking changes on the 7.x branch before release
  src/CodeGeneration/ApiGenerator/Configuration/Overrides/GlobalOverrides.cs
  src/Elasticsearch.Net/Api/RequestParameters/RequestParameters.Cat.cs
  src/Nest/Descriptors.Cat.cs
  src/Nest/Requests.Cat.cs
Labels: Port to master, v7.5.0

#4272 Add support to retrieve all API keys if user has privilege.
  src/Tests/Tests/Framework/EndpointTests/CoordinatedIntegrationTestBase.cs
  src/Tests/Tests/Framework/EndpointTests/TestState/CoordinatedUsage.cs
  src/Tests/Tests/XPack/Security/ApiKey/SecurityApiKeyTests.cs
Labels: Port to master, v7.5.0

#4273 Add Pause/Resume Auto Follower APIs
  src/CodeGeneration/ApiGenerator/Configuration/CodeConfiguration.cs
  src/Elasticsearch.Net/Api/RequestParameters/RequestParameters.CrossClusterReplication.cs
  src/Elasticsearch.Net/ElasticLowLevelClient.CrossClusterReplication.cs
  src/Nest/Descriptors.CrossClusterReplication.cs
  src/Nest/ElasticClient.CrossClusterReplication.cs
  src/Nest/Requests.CrossClusterReplication.cs
  src/Nest/XPack/CrossClusterReplication/AutoFollow/PauseAutoFollowPattern/PauseAutoFollowPatternRequest.cs
  src/Nest/XPack/CrossClusterReplication/AutoFollow/PauseAutoFollowPattern/PauseAutoFollowPatternResponse.cs
  src/Nest/XPack/CrossClusterReplication/AutoFollow/ResumeAutoFollowPattern/ResumeAutoFollowPatternRequest.cs
  src/Nest/XPack/CrossClusterReplication/AutoFollow/ResumeAutoFollowPattern/ResumeAutoFollowPatternResponse.cs
  src/Nest/_Generated/ApiUrlsLookup.generated.cs
  src/Tests/Tests/XPack/CrossClusterReplication/AutoFollow/PauseAutoFollowPattern/PauseAutoFollowPatternUrlTests.cs
  src/Tests/Tests/XPack/CrossClusterReplication/AutoFollow/ResumeAutoFollowPattern/ResumeAutoFollowPatternUrlTests.cs
  src/Tests/Tests/XPack/CrossClusterReplication/CrossClusterReplicationAutoFollowTests .cs
Labels: Port to master, v7.5.0

#4277 Add allow_lazy_open to machine learning jobs.
  src/Nest/XPack/MachineLearning/Job/Config/Job.cs
  src/Nest/XPack/MachineLearning/PutJob/PutJobRequest.cs
  src/Nest/XPack/MachineLearning/PutJob/PutJobResponse.cs
  src/Nest/XPack/MachineLearning/UpdateJob/UpdateJobRequest.cs
Labels: Port to master, v7.5.0

#4286 Add option to stop machine learning datafeed that finds no data.
  src/Nest/XPack/MachineLearning/Datafeed/DatafeedConfig.cs
  src/Nest/XPack/MachineLearning/PutDatafeed/PutDatafeedRequest.cs
  src/Nest/XPack/MachineLearning/PutDatafeed/PutDatafeedResponse.cs
  src/Nest/XPack/MachineLearning/UpdateDataFeed/UpdateDatafeedRequest.cs
  src/Nest/XPack/MachineLearning/UpdateDataFeed/UpdateDatafeedResponse.cs
Labels: Port to master, v7.5.0

#4290 Fix #4289 low level client index http method generation wrong
  src/CodeGeneration/ApiGenerator/Domain/Specification/ApiEndpoint.cs
  src/Elasticsearch.Net/ElasticLowLevelClient.NoNamespace.cs
  src/Elasticsearch.Net/IElasticLowLevelClient.Generated.cs
  src/Tests/Tests/Document/Single/Index/IndexUrlTests.cs
  src/Tests/Tests/Framework/EndpointTests/UrlTests.cs
Labels: 7.5.1, Bug
