Repository elastic/elasticsearch-net, pull requests merged in 2019-08, with the labels that each got.

#3989 AuditTrail integration assertion fix
  src/Tests/Tests/ClientConcepts/Troubleshooting/AuditTrail.doc.cs
Labels: Infra, Port to 6.x, Port to master, v7.2.0

#3986 Add 7.2 to the azure devops matrix
  azure-pipelines.yml
Labels: Feature, Infra, Port to 7.x, v7.2.0

#3966 Expose Response on GetTaskResponse
  src/Nest/Cluster/TaskManagement/GetTask/GetTaskResponse.cs
  src/Nest/CommonAbstractions/LazyDocument/LazyDocument.cs
  src/Tests/Tests/Cluster/TaskManagement/GetTask/GetTaskApiTests.cs
Labels: Feature, v7.2.0

#3998 Add numeric_type sorting option.
  src/Nest/Search/Search/Sort/NumericType.cs
  src/Nest/Search/Search/Sort/SortBase.cs
  src/Tests/Tests/Search/Request/SortUsageTests.cs
Labels: Port to master, v7.2.0

#3996 Add created_by info to usage stats.
  src/Nest/XPack/Info/XPackUsage/XPackUsageResponse.cs
Labels: Port to master, v7.2.0

#3995 Add packaging to cluster stats response.
  src/Nest/Cluster/ClusterStats/ClusterNodesStats.cs
Labels: Port to master, v7.2.0

#3992 Expose external refreshes through the stats API
  src/Nest/CommonOptions/Stats/RefreshStats.cs
Labels: Port to master, v7.2.0

#4007 Fixed formatting typos (’ --> ')
  src/Nest/Ingest/Processors/DateIndexNameProcessor.cs
Labels: Docs, Port to 7.x, v7.2.0, v8.0.0

#3988 Force selection of calendar or fixed intervals in date histo aggregations
  src/Nest/Aggregations/Bucket/DateHistogram/DateHistogramAggregation.cs
  src/Tests/Tests.Reproduce/GithubIssue3673.cs
  src/Tests/Tests/Aggregations/Bucket/DateHistogram/DateHistogramAggregationUsageTests.cs
  src/Tests/Tests/Aggregations/Pipeline/AverageBucket/AverageBucketAggregationUsageTests.cs
  src/Tests/Tests/Aggregations/Pipeline/BucketScript/BucketScriptAggregationUsageTests.cs
  src/Tests/Tests/Aggregations/Pipeline/BucketSelector/BucketSelectorAggregationUsageTests.cs
  src/Tests/Tests/Aggregations/Pipeline/BucketSort/BucketSortAggregationUsageTests.cs
  src/Tests/Tests/Aggregations/Pipeline/CumulativeSum/CumulativeSumAggregationUsageTests.cs
  src/Tests/Tests/Aggregations/Pipeline/Derivative/DerivativeAggregationUsageTests.cs
  src/Tests/Tests/Aggregations/Pipeline/ExtendedStatsBucket/ExtendedStatsBucketAggregationUsageTests.cs
  src/Tests/Tests/Aggregations/Pipeline/MaxBucket/MaxBucketAggregationUsageTests.cs
  src/Tests/Tests/Aggregations/Pipeline/MinBucket/MinBucketAggregationUsageTests.cs
  src/Tests/Tests/Aggregations/Pipeline/MovingAverage/MovingAverageEwmaAggregationUsageTests.cs
  src/Tests/Tests/Aggregations/Pipeline/MovingAverage/MovingAverageHoltLinearAggregationUsageTests.cs
  src/Tests/Tests/Aggregations/Pipeline/MovingAverage/MovingAverageHoltWintersAggregationUsageTests.cs
  src/Tests/Tests/Aggregations/Pipeline/MovingAverage/MovingAverageLinearAggregationUsageTests.cs
  src/Tests/Tests/Aggregations/Pipeline/MovingAverage/MovingAverageSimpleAggregationUsageTests.cs
  src/Tests/Tests/Aggregations/Pipeline/MovingFunction/MovingFunctionAggregationUsageTests.cs
  src/Tests/Tests/Aggregations/Pipeline/PercentilesBucket/PercentilesBucketAggregationUsageTests.cs
  src/Tests/Tests/Aggregations/Pipeline/SerialDifferencing/SerialDifferencingAggregationUsageTests.cs
  src/Tests/Tests/Aggregations/Pipeline/StatsBucket/StatsBucketAggregationUsageTests.cs
  src/Tests/Tests/Aggregations/Pipeline/SumBucket/SumBucketAggregationUsageTests.cs
  src/Tests/Tests/CodeStandards/Descriptors.doc.cs
Labels: Port to master, v7.2.0

#3984 Introduce the columnar option for SQL REST requests.
  src/Nest/XPack/Sql/QuerySql/QuerySqlRequest.cs
  src/Nest/XPack/Sql/QuerySql/QuerySqlResponse.cs
Labels: Port to master, v7.2.0

#3997 Serialize GeoLocation with internal serializer
  src/Serializers/Nest.JsonNetSerializer/Converters/HandleNestTypesOnSourceJsonConverter.cs
  src/Tests/Tests.Reproduce/GitHubIssue3981.cs
Labels: Bug, Port to 7.x, Port to master, v6.8.2

#4005 Add a CloudConnectionPool
  src/Elasticsearch.Net/Configuration/ConnectionConfiguration.cs
  src/Elasticsearch.Net/Configuration/Security/ApiKeyAuthenticationCredentials.cs
  src/Elasticsearch.Net/Configuration/Security/BasicAuthenticationCredentials.cs
  src/Elasticsearch.Net/ConnectionPool/CloudConnectionPool.cs
  src/Elasticsearch.Net/ConnectionPool/SingleNodeConnectionPool.cs
  src/Elasticsearch.Net/ElasticLowLevelClient.cs
  src/Nest/CommonAbstractions/ConnectionSettings/ConnectionSettingsBase.cs
  src/Nest/ElasticClient.cs
  src/Tests/Tests.Configuration/tests.default.yaml
  src/Tests/Tests/ClientConcepts/ConnectionPooling/BuildingBlocks/ConnectionPooling.doc.cs
Labels: Feature, Port to master, v7.2.0, v8.0.0

#3983 Implement distance_feature query
  src/Nest/QueryDsl/Abstractions/Container/IQueryContainer.cs
  src/Nest/QueryDsl/Abstractions/Container/QueryContainer-Assignments.cs
  src/Nest/QueryDsl/Abstractions/Container/QueryContainerDescriptor.cs
  src/Nest/QueryDsl/Query.cs
  src/Nest/QueryDsl/Specialized/DistanceFeature/DistanceFeatureQuery.cs
  src/Nest/QueryDsl/Visitor/DslPrettyPrintVisitor.cs
  src/Nest/QueryDsl/Visitor/QueryVisitor.cs
  src/Nest/QueryDsl/Visitor/QueryWalker.cs
  src/Tests/Tests/QueryDsl/Specialized/DistanceFeature/DistanceFeatureTimeQueryUsageTests.cs
Labels: Port to master, v7.2.0

#4002 make sure types that implement DebuggerDisplay override ToString sinc…
  src/Nest/CommonAbstractions/Infer/Field/Field.cs
  src/Nest/CommonAbstractions/Infer/Fields/Fields.cs
  src/Nest/CommonAbstractions/Infer/Id/Id.cs
  src/Nest/CommonAbstractions/Infer/Id/Ids.cs
  src/Nest/CommonAbstractions/Infer/IndexName/IndexName.cs
  src/Nest/CommonAbstractions/Infer/Indices/Indices.cs
  src/Nest/CommonAbstractions/Infer/JoinFieldRouting/Routing.cs
  src/Nest/CommonAbstractions/Infer/Name/Name.cs
  src/Nest/CommonAbstractions/Infer/Name/Names.cs
  src/Nest/CommonAbstractions/Infer/NodeId/NodeIds.cs
  src/Nest/CommonAbstractions/Infer/PropertyName/PropertyName.cs
  src/Nest/CommonAbstractions/Infer/RelationName/RelationName.cs
  src/Nest/Mapping/Types/PropertyBase.cs
Labels: Feature, Port to 7.x, v7.2.0, v8.0.0

#4014 BulkAll() improvements
  src/Nest/CommonAbstractions/Extensions/Extensions.cs
  src/Nest/Document/Multiple/BulkAll/BulkAllObservable.cs
  src/Nest/Document/Multiple/BulkAll/BulkAllRequest.cs
  src/Tests/Tests/Document/Multiple/BulkAll/BulkAllExceptionApiTests.cs
  src/Tests/Tests/Framework/VirtualClustering/VirtualizedCluster.cs
Labels: Bug, Feature, v7.2.0, v8.0.0

#4016 more docs examples
  examples/Mapping/Dynamic/TemplatesPage/0b91c082258ce623cc716b679aace653.asciidoc
  examples/Mapping/Dynamic/TemplatesPage/4f54b88e05c7a62901062e9e0ed13e5a.asciidoc
  examples/Mapping/Dynamic/TemplatesPage/bb33e638fdeded7d721d9bbac2305fda.asciidoc
  examples/Mapping/Dynamic/TemplatesPage/be51ed37c8425d281a8153abe56b04cb.asciidoc
  examples/QueryDsl/QueryStringQueryPage/28aad2c5942bfb221c2bf1bbdc01658e.asciidoc
  examples/QueryDsl/QueryStringQueryPage/58b5003c0a53a39bf509aa3797aad471.asciidoc
  examples/QueryDsl/QueryStringQueryPage/60ee33f3acfdd0fe6f288ac77312c780.asciidoc
  examples/QueryDsl/QueryStringQueryPage/6f21a878fee3b43c5332b81aaddbeac7.asciidoc
  examples/QueryDsl/QueryStringQueryPage/81f09836772b03f6e7e8e7986409d67e.asciidoc
  examples/QueryDsl/QueryStringQueryPage/a2a25aad1fea9a541b52ac613c78fb64.asciidoc
  examples/QueryDsl/QueryStringQueryPage/be1bd47393646ac6bbee177d1cdb7738.asciidoc
  examples/QueryDsl/QueryStringQueryPage/db6cba451ba562abe953d09ad80cc15c.asciidoc
  examples/QueryDsl/QueryStringQueryPage/e17e8852ec3f31781e1364f4dffeb6d0.asciidoc
  examples/QueryDsl/QueryStringQueryPage/f2d68493abd3ca430bd03a7f7f8d18f9.asciidoc
  examples/QueryDsl/QueryStringQueryPage/f32f0c19b42de3b87dd764fe4ca17e7c.asciidoc
  examples/QueryDsl/QueryStringQueryPage/fdd38f0d248385a444c777e7acd97846.asciidoc
  examples/QueryDsl/QueryStringQueryPage/fe1dd67108b04e07d0832b539d4e0d99.asciidoc
  examples/Root/AnalysisPage/7ffee3c2a5581994fc0ea59dd106d39f.asciidoc
  examples/Root/MappingPage/b311b42b7dcc69821df1f77bfaf2d50d.asciidoc
  examples/Root/SearchPage/014b788c879e4aaa1020672e45e25473.asciidoc
  examples/Root/SearchPage/189a921df2f5b1fe580937210ce9c1c2.asciidoc
  examples/Root/SearchPage/8acc1d67b152e7027e0f0e1a8b4b2431.asciidoc
  src/Examples/Examples/Mapping/Dynamic/FieldMappingPage.cs
  src/Examples/Examples/Mapping/Dynamic/TemplatesPage.cs
  src/Examples/Examples/QueryDsl/QueryStringQueryPage.cs
  src/Examples/Examples/ResponseExtensions.cs
  src/Examples/Examples/Root/AnalysisPage.cs
  src/Examples/Examples/Root/GettingStartedPage.cs
  src/Examples/Examples/Root/MappingPage.cs
  src/Examples/Examples/Root/SearchPage.cs
Labels: Docs

#4017 Add XML docs for index inference on BulkAll
  src/Nest/Document/Multiple/BulkAll/BulkAllRequest.cs
  src/Nest/Document/Multiple/BulkAll/ElasticClient-BulkAll.cs
Labels: Docs

#4015 Add if_seq_no and if_primary_term to bulk updates.
  src/Nest/Document/Multiple/Bulk/BulkOperation/BulkIndex.cs
  src/Nest/Document/Multiple/Bulk/BulkOperation/BulkOperationBase.cs
  src/Nest/Document/Multiple/Bulk/BulkOperation/BulkOperationsCollection.cs
  src/Nest/Document/Multiple/Bulk/BulkOperation/BulkUpdate.cs
  src/Nest/Document/Multiple/Bulk/BulkOperation/BulkUpdateBody.cs
  src/Nest/Document/Multiple/BulkAll/BulkAllObservable.cs
Labels: Feature, v6.8.2, v7.2.0

#4019 Map node failures.
  src/Nest/Cluster/NodesResponseBase.cs
  src/Tests/Tests/Cluster/NodesUsage/NodesUsageUnitTests.cs
Labels: Port to master, v7.2.0

#4022 Delete existing docs when generating new docs
  src/CodeGeneration/DocGenerator/LitUp.cs
Labels: Docs

#4026 Ensure GeoLocationFormatter returns GeoLocation type
  src/Nest/QueryDsl/Geo/GeoLocationFormatter.cs
Labels: Bug, v7.2.0

#4027 Normalize exception from cancelling an observable coordinated operation
  src/Elasticsearch.Net/Transport/Pipeline/RequestPipeline.cs
  src/Elasticsearch.Net/Transport/Transport.cs
  src/Nest/CommonAbstractions/Reactive/CoordinatedRequestObserverBase.cs
  src/Tests/Tests/Document/Multiple/BulkAll/BulkAllCancellationTokenApiTests.cs
  src/Tests/Tests/Document/Multiple/BulkAll/BulkAllDisposeApiTests.cs
Labels: Bug, v7.2.0

#4024 feat(date-range-agg): Add Missing method
  src/Nest/Aggregations/Bucket/DateRange/DateRangeAggregation.cs
Labels: Feature, v6.8.2, v7.2.0

#4042 Serialize Distance and Percentiles aggregate using an invariant locale
  src/Nest/Aggregations/AggregateFormatter.cs
  src/Nest/CommonOptions/Geo/Distance.cs
  src/Tests/Tests.Reproduce/GithubIssue4041.cs
  src/Tests/Tests.Reproduce/GithubIssue4044.cs
  src/Tests/Tests/Tests.csproj
Labels: Bug, v7.2.0

#4047 Ensure filters created are deleted
  src/Tests/Tests/XPack/MachineLearning/GetFilters/GetFiltersApiTests.cs
  src/Tests/Tests/XPack/MachineLearning/MachineLearningIntegrationTestBase.cs
  src/Tests/Tests/XPack/MachineLearning/PutFilter/PutFilterApiTests.cs
  src/Tests/Tests/XPack/MachineLearning/UpdateFilter/UpdateFilterApiTests.cs
Labels: Port to master, flakey test, v7.3.0

#4049 Add ml to NodeRole enum
  src/Nest/Cluster/NodesInfo/NodeRole.cs
Labels: Bug, v8.0.0

#4053 Add minimum_interval to AutoDateHistogram aggregation
  src/Nest/Aggregations/Bucket/AutoDateHistogram/AutoDateHistogramAggregation.cs
  src/Nest/Aggregations/Bucket/AutoDateHistogram/MinimumInterval.cs
  src/Tests/Tests/Aggregations/Bucket/AutoDateHistogram/AutoDateHistogramAggregationUsageTests.cs
Labels: Feature, v7.3.0

#4054 Implement Rare Terms aggregation
  src/Nest/Aggregations/AggregateDictionary.cs
  src/Nest/Aggregations/AggregationContainer.cs
  src/Nest/Aggregations/Bucket/RareTerms/RareTermsAggregation.cs
  src/Nest/Aggregations/Bucket/RareTerms/RareTermsBucket.cs
  src/Nest/Aggregations/Visitor/AggregationVisitor.cs
  src/Nest/Aggregations/Visitor/AggregationWalker.cs
  src/Tests/Tests/Aggregations/Bucket/RareTerms/RareTermsAggregationUsageTests.cs
Labels: Feature, v7.3.0

#4056 Deprecate CommonTerms query and CutoffFrequency of MatchQuery
  src/Nest/QueryDsl/Abstractions/Container/IQueryContainer.cs
  src/Nest/QueryDsl/Abstractions/Container/QueryContainer-Assignments.cs
  src/Nest/QueryDsl/Abstractions/Container/QueryContainerDescriptor.cs
  src/Nest/QueryDsl/FullText/CommonTerms/CommonTermsQuery.cs
  src/Nest/QueryDsl/FullText/Match/MatchQuery.cs
  src/Nest/QueryDsl/Query.cs
  src/Nest/QueryDsl/Visitor/DslPrettyPrintVisitor.cs
  src/Nest/QueryDsl/Visitor/QueryVisitor.cs
  src/Tests/Tests/QueryDsl/FullText/CommonTerms/CommonTermsUsageTests.cs
  src/Tests/Tests/QueryDsl/FullText/Match/MatchUsageTests.cs
Labels: Deprecation, v7.3.0

#4058 Add support for flattened datatype
  src/Nest/Mapping/Types/Complex/Flattened/FlattenedAttribute.cs
  src/Nest/Mapping/Types/Complex/Flattened/FlattenedProperty.cs
  src/Nest/Mapping/Types/FieldType.cs
  src/Nest/Mapping/Types/Properties.cs
  src/Nest/Mapping/Types/PropertyFormatter.cs
  src/Nest/Mapping/Visitor/IMappingVisitor.cs
  src/Nest/Mapping/Visitor/IPropertyVisitor.cs
  src/Nest/Mapping/Visitor/MappingWalker.cs
  src/Nest/Mapping/Visitor/NoopPropertyVisitor.cs
  src/Tests/Tests.Core/ManagedElasticsearch/NodeSeeders/DefaultSeeder.cs
  src/Tests/Tests.Domain/Extensions/DateTimeExtensions.cs
  src/Tests/Tests.Domain/Project.cs
  src/Tests/Tests/Indices/MappingManagement/GetMapping/GetMappingApiTest.cs
  src/Tests/Tests/Indices/MappingManagement/PutMapping/PutMappingApiTest.cs
  src/Tests/Tests/Mapping/Types/Complex/Flattened/FlattenedAttributeTests.cs
  src/Tests/Tests/Mapping/Types/Complex/Flattened/FlattenedPropertyTests.cs
Labels: Feature, v7.3.0

#4060 Add wildcard and prefix interval rules
  src/CodeGeneration/DocGenerator/StringExtensions.cs
  src/Nest/QueryDsl/FullText/Intervals/IntervalsPrefix.cs
  src/Nest/QueryDsl/FullText/Intervals/IntervalsQuery.cs
  src/Nest/QueryDsl/FullText/Intervals/IntervalsWildcard.cs
  src/Tests/Tests/QueryDsl/FullText/Intervals/IntervalsUsageTests.cs
Labels: Feature, v7.3.0
