Repository elastic/elasticsearch-net, pull requests merged in 2019-01, with the labels that each got.

#3543 Return overloads that do not take format on Field in 6.x,
  src/Nest/CommonAbstractions/Infer/Field/Field.cs
  src/Nest/CommonAbstractions/Static/Infer.cs
  src/Tests/Tests/ClientConcepts/HighLevel/Inference/FieldInference.doc.cs
  src/Tests/Tests/Search/Search/SearchApiTests.cs
Labels: 6.4.2, Bug

#3518 Updated Xmldocs
  src/Elasticsearch.Net/Configuration/ConnectionConfiguration.cs
  src/Elasticsearch.Net/Configuration/IConnectionConfigurationValues.cs
  src/Elasticsearch.Net/Configuration/RequestConfiguration.cs
Labels: v6.4.2

#3519 Document how to use a custom authentication header e.g Kerberos
  src/Tests/Tests/ClientConcepts/Connection/ModifyingDefaultConnection.doc.cs
Labels: Port to master, v6.5.0

#3520 deprecate standard token filter as per elastic/elasticsearch#33468
  src/Nest/Analysis/TokenFilters/StandardTokenFilter.cs
  src/Nest/Analysis/TokenFilters/TokenFilterJsonConverter.cs
  src/Nest/Analysis/TokenFilters/TokenFilters.cs
  src/Nest/Indices/Analyze/AnalyzeTokenFilters.cs
  src/Tests/Tests/Analysis/TokenFilters/TokenFilterTests.cs
Labels: v6.5.0

#3521 Add support for the auto_date_histogram aggregations
  src/Nest/Aggregations/AggregateDictionary.cs
  src/Nest/Aggregations/AggregateJsonConverter.cs
  src/Nest/Aggregations/AggregationContainer.cs
  src/Nest/Aggregations/Bucket/AutoDateHistogram/AutoDateHistogramAggregation.cs
  src/Nest/Aggregations/Bucket/AutoDateHistogram/AutoDateHistogramBucket.cs
  src/Nest/Aggregations/Bucket/BucketAggregate.cs
  src/Nest/Aggregations/Bucket/DateHistogram/DateHistogramAggregation.cs
  src/Tests/Tests/Aggregations/Bucket/AutoDateHistogram/AutoDateHistogramAggregationUsageTests.cs
Labels: v6.5.0

#3528 V65/processors
  src/Nest/Ingest/PipelineJsonConverter.cs
  src/Nest/Ingest/Processor.cs
  src/Nest/Ingest/Processors/DissectProcessor.cs
  src/Nest/Ingest/Processors/DropProcessor.cs
  src/Nest/Ingest/Processors/PipelineProcessor.cs
  src/Nest/Ingest/Processors/SetSecurityUserProcessor .cs
  src/Nest/Ingest/ProcessorsDescriptor.cs
  src/Tests/Tests/Ingest/ProcessorAssertions.cs
Labels: v6.5.0

#3529 Add processor stats to node ingest stats
  src/Nest/Cluster/NodesStats/Statistics/IngestStats.cs
  src/Tests/Tests.Core/ManagedElasticsearch/NodeSeeders/DefaultSeeder.cs
  src/Tests/Tests/Cluster/NodesStats/NodesStatsApiTests.cs
Labels: v6.5.0

#3530 Add support for default pipeline on index settings
  src/Nest/IndexModules/IndexSettings/Settings/DynamicIndexSettings.cs
  src/Nest/IndexModules/IndexSettings/Settings/IndexSettings.cs
  src/Nest/IndexModules/IndexSettings/Settings/IndexSettingsConverter.cs
  src/Nest/IndexModules/IndexSettings/Settings/UpdatableIndexSettings.cs
  src/Tests/Tests/IndexModules/IndexSettings/Settings/TypedIndexSettings.cs
Labels: v6.5.0

#3531 Add support for source only snapshot repository
  src/Nest/Ingest/Processors/Plugins/GeoIpProcessor.cs
  src/Nest/Modules/SnapshotAndRestore/Repositories/AzureRepository.cs
  src/Nest/Modules/SnapshotAndRestore/Repositories/CreateRepository/CreateRepositoryRequest.cs
  src/Nest/Modules/SnapshotAndRestore/Repositories/FileSystemRepository.cs
  src/Nest/Modules/SnapshotAndRestore/Repositories/HdfsRepository.cs
  src/Nest/Modules/SnapshotAndRestore/Repositories/ISnapshotRepository.cs
  src/Nest/Modules/SnapshotAndRestore/Repositories/ReadOnlyUrlRepository.cs
  src/Nest/Modules/SnapshotAndRestore/Repositories/S3Repository.cs
  src/Nest/Modules/SnapshotAndRestore/Repositories/SourceOnlyRepository .cs
  src/Tests/Tests/Modules/SnapshotAndRestore/Repositories/CreateRepository/CreateRepositoryApiTests.cs
Labels: v6.5.0

#3534 Adds support for get_basic_license_status and start_basic_license API's
  src/CodeGeneration/ApiGenerator/ApiGenerator.cs
  src/Elasticsearch.Net/Domain/RequestParameters/RequestParameters.Generated.cs
  src/Elasticsearch.Net/ElasticLowLevelClient.Generated.cs
  src/Elasticsearch.Net/IElasticLowLevelClient.Generated.cs
  src/Nest/XPack/License/GetBasicLicenseStatus/ElasticClient-GetBasicLicenseStatus.cs
  src/Nest/XPack/License/GetBasicLicenseStatus/GetBasicLicenseStatusRequest.cs
  src/Nest/XPack/License/GetBasicLicenseStatus/GetBasicLicenseStatusResponse.cs
  src/Nest/XPack/License/StartBasicLicense/ElasticClient-StartBasicLicense.cs
  src/Nest/XPack/License/StartBasicLicense/StartBasicLicenseRequest.cs
  src/Nest/XPack/License/StartBasicLicense/StartBasicLicenseResponse.cs
  src/Nest/_Generated/_Descriptors.generated.cs
  src/Nest/_Generated/_LowLevelDispatch.generated.cs
  src/Nest/_Generated/_Requests.generated.cs
  src/Tests/Tests/CodeStandards/Responses.doc.cs
  src/Tests/Tests/XPack/License/GetBasicLicenseStatus/GetBasicLicenseStatusApiTests.cs
  src/Tests/Tests/XPack/License/GetBasicLicenseStatus/GetBasicLicenseStatusUrlTests.cs
  src/Tests/Tests/XPack/License/StartBasicLicense/StartBasicLicenseApiTests.cs
  src/Tests/Tests/XPack/License/StartBasicLicense/StartBasicLicenseUrlTests.cs
Labels: Feature, v6.5.0

#3492 Move files from machine learning zip
  src/Tests/Tests.Core/ManagedElasticsearch/Clusters/XPackCluster.cs
  src/Tests/Tests/XPack/MachineLearning/MachineLearningCluster.cs
Labels: Cleanup

#3545 fix #3544 JsonNetSerializer now also implements IPropertyMappingProvi…
  src/Nest/CommonAbstractions/ConnectionSettings/ConnectionSettingsBase.cs
  src/Serializers/Nest.JsonNetSerializer/ConnectionSettingsAwareSerializerBase.PropertyMappingProvider.cs
  src/Tests/Tests/ClientConcepts/HighLevel/Inference/FieldInference.doc.cs
Labels: Feature, v6.5.0

#3537 add support for the get ssl certificates API
  src/CodeGeneration/ApiGenerator/ApiGenerator.cs
  src/CodeGeneration/ApiGenerator/Program.cs
  src/Elasticsearch.Net/Domain/RequestParameters/RequestParameters.Generated.cs
  src/Elasticsearch.Net/ElasticLowLevelClient.Generated.cs
  src/Elasticsearch.Net/IElasticLowLevelClient.Generated.cs
  src/Nest/XPack/Ssl/GetCertificates/ElasticClient-GetCertificates.cs
  src/Nest/XPack/Ssl/GetCertificates/GetCertificatesRequest.cs
  src/Nest/XPack/Ssl/GetCertificates/GetCertificatesResponse.cs
  src/Nest/_Generated/_Descriptors.generated.cs
  src/Nest/_Generated/_LowLevelDispatch.generated.cs
  src/Nest/_Generated/_Requests.generated.cs
  src/Tests/Tests/XPack/Ssl/GetCertificates/GetCertificatesApiTests.cs
  src/Tests/Tests/XPack/Ssl/GetCertificates/GetCertificatesUrlTests.cs
Labels: Feature, v6.5.0

#3536 add support for the reload secure settings API
  src/CodeGeneration/ApiGenerator/ApiGenerator.cs
  src/Elasticsearch.Net/Domain/RequestParameters/RequestParameters.Generated.cs
  src/Elasticsearch.Net/ElasticLowLevelClient.Generated.cs
  src/Elasticsearch.Net/IElasticLowLevelClient.Generated.cs
  src/Nest/Cluster/ReloadSecureSettings/ElasticClient-ReloadSecureSettings.cs
  src/Nest/Cluster/ReloadSecureSettings/ReloadSecureSettingsRequest.cs
  src/Nest/Cluster/ReloadSecureSettings/ReloadSecureSettingsResponse.cs
  src/Nest/_Generated/_Descriptors.generated.cs
  src/Nest/_Generated/_LowLevelDispatch.generated.cs
  src/Nest/_Generated/_Requests.generated.cs
  src/Tests/Tests/Cluster/ReloadSecureSettings/ReloadSecureSettingsApiTests.cs
  src/Tests/Tests/Cluster/ReloadSecureSettings/ReloadSecureSettingsUrlTests.cs
Labels: Feature, v6.5.0

#3535 add support for the rollup index caps API
  src/CodeGeneration/ApiGenerator/ApiGenerator.cs
  src/Elasticsearch.Net/Domain/RequestParameters/RequestParameters.Generated.cs
  src/Elasticsearch.Net/ElasticLowLevelClient.Generated.cs
  src/Elasticsearch.Net/IElasticLowLevelClient.Generated.cs
  src/Nest/XPack/RollUp/DeleteRollupJob/DeleteRollupJobResponse.cs
  src/Nest/XPack/RollUp/GetRollupIndexCapabilities/ElasticClient-GetRollupIndexCapabilities.cs
  src/Nest/XPack/RollUp/GetRollupIndexCapabilities/GetRollupIndexCapabilitiesRequest.cs
  src/Nest/XPack/RollUp/GetRollupIndexCapabilities/GetRollupIndexCapabilitiesResponse.cs
  src/Nest/_Generated/_Descriptors.generated.cs
  src/Nest/_Generated/_LowLevelDispatch.generated.cs
  src/Nest/_Generated/_Requests.generated.cs
  src/Tests/Tests/XPack/Rollup/GetRollupCapabilities/GetRollupCapabilitiesUrlTests.cs
  src/Tests/Tests/XPack/Rollup/GetRollupIndexCapabilities/GetRollupIndexCapabilitiesUrlTests.cs
  src/Tests/Tests/XPack/Rollup/RollupJobCrudTests.cs
Labels: Feature, v6.5.0

#3556 [DOCS] Comments out broken link
  docs/aggregations/bucket/auto-date-histogram/auto-date-histogram-aggregation-usage.asciidoc
Labels: Docs

#3555 [DOCS] Changed URL from 6.4 to 6.5
  docs/aggregations/bucket/auto-date-histogram/auto-date-histogram-aggregation-usage.asciidoc
Labels: Docs
