Repository elastic/elasticsearch-net, pull requests merged in 2019-03, with the labels that each got.

#3558 Add keywords_pattern to Keyword Marker Token Filter.
  src/Nest/Analysis/TokenFilters/KeywordMarkerTokenFilter.cs
  src/Tests/Tests/Analysis/TokenFilters/TokenFilterTests.cs
Labels: Port to master, v6.6.0

#3557 Use the version number present in the global.json file when generating documentation
  src/CodeGeneration/DocGenerator/Program.cs
Labels: Port to 6.x

#3572 Add articles_case to elision token filter
  src/Nest/Analysis/TokenFilters/ElisionTokenFilter.cs
  src/Tests/Tests/Analysis/TokenFilters/TokenFilterTests.cs
Labels: Port to 5.x, Port to 6.x, v5.6.6, v6.6.0

#3580 Avoid doing multiple dictionary lookups
  src/Elasticsearch.Net/Responses/Sniff/SniffResponse.cs
  src/Elasticsearch.Net/Serialization/SimpleJson.cs
  src/Nest/Aggregations/Metric/PercentileRanks/PercentileRanksAggregationJsonConverter.cs
  src/Nest/Aggregations/Metric/Percentiles/PercentilesAggregationJsonConverter.cs
  src/Nest/Aggregations/Pipeline/MovingAverage/MovingAverageAggregationJsonConverter.cs
  src/Nest/CommonAbstractions/ConnectionSettings/ConnectionSettingsBase.cs
  src/Nest/CommonOptions/Scripting/ScriptJsonConverter.cs
  src/Nest/IndexModules/IndexSettings/Settings/IndexSettingsConverter.cs
  src/Nest/Modules/SnapshotAndRestore/Repositories/GetRepository/GetRepositoryResponse.cs
  src/Nest/XPack/Watcher/Condition/ScriptConditionBase.cs
  src/Nest/XPack/Watcher/Input/ChainInput.cs
  src/Nest/XPack/Watcher/Transform/ScriptTransformBase.cs
Labels: Cleanup, Performance, Port to 5.x, Port to master, port to 7.x

#3586 fix #3582 low level client sniffing
  src/Elasticsearch.Net/Serialization/SimpleJson.cs
  src/Tests/Tests/ClientConcepts/LowLevel/SniffOnLowLevelClient.cs
Labels: Bug, v6.5.1

#3587 fix #3582 low level client sniffing
  src/Elasticsearch.Net/Serialization/SimpleJson.cs
  src/Tests/Tests/ClientConcepts/LowLevel/SniffOnLowLevelClient.cs
Labels: Bug, v5.6.7

#3588 fix #3585 VoidResponse should not be shared
  src/Elasticsearch.Net/Transport/Pipeline/ResponseBuilder.cs
Labels: Bug, v5.6.7, v6.5.1

#3589 fix #3578 Add support for disabling id inference
  src/Nest/CommonAbstractions/ConnectionSettings/ClrTypeDefaults.cs
  src/Nest/CommonAbstractions/ConnectionSettings/ConnectionSettingsBase.cs
  src/Nest/CommonAbstractions/ConnectionSettings/IConnectionSettingsValues.cs
  src/Nest/CommonAbstractions/Infer/Id/IdResolver.cs
  src/Nest/CommonAbstractions/SerializationBehavior/PropertyMapping.cs
  src/Tests/Tests.Core/Xunit/ProjectReferenceOnlyAttribute.cs
  src/Tests/Tests/ClientConcepts/HighLevel/Inference/IdsInference.doc.cs
  src/Tests/Tests/CodeStandards/Descriptors.doc.cs
Labels: Feature, v6.6.0, v7.0.0

#3613 6.x
  src/Nest/CommonAbstractions/DictionaryLike/IsAReadOnlyDictionary/IsADictionaryBase.cs
  src/Nest/CommonAbstractions/Extensions/TypeExtensions.cs
  src/Nest/Search/MultiSearch/MultiSearchJsonConverter.cs
  src/Nest/Search/MultiSearchTemplate/MultiSearchTemplateJsonConverter.cs
  src/Nest/XPack/MachineLearning/PostJobData/PostJobDataRequest.cs
Labels: Feature, Performance, v5.6.7, v6.6.0

#3574 Move linux build to AppVeyor
  .travis.yml
  appveyor.yml
  azure-pipelines.yml
  build/scripts/Building.fsx
  build/scripts/Testing.fsx
  global.json
  readme.md
  src/Elasticsearch.sln
  src/Tests/Tests.Configuration/tests.default.yaml
  src/Tests/Tests/Tests.csproj
Labels: Port to 5.x, Port to 6.x, port to 7.x
