Repository elastic/elasticsearch-net, pull requests merged in 2019-07, with the labels that each got.

#3909 Serialize only script in script_score function
  src/Nest/QueryDsl/Compound/FunctionScore/Functions/ScoreFunctionJsonFormatter.cs
  src/Tests/Tests/QueryDsl/Compound/FunctionScore/FunctionScoreQueryUsageTests.cs
Labels: Bug, Port to 7.x, v7.1.0

#3910 Include time zone information for Local and Utc DateTimeKind
  docs/common-options/date-math/date-math-expressions.asciidoc
  src/CodeGeneration/DocGenerator/StringExtensions.cs
  src/CodeGeneration/DocGenerator/SyntaxNodeExtensions.cs
  src/Elasticsearch.Net/Extensions/StringBuilderCache.cs
  src/Nest/CommonOptions/DateMath/DateMath.cs
  src/Tests/Tests/CommonOptions/DateMath/DateMathExpressions.doc.cs
Labels: Bug, v7.1.0

#3921 Fix/7.x/compression dotnetcore
  src/Elasticsearch.Net/Connection/Content/RequestDataContent.cs
  src/Elasticsearch.Net/Connection/HttpConnection.cs
  src/Tests/Tests.Configuration/EnvironmentConfiguration.cs
  src/Tests/Tests.Configuration/TestConfigurationBase.cs
  src/Tests/Tests.Configuration/TestConfigurationExtensions.cs
  src/Tests/Tests.Configuration/YamlConfiguration.cs
  src/Tests/Tests.Configuration/tests.default.yaml
  src/Tests/Tests.Core/Client/Settings/TestConnectionSettings.cs
  src/Tests/Tests.Core/Xunit/NestXunitRunOptions.cs
Labels: Bug, v7.0.1

#3922 Support numbers with exponent in WKT
  src/Nest/QueryDsl/Geo/WKT/GeoWKTReader.cs
  src/Tests/Tests/QueryDsl/Geo/Shape/GeoWKTTests.cs
Labels: Bug, v7.1.0

#3919 Add script_score query support
  docs/query-dsl.asciidoc
  docs/query-dsl/compound/function-score/function-score-query-usage.asciidoc
  docs/query-dsl/specialized/script-score/script-score-query-usage.asciidoc
  src/CodeGeneration/DocGenerator/StringExtensions.cs
  src/Nest/QueryDsl/Abstractions/Container/IQueryContainer.cs
  src/Nest/QueryDsl/Abstractions/Container/QueryContainer-Assignments.cs
  src/Nest/QueryDsl/Abstractions/Container/QueryContainerDescriptor.cs
  src/Nest/QueryDsl/Query.cs
  src/Nest/QueryDsl/Specialized/ScriptScore/ScriptScoreQuery.cs
  src/Nest/QueryDsl/Visitor/DslPrettyPrintVisitor.cs
  src/Nest/QueryDsl/Visitor/QueryVisitor.cs
  src/Nest/QueryDsl/Visitor/QueryWalker.cs
  src/Tests/Tests/QueryDsl/Specialized/ScriptScore/ScriptScoreQueryUsageTests.cs
Labels: Feature, v7.1.0

#3917 Add track_total_hits to search request body
  src/CodeGeneration/ApiGenerator/Configuration/Overrides/GlobalOverrides.cs
  src/Elasticsearch.Net/Api/RequestParameters/RequestParameters.NoNamespace.cs
  src/Nest/Descriptors.NoNamespace.cs
  src/Nest/Requests.NoNamespace.cs
  src/Nest/Search/MultiSearch/MultiSearchFormatter.cs
  src/Nest/Search/MultiSearch/MultiSearchRequest.cs
  src/Nest/Search/Search/SearchRequest.cs
  src/Tests/Tests/Search/MultiSearch/MultiSearchApiTests.cs
Labels: Bug, v7.1.0

#3911 Include size of snapshot in snapshot metadata
  src/Nest/Modules/SnapshotAndRestore/Snapshot/SnapshotStatus/SnapshotStatusResponse.cs
Labels: Feature, v7.1.0

#3918 Obsolete AllField and IndexField
  src/Nest/Indices/MappingManagement/GetFieldMapping/FieldMappingFormatter.cs
  src/Nest/Indices/MappingManagement/PutMapping/PutMappingRequest.cs
  src/Nest/Mapping/Mappings.cs
  src/Nest/Mapping/MetaFields/All/AllField.cs
  src/Nest/Mapping/MetaFields/Index/IndexField.cs
  src/Nest/Mapping/TypeMapping.cs
Labels: Bug, v7.1.0

#3944 Handle cat API 404 responses
  src/Nest/Cat/CatResponse.cs
  src/Nest/Cat/CatResponseBuilder.cs
  src/Tests/Tests/Cat/CatCount/CatCountApiTests.cs
Labels: Bug, v7.1.0

#3942 Honour IPropertyMappingProvider on custom IElastisearchSerializer
  src/Nest/CommonAbstractions/ConnectionSettings/ConnectionSettingsBase.cs
  src/Tests/Tests.Reproduce/GitHubIssue3926.cs
Labels: Bug, v7.1.0

#3941 Add rank_feature, rank_feature fields and rank_feature query
  docs/code-standards/descriptors.asciidoc
  docs/query-dsl.asciidoc
  docs/query-dsl/specialized/rank-feature/rank-feature-query-usage.asciidoc
  src/Nest/Mapping/Types/Core/RankFeature/RankFeatureAttribute.cs
  src/Nest/Mapping/Types/Core/RankFeature/RankFeatureProperty.cs
  src/Nest/Mapping/Types/Core/RankFeatures/RankFeaturesAttribute.cs
  src/Nest/Mapping/Types/Core/RankFeatures/RankFeaturesProperty.cs
  src/Nest/Mapping/Types/FieldType.cs
  src/Nest/Mapping/Types/Properties.cs
  src/Nest/Mapping/Types/PropertyBase.cs
  src/Nest/Mapping/Types/PropertyFormatter.cs
  src/Nest/Mapping/Visitor/IMappingVisitor.cs
  src/Nest/Mapping/Visitor/IPropertyVisitor.cs
  src/Nest/Mapping/Visitor/MappingWalker.cs
  src/Nest/Mapping/Visitor/NoopPropertyVisitor.cs
  src/Nest/QueryDsl/Abstractions/Container/IQueryContainer.cs
  src/Nest/QueryDsl/Abstractions/Container/QueryContainer-Assignments.cs
  src/Nest/QueryDsl/Abstractions/Container/QueryContainerDescriptor.cs
  src/Nest/QueryDsl/Query.cs
  src/Nest/QueryDsl/Specialized/RankFeature/RankFeatureQuery.cs
  src/Nest/QueryDsl/Visitor/DslPrettyPrintVisitor.cs
  src/Nest/QueryDsl/Visitor/QueryVisitor.cs
  src/Nest/QueryDsl/Visitor/QueryWalker.cs
  src/Tests/Tests.Core/ManagedElasticsearch/NodeSeeders/DefaultSeeder.cs
  src/Tests/Tests.Domain/Project.cs
  src/Tests/Tests/CodeStandards/Descriptors.doc.cs
  src/Tests/Tests/Indices/MappingManagement/GetMapping/GetMappingApiTest.cs
  src/Tests/Tests/Indices/MappingManagement/PutMapping/PutMappingApiTest.cs
  src/Tests/Tests/Mapping/Types/Core/RankFeature/RankFeatureAttributeTests.cs
  src/Tests/Tests/Mapping/Types/Core/RankFeature/RankFeaturePropertyTests.cs
  src/Tests/Tests/Mapping/Types/Core/RankFeatures/RankFeaturesAttributeTests.cs
  src/Tests/Tests/Mapping/Types/Core/RankFeatures/RankFeaturesPropertyTests.cs
  src/Tests/Tests/QueryDsl/Specialized/RankFeature/RankFeatureQueryUsageTests.cs
  src/Tests/Tests/Search/FieldCapabilities/FieldCapabilitiesApiTests.cs
Labels: Feature, Port to 7.x, v7.1.0

#3937 Additions to Invalidate Token API
  src/Nest/XPack/Security/User/InvalidateUserAccessToken/InvalidateUserAccessTokenRequest.cs
  src/Nest/XPack/Security/User/InvalidateUserAccessToken/InvalidateUserAccessTokenResponse.cs
Labels: Feature, v7.1.0

#3927 Add CCR Follow Info API
  src/CodeGeneration/ApiGenerator/Configuration/CodeConfiguration.cs
  src/Elasticsearch.Net/Api/RequestParameters/RequestParameters.CrossClusterReplication.cs
  src/Elasticsearch.Net/ElasticLowLevelClient.CrossClusterReplication.cs
  src/Nest/Descriptors.CrossClusterReplication.cs
  src/Nest/ElasticClient.CrossClusterReplication.cs
  src/Nest/Requests.CrossClusterReplication.cs
  src/Nest/XPack/CrossClusterReplication/Follow/FollowInfo/FollowConfig.cs
  src/Nest/XPack/CrossClusterReplication/Follow/FollowInfo/FollowInfoRequest.cs
  src/Nest/XPack/CrossClusterReplication/Follow/FollowInfo/FollowInfoResponse.cs
  src/Nest/XPack/CrossClusterReplication/Follow/FollowInfo/FollowerIndexStatus.cs
  src/Nest/_Generated/ApiUrlsLookup.generated.cs
  src/Tests/Tests/XPack/CrossClusterReplication/CrossClusterReplicationFollowTests.cs
Labels: Feature, v7.1.0

#3912 Implement Api Key authorisation on requests
  src/Elasticsearch.Net/Configuration/ConnectionConfiguration.cs
  src/Elasticsearch.Net/Configuration/IConnectionConfigurationValues.cs
  src/Elasticsearch.Net/Configuration/RequestConfiguration.cs
  src/Elasticsearch.Net/Configuration/Security/ApiKeyAuthenticationCredentials.cs
  src/Elasticsearch.Net/Connection/HttpConnection.cs
  src/Elasticsearch.Net/Connection/HttpWebRequestConnection.cs
  src/Elasticsearch.Net/Transport/Pipeline/RequestData.cs
  src/Elasticsearch.Net/Transport/Pipeline/RequestPipeline.cs
  src/Tests/Tests.Core/Extensions/EphemeralClusterExtensions.cs
  src/Tests/Tests/ClientConcepts/Troubleshooting/DebugInformation.doc.cs
  src/Tests/Tests/XPack/Security/ApiKey/SecurityApiKeyUsageTests.cs
Labels: Feature, v7.1.0

#3948 Add System.Diagnostics.DiagnosticSource reference for NetStandard 2.0
  build/Elasticsearch.Net.nuspec
  src/Elasticsearch.Net/Elasticsearch.Net.csproj
Labels: Bug, v7.1.0

#3955 Remove Scalar Nanos implementation
  src/Nest/Mapping/DynamicTemplate/SingleMapping.cs
  src/Nest/Mapping/Types/Properties-Scalar.cs
  src/Tests/Tests/Mapping/Scalar/ScalarUsageTests.cs
Labels: v7.1.0

#3957 Ignore Empty Filters tests
  docs/aggregations.asciidoc
  docs/aggregations/bucket/filters/filters-aggregation-usage.asciidoc
  docs/aggregations/bucket/geo-hash-tile/geo-tile-grid-aggregation-usage.asciidoc
  docs/client-concepts/connection/configuration-options.asciidoc
  docs/mapping/scalar/scalar-usage.asciidoc
  docs/x-pack/security/api-key/security-api-key-usage.asciidoc
  src/Tests/Tests/Aggregations/Bucket/Filters/FiltersAggregationUsageTests.cs
Labels: v7.1.0

#3968 Improve Index name inference docs
  docs/client-concepts/high-level/inference/index-name-inference.asciidoc
  src/Tests/Tests/ClientConcepts/HighLevel/Inference/IndexNameInference.doc.cs
Labels: Docs, v7.2.0
