Repository elastic/elasticsearch-net, pull requests merged in 2019-10, with the labels that each got.

#4112 Fix initial randomization of nodes
  src/Elasticsearch.Net/ConnectionPool/StaticConnectionPool.cs
  src/Tests/Tests/ClientConcepts/ConnectionPooling/BuildingBlocks/ConnectionPooling.doc.cs
Labels: Bug, v6.8.3, v7.3.1

#4113 Doc Generation move to .NET core 3.0
  global.json
  src/CodeGeneration/DocGenerator/AsciiDoc/GeneratedAsciidocVisitor.cs
  src/CodeGeneration/DocGenerator/Buildalyzer/AnalyzerManager.cs
  src/CodeGeneration/DocGenerator/Buildalyzer/AnalyzerManagerExtensions.cs
  src/CodeGeneration/DocGenerator/Buildalyzer/Environment/BuildEnvironment.cs
  src/CodeGeneration/DocGenerator/Buildalyzer/Environment/CoreEnvironment.cs
  src/CodeGeneration/DocGenerator/Buildalyzer/Environment/DotnetPathResolver.cs
  src/CodeGeneration/DocGenerator/Buildalyzer/Environment/EnvironmentFactory.cs
  src/CodeGeneration/DocGenerator/Buildalyzer/Environment/FrameworkEnvironment.cs
  src/CodeGeneration/DocGenerator/Buildalyzer/Environment/MsBuildProperties.cs
  src/CodeGeneration/DocGenerator/Buildalyzer/Logging/EmptyDisposable.cs
  src/CodeGeneration/DocGenerator/Buildalyzer/Logging/TextWriterLogger.cs
  src/CodeGeneration/DocGenerator/Buildalyzer/Logging/TextWriterLoggerProvider.cs
  src/CodeGeneration/DocGenerator/Buildalyzer/ProjectAnalyzer.cs
  src/CodeGeneration/DocGenerator/Buildalyzer/ProjectAnalyzerExtensions.cs
  src/CodeGeneration/DocGenerator/Buildalyzer/XDocumentExtensions.cs
  src/CodeGeneration/DocGenerator/DocGenerator.csproj
  src/CodeGeneration/DocGenerator/LitUp.cs
  src/CodeGeneration/DocGenerator/Program.cs
  src/CodeGeneration/ElasticsearchCodeGeneration.sln
  src/Elasticsearch.Net/Elasticsearch.Net.csproj
  src/Nest/Nest.csproj
  src/Tests/Tests/Tests.csproj
Labels: Infra

#4111 Fix flaky histogram aggregation
  src/Tests/Tests/Aggregations/Bucket/Histogram/HistogramAggregationUsageTests.cs
Labels: flakey test

#4107 Remove Neighbors and use Union<Distance,int> for Precision
  src/Nest/Mapping/Types/Specialized/Completion/CategorySuggestContext.cs
  src/Nest/Mapping/Types/Specialized/Completion/GeoSuggestContext.cs
  src/Nest/Mapping/Types/Specialized/Completion/ISuggestContext.cs
  src/Nest/Mapping/Types/Specialized/Completion/SuggestContextFormatter.cs
  src/Nest/Mapping/Types/Specialized/Completion/SuggestContextsDescriptor.cs
  src/Nest/Search/Suggesters/ContextSuggester/GeoSuggestContext.cs
  src/Tests/Tests.Core/ManagedElasticsearch/NodeSeeders/DefaultSeeder.cs
Labels: Breaking, v8.0.0

#4127 Deserialize boolean strings to dynamic mapping
  src/Nest/Mapping/DynamicMapping.cs
  src/Nest/Mapping/TypeMapping.cs
  src/Nest/Mapping/Types/Complex/Object/ObjectProperty.cs
  src/Tests/Tests.Core/ManagedElasticsearch/NodeSeeders/DefaultSeeder.cs
Labels: Bug, v7.4.0

#4126 Implement Snapshot Lifecycle Management APIs
  src/CodeGeneration/ApiGenerator/Configuration/CodeConfiguration.cs
  src/CodeGeneration/ApiGenerator/Domain/Code/CsharpNames.cs
  src/CodeGeneration/ApiGenerator/Domain/Specification/UrlPart.cs
  src/CodeGeneration/ApiGenerator/RestSpecification/_Patches/slm.get_lifecycle.patch.json
  src/Elasticsearch.Net/Api/RequestParameters/RequestParameters.Slm.cs
  src/Elasticsearch.Net/Api/RequestParameters/RequestParameters.SnapshotLifecycleManagement.cs
  src/Elasticsearch.Net/ElasticLowLevelClient.NoNamespace.cs
  src/Elasticsearch.Net/ElasticLowLevelClient.SnapshotLifecycleManagement.cs
  src/Elasticsearch.Net/IElasticLowLevelClient.Generated.cs
  src/Nest/Descriptors.SnapshotLifecycleManagement.cs
  src/Nest/ElasticClient.NoNamespace.cs
  src/Nest/ElasticClient.SnapshotLifecycleManagement.cs
  src/Nest/IElasticClient.Generated.cs
  src/Nest/Requests.SnapshotLifecycleManagement.cs
  src/Nest/Requests.cs
  src/Nest/XPack/Slm/DeleteLifecycle/DeleteSnapshotLifecycleRequest.cs
  src/Nest/XPack/Slm/DeleteLifecycle/DeleteSnapshotLifecycleResponse.cs
  src/Nest/XPack/Slm/ExecuteLifecycle/ExecuteSnapshotLifecycleRequest.cs
  src/Nest/XPack/Slm/ExecuteLifecycle/ExecuteSnapshotLifecycleResponse.cs
  src/Nest/XPack/Slm/GetLifecycle/GetSnapshotLifecycleRequest.cs
  src/Nest/XPack/Slm/GetLifecycle/GetSnapshotLifecycleResponse.cs
  src/Nest/XPack/Slm/PutLifecycle/PutSnapshotLifecycleRequest.cs
  src/Nest/XPack/Slm/PutLifecycle/PutSnapshotLifecycleResponse.cs
  src/Nest/XPack/Slm/SnapshotLifecycleConfig.cs
  src/Nest/XPack/Slm/SnapshotLifecyclePolicy.cs
  src/Nest/XPack/Slm/SnapshotLifecyclePolicyMetadata.cs
  src/Nest/_Generated/ApiUrlsLookup.generated.cs
  src/Tests/Tests/XPack/Slm/DeleteLifecycle/DeleteLifecycleUrlTests.cs
  src/Tests/Tests/XPack/Slm/ExecuteLifecycle/ExecuteLifecycleUrlTests.cs
  src/Tests/Tests/XPack/Slm/GetLifecycle/GetLifecycleUrlTests.cs
  src/Tests/Tests/XPack/Slm/PutLifecycle/PutLifecycleUrlTests.cs
  src/Tests/Tests/XPack/Slm/SlmApiTests.cs
Labels: Feature, Port to master, v7.4.0

#4132 Write null when ISort or SortKey is null
  src/Nest/CommonOptions/Sorting/SortFormatter.cs
Labels: Bug, v7.4.0

#4134 Fix test for random initialized node
  src/Elasticsearch.Net/ConnectionPool/StaticConnectionPool.cs
  src/Tests/Tests/ClientConcepts/ConnectionPooling/BuildingBlocks/ConnectionPooling.doc.cs
Labels: Port to master

#4136 S3 repo settings: path style access
  src/Nest/Modules/SnapshotAndRestore/Repositories/S3Repository.cs
Labels: Feature, Port to master, v7.4.0

#4138 Add support for inlined user dictionary in the Kuromoji plugin
  src/Nest/Analysis/Plugins/Kuromoji/KuromojiTokenizer.cs
  src/Tests/Tests/Analysis/Tokenizers/TokenizerTests.cs
Labels: Feature, Port to master, v7.4.0

#4139 Add max_iterations configuration to watcher action with foreach execu…
  src/Nest/XPack/Watcher/Action/ActionBase.cs
  src/Nest/XPack/Watcher/Action/ActionsDescriptorBase.cs
  src/Tests/Tests/XPack/Watcher/PutWatch/PutWatchApiTests.cs
Labels: Feature, Port to 7.x, v7.4.0

#4140 Add shift option to moving_avg aggregation
  src/Nest/Aggregations/Pipeline/MovingFunction/MovingFunctionAggregation.cs
  src/Tests/Tests/Aggregations/Pipeline/MovingFunction/MovingFunctionAggregationUsageTests.cs
Labels: Feature, Port to master, v7.4.0

#4142 Expose index age in ILM explain output
  src/Nest/XPack/Ilm/ExplainLifecycle/ExplainLifecycleResponse.cs
  src/Tests/Tests/XPack/Ilm/IlmApiTests.cs
Labels: Feature, Port to master, v7.4.0

#4143 Search enhancement: pinned queries
  src/Nest/QueryDsl/Abstractions/Container/IQueryContainer.cs
  src/Nest/QueryDsl/Abstractions/Container/QueryContainer-Assignments.cs
  src/Nest/QueryDsl/Abstractions/Container/QueryContainerDescriptor.cs
  src/Nest/QueryDsl/Query.cs
  src/Nest/QueryDsl/Specialized/Pinned/PinnedQuery.cs
  src/Nest/QueryDsl/TermLevel/Ids/IdsQuery.cs
  src/Nest/QueryDsl/Visitor/DslPrettyPrintVisitor.cs
  src/Nest/QueryDsl/Visitor/QueryVisitor.cs
  src/Nest/QueryDsl/Visitor/QueryWalker.cs
  src/Tests/Tests/QueryDsl/Specialized/Pinned/PinnedQueryUsageTests.cs
Labels: Feature, Port to master, v7.4.0

#4141 Include in-progress snapshot for a policy with get SLM policy API
  src/Nest/XPack/Slm/SnapshotLifecyclePolicyMetadata.cs
  src/Tests/Tests/XPack/Slm/SlmApiTests.cs
Labels: Feature, Port to master, v7.4.0

#4146 Implement disable_chucked_encoding s3 repository setting.
  src/Nest/Modules/SnapshotAndRestore/Repositories/S3Repository.cs
Labels: Port to master, v7.4.0

#4151 Implement vector usage
  src/Nest/XPack/Info/XPackUsage/XPackUsageResponse.cs
  src/Tests/Tests/XPack/Info/XPackInfoApiTests.cs
Labels: Port to master, v7.4.0

#4155 Implement shape queries.
  docs/query-dsl/geo/geo-shape/geo-shape-query-usage.asciidoc
  docs/query-dsl/specialized/shape/shape-query-usage.asciidoc
  src/Nest/CommonOptions/Shape/ShapeRelation.cs
  src/Nest/QueryDsl/Abstractions/Container/IQueryContainer.cs
  src/Nest/QueryDsl/Abstractions/Container/QueryContainer-Assignments.cs
  src/Nest/QueryDsl/Abstractions/Container/QueryContainerDescriptor.cs
  src/Nest/QueryDsl/Query.cs
  src/Nest/QueryDsl/Specialized/Shape/IShapeQuery.cs
  src/Nest/QueryDsl/Specialized/Shape/ShapeQueryFormatter.cs
  src/Nest/QueryDsl/Visitor/DslPrettyPrintVisitor.cs
  src/Nest/QueryDsl/Visitor/QueryVisitor.cs
  src/Nest/QueryDsl/Visitor/QueryWalker.cs
  src/Tests/Tests/QueryDsl/Geo/GeoShape/GeoShapeQueryUsageTests.cs
  src/Tests/Tests/QueryDsl/Geo/GeoShape/GeoShapeSerializationTests.cs
  src/Tests/Tests/QueryDsl/Geo/GeoShape/GeoWKTTests.cs
  src/Tests/Tests/QueryDsl/Specialized/Shape/ShapeQueryUsageTests.cs
  src/Tests/Tests/QueryDsl/Specialized/Shape/ShapeSerializationTests.cs
Labels: Port to master, v7.4.0

#4166 7.x integration tests fixes
  src/Tests/Tests.Core/ManagedElasticsearch/NodeSeeders/DefaultSeeder.cs
  src/Tests/Tests.Domain/Project.cs
  src/Tests/Tests/CodeStandards/Serialization/Enums.cs
  src/Tests/Tests/Indices/MappingManagement/PutMapping/PutMappingApiTest.cs
  src/Tests/Tests/QueryDsl/Specialized/Shape/ShapeQueryUsageTests.cs
  src/Tests/Tests/QueryDsl/Specialized/Shape/ShapeSerializationTests.cs
Labels: Infra, v7.4.0

#4163 Add average_search_time_per_bucket_ms and total_bucket_processing_tim…
  src/Nest/XPack/MachineLearning/Datafeed/DatafeedStats.cs
  src/Nest/XPack/MachineLearning/Job/Config/JobStats.cs
  src/Tests/Tests/XPack/MachineLearning/GetDatafeedStats/GetDatafeedStatsApiTests.cs
Labels: Feature, Port to master, v7.4.0

#4137 Deprecate the ability to update datafeed's job_id
  src/Nest/XPack/MachineLearning/UpdateDataFeed/UpdateDatafeedRequest.cs
  src/Tests/Tests/XPack/MachineLearning/UpdateDatafeed/UpdateDatafeedApiTests.cs
Labels: Port to master, v7.4.0

#4161 Add Circle processor
  src/Nest/Ingest/ProcessorFormatter.cs
  src/Nest/Ingest/Processors/CircleProcessor.cs
  src/Nest/Ingest/Processors/DissectProcessor.cs
  src/Nest/Ingest/ProcessorsDescriptor.cs
  src/Tests/Tests/Ingest/ProcessorAssertions.cs
Labels: Port to master, v7.4.0

#4162 Implement snapshot records for last_success and last_failure on SnapshotLifecyclePolicyMetadata.
  src/Nest/XPack/Slm/SnapshotLifecyclePolicyMetadata.cs
Labels: Port to master, v7.4.0

#4169 Fix aggs integration tests where buckets can be empty
  src/Tests/Tests/Aggregations/Pipeline/BucketScript/BucketScriptAggregationUsageTests.cs
  src/Tests/Tests/Aggregations/Pipeline/Derivative/DerivativeAggregationUsageTests.cs
  src/Tests/Tests/Aggregations/Pipeline/MovingAverage/MovingAverageEwmaAggregationUsageTests.cs
  src/Tests/Tests/Aggregations/Pipeline/MovingAverage/MovingAverageHoltLinearAggregationUsageTests.cs
  src/Tests/Tests/Aggregations/Pipeline/MovingAverage/MovingAverageHoltWintersAggregationUsageTests.cs
  src/Tests/Tests/Aggregations/Pipeline/MovingAverage/MovingAverageSimpleAggregationUsageTests.cs
  src/Tests/Tests/Aggregations/Pipeline/SerialDifferencing/SerialDifferencingAggregationUsageTests.cs
Labels: flakey test

#4158 remove hardcoded \r\n from code generator strings
  src/Auxiliary/Elasticsearch.Net.VirtualizedCluster/Audit/Auditor.cs
  src/CodeGeneration/ApiGenerator/Domain/Code/HighLevel/Requests/Constructor.cs
  src/CodeGeneration/ApiGenerator/Generator/CodeGenerator.cs
  src/CodeGeneration/ApiGenerator/Views/HighLevel/Descriptors/XmlDocs.cshtml
  src/CodeGeneration/ApiGenerator/Views/LowLevel/Enums.Generated.cshtml
  src/CodeGeneration/DocGenerator/AsciiDoc/GeneratedAsciidocVisitor.cs
  src/CodeGeneration/DocGenerator/AsciiDoc/RawAsciidocVisitor.cs
  src/CodeGeneration/DocGenerator/XmlDocs/XmlDocsVisitor.cs
  src/Elasticsearch.Net/Responses/ResponseStatics.cs
  src/Tests/Tests.Core/Extensions/DiffExtensions.cs
  src/Tests/Tests.Core/ManagedElasticsearch/Tasks/WriteAnalysisFiles.cs
  src/Tests/Tests/Framework/Extensions/UriExtensions.cs
Labels: Infra

#4173 Convert SLM API dates returned as long to DateTimeOffset
  src/Nest/XPack/Slm/SnapshotLifecyclePolicyMetadata.cs
  src/Tests/Tests/XPack/Slm/SlmApiTests.cs
Labels: Port to master, v7.4.0

#4175 Serialize dates with min 3 fractional digits when using SourceSeriali…
  src/Tests/Tests.Core/Client/Serializers/TestSourceSerializerBase.cs
  src/Tests/Tests.Core/Xunit/NestXunitRunOptions.cs
  src/Tests/Tests.Domain/JsonConverters/DateTimeConverter.cs
  src/Tests/Tests/Cluster/TaskManagement/GetTask/GetTaskApiTests.cs
Labels: Flakey test

#4176 Ignore TimingStats object if version < 7.4.0
  src/Tests/Tests/XPack/MachineLearning/GetDatafeedStats/GetDatafeedStatsApiTests.cs
Labels: Port to master, v7.4.0

#4184 Forward port of backport improvements #4123
  src/Elasticsearch.Net/Responses/Dynamic/DynamicValue.cs
  src/Tests/Tests/ClientConcepts/LowLevel/LowLevelResponseTypes.doc.cs
  src/Tests/Tests/Search/MultiSearch/MultiSearchLowLevelPostDataTests.cs
Labels: Infra

#4188 alternative approach to internalsvisible to
  src/Elasticsearch.Net/Elasticsearch.Net.csproj
  src/Elasticsearch.Net/Properties/ClsCompliancy.cs
  src/InternalsVisible.targets
  src/Library.build.props
  src/Nest/Nest.csproj
  src/Nest/Properties/ClsCompliancy.cs
Labels: Infra

#4190 Utf8Json dynamic type namespaces
  src/Elasticsearch.Net/Utf8Json/Resolvers/CompositeResolver.cs
  src/Elasticsearch.Net/Utf8Json/Resolvers/DynamicObjectResolver.cs
Labels: Infra
