Repository elastic/elasticsearch-net, pull requests merged in 2019-04, with the labels that each got.

#3635 Add prebuilt ICU Analyzer
  src/Nest/Analysis/Analyzers/AnalyzerJsonConverter.cs
  src/Nest/Analysis/Analyzers/Analyzers.cs
  src/Nest/Analysis/Plugins/Icu/Collation/IcuCollationAlternate.cs
  src/Nest/Analysis/Plugins/Icu/Collation/IcuCollationCaseFirst.cs
  src/Nest/Analysis/Plugins/Icu/Collation/IcuCollationDecomposition.cs
  src/Nest/Analysis/Plugins/Icu/Collation/IcuCollationStrength.cs
  src/Nest/Analysis/Plugins/Icu/IcuAnalyzer.cs
  src/Nest/Analysis/Plugins/Icu/IcuCollationTokenFilter.cs
  src/Nest/Analysis/Plugins/Icu/IcuFoldingTokenFilter.cs
  src/Nest/Analysis/Plugins/Icu/IcuNormalizationCharFilter.cs
  src/Nest/Analysis/Plugins/Icu/IcuNormalizationTokenFilter.cs
  src/Nest/Analysis/Plugins/Icu/IcuTokenizer.cs
  src/Nest/Analysis/Plugins/Icu/IcuTransformTokenFilter.cs
  src/Nest/Analysis/Plugins/Icu/Normalization/IcuNormalizationMode.cs
  src/Nest/Analysis/Plugins/Icu/Normalization/IcuNormalizationType.cs
  src/Nest/Analysis/Plugins/Icu/Transform/IcuNormalizationType.cs
  src/Tests/Tests/Analysis/Analyzers/AnalyzerTests.cs
Labels: Feature, v6.7.0

#3628 Use IScript on ScriptQuery
  src/Nest/CommonOptions/Scripting/InlineScript.cs
  src/Nest/CommonOptions/Scripting/ScriptBase.cs
  src/Nest/QueryDsl/Compound/FunctionScore/Functions/IScoreFunction.cs
  src/Nest/QueryDsl/Compound/FunctionScore/Functions/ScoreFunctionJsonFormatter.cs
  src/Nest/QueryDsl/Compound/FunctionScore/Functions/ScriptScore/ScriptScoreFunction.cs
  src/Nest/QueryDsl/Specialized/Script/ScriptQuery.cs
  src/Nest/QueryDsl/Specialized/Script/ScriptQueryFormatter.cs
  src/Tests/Tests.Configuration/tests.default.yaml
  src/Tests/Tests/Aggregations/Bucket/Filter/FilterAggregationUsageTests.cs
  src/Tests/Tests/QueryDsl/Compound/FunctionScore/FunctionScoreQueryUsageTests.cs
  src/Tests/Tests/QueryDsl/Specialized/Script/ScriptQueryUsageTests.cs
Labels: Breaking, v7.0.0

#3651 Docs: Fix the delimiter on a code block
  docs/elasticsearch-net/building-requests.asciidoc
Labels: Docs, v1.9.3

#3648 Use HttpMessageHandler on HttpConnection
  src/Elasticsearch.Net/Connection/HttpConnection.cs
  src/Elasticsearch.Net/Transport/Pipeline/RequestData.cs
  src/Elasticsearch.Net/Transport/Pipeline/ResponseBuilder.cs
  src/Tests/Tests/ClientConcepts/Connection/HttpConnectionTests.cs
Labels: Breaking, v7.0.0

#3646 Consistent Sort type names
  src/Nest/CommonOptions/Sorting/SortFormatter.cs
  src/Nest/Document/Multiple/ScrollAll/ScrollAllObservable.cs
  src/Nest/Search/Search/Sort/FieldSort.cs
  src/Nest/Search/Search/Sort/GeoDistanceSort.cs
  src/Nest/Search/Search/Sort/ScriptSort.cs
  src/Nest/Search/Search/Sort/SortBase.cs
  src/Nest/Search/Search/Sort/SortDescriptor.cs
  src/Tests/Tests/Aggregations/Metric/TopHits/TopHitsAggregationUsageTests.cs
  src/Tests/Tests/Aggregations/Pipeline/BucketSort/BucketSortAggregationUsageTests.cs
  src/Tests/Tests/Document/Multiple/ReindexOnServer/ReindexOnServerApiTests.cs
  src/Tests/Tests/Document/Multiple/ReindexOnServer/ReindexOnServerSliceApiTests.cs
  src/Tests/Tests/Search/Request/SearchAfterUsageTests.cs
  src/Tests/Tests/Search/Request/SortUsageTests.cs
Labels: Breaking, v7.0.0

#3647 Add IpRangeBucket for IpRangeAggregation
  src/Nest/Aggregations/AggregateDictionary.cs
  src/Nest/Aggregations/AggregateFormatter.cs
  src/Nest/Aggregations/Bucket/IpRange/IpRangeBucket.cs
  src/Tests/Tests/Aggregations/Bucket/IpRange/IpRangeAggregationUsageTests.cs
Labels: Breaking, v7.0.0

#3650 fix places where IMemoryStreamFactory was being side stepped
  src/Elasticsearch.Net/Configuration/ConnectionConfiguration.cs
  src/Elasticsearch.Net/Providers/RecyclableMemoryStreamFactory.cs
  src/Elasticsearch.Net/Responses/ElasticsearchResponse.cs
  src/Elasticsearch.Net/Responses/HttpDetails/ApiCallDetails.cs
  src/Elasticsearch.Net/Responses/HttpDetails/IApiCallDetails.cs
  src/Elasticsearch.Net/Responses/Special/BytesResponse.cs
  src/Elasticsearch.Net/Responses/Special/StringResponse.cs
  src/Elasticsearch.Net/Serialization/IElasticsearchSerializer.cs
  src/Elasticsearch.Net/Transport/Pipeline/RequestPipeline.cs
  src/Elasticsearch.Net/Transport/Pipeline/ResponseBuilder.cs
  src/Elasticsearch.Net/Transport/PostData.cs
  src/Elasticsearch.Net/Transport/SerializableData.cs
  src/Nest/Cat/CatHelp/ElasticClient-CatHelp.cs
  src/Nest/Document/Multiple/Bulk/BulkRequestFormatter.cs
  src/Nest/Search/MultiSearch/MultiSearchJsonConverter.cs
  src/Nest/Search/MultiSearchTemplate/MultiSearchTemplateJsonConverter.cs
  src/Nest/XPack/MachineLearning/PostJobData/PostJobDataRequest.cs
  src/Serializers/Nest.JsonNetSerializer/ConnectionSettingsAwareSerializerBase.Serializer.cs
  src/Serializers/Nest.JsonNetSerializer/Converters/HandleNestTypesOnSourceJsonConverter.cs
  src/Serializers/Nest.JsonNetSerializer/JTokenExtensions.cs
  src/Tests/Tests.Core/Client/FixedResponseClient.cs
  src/Tests/Tests.Core/Serialization/RoundtripperDsl.cs
  src/Tests/Tests.Reproduce/DateSerialization.cs
  src/Tests/Tests/Framework/SerializationTests/CompositeKeySerializationTests.cs
  src/Tests/Tests/Search/MultiSearch/MultiSearchLowLevelPostDataTests.cs
Labels: Refactoring, v7.0.0

#3661 Use float? for suggester fractional properties
  src/Nest/Mapping/Types/Specialized/Attachment/Attachment.cs
  src/Nest/Search/Suggesters/CompletionSuggester/CompletionField.cs
  src/Nest/Search/Suggesters/CompletionSuggester/CompletionSuggester.cs
  src/Nest/Search/Suggesters/CompletionSuggester/FuzzySuggest.cs
  src/Nest/Search/Suggesters/CompletionSuggester/SuggestFuzziness.cs
  src/Nest/Search/Suggesters/PhraseSuggester/DirectGenerator.cs
  src/Nest/Search/Suggesters/PhraseSuggester/PhraseSuggestCollate.cs
  src/Nest/Search/Suggesters/PhraseSuggester/PhraseSuggestCollateQuery.cs
  src/Nest/Search/Suggesters/PhraseSuggester/PhraseSuggestHighlight.cs
  src/Nest/Search/Suggesters/PhraseSuggester/PhraseSuggester.cs
  src/Nest/Search/Suggesters/Suggest.cs
  src/Nest/Search/Suggesters/SuggestContainer.cs
  src/Nest/Search/Suggesters/SuggesterBase.cs
  src/Nest/Search/Suggesters/TermSuggester/StringDistance.cs
  src/Nest/Search/Suggesters/TermSuggester/SuggestSort.cs
  src/Nest/Search/Suggesters/TermSuggester/TermSuggester.cs
  src/Tests/Tests/Search/Request/SuggestUsageTests.cs
Labels: Breaking, v7.0.0

#3667 Deserialize relation on TotalHits
  src/Elasticsearch.Net/Utf8Json/Formatters/EnumFormatter.cs
  src/Nest/Aggregations/AggregateFormatter.cs
  src/Nest/Aggregations/Metric/TopHits/TopHitsAggregate.cs
  src/Nest/Search/Search/Hits/HitsMetaData.cs
  src/Nest/Search/Search/Hits/HitsTotal.cs
  src/Nest/Search/Search/Hits/InnerHitsMetaData.cs
  src/Nest/Search/Search/Hits/TotalHits.cs
  src/Nest/Search/Search/SearchResponse.cs
  src/Tests/Tests/Search/MultiSearch/MultiSearchApiTests.cs
  src/Tests/Tests/Search/Search/SearchApiTests.cs
Labels: v7.0.0

#3666 Since SynchronizedCollection is only used in one place rename it to f…
  src/Nest/CommonAbstractions/Extensions/Extensions.cs
  src/Nest/CrossPlatform/SynchronizedCollection.cs
  src/Nest/Document/Multiple/Bulk/BulkOperation/BulkOperationsCollection.cs
  src/Nest/Document/Multiple/Bulk/BulkRequest.cs
  src/Nest/Document/Multiple/Bulk/BulkResponse.cs
  src/Nest/Document/Multiple/Bulk/ElasticClient-DeleteMany.cs
  src/Nest/Document/Multiple/Bulk/ElasticClient-IndexMany.cs
  src/Tests/Tests/CodeStandards/NamingConventions.doc.cs
Labels: Port to master, v7.0.0

#3676 Docs: Drop subtitle in Asciidoctor
  docs/index.asciidoc
Labels: Docs

#3679 Fix utf8json escape characters
  src/Elasticsearch.Net/Utf8Json/JsonReader.cs
Labels: Bug, v7.0.0

#3649 Refactor/test version config
  build/scripts/Building.fs
  build/scripts/Cluster.fs
  build/scripts/Paths.fs
  build/scripts/Targets.fs
  build/scripts/Testing.fs
  build/scripts/Tooling.fs
  src/CodeGeneration/DocGenerator/DocGenerator.csproj
  src/Tests/Tests.ClusterLauncher/ClusterLaunchProgram.cs
  src/Tests/Tests.Configuration/ConfigurationLoader.cs
  src/Tests/Tests.Configuration/EnvironmentConfiguration.cs
  src/Tests/Tests.Configuration/TestConfigurationBase.cs
  src/Tests/Tests.Configuration/TestConfigurationExtensions.cs
  src/Tests/Tests.Configuration/TestMode.cs
  src/Tests/Tests.Configuration/YamlConfiguration.cs
  src/Tests/Tests.Configuration/tests.default.yaml
  src/Tests/Tests.Core/Client/TestClient.cs
  src/Tests/Tests.Core/Extensions/TestConfigurationExtensions.cs
  src/Tests/Tests.Core/ManagedElasticsearch/Clusters/ClientTestClusterBase.cs
  src/Tests/Tests.Core/Xunit/NestXunitRunOptions.cs
  src/Tests/Tests/Search/SearchUsageTestBase.cs
  src/Tests/Tests/Tests.csproj
Labels: Refactoring

#3665 Remove superfluous pragma directives
  src/CodeGeneration/ApiGenerator/Views/Enums.Generated.cshtml
  src/Elasticsearch.Net/Configuration/ConnectionConfiguration.cs
  src/Elasticsearch.Net/Connection/CertificateValidations.cs
  src/Elasticsearch.Net/Connection/HttpConnection-CoreFx.cs
  src/Elasticsearch.Net/Connection/HttpWebRequestConnection.cs
  src/Elasticsearch.Net/CrossPlatform/TypeExtensions.cs
  src/Elasticsearch.Net/Domain/Enums.Generated.cs
  src/Elasticsearch.Net/Extensions/Extensions.cs
  src/Elasticsearch.Net/Extensions/TypeExtensions.cs
  src/Elasticsearch.Net/Extensions/X509CertificateExtensions.cs
  src/Elasticsearch.Net/Responses/Dynamic/ElasticsearchDynamicValue.cs
  src/Elasticsearch.Net/Serialization/LowLevelRequestResponseSerializer.cs
  src/Elasticsearch.Net/Transport/PostData.cs
  src/Nest/Aggregations/AggregateJsonConverter.cs
  src/Nest/Aggregations/Pipeline/BucketsPath.cs
  src/Nest/Aggregations/Pipeline/MovingAverage/MovingAverageAggregationJsonConverter.cs
  src/Nest/Analysis/Analyzers/Analyzers.cs
  src/Nest/Analysis/CharFilters/CharFilters.cs
  src/Nest/Analysis/Normalizers/Normalizers.cs
  src/Nest/Analysis/TokenFilters/TokenFilters.cs
  src/Nest/Analysis/Tokenizers/Tokenizers.cs
  src/Nest/CommonAbstractions/DictionaryLike/PerFieldAnalyzer/PerFieldAnalyzer.cs
  src/Nest/CommonAbstractions/Extensions/Extensions.cs
  src/Nest/CommonAbstractions/Extensions/TypeExtensions.cs
  src/Nest/CommonAbstractions/Fields/FieldValues.cs
  src/Nest/CommonAbstractions/Infer/Field/FieldExpressionVisitor.cs
  src/Nest/CommonAbstractions/SerializationBehavior/Attributes/StringTimeSpanConverter.cs
  src/Nest/CommonAbstractions/SerializationBehavior/ElasticContractResolver.cs
  src/Nest/CommonAbstractions/SerializationBehavior/GenericJsonConverters/EnumMemberValueCasingJsonConverter.cs
  src/Nest/CommonAbstractions/SerializationBehavior/SourceValueWriteConverter.cs
  src/Nest/CommonOptions/Scripting/ScriptFields.cs
  src/Nest/CommonOptions/TimeUnit/Time.cs
  src/Nest/CrossPlatform/SynchronizedCollection.cs
  src/Nest/CrossPlatform/TypeExtensions.cs
  src/Nest/IndexModules/Similarity/CustomSimilarity.cs
  src/Nest/Indices/AliasManagement/Aliases.cs
  src/Nest/Mapping/DynamicTemplate/DynamicTemplateContainer.cs
  src/Nest/Mapping/Mappings.cs
  src/Nest/Mapping/TypeMapping.cs
  src/Nest/Mapping/Types/Core/Join/Relations.cs
  src/Nest/Mapping/Types/Properties.cs
  src/Nest/Mapping/Visitor/PropertyWalker.cs
  src/Nest/Modules/SnapshotAndRestore/Repositories/GetRepository/GetRepositoryResponseJsonConverter.cs
  src/Nest/Search/Suggesters/SuggestContainer.cs
  src/Tests/Tests/Aggregations/AggregationVisitorTests.cs
  src/Tests/Tests/CodeStandards/Analysis.cs
  src/Tests/Tests/CodeStandards/Descriptors.doc.cs
  src/Tests/Tests/CodeStandards/ElasticClient.doc.cs
  src/Tests/Tests/CodeStandards/NamingConventions.doc.cs
  src/Tests/Tests/CodeStandards/Queries.doc.cs
  src/Tests/Tests/CodeStandards/Responses.doc.cs
  src/Tests/Tests/CodeStandards/Serialization/Converters.doc.cs
  src/Tests/Tests/Document/Single/Index/IndexIngestAttachmentApiTests.cs
  src/Tests/Tests/Framework/Extensions/TypeExtensions.cs
  src/Tests/Tests/Framework/Extensions/WaitHandleExtensions.cs
  src/Tests/Tests/Framework/Extensions/WebClient-CoreFx.cs
  src/Tests/Tests/Ingest/ProcessorSerializationTests.cs
  src/Tests/Tests/XPack/MachineLearning/DetectorSerializationTests.cs
Labels: Cleanup, Port to master, port to 7.x, v6.7.0

#3621 Add indexing documentation
  docs/client-concepts/high-level/indexing/indexing.asciidoc
  docs/client-concepts/high-level/indexing/ingest-nodes.asciidoc
  docs/client-concepts/high-level/indexing/pipelines.asciidoc
  src/Tests/Tests/ClientConcepts/HighLevel/Indexing/Indexing.doc.cs
  src/Tests/Tests/ClientConcepts/HighLevel/Indexing/IngestNodes.doc.cs
  src/Tests/Tests/ClientConcepts/HighLevel/Indexing/Pipelines.doc.cs
  src/Tests/Tests/high-level.asciidoc
Labels: Docs, Port to master, port to 7.x
