Repository elastic/elasticsearch-net, pull requests merged in 2019-09, with the labels that each got.

#4062 Add FollowerAliasesVersion to follow index shard stats
  src/Nest/XPack/CrossClusterReplication/Follow/FollowIndexStats/FollowIndexShardStats.cs
Labels: Feature, v7.3.0

#4069 Add timing stats to machine learning job stats
  src/Nest/XPack/MachineLearning/Job/Config/JobStats.cs
  src/Tests/Tests/XPack/MachineLearning/GetJobStats/GetJobStatsApiTests.cs
Labels: Feature, v7.3.0

#4071 Add max_docs to ReindexOnServer API
  src/Nest/Document/Multiple/DeleteByQuery/DeleteByQueryRequest.cs
  src/Nest/Document/Multiple/ReindexOnServer/ReindexOnServerRequest.cs
  src/Nest/Document/Multiple/ReindexOnServer/ReindexSource.cs
  src/Nest/Document/Multiple/UpdateByQuery/UpdateByQueryRequest.cs
Labels: Deprecation, v7.3.0

#4066 Add shards_acknowledged and indices results to CloseIndexResponse
  src/Nest/Indices/IndexManagement/OpenCloseIndex/CloseIndex/CloseIndexResponse.cs
  src/Tests/Tests/Indices/IndexManagement/OpenCloseIndex/CloseIndex/CloseIndexApiTests.cs
Labels: Feature, v7.3.0

#4073 Add support for SourceOnly snapshot repository
  src/Elasticsearch.Net/Utf8Json/JsonReader.cs
  src/Nest/Modules/SnapshotAndRestore/Repositories/AzureRepository.cs
  src/Nest/Modules/SnapshotAndRestore/Repositories/CreateRepository/CreateRepositoryRequest.cs
  src/Nest/Modules/SnapshotAndRestore/Repositories/FileSystemRepository.cs
  src/Nest/Modules/SnapshotAndRestore/Repositories/GetRepository/GetRepositoryResponseFormatter.cs
  src/Nest/Modules/SnapshotAndRestore/Repositories/HdfsRepository.cs
  src/Nest/Modules/SnapshotAndRestore/Repositories/ISnapshotRepository.cs
  src/Nest/Modules/SnapshotAndRestore/Repositories/ReadOnlyUrlRepository.cs
  src/Nest/Modules/SnapshotAndRestore/Repositories/S3Repository.cs
  src/Nest/Modules/SnapshotAndRestore/Repositories/SourceOnlyRepository.cs
  src/Tests/Tests/Modules/SnapshotAndRestore/Repositories/CreateRepository/CreateRepositoryApiTests.cs
  src/Tests/Tests/Modules/SnapshotAndRestore/Repositories/GetRepository/GetRepositoryApiTests.cs
Labels: Feature, v7.3.0

#4068 Allow execution of each Watcher action in array
  src/Nest/XPack/Watcher/Action/ActionBase.cs
  src/Nest/XPack/Watcher/Action/ActionsDescriptorBase.cs
  src/Tests/Tests/XPack/Watcher/PutWatch/PutWatchApiTests.cs
Labels: Feature, v7.3.0

#4065 Add x-pack features to XPackUsage and XPackInfo responses
  src/Nest/XPack/Info/XPackInfo/XPackInfoResponse.cs
  src/Nest/XPack/Info/XPackUsage/XPackUsageResponse.cs
  src/Tests/Tests/XPack/Info/XPackInfoApiTests.cs
Labels: Feature, v7.3.0

#4075 Skip max_docs query string params
  src/CodeGeneration/ApiGenerator/Configuration/Overrides/Endpoints/DeleteByQueryOverrides.cs
  src/CodeGeneration/ApiGenerator/Configuration/Overrides/Endpoints/ReindexOnServerOverrides.cs
  src/CodeGeneration/ApiGenerator/Configuration/Overrides/Endpoints/UpdateByQueryOverrides.cs
  src/Elasticsearch.Net/Api/RequestParameters/RequestParameters.NoNamespace.cs
  src/Nest/Descriptors.NoNamespace.cs
  src/Nest/Requests.NoNamespace.cs
  src/Tests/Tests/Document/Multiple/DeleteByQuery/DeleteByQueryApiTests.cs
Labels: v7.3.0

#4081 update Bullseye to 3.0.0-rc.1
  build/scripts/scripts.fsproj
Labels: Infra, Port to 5.x, Port to 6.x, Port to 7.x

#4086 Add Flags property, use in tests
  src/Nest/Analysis/CharFilters/PatternReplaceCharFilter.cs
  src/Tests/Tests/Analysis/CharFilters/CharFilterTests.cs
Labels: Feature, v6.8.3, v7.3.1

#4097 Move to .NET 3.0 and C# 8.0
  appveyor.yml
  azure-pipelines.yml
  build/scripts/Benchmarking.fs
  build/scripts/Differ.fs
  build/scripts/Documentation.fs
  build/scripts/Projects.fs
  build/scripts/ReposTooling.fs
  build/scripts/ShadowDependencies.fs
  build/scripts/Testing.fs
  build/scripts/Tooling.fs
  build/scripts/scripts.fsproj
  dotnet-tools.json
  global.json
  nuget.config
  src/CodeGeneration/ApiGenerator/ApiGenerator.csproj
  src/CodeGeneration/ApiGenerator/Domain/Code/LowLevel/LowLevelClientMethod.cs
  src/CodeGeneration/DocGenerator/AsciiDoc/GeneratedAsciidocVisitor.cs
  src/CodeGeneration/DocGenerator/DocGenerator.csproj
  src/CodeGeneration/DocGenerator/Program.cs
  src/Directory.Build.props
  src/Elasticsearch.Net/ElasticLowLevelClient.cs
  src/Examples/Examples/Examples.csproj
  src/Examples/ExamplesGenerator/ExamplesGenerator.csproj
  src/Library.build.props
  src/Nest/Nest.csproj
  src/PublishArtifacts.build.props
  src/Tests/Tests.Benchmarking/Tests.Benchmarking.csproj
  src/Tests/Tests.ClusterLauncher/Tests.ClusterLauncher.csproj
  src/Tests/Tests.Core/ManagedElasticsearch/Clusters/WritableCluster.cs
  src/Tests/Tests.Core/Tests.Core.csproj
  src/Tests/Tests.Domain/Tests.Domain.csproj
  src/Tests/Tests.Reproduce/Tests.Reproduce.csproj
  src/Tests/Tests.ScratchPad/Tests.ScratchPad.csproj
  src/Tests/Tests/CodeStandards/NamingConventions.doc.cs
  src/Tests/Tests/Document/Single/Index/IndexIngestAttachmentApiTests.cs
  src/Tests/Tests/Tests.csproj
Labels: Infra

#4077 Build DebugInformation uri and method from Request or ApiCallDetails
  src/Elasticsearch.Net/Exceptions/ElasticsearchClientException.cs
  src/Elasticsearch.Net/Responses/ResponseStatics.cs
  src/Elasticsearch.Net/Transport/Pipeline/RequestPipeline.cs
  src/Nest/Document/Multiple/BulkAll/BulkAllObservable.cs
Labels: Bug, v7.3.1

#4090 Add PatternReplaceTokenFilter Flags property
  src/Nest/Analysis/TokenFilters/PatternReplaceTokenFilter.cs
  src/Tests/Tests/Analysis/TokenFilters/TokenFilterTests.cs
Labels: Feature, v6.8.3, v7.3.1

#4031 Only run IL rewriting target when releasing or on CI
  build/scripts/Paths.fs
  build/scripts/Projects.fs
  build/scripts/ShadowDependencies.fs
  build/scripts/Targets.fs
  build/scripts/Testing.fs
  src/Tests/Tests.Core/Xunit/SkipOnCiAttribute.cs
  src/Tests/Tests/Document/Multiple/BulkAll/BulkAllExceptionApiTests.cs
Labels: Infra, Port to 7.x

#4109 Fix Extended stats deserialization
  src/Nest/Aggregations/AggregateJsonConverter.cs
  src/Tests/Tests.Reproduce/GitHubIssue4103.cs
Labels: Bug, v6.8.3

#4106 Serialize first precision value on GeoSuggest
  src/Nest/CommonAbstractions/SerializationBehavior/JsonFormatters/SingleOrEnumerableFormatter.cs
  src/Nest/Mapping/Types/Specialized/Completion/CategorySuggestContext.cs
  src/Nest/Mapping/Types/Specialized/Completion/GeoSuggestContext.cs
  src/Nest/Mapping/Types/Specialized/Completion/ISuggestContext.cs
  src/Nest/Mapping/Types/Specialized/Completion/SuggestContextFormatter.cs
  src/Nest/Mapping/Types/Specialized/Completion/SuggestContextsDescriptor.cs
  src/Tests/Tests.Core/ManagedElasticsearch/NodeSeeders/DefaultSeeder.cs
Labels: Bug, v7.3.1

#4108 Honour PropertyNameAttribute Ignore property in mappings
  src/Nest/CommonAbstractions/SerializationBehavior/PropertyMapping.cs
  src/Tests/Tests/ClientConcepts/HighLevel/Mapping/IgnoringProperties.doc.cs
Labels: Bug, v7.3.1
