Repository elastic/elasticsearch-net, pull requests merged in 2019-11, with the labels that each got.

#4182 Remove redundant SLM types.
  src/Elasticsearch.Net/Api/RequestParameters/RequestParameters.Slm.cs
Labels: Port to master, v7.4.1

#4201 Added pipeline to ReindexDestination (#4183) (#4187)
  src/Nest/Document/Multiple/ReindexOnServer/ReindexDestination.cs
  src/Tests/Tests/Document/Multiple/ReindexOnServer/ReindexOnServerPipelineApiTests.cs
Labels: Feature, v7.4.1

#4178 Security API changes to add owner flag
  src/CodeGeneration/ApiGenerator/RestSpecification/_Patches/security.get_api_key.patch.json
  src/Elasticsearch.Net/Api/RequestParameters/RequestParameters.Security.cs
  src/Nest/Descriptors.Security.cs
  src/Nest/Requests.Security.cs
  src/Nest/XPack/Security/ApiKey/InvalidateApiKey/InvalidateApiKeyRequest.cs
Labels: Port to master, v7.4.1

#4213 Fix DynamicResponse not parsing when mimetype contains charset
  src/Elasticsearch.Net/Transport/Pipeline/ResponseBuilder.cs
Labels: Bug, Port to master, v7.4.1

#4206 Adds versioned benchmarking
  nuget.config
  src/Elasticsearch.Net/Providers/MemoryStreamFactory.cs
  src/Tests/Tests.Benchmarking/BenchmarkProgram.cs
  src/Tests/Tests.Benchmarking/BulkBenchmarkTests.cs
  src/Tests/Tests.Benchmarking/Tests.Benchmarking.csproj
  src/Tests/Tests.Core/Client/Settings/AlwaysInMemoryConnectionSettings.cs
  src/Tests/Tests.Core/Client/Settings/TestConnectionSettings.cs
  src/Tests/Tests.Core/Client/TestClient.cs
  src/Tests/Tests.Core/Extensions/TestConfigurationExtensions.cs
  src/Tests/Tests.Domain/Project.cs
  src/Tests/Tests.ScratchPad/Program.cs
  src/Tests/Tests.ScratchPad/Tests.ScratchPad.csproj
  src/Tests/Tests/ClientConcepts/Connection/HttpConnectionTests.cs
Labels: Feature, Infra, Port to master

#4202 Allow MemoryStreamFactory to be pluggable
  src/Auxiliary/Elasticsearch.Net.VirtualizedCluster/FixedPipelineFactory.cs
  src/Elasticsearch.Net/Configuration/ConnectionConfiguration.cs
  src/Elasticsearch.Net/Providers/MemoryStreamFactory.cs
  src/Elasticsearch.Net/Serialization/ElasticsearchSerializerExtensions.cs
Labels: Feature, Port to master, v7.4.1, v8.0.0

#4204 Fix/7.x/upgrade recyclable memory stream factory
  src/Elasticsearch.Net/Providers/RecyclableMemoryStream.cs
  src/Elasticsearch.Net/Providers/RecyclableMemoryStreamFactory.cs
  src/Elasticsearch.Net/Providers/RecyclableMemoryStreamManager-Events.cs
  src/Elasticsearch.Net/Providers/RecyclableMemoryStreamManager.cs
Labels: Feature, Port to master, v7.4.1, v8.0.0

#4207 RestSpecDownloader uses windows path separator
  src/CodeGeneration/ApiGenerator/RestSpecDownloader.cs
Labels: Infra, Port to master

#4208 Use MemoryStreamFactory everywhere
  src/Auxiliary/Elasticsearch.Net.VirtualizedCluster/MockResponses/SniffResponseBytes.cs
  src/Auxiliary/Elasticsearch.Net.VirtualizedCluster/Rules/RuleBase.cs
  src/Auxiliary/Elasticsearch.Net.VirtualizedCluster/VirtualClusterConnection.cs
  src/Elasticsearch.Net/Utf8Json/Internal/Emit/ILViewer.cs
Labels: Port to master, v7.4.1, v8.0.0

#4216 Feature/master/versioned benchmarks
  nuget.config
  src/Elasticsearch.Net/Providers/MemoryStreamFactory.cs
  src/Tests/Tests.Benchmarking/BenchmarkProgram.cs
  src/Tests/Tests.Benchmarking/BulkBenchmarkTests.cs
  src/Tests/Tests.Benchmarking/Tests.Benchmarking.csproj
  src/Tests/Tests.Core/Client/Settings/AlwaysInMemoryConnectionSettings.cs
  src/Tests/Tests.Core/Client/Settings/TestConnectionSettings.cs
  src/Tests/Tests.Core/Client/TestClient.cs
  src/Tests/Tests.Core/Extensions/TestConfigurationExtensions.cs
  src/Tests/Tests.Domain/Project.cs
  src/Tests/Tests.ScratchPad/Program.cs
  src/Tests/Tests.ScratchPad/Tests.ScratchPad.csproj
Labels: Infra

#4214 Deserialize anonymous bucket with only doc_count
  src/Nest/Aggregations/AggregateFormatter.cs
  src/Tests/Tests.Reproduce/GithubIssue4197.cs
Labels: Bug, Port to master, v7.4.1

#4219 Serialize own IProperty implementations
  docs/client-concepts/connection/configuration-options.asciidoc
  docs/client-concepts/high-level/serialization/extending-nest-types.asciidoc
  docs/high-level.asciidoc
  src/Nest/Mapping/Types/PropertyFormatter.cs
  src/Tests/Tests/ClientConcepts/HighLevel/Serialization/ExtendingNestTypes.doc.cs
  src/Tests/Tests/high-level.asciidoc
Labels: Bug, v7.4.1

#4221 Fix spelling mistakes.
  docs/client-concepts/connection-pooling/building-blocks/connection-pooling.asciidoc
  docs/client-concepts/connection-pooling/request-overrides/disable-sniff-ping-per-request.asciidoc
  docs/client-concepts/connection-pooling/sniffing/on-stale-cluster-state.asciidoc
  docs/client-concepts/connection/configuration-options.asciidoc
  docs/client-concepts/high-level/mapping/parent-child-relationships.asciidoc
  docs/client-concepts/high-level/serialization/extending-nest-types.asciidoc
  docs/client-concepts/low-level/lifetimes.asciidoc
  docs/client-concepts/low-level/post-data.asciidoc
  docs/common-options/time-unit/time-units.asciidoc
  src/Tests/Tests/ClientConcepts/Connection/ConfigurationOptions.doc.cs
  src/Tests/Tests/ClientConcepts/ConnectionPooling/BuildingBlocks/ConnectionPooling.doc.cs
  src/Tests/Tests/ClientConcepts/ConnectionPooling/RequestOverrides/DisableSniffPingPerRequest.doc.cs
  src/Tests/Tests/ClientConcepts/ConnectionPooling/Sniffing/OnStaleClusterState.doc.cs
  src/Tests/Tests/ClientConcepts/HighLevel/Mapping/ParentChildRelationships.doc.cs
  src/Tests/Tests/ClientConcepts/HighLevel/Serialization/ExtendingNestTypes.doc.cs
  src/Tests/Tests/ClientConcepts/LowLevel/Lifetimes.doc.cs
  src/Tests/Tests/ClientConcepts/LowLevel/PostData.doc.cs
  src/Tests/Tests/CommonOptions/TimeUnit/TimeUnits.doc.cs
Labels: Port to master, v7.4.1

#4220 Replace links to elasticsearch.org with elastic.co
  contributing.md
  src/Elasticsearch.Net/Configuration/ConnectionConfiguration.cs
  src/Elasticsearch.Net/Configuration/IConnectionConfigurationValues.cs
  src/Nest/Document/Multiple/Bulk/ElasticClient-DeleteMany.cs
  src/Nest/Document/Multiple/Bulk/ElasticClient-IndexMany.cs
  src/Nest/Document/Multiple/MultiGet/ElasticClient-GetMany.cs
  src/Nest/Document/Multiple/MultiGet/ElasticClient-SourceMany.cs
  src/Nest/Document/Single/Index/ElasticClient-Index.cs
  src/Nest/Indices/MappingManagement/PutMapping/ElasticClient-Map.cs
  src/Tests/Tests/XPack/MachineLearning/MachineLearningCluster.cs
Labels: Docs, v7.4.1

#4218 Increment count when serialising multiple lifecycle actions.
  src/Nest/XPack/Ilm/LifecycleActions.cs
  src/Tests/Tests/XPack/Ilm/IlmApiTests.cs
Labels: Port to master, v7.4.1

#4210 reintroduce skipdocs for default build target
  build/scripts/Commandline.fs
Labels: Infra, Port to master

#4222 Add support for WKT with GeoLocation type
  src/Nest/QueryDsl/Geo/GeoLocation.cs
  src/Nest/QueryDsl/Geo/GeoLocationFormatter.cs
  src/Nest/QueryDsl/Geo/Shape/GeoShapeBase.cs
  src/Nest/QueryDsl/Geo/WKT/GeoWKTReader.cs
  src/Tests/Tests/CodeStandards/Serialization/GeoLocationTests.cs
Labels: Feature, v7.4.1

#4223 Diff release version against previous version from Nuget
  build/scripts/Differ.fs
  build/scripts/Targets.fs
  build/scripts/scripts.fsproj
Labels: Infra, v7.4.1

#4224 Sourcelink and include PDBs in nuget packages
  build/Elasticsearch.Net.VirtualizedCluster.nuspec
  build/Elasticsearch.Net.nuspec
  build/NEST.JsonNetSerializer.nuspec
  build/NEST.nuspec
  build/scripts/Commandline.fs
  build/scripts/Releasing.fs
  build/scripts/Tooling.fs
  src/PublishArtifacts.build.props
Labels: Infra

#4225 Remove lat lon bound checks from GeoLocation
  src/Nest/QueryDsl/Geo/GeoLocation.cs
Labels: Feature, v7.4.1

#4230 Share random seed between test framework and build scripts
  build/scripts/Commandline.fs
  build/scripts/Targets.fs
  build/scripts/Testing.fs
Labels: Infra

#4238 Expose q querystring parameter on search
  src/CodeGeneration/ApiGenerator/Configuration/Overrides/Endpoints/SearchOverrides.cs
  src/Elasticsearch.Net/Api/RequestParameters/RequestParameters.NoNamespace.cs
  src/Nest/Descriptors.NoNamespace.cs
  src/Nest/Requests.NoNamespace.cs
  src/Nest/Search/Search/SearchRequest.cs
Labels: Feature, Port to 7.x, v7.5.0, v8.0.0

#4236 Fix null ref DynamicResponse when host not available
  src/Elasticsearch.Net/Transport/Pipeline/ResponseBuilder.cs
Labels: Port to master, v7.5.0
