Repository elastic/elasticsearch-net, pull requests merged in 2019-06, with the labels that each got.

#3786 Re instantiate custom deserialisation for nodes hot threads
  src/CodeGeneration/ApiGenerator/Domain/Code/HighLevel/Methods/InitializerMethod.cs
  src/Nest/ElasticClient.Nodes.cs
  src/Nest/ElasticClient.cs
Labels: v7.0.0

#3793 Custom response deserialization wiring
  src/CodeGeneration/ApiGenerator/Configuration/CodeConfiguration.cs
  src/CodeGeneration/ApiGenerator/Domain/Code/CsharpNames.cs
  src/CodeGeneration/ApiGenerator/Domain/Code/HighLevel/Methods/InitializerMethod.cs
  src/CodeGeneration/ApiGenerator/Views/HighLevel/Client/InitializerSyntax/InitializerMethod.cshtml
  src/Elasticsearch.Net/Api/RequestParameters/IRequestParameters.cs
  src/Elasticsearch.Net/Api/RequestParameters/RequestParameters.cs
  src/Elasticsearch.Net/Serialization/CustomResponseBuilderBase.cs
  src/Elasticsearch.Net/Serialization/ElasticsearchSerializerExtensions.cs
  src/Elasticsearch.Net/Transport/Pipeline/RequestData.cs
  src/Elasticsearch.Net/Transport/Pipeline/ResponseBuilder.cs
  src/Nest/Cat/CatHelpResponseBuilder.cs
  src/Nest/Cat/CatResponseBuilder.cs
  src/Nest/Cluster/NodesHotThreads/NodeHotThreadsResponseBuilder.cs
  src/Nest/Cluster/NodesHotThreads/NodesHotThreadsRequest.cs
  src/Nest/Cluster/NodesHotThreads/NodesHotThreadsResponse.cs
  src/Nest/CommonAbstractions/ConnectionSettings/ConnectionSettingsBase.cs
  src/Nest/CommonAbstractions/ConnectionSettings/ConnectionSettingsValuesExtensions.cs
  src/Nest/CommonAbstractions/ForAttribute.cs
  src/Nest/CommonAbstractions/Request/RequestBase.cs
  src/Nest/CommonAbstractions/SerializationBehavior/InternalSerializer.cs
  src/Nest/CommonAbstractions/SerializationBehavior/StatefulSerializerExtensions.cs
  src/Nest/CommonAbstractions/SerializationBehavior/StatefulSerializerFactory.cs
  src/Nest/Document/Multiple/MultiGet/Request/MultiGetRequest.cs
  src/Nest/Document/Multiple/MultiGet/Request/MultiGetResponseBuilder.cs
  src/Nest/Document/Single/Source/SourceRequest.cs
  src/Nest/Document/Single/Source/SourceRequestResponseBuilder.cs
  src/Nest/ElasticClient.Cat.cs
  src/Nest/ElasticClient.NoNamespace.cs
  src/Nest/ElasticClient.Nodes.cs
  src/Nest/ElasticClient.cs
  src/Nest/Search/MultiSearch/MultiSearchRequest.cs
  src/Nest/Search/MultiSearch/MultiSearchResponseBuilder.cs
  src/Nest/Search/MultiSearchTemplate/MultiSearchTemplateRequest.cs
  src/Nest/Search/Search/SearchRequest.cs
  src/Nest/Search/SearchTemplate/SearchTemplateRequest.cs
  src/Nest/XPack/Sql/TranslateSql/TranslateSqlRequest.cs
  src/Nest/XPack/Sql/TranslateSql/TranslateSqlResponseBuilder.cs
  src/Nest/XPack/Ssl/GetCertificates/GetCertificatesRequest.cs
  src/Nest/XPack/Ssl/GetCertificates/GetCertificatesResponseBuilder.cs
Labels: v7.0.0

#3794 PostData contained routines to handle serializable but can not be con…
  src/Elasticsearch.Net/Transport/PostData.cs
  src/Elasticsearch.Net/Transport/SerializableData.cs
Labels: v7.0.0

#3779 Use a custom convertor for GeoOrientation to tolerate alternative options in Elasticsearch #3776
  src/Nest/CommonAbstractions/SerializationBehavior/JsonFormatters/NestFormatterResolver.cs
  src/Nest/Mapping/Types/Geo/GeoShape/GeoOrientation.cs
  src/Tests/Tests/Mapping/Types/Geo/GeoShape/GeoShapeClusterMetadataApiTests.cs
Labels: v7.0.0

#3780 Add pretty names (and other properties) to the cluster stats response. #3766
  src/Nest/Cluster/ClusterStats/ClusterNodesStats.cs
  src/Nest/Cluster/ClusterStats/ClusterStatsResponse.cs
  src/Nest/Cluster/NodesInfo/NodeInfo.cs
  src/Nest/CommonOptions/Stats/CompletionStats.cs
  src/Nest/CommonOptions/Stats/FieldDataStats.cs
  src/Nest/CommonOptions/Stats/PluginStats.cs
  src/Nest/CommonOptions/Stats/QueryCacheStats.cs
  src/Nest/CommonOptions/Stats/SegmentsStats.cs
  src/Tests/Tests/Cluster/ClusterStats/ClusterStatsApiTests.cs
Labels: v7.0.0

#3805 Routing must be specified when doc used
  src/Nest/QueryDsl/Specialized/MoreLikeThis/Like/LikeDocument.cs
  src/Tests/Tests/QueryDsl/Specialized/MoreLikeThis/MoreLikeThisFullDocumentQueryUsageTests.cs
Labels: v7.0.0, v7.0.0-beta1

#3807 Use indexers to set default mapping values
  src/Nest/CommonAbstractions/ConnectionSettings/ConnectionSettingsBase.cs
Labels: v7.0.0, v7.0.0-beta1

#3806 User SecureString for Basic and Proxy passwords
  src/Elasticsearch.Net/Configuration/ConnectionConfiguration.cs
  src/Elasticsearch.Net/Configuration/IConnectionConfigurationValues.cs
  src/Elasticsearch.Net/Configuration/RequestConfiguration.cs
  src/Elasticsearch.Net/Configuration/Security/BasicAuthenticationCredentials.cs
  src/Elasticsearch.Net/Connection/HttpConnection.cs
  src/Elasticsearch.Net/Connection/SecureStrings.cs
  src/Elasticsearch.Net/Transport/Pipeline/RequestData.cs
  src/Tests/Tests/Cat/CatIndices/CatIndicesApiTests.cs
  src/Tests/Tests/ClientConcepts/Connection/HttpConnectionTests.cs
  src/Tests/Tests/XPack/Security/ApiKey/SecurityApiKeyTests.cs
  src/Tests/Tests/XPack/Security/Authenticate/AuthenticateApiTests.cs
  src/Tests/Tests/XPack/Security/Privileges/ApplicationPrivilegesApiTests.cs
Labels: v7.0.0, v7.0.0-beta1

#3809 Add overloads of SerializeToString and SerializeToBytes
  src/Elasticsearch.Net/Serialization/ElasticsearchSerializerExtensions.cs
Labels: v7.0.0, v7.0.0-beta1

#3784 Add User-Agent string to API calls to Elasticsearch
  src/Elasticsearch.Net/Configuration/ConnectionConfiguration.cs
  src/Elasticsearch.Net/Configuration/IConnectionConfigurationValues.cs
  src/Elasticsearch.Net/Connection/HttpConnection-CoreFx.cs
  src/Elasticsearch.Net/Connection/HttpWebRequestConnection.cs
  src/Elasticsearch.Net/Domain/NativeMethods.cs
  src/Elasticsearch.Net/Domain/RuntimeInformation.cs
  src/Elasticsearch.Net/Transport/Pipeline/RequestData.cs
  src/Nest/CommonAbstractions/ConnectionSettings/ConnectionSettingsBase.cs
  src/Nest/CrossPlatform/NativeMethods.cs
  src/Nest/CrossPlatform/RuntimeInformation.cs
Labels: Discuss, Port to 7.x, Port to master

#3820 Write WKT coordinates with invariant culture
  src/Nest/QueryDsl/Geo/WKT/GeoWKTWriter.cs
  src/Tests/Tests.Reproduce/GitHubIssue3819.cs
  src/Tests/Tests.Reproduce/UseCultureAttribute.cs
Labels: Bug, Port to 6.x, v6.8.1, v7.0.0, v7.0.0-rc1

#3825 Use Marshal.SecureStringToGlobalAllocUnicode
  src/Elasticsearch.Net/Configuration/ConnectionConfiguration.cs
  src/Elasticsearch.Net/Configuration/Security/BasicAuthenticationCredentials.cs
  src/Elasticsearch.Net/Connection/SecureStrings.cs
  src/Tests/Tests/ClientConcepts/Connection/SecureStringsTests.cs
Labels: Bug, v7.0.0, v7.0.0-rc1

#3844 Align Cat Threadpool properties
  src/Nest/Cat/CatThreadPool/CatThreadPoolRecord.cs
  src/Tests/Tests/Cat/CatThreadPool/CatThreadpoolApiTests.cs
Labels: Breaking, Feature, v7.0.0, v7.0.0-rc1

#3842 Add updateable index settings for nested fields and nested objects li…
  src/Nest/IndexModules/IndexSettings/Settings/UpdatableIndexSettings.cs
Labels: Feature, v7.0.0, v7.0.0-rc1

#3841 Adding took time to _msearch
  src/Nest/Search/MultiSearch/MultiSearchResponse.cs
  src/Nest/Search/MultiSearch/MultiSearchResponseFormatter.cs
  src/Tests/Tests/Search/MultiSearch/MultiSearchApiTests.cs
Labels: Feature, v7.0.0

#3840 Update documentation for default number of shards
  src/Nest/IndexModules/IndexSettings/Settings/IndexSettings.cs
Labels: Breaking, v7.0.0, v7.0.0-rc1

#3839 Remove Migration Assistance and Upgrade APIs
  src/CodeGeneration/ApiGenerator/ApiGenerator.csproj
  src/CodeGeneration/ApiGenerator/RestSpecification/Core/root.html
  src/CodeGeneration/ApiGenerator/RestSpecification/XPack/migration.get_assistance.json
  src/CodeGeneration/ApiGenerator/RestSpecification/XPack/migration.upgrade.json
  src/CodeGeneration/ApiGenerator/RestSpecification/XPack/root.html
  src/CodeGeneration/ApiGenerator/last_downloaded_version.txt
  src/Elasticsearch.Net/Api/RequestParameters/RequestParameters.Migration.cs
  src/Elasticsearch.Net/ElasticLowLevelClient.Migration.cs
  src/Nest/Descriptors.Migration.cs
  src/Nest/ElasticClient.Migration.cs
  src/Nest/Requests.Migration.cs
  src/Nest/XPack/Migration/MigrationAssistance/MigrationAssistanceRequest.cs
  src/Nest/XPack/Migration/MigrationAssistance/MigrationAssistanceResponse.cs
  src/Nest/XPack/Migration/MigrationUpgrade/MigrationUpgradeRequest.cs
  src/Nest/XPack/Migration/MigrationUpgrade/MigrationUpgradeResponse.cs
  src/Nest/_Generated/ApiUrlsLookup.generated.cs
  src/Tests/Tests/XPack/Migration/MigrationAssistance/MigrationAssistanceApiTests.cs
  src/Tests/Tests/XPack/Migration/MigrationAssistance/MigrationAssistanceUrlTests.cs
  src/Tests/Tests/XPack/Migration/MigrationUpgrade/InvalidMigrationUpgradeApiTests.cs
  src/Tests/Tests/XPack/Migration/MigrationUpgrade/MigrationUpgradeUrlTests.cs
Labels: Breaking, v7.0.0, v7.0.0-rc1

#3838 Add updateable max* index settings
  src/Nest/IndexModules/IndexSettings/Settings/UpdatableIndexSettings.cs
Labels: Feature, v7.0.0, v7.0.0-rc1

#3837 Add index.analyze.max_token_count to updateable index settings
  src/Nest/IndexModules/IndexSettings/Settings/UpdatableIndexSettings.cs
Labels: Feature, v7.0.0, v7.0.0-rc1

#3835 Support deprecated delimited_payload_filter name in deserialization
  src/Nest/Analysis/TokenFilters/TokenFilterFormatter.cs
Labels: Breaking, v7.0.0, v7.0.0-rc1

#3834 Sum on stats aggregation always returns a value
  src/Nest/Aggregations/AggregateFormatter.cs
  src/Nest/Aggregations/Metric/ExtendedStats/ExtendedStatsAggregate.cs
  src/Nest/Aggregations/Metric/Stats/StatsAggregate.cs
  src/Tests/Tests/Aggregations/Metric/ExtendedStats/ExtendedStatsAggregationUsageTests.cs
Labels: v7.0.0, v7.0.0-rc1

#3827 Add index name to ICreateIndexResponse
  src/Nest/Indices/IndexManagement/CreateIndex/CreateIndexResponse.cs
  src/Tests/Tests/Indices/IndexManagement/CreateIndex/CreateIndexApiTests.cs
Labels: Port to 7.x, Port to master, v6.8.1, v7.0.0

#3833 Advance reader when not expected JSON token
  src/Nest/Aggregations/Bucket/Terms/TermsExcludeFormatter.cs
  src/Nest/Aggregations/Bucket/Terms/TermsIncludeFormatter.cs
  src/Nest/Aggregations/Metric/PercentileRanks/PercentileRanksAggregationFormatter.cs
  src/Nest/Aggregations/Metric/Percentiles/PercentilesAggregationFormatter.cs
  src/Nest/Aggregations/Pipeline/MovingAverage/MovingAverageAggregationFormatter.cs
  src/Nest/CommonAbstractions/Fields/FieldValuesFormatter.cs
  src/Nest/CommonAbstractions/Infer/IndexName/IndexNameFormatter.cs
  src/Nest/CommonAbstractions/Infer/Indices/IndicesFormatter.cs
  src/Nest/CommonAbstractions/Infer/PropertyName/PropertyNameFormatter.cs
  src/Nest/CommonAbstractions/Infer/RelationName/RelationNameFormatter.cs
  src/Nest/CommonAbstractions/LazyDocument/LazyDocumentFormatter.cs
  src/Nest/CommonAbstractions/SerializationBehavior/JsonFormatters/DateTimeOffsetEpochMillisecondsFormatter.cs
  src/Nest/CommonAbstractions/SerializationBehavior/JsonFormatters/IndicesBoostFormatter.cs
  src/Nest/CommonAbstractions/SerializationBehavior/JsonFormatters/NullableDateTimeOffsetEpochSecondsFormatter.cs
  src/Nest/CommonAbstractions/SerializationBehavior/JsonFormatters/SortOrderFormatter.cs
  src/Nest/CommonOptions/Fuzziness/FuzzinessFormatter.cs
  src/Nest/CommonOptions/Geo/DistanceFormatter.cs
  src/Nest/CommonOptions/Scripting/ScriptFormatter.cs
  src/Nest/QueryDsl/MultiTermQueryRewrite/MultiTermQueryRewriteFormatter.cs
  src/Nest/QueryDsl/TermLevel/Fuzzy/FuzzyQueryFormatter.cs
  src/Nest/QueryDsl/TermLevel/Terms/TermsQueryFormatter.cs
  src/Nest/Search/Suggesters/ContextSuggester/SuggestContextFormatter.cs
Labels: v7.0.0, v7.0.0-rc1

#3824 Feature/7.x/cluster state dynamic
  src/Elasticsearch.Net/Responses/Dynamic/DynamicDictionary.cs
  src/Elasticsearch.Net/Responses/Dynamic/DynamicResponse.cs
  src/Elasticsearch.Net/Responses/Dynamic/DynamicValue.cs
  src/Elasticsearch.Net/Serialization/Formatters/DynamicDictionaryFormatter.cs
  src/Elasticsearch.Net/Transport/Pipeline/ResponseBuilder.cs
  src/Nest/Cluster/ClusterReroute/ClusterRerouteResponse.cs
  src/Nest/Cluster/ClusterReroute/ClusterRerouteState.cs
  src/Nest/Cluster/ClusterState/AllocationId.cs
  src/Nest/Cluster/ClusterState/BlockState.cs
  src/Nest/Cluster/ClusterState/ClusterStateResponse.cs
  src/Nest/Cluster/ClusterState/IndexRoutingTable.cs
  src/Nest/Cluster/ClusterState/MetadataIndexState.cs
  src/Nest/Cluster/ClusterState/MetadataState.cs
  src/Nest/Cluster/ClusterState/NodeState.cs
  src/Nest/Cluster/ClusterState/RoutingNodesState.cs
  src/Nest/Cluster/ClusterState/RoutingShard.cs
  src/Nest/Cluster/ClusterState/RoutingTableState.cs
  src/Nest/Cluster/ClusterState/StoredScriptMapping.cs
  src/Nest/Cluster/NodesInfo/NodeInfo.cs
  src/Nest/CommonAbstractions/Response/DynamicResponseBase.cs
  src/Tests/Tests.Configuration/tests.default.yaml
  src/Tests/Tests/Cluster/ClusterState/ClusterStateApiTests.cs
Labels: Feature, v7.0.0

#3831 Return of net461
  azure-pipelines.yml
  build/Elasticsearch.Net.nuspec
  build/NEST.JsonNetSerializer.nuspec
  build/NEST.nuspec
  build/scripts/Projects.fs
  src/Elasticsearch.Net/Connection/HttpConnection-FullFramework.cs
  src/Elasticsearch.Net/Connection/HttpConnection.cs
  src/Elasticsearch.Net/Connection/HttpWebRequestConnection.cs
  src/Elasticsearch.Net/Elasticsearch.Net.csproj
  src/Elasticsearch.Net/Utf8Json/Formatters/TupleFormatter.cs
  src/Elasticsearch.Net/Utf8Json/Formatters/ValueTupleFormatter.cs
  src/Library.build.props
  src/Nest/Nest.csproj
  src/PublishArtifacts.build.props
  src/Serializers/Nest.JsonNetSerializer/Nest.JsonNetSerializer.csproj
  src/Tests/Tests/ClientConcepts/Certificates/WorkingWithCertificates.doc.cs
  src/Tests/Tests/ClientConcepts/Connection/HttpConnectionTests.cs
  src/Tests/Tests/ClientConcepts/Connection/ModifyingDefaultConnection.doc.cs
  src/Tests/Tests/Cluster/ClusterReroute/ClusterRerouteApiTests.cs
  src/Tests/Tests/Cluster/ClusterStats/ClusterStatsApiTests.cs
  src/Tests/Tests/Cluster/RemoteInfo/RemoteInfoApiTests.cs
  src/Tests/Tests/Framework/EndpointTests/CoordinatedIntegrationTestBase.cs
  src/Tests/Tests/Framework/EndpointTests/TestState/CoordinatedUsage.cs
  src/Tests/Tests/Framework/Extensions/FullFrameworkExtensions.cs
  src/Tests/Tests/Framework/Extensions/WaitHandleExtensions.cs
  src/Tests/Tests/Framework/Extensions/WebClient-CoreFx.cs
  src/Tests/Tests/Tests.csproj
Labels: Feature, v7.0.0

#3865 Delete Indices Upgrade APIs
  src/CodeGeneration/ApiGenerator/Configuration/CodeConfiguration.cs
  src/Elasticsearch.Net/Api/RequestParameters/RequestParameters.Indices.cs
  src/Elasticsearch.Net/ElasticLowLevelClient.Indices.cs
  src/Nest/Descriptors.Indices.cs
  src/Nest/ElasticClient.Indices.cs
  src/Nest/Indices/StatusManagement/Upgrade/UpgradeRequest.cs
  src/Nest/Indices/StatusManagement/Upgrade/UpgradeResponse.cs
  src/Nest/Indices/StatusManagement/Upgrade/UpgradeStatus/UpgradeStatus.cs
  src/Nest/Indices/StatusManagement/Upgrade/UpgradeStatus/UpgradeStatusRequest.cs
  src/Nest/Indices/StatusManagement/Upgrade/UpgradeStatus/UpgradeStatusResponse.cs
  src/Nest/Requests.Indices.cs
  src/Nest/_Generated/ApiUrlsLookup.generated.cs
  src/Tests/Tests/Indices/StatusManagement/Upgrade/UpgradeApiTests.cs
  src/Tests/Tests/Indices/StatusManagement/Upgrade/UpgradeUrlTests.cs
Labels: Breaking, v7.0.0, v7.0.0-rc1

#3864 Remove HighlightDocumentDictionary, HighlightHit
  src/Nest/Search/Explain/Explanation.cs
  src/Nest/Search/Search/Highlighting/Highlight.cs
  src/Nest/Search/Search/Highlighting/HighlightDocumentDictionary.cs
  src/Nest/Search/Search/Highlighting/HighlightHit.cs
  src/Nest/Search/Search/Hits/Hit.cs
  src/Tests/Tests/Search/Request/HighlightingUsageTests.cs
  src/Tests/Tests/Search/Request/InnerHitsUsageTests.cs
  src/Tests/Tests/Search/WritingQueries.doc.cs
Labels: Breaking, v7.0.0, v7.0.0-rc1

#3815 Collection deserialisation needs to check for null tokens
  src/Nest/Aggregations/Bucket/SignificantTerms/IncludeExclude.cs
  src/Nest/Cat/CatHelpResponseBuilder.cs
  src/Nest/Cat/CatResponseBuilder.cs
  src/Nest/Cluster/NodesHotThreads/NodeHotThreadsResponseBuilder.cs
  src/Nest/CommonAbstractions/LazyDocument/LazyDocumentFormatter.cs
  src/Nest/CommonAbstractions/SerializationBehavior/Attributes/MachineLearningDateTimeAttribute.cs
  src/Nest/CommonAbstractions/SerializationBehavior/JsonFormatters/DateTimeOffsetEpochMillisecondsFormatter.cs
  src/Nest/Document/Multiple/MultiGet/Request/MultiGetResponseBuilder.cs
  src/Nest/Document/Single/Source/SourceRequestResponseBuilder.cs
  src/Nest/ElasticClient.MachineLearning.cs
  src/Nest/ElasticClient.cs
  src/Nest/Indices/AliasManagement/Alias/Actions/IAliasAction.cs
  src/Nest/QueryDsl/Span/Gap/SpanGapQuery.cs
  src/Nest/QueryDsl/TermLevel/Fuzzy/FuzzyQueryFormatter.cs
  src/Nest/Search/MultiSearch/MultiSearchResponseBuilder.cs
  src/Nest/Search/Search/SourceFiltering/SourceFilterJsonConverter.cs
  src/Nest/Search/Suggesters/ContextSuggester/SuggestContextFormatter.cs
  src/Nest/XPack/MachineLearning/Job/Detectors/Detector.cs
  src/Nest/XPack/MachineLearning/PreviewDatafeed/PreviewDatafeedRequest.cs
  src/Nest/XPack/MachineLearning/PreviewDatafeed/PreviewDatafeedResponse.cs
  src/Nest/XPack/MachineLearning/PreviewDatafeed/PreviewDatafeedResponseBuilder.cs
  src/Nest/XPack/Sql/QuerySql/SqlValue.cs
  src/Nest/XPack/Sql/TranslateSql/TranslateSqlResponseBuilder.cs
  src/Nest/XPack/Ssl/GetCertificates/GetCertificatesResponseBuilder.cs
  src/Tests/Tests.Domain/Metric.cs
  src/Tests/Tests.Reproduce/GithubIssue3813.cs
Labels: v7.0.0

#3862 Feature/7.x/diagnostics source
  src/Elasticsearch.Net/Auditing/Audit.cs
  src/Elasticsearch.Net/Auditing/AuditEvent.cs
  src/Elasticsearch.Net/Auditing/Auditable.cs
  src/Elasticsearch.Net/Configuration/ConnectionConfiguration.cs
  src/Elasticsearch.Net/Connection/Content/RequestDataContent.cs
  src/Elasticsearch.Net/Connection/HttpConnection.cs
  src/Elasticsearch.Net/Diagnostics/AuditDiagnosticObserver.cs
  src/Elasticsearch.Net/Diagnostics/Diagnostic.cs
  src/Elasticsearch.Net/Diagnostics/DiagnosticSources.cs
  src/Elasticsearch.Net/Diagnostics/HttpConnectionDiagnosticObserver.cs
  src/Elasticsearch.Net/Diagnostics/RequestPipelineDiagnosticObserver.cs
  src/Elasticsearch.Net/Diagnostics/SerializerDiagnosticObserver.cs
  src/Elasticsearch.Net/Diagnostics/TypedDiagnosticObserverBase.cs
  src/Elasticsearch.Net/Elasticsearch.Net.csproj
  src/Elasticsearch.Net/Serialization/DiagnosticsSerializerProxy.cs
  src/Elasticsearch.Net/Serialization/IInternalSerializerWithFormatter.cs
  src/Elasticsearch.Net/Transport/Pipeline/RequestData.cs
  src/Elasticsearch.Net/Transport/Pipeline/RequestPipeline.cs
  src/Elasticsearch.Net/Transport/Pipeline/ResponseBuilder.cs
  src/Nest/CommonAbstractions/ConnectionSettings/ConnectionSettingsBase.cs
  src/Nest/CommonAbstractions/SerializationBehavior/DefaultHighLevelSerializer.cs
  src/Nest/CommonAbstractions/SerializationBehavior/StatefulSerializerExtensions.cs
  src/Tests/Tests.Configuration/tests.default.yaml
  src/Tests/Tests.ScratchPad/Program.cs
  src/Tests/Tests.ScratchPad/Tests.ScratchPad.csproj
  src/Tests/Tests/ClientConcepts/Troubleshooting/DiagnosticSource.doc.cs
  src/Tests/Tests/CodeStandards/NamingConventions.doc.cs
  src/Tests/Tests/CodeStandards/Responses.doc.cs
  src/Tests/Tests/Tests.csproj
Labels: Feature, Performance, v7.0.0

#3871 Feature/7.x/warnings as errors
  src/CodeGeneration/DocGenerator/DocGenerator.csproj
  src/CodeGeneration/DocGenerator/Documentation/Files/DocumentationFile.cs
  src/Elasticsearch.Net/Connection/Content/RequestDataContent.cs
  src/Elasticsearch.Net/Elasticsearch.Net.csproj
  src/Elasticsearch.Net/Transport/Pipeline/ResponseBuilder.cs
  src/Elasticsearch.sln
  src/Library.build.props
  src/Nest/Cat/CatHelpResponseBuilder.cs
  src/Nest/Cat/CatResponseBuilder.cs
  src/Nest/Cluster/NodesHotThreads/NodeHotThreadsResponseBuilder.cs
  src/Nest/Document/Multiple/BulkAll/BulkAllObservable.cs
  src/Nest/Document/Multiple/MultiGet/Request/MultiGetResponseBuilder.cs
  src/Nest/Document/Single/Source/SourceRequestResponseBuilder.cs
  src/Nest/Nest.csproj
  src/Nest/Search/MultiSearch/MultiSearchResponseBuilder.cs
  src/Nest/XPack/MachineLearning/PreviewDatafeed/PreviewDatafeedResponseBuilder.cs
  src/Nest/XPack/Sql/TranslateSql/TranslateSqlResponseBuilder.cs
  src/Nest/XPack/Ssl/GetCertificates/GetCertificatesResponseBuilder.cs
  src/Serializers/Nest.JsonNetSerializer/Nest.JsonNetSerializer.csproj
  src/Tests.build.props
  src/Tests/Directory.Build.props
  src/Tests/Tests.Core/Tests.Core.csproj
Labels: Bug, Feature, v7.0.0

#3867 Fix/7.x/clean up type extensions
  src/Nest/CommonAbstractions/Extensions/StringExtensions.cs
  src/Nest/CommonAbstractions/Extensions/TypeExtensions.cs
Labels: Refactoring, v7.0.0

#3866 Fix/7.x/unmapped
  src/CodeGeneration/ApiGenerator/Configuration/CodeConfiguration.cs
  src/CodeGeneration/ApiGenerator/Views/HighLevel/Descriptors/Descriptor.cshtml
  src/CodeGeneration/ApiGenerator/Views/HighLevel/Requests/RequestImplementations.cshtml
  src/Nest/Descriptors.IndexLifecycleManagement.cs
  src/Nest/Descriptors.Security.cs
  src/Nest/Requests.IndexLifecycleManagement.cs
  src/Nest/Requests.Security.cs
Labels: Bug, v7.0.0

#3868 rename ICovariantSearch
  src/Nest/Search/ITypedSearchRequest.cs
  src/Nest/Search/MultiSearch/MultiSearchResponseFormatter.cs
  src/Nest/Search/Scroll/Scroll/ScrollRequest.cs
  src/Nest/Search/Search/SearchRequest.cs
  src/Nest/Search/SearchTemplate/SearchTemplateRequest.cs
Labels: Refactoring, v7.0.0

#3869 DocCount no longer nullable on matrix stats aggregation
  src/Nest/Aggregations/AggregateFormatter.cs
  src/Nest/Aggregations/Matrix/MatrixStats/MatrixStatsAggregate.cs
  src/Tests/Tests.Configuration/tests.default.yaml
  src/Tests/Tests/Aggregations/Matrix/MatrixStats/MatrixStatsAggregationUsageTests.cs
Labels: Refactoring, v7.0.0

#3872 Lazy document now uses source serializer and has async overloads
  src/Elasticsearch.Net/Providers/RecyclableMemoryStreamFactory.cs
  src/Nest/Aggregations/AggregateFormatter.cs
  src/Nest/CommonAbstractions/LazyDocument/LazyDocument.cs
Labels: Refactoring, v7.0.0

#3878 Dictionary serialization tests
  src/Elasticsearch.Net/Serialization/Formatters/ExceptionFormatter.cs
  src/Elasticsearch.Net/Utf8Json/Formatters/DictionaryFormatter.cs
  src/Nest/Aggregations/VerbatimDictionaryKeysFormatter.cs
  src/Tests/Tests/Framework/SerializationTests/DictionarySerializationTests.cs
Labels: Port to 6.x, v7.0.0, v7.0.0-rc1

#3879 Make Should implementation explicit
  src/Nest/QueryDsl/Compound/Bool/BoolQuery.cs
Labels: v7.0.0

#3883 Fix CatHelp NodeHotThreads integ tests due to mimetype mismatch
  build/scripts/Tooling.fs
  build/scripts/scripts.fsproj
  src/Elasticsearch.Net/Connection/HttpWebRequestConnection.cs
  src/Elasticsearch.Net/Transport/Pipeline/RequestData.cs
  src/Nest/Cluster/NodesHotThreads/NodesHotThreadsRequest.cs
  src/Nest/CommonAbstractions/Request/RequestBase.cs
  src/Nest/ElasticClient.cs
  src/Tests/Tests.Benchmarking/Tests.Benchmarking.csproj
  src/Tests/Tests.Core/Tests.Core.csproj
  src/Tests/Tests.Domain/Tests.Domain.csproj
  src/Tests/Tests/ClientConcepts/Troubleshooting/DiagnosticSource.doc.cs
  src/Tests/Tests/Framework/EndpointTests/CoordinatedIntegrationTestBase.cs
  src/Tests/Tests/Indices/IndexManagement/RolloverIndex/RolloverIndexApiTests.cs
  src/Tests/Tests/XPack/Security/User/PutUser/PutUserApiTests.cs
Labels: Bug, v7.0.0

#3887 ResponseBuilder mimeType check is too strict on net461
  src/Elasticsearch.Net/Transport/Pipeline/ResponseBuilder.cs
Labels: Bug, v7.0.0

#3891 Ephemeral Cluster for tests now uses a SHA has for its cached folder
  build/scripts/scripts.fsproj
  src/Tests/Tests.Benchmarking/Tests.Benchmarking.csproj
  src/Tests/Tests.Core/Tests.Core.csproj
  src/Tests/Tests.Domain/Tests.Domain.csproj
Labels: Bug, v7.0.0

#3892 remove valuetuple and valuetask dependencies
  build/Elasticsearch.Net.nuspec
  src/Elasticsearch.Net/Configuration/ConnectionConfiguration.cs
  src/Elasticsearch.Net/Connection/Content/RequestDataContent.cs
  src/Elasticsearch.Net/Diagnostics/AuditDiagnosticObserver.cs
  src/Elasticsearch.Net/Diagnostics/HttpConnectionDiagnosticObserver.cs
  src/Elasticsearch.Net/Diagnostics/RequestPipelineDiagnosticObserver.cs
  src/Elasticsearch.Net/Diagnostics/SerializerDiagnosticObserver.cs
  src/Elasticsearch.Net/Diagnostics/TypedDiagnosticObserverBase.cs
  src/Elasticsearch.Net/Elasticsearch.Net.csproj
  src/Elasticsearch.Net/Serialization/DiagnosticsSerializerProxy.cs
  src/Elasticsearch.Net/Utf8Json/Formatters/StandardClassLibraryFormatters.cs
  src/Elasticsearch.Net/Utf8Json/Formatters/ValueTupleFormatter.cs
  src/Elasticsearch.Net/Utf8Json/Resolvers/DynamicGenericResolver.cs
  src/Serializers/Nest.JsonNetSerializer/Converters/HandleNestTypesOnSourceJsonConverter.cs
  src/Tests/Tests.ScratchPad/Program.cs
  src/Tests/Tests/ClientConcepts/Troubleshooting/DiagnosticSource.doc.cs
  src/Tests/Tests/Tests.csproj
Labels: Bug, v7.0.0

#3893 add System.DiagnosticSource to nuspec
  build/Elasticsearch.Net.nuspec
Labels: v7.0.0
