Repository elastic/elasticsearch-net, pull requests merged in 2020-03, with the labels that each got.

#4470 Adds socket timeout and connect timeout options to reindex on server.
  src/Nest/Document/Multiple/ReindexOnServer/RemoteSource.cs
  tests/Tests/Document/Multiple/ReindexOnServer/ReindexOnServerRemoteApiTests.cs
Labels: backport 7.6, backport 7.x

#4468 Deserialize string bool and int repository setting values
  src/Nest/Modules/SnapshotAndRestore/Repositories/AzureRepository.cs
  src/Nest/Modules/SnapshotAndRestore/Repositories/HdfsRepository.cs
  src/Nest/Modules/SnapshotAndRestore/Repositories/ReadOnlyUrlRepository.cs
  src/Nest/Modules/SnapshotAndRestore/Repositories/S3Repository.cs
  tests/Tests.Reproduce/GithubIssue4467.cs
Labels: Bug, backport 7.6, backport 7.x, v7.6.1

#4478 Update .ci folder to latest incarnation
  .ci/functions/cleanup.sh
  .ci/functions/imports.sh
  .ci/functions/wait-for-container.sh
  .ci/jobs/defaults.yml
  .ci/readme.md
  .ci/run-elasticsearch.sh
  .ci/run-repository.sh
  .ci/run-tests
  .ci/test-matrix.yml
Labels: Infra, backport 7.x

#4477 Delete dependant fles generated by the ApiGenerator before generating them
  src/ApiGenerator/Generator/Razor/DescriptorsGenerator.cs
  src/ApiGenerator/Generator/Razor/HighLevelClientImplementationGenerator.cs
  src/ApiGenerator/Generator/Razor/LowLevelClientImplementationGenerator.cs
  src/ApiGenerator/Generator/Razor/RequestParametersGenerator.cs
  src/ApiGenerator/Generator/Razor/RequestsGenerator.cs
Labels: backport 7.6, backport 7.x

#4460 Update readme.md for LLC compatibility
  readme.md
  src/ApiGenerator/Views/LowLevel/Client/Methods/MethodDocs.cshtml
Labels: backport 7.x, v7.7.0

#4479 Update .ci folder to latest incarnation
  .ci/certs/ca.crt
  .ci/certs/ca.key
  .ci/certs/testnode.crt
  .ci/certs/testnode.key
  .ci/certs/testnode_san.crt
  .ci/certs/testnode_san.key
  .ci/functions/cleanup.sh
  .ci/functions/imports.sh
  .ci/functions/wait-for-container.sh
  .ci/jobs/defaults.yml
  .ci/run-elasticsearch.sh
  .ci/run-repository.sh
  .ci/run-tests
  .ci/test-matrix.yml
Labels: Infra

#4484 Update .ci folder
  .ci/certs/ca.crt
  .ci/certs/ca.key
  .ci/certs/ca.pem
  .ci/certs/testnode.crt
  .ci/certs/testnode.key
  .ci/certs/testnode_san.crt
  .ci/certs/testnode_san.key
  .ci/functions/wait-for-container.sh
  .ci/run-repository.sh
Labels: Infra, backport 7.x

#4485 Deduplicate example method names
  src/ExamplesGenerator/AsciiDocParser.cs
  src/ExamplesGenerator/CSharpGenerator.cs
  src/ExamplesGenerator/ReferenceExample.cs
  tests/Examples/Aggregations/Metrics/TopMetricsAggregationPage.cs
  tests/Examples/Analysis/Tokenfilters/TrimTokenfilterPage.cs
  tests/Examples/Ml/AnomalyDetection/Apis/GetJobStatsPage.cs
  tests/Examples/Setup/RestartClusterPage.cs
  tests/Examples/Upgrade/RollingUpgradePage.cs
Labels: Docs

#4488 Fix distance_feature query serialization
  docs/query-dsl/specialized/distance-feature/distance-feature-query-usage.asciidoc
  src/Nest/QueryDsl/Specialized/DistanceFeature/DistanceFeatureQuery.cs
  tests/Tests.Reproduce/GitHubIssue4487.cs
  tests/Tests/QueryDsl/Specialized/DistanceFeature/DistanceFeatureQueryUsageTests.cs
Labels: Bug, backport 7.6, backport 7.x, v7.6.1

#4491 Improve generated release notes
  build/scripts/Paths.fs
  build/scripts/ReleaseNotes.fs
Labels: Infra, backport 6.x, backport 7.6, backport 7.x

#4495 Fix SearchTemplateApiTests error reason
  tests/Tests/Search/SearchTemplate/SearchTemplateApiTests.cs
Labels: backport 7.6

#4499 Fix spelling of client in VirtualizedCluster
  src/Elasticsearch.Net.VirtualizedCluster/Elasticsearch.Net.VirtualizedCluster.csproj
Labels: backport 7.6, backport 7.x

#4504 Removes pretty print serialisation as it is not used.
  src/Elasticsearch.Net/Utf8Json/JsonSerializer.cs
Labels: backport 7.7, backport 7.x

#4514 Fix API generator (#4456)
  src/ApiGenerator/Domain/RestApiSpec.cs
  src/ApiGenerator/Generator/Razor/LowLevelClientImplementationGenerator.cs
  src/ApiGenerator/Generator/Razor/RequestParametersGenerator.cs
  src/ApiGenerator/Views/LowLevel/Client/Implementation/ElasticLowLevelClient.cshtml
  src/ApiGenerator/Views/LowLevel/Client/Interface/IElasticLowLevelClient.cshtml
  src/ApiGenerator/Views/LowLevel/Client/Usings.cshtml
Labels: backport 7.7, backport master

#4502 Remove MemoryStreamFactory and replace with RecyclableMemoryStreamFactory
  src/Elasticsearch.Net/Providers/MemoryStreamFactory.cs
  tests/Tests.Benchmarking/BulkBenchmarkTests.cs
  tests/Tests/ClientConcepts/Connection/HttpConnectionTests.cs
  tests/Tests/ClientConcepts/ConnectionPooling/BuildingBlocks/RequestPipelines.doc.cs
  tests/Tests/ClientConcepts/ConnectionPooling/Sniffing/RoleDetection.doc.cs
  tests/Tests/CodeStandards/Serialization/GeoLocationTests.cs
Labels: backport 7.7, backport master

#4503 ISO8601TimeSpanFormatter to use local byte[] array, as opposed to renting from pool.
  src/Elasticsearch.Net/Utf8Json/Formatters/DateTimeFormatter.cs
  tests/Tests.Reproduce/TimeSpanSerialization.cs
Labels: backport 7.7, backport master
