Repository elastic/elasticsearch-net, pull requests merged in 2020-04, with the labels that each got.

#4544 Fix Node Info
  src/Nest/Cluster/NodesInfo/NodeInfo.cs
  src/Nest/Cluster/NodesInfo/NodeRole.cs
Labels: backport 7.x, backport master, v7.7.0

#4545 Fixes integration tests against latest 7.7.0-SNAPSHOT
  tests/Tests/Aggregations/Pipeline/Derivative/DerivativeAggregationUsageTests.cs
  tests/Tests/Aggregations/Pipeline/MovingAverage/MovingAverageEwmaAggregationUsageTests.cs
  tests/Tests/Aggregations/Pipeline/MovingAverage/MovingAverageHoltLinearAggregationUsageTests.cs
  tests/Tests/Aggregations/Pipeline/MovingAverage/MovingAverageHoltWintersAggregationUsageTests.cs
  tests/Tests/Aggregations/Pipeline/MovingAverage/MovingAverageLinearAggregationUsageTests.cs
  tests/Tests/Aggregations/Pipeline/MovingAverage/MovingAverageSimpleAggregationUsageTests.cs
  tests/Tests/Aggregations/Pipeline/MovingFunction/MovingFunctionAggregationUsageTests.cs
  tests/Tests/Aggregations/Pipeline/SerialDifferencing/SerialDifferencingAggregationUsageTests.cs
  tests/Tests/QueryDsl/TermLevel/Terms/TermsLookupQueryUsageTests.cs
  tests/Tests/Search/SearchTemplate/SearchTemplateApiTests.cs
Labels: backport 7.x, backport master, v7.7.0

#4549 Remove snapshot testing from YAML run
  tests/Tests.YamlRunner/SkipList.fs
Labels: backport 7.x, backport master, v7.7.0

#4552 Update specifications
  src/ApiGenerator/Configuration/CodeConfiguration.cs
  src/ApiGenerator/RestSpecification/Core/root.html
  src/ApiGenerator/RestSpecification/XPack/cat.transforms.json
  src/ApiGenerator/RestSpecification/XPack/root.html
  src/Elasticsearch.Net/Api/RequestParameters/RequestParameters.Cat.cs
  src/Elasticsearch.Net/ElasticLowLevelClient.Cat.cs
  src/Nest/_Generated/ApiUrlsLookup.generated.cs
Labels: Self Reviewed, backport 7.x, backport master, v7.7.0

#4541 Add formatter for int -> string
  src/Nest/CommonAbstractions/SerializationBehavior/JsonFormatters/IntStringFormatter.cs
  src/Nest/Modules/SnapshotAndRestore/Snapshot/SnapshotShardFailure.cs
  tests/Tests.Reproduce/GitHubIssue4537.cs
Labels: Bug, backport 7.6, backport 7.7

#4543 Change SnapshotShardFailure shard_id to int
  src/Nest/Modules/SnapshotAndRestore/Snapshot/SnapshotShardFailure.cs
Labels: Bug, v8.0.0-alpha1

#4558 Update to latest CI packages
  build/scripts/scripts.fsproj
  tests/Tests.Configuration/Tests.Configuration.csproj
  tests/Tests.Core/Tests.Core.csproj
  tests/Tests.Domain/Tests.Domain.csproj
Labels: backport 7.x, backport master, v7.7.0

#4556 upgrade Bullseye from 3.1.0 to 3.3.0
  build/scripts/scripts.fsproj
Labels: backport 7.6, backport 7.7, backport 7.x

#4560 Update docs on master
  docs/client-concepts/connection-pooling/building-blocks/request-pipelines.asciidoc
Labels: Docs

#4561 Ignore indices.data_stream as API is unstable (experimental)
  tests/Tests.YamlRunner/SkipList.fs
Labels: backport 7.x, backport master, v7.7.0

#4581 Fix InternalsVisibleTo for versioned assemblies
  .gitignore
  Directory.Build.targets
  build/scripts/Versioning.fs
Labels: Bug, backport 7.6, backport 7.7, backport 7.x

#4580 Update custom serialization docs
  docs/client-concepts/high-level/serialization/custom-serialization.asciidoc
  docs/query-dsl.asciidoc
  tests/Tests/ClientConcepts/HighLevel/Serialization/CustomSerialization.doc.cs
Labels: Docs, backport 7.6, backport 7.7, backport 7.x

#4589 Update cluster.remote.connect to node.remote_cluster_client
  tests/Tests.Core/ManagedElasticsearch/Clusters/ClientTestClusterBase.cs
Labels: backport 7.6, backport 7.7, backport 7.x

#4529 Implement indices.reload_search_analyzers
  src/ApiGenerator/Configuration/CodeConfiguration.cs
  src/Nest/Descriptors.Indices.cs
  src/Nest/ElasticClient.Indices.cs
  src/Nest/Indices/ReloadSearchAnalyzers/ReloadDetails.cs
  src/Nest/Indices/ReloadSearchAnalyzers/ReloadSearchAnalyzersRequest.cs
  src/Nest/Indices/ReloadSearchAnalyzers/ReloadSearchAnalyzersResponse.cs
  src/Nest/Requests.Indices.cs
  tests/Tests/Indices/ReloadSearchAnalyzers/ReloadSearchAnalyzersApiTests.cs
  tests/Tests/Indices/ReloadSearchAnalyzers/ReloadSearchAnalyzersUrlTests.cs
Labels: backport 7.x, backport master, v7.7.0

#4530 Implement ml.estimate_model_memory.json
  src/ApiGenerator/Configuration/CodeConfiguration.cs
  src/Nest/Descriptors.MachineLearning.cs
  src/Nest/ElasticClient.MachineLearning.cs
  src/Nest/Requests.MachineLearning.cs
  src/Nest/XPack/MachineLearning/EstimateModelMemory/EstimateModelMemoryRequest.cs
  src/Nest/XPack/MachineLearning/EstimateModelMemory/EstimateModelMemoryResponse.cs
  tests/Tests/XPack/MachineLearning/EstimateModelMemory/EstimateModelMemoryApiTests.cs
  tests/Tests/XPack/MachineLearning/EstimateModelMemory/EstimateModelMemoryUrlTests.cs
Labels: backport 7.x, backport master, v7.7.0

#4535 Implement ml.set_upgrade_mode
  src/ApiGenerator/Configuration/CodeConfiguration.cs
  src/Nest/Descriptors.MachineLearning.cs
  src/Nest/ElasticClient.MachineLearning.cs
  src/Nest/Requests.MachineLearning.cs
  src/Nest/XPack/MachineLearning/SetUpgradeMode/SetUpgradeModeRequest.cs
  src/Nest/XPack/MachineLearning/SetUpgradeMode/SetUpgradeModeResponse.cs
  tests/Tests/XPack/MachineLearning/SetUpgradeMode/SetUpgradeModeApiTests.cs
  tests/Tests/XPack/MachineLearning/SetUpgradeMode/SetUpgradeModeUrlTests.cs
Labels: backport 7.x, backport master, v7.7.0

#4590 Fix InvalidSearchApiTests expected status code and message
  tests/Tests/Search/Search/InvalidSearchApiTests.cs
Labels: v8.0.0-alpha1

#4536 Implement security.get_builtin_privileges
  src/ApiGenerator/Configuration/CodeConfiguration.cs
  src/Nest/Descriptors.Security.cs
  src/Nest/ElasticClient.Security.cs
  src/Nest/Requests.Security.cs
  src/Nest/XPack/Security/Privileges/GetBuiltinPrivileges/GetBuiltinPrivilegesRequest.cs
  src/Nest/XPack/Security/Privileges/GetBuiltinPrivileges/GetBuiltinPrivilegesResponse.cs
  tests/Tests/XPack/Security/GetBuiltinPrivileges/GetBuiltinPrivilegesApiTests.cs
  tests/Tests/XPack/Security/GetBuiltinPrivileges/GetBuiltinPrivilegesUrlTests.cs
Labels: backport 7.x, backport master, v7.7.0

#4557 Implement cat.transforms
  src/ApiGenerator/Configuration/CodeConfiguration.cs
  src/Elasticsearch.Net/Api/RequestParameters/RequestParameters.Cat.cs
  src/Elasticsearch.Net/ElasticLowLevelClient.Cat.cs
  src/Nest/Cat/CatTransforms/CatTransformsRecord.cs
  src/Nest/Cat/CatTransforms/CatTransformsRequest.cs
  src/Nest/Cat/CatTransforms/TransformState.cs
  src/Nest/Cat/CatTransforms/TransformType.cs
  src/Nest/Descriptors.Cat.cs
  src/Nest/ElasticClient.Cat.cs
  src/Nest/Requests.Cat.cs
  tests/Tests/Cat/CatTransform/CatTransformsApiTests.cs
  tests/Tests/Cat/CatTransform/CatTransformsUrlTests.cs
Labels: backport 7.x, backport master, v7.7.0

#4562 Implement cat.ml_trained_models
  src/ApiGenerator/Configuration/CodeConfiguration.cs
  src/Elasticsearch.Net/Api/RequestParameters/RequestParameters.Cat.cs
  src/Elasticsearch.Net/ElasticLowLevelClient.Cat.cs
  src/Nest/Cat/CatTrainedModels/CatTrainedModelsRecord.cs
  src/Nest/Cat/CatTrainedModels/CatTrainedModelsRequest.cs
  src/Nest/Descriptors.Cat.cs
  src/Nest/ElasticClient.Cat.cs
  src/Nest/Requests.Cat.cs
  src/Nest/_Generated/ApiUrlsLookup.generated.cs
  tests/Tests/Cat/CatTrainedModels/CatTrainedModelsApiTests.cs
  tests/Tests/Cat/CatTrainedModels/CatTrainedModelsUrlTests.cs
Labels: backport 7.x, backport master, v7.7.0

#4563 Implement cat.ml_jobs
  src/ApiGenerator/Configuration/CodeConfiguration.cs
  src/Elasticsearch.Net/Api/RequestParameters/RequestParameters.Cat.cs
  src/Elasticsearch.Net/ElasticLowLevelClient.Cat.cs
  src/Nest/Cat/CatJobs/CatJobsRecord.cs
  src/Nest/Cat/CatJobs/CatJobsRequest.cs
  src/Nest/Cat/CatJobs/ModelCategorizationStatus.cs
  src/Nest/Cat/CatJobs/ModelMemoryStatus.cs
  src/Nest/Descriptors.Cat.cs
  src/Nest/Descriptors.MachineLearning.cs
  src/Nest/ElasticClient.Cat.cs
  src/Nest/ElasticClient.MachineLearning.cs
  src/Nest/Requests.Cat.cs
  src/Nest/Requests.MachineLearning.cs
  src/Nest/_Generated/ApiUrlsLookup.generated.cs
  tests/Tests/Cat/CatJobs/CatJobsApiTests.cs
  tests/Tests/Cat/CatJobs/CatJobsUrlTests.cs
Labels: backport 7.x, backport master, v7.7.0

#4564 Implement cat.ml_datafeeds
  src/ApiGenerator/Configuration/CodeConfiguration.cs
  src/Elasticsearch.Net/Api/RequestParameters/RequestParameters.Cat.cs
  src/Elasticsearch.Net/ElasticLowLevelClient.Cat.cs
  src/Nest/Cat/CatDatafeeds/CatDatafeedsRecord.cs
  src/Nest/Cat/CatDatafeeds/CatDatafeedsRequest.cs
  src/Nest/Descriptors.Cat.cs
  src/Nest/ElasticClient.Cat.cs
  src/Nest/Requests.Cat.cs
  src/Nest/XPack/MachineLearning/Datafeed/DatafeedState.cs
  src/Nest/_Generated/ApiUrlsLookup.generated.cs
  tests/Tests/Cat/CatDatafeeds/CatDatafeedsApiTests.cs
  tests/Tests/Cat/CatDatafeeds/CatDatafeedsUrlTests.cs
Labels: backport 7.x, backport master, v7.7.0

#4565 Implement cat.ml_data_frame_analytics
  src/ApiGenerator/Configuration/CodeConfiguration.cs
  src/Elasticsearch.Net/Api/RequestParameters/RequestParameters.Cat.cs
  src/Elasticsearch.Net/ElasticLowLevelClient.Cat.cs
  src/Nest/Cat/CatDataFrameAnalytics/CatDataFrameAnalyticsRecord.cs
  src/Nest/Cat/CatDataFrameAnalytics/CatDataFrameAnalyticsRequest.cs
  src/Nest/Descriptors.Cat.cs
  src/Nest/ElasticClient.Cat.cs
  src/Nest/Requests.Cat.cs
  src/Nest/_Generated/ApiUrlsLookup.generated.cs
  tests/Tests/Cat/CatDataFrameAnalytics/CatDataFrameAnalyticsApiTests.cs
  tests/Tests/Cat/CatDataFrameAnalytics/CatDataFrameAnalyticsUrlTests.cs
Labels: backport 7.x, backport master, v7.7.0

#4591 Add nori_number token filter in analysis-nori and discard_punctuation to filter
  src/Nest/Analysis/Analyzers/NoriAnalyzer.cs
  src/Nest/Analysis/Tokenizers/NoriTokenizer.cs
  tests/Tests/Analysis/Tokenizers/TokenizerTests.cs
Labels: backport 7.x, backport master, v7.7.0

#4594 Implement Top Metrics aggregation
  src/Nest/Aggregations/AggregateDictionary.cs
  src/Nest/Aggregations/AggregateFormatter.cs
  src/Nest/Aggregations/AggregationContainer.cs
  src/Nest/Aggregations/Metric/TopMetrics/TopMetricsAggregate.cs
  src/Nest/Aggregations/Metric/TopMetrics/TopMetricsAggregation.cs
  src/Nest/Aggregations/Metric/TopMetrics/TopMetricsValue.cs
  src/Nest/Aggregations/Visitor/AggregationVisitor.cs
  tests/Tests/Aggregations/Metric/TopMetrics/TopMetricsAggregationUsageTests.cs
Labels: backport 7.x, backport master, v7.7.0

#4597 Add empty_value parameter to CSV processor
  src/Nest/Ingest/Processors/CsvProcessor.cs
  tests/Tests/Ingest/ProcessorAssertions.cs
Labels: backport 7.x, backport master, v7.7.0

#4598 Allow forcemerge in the hot phase for ILM policies
  src/Nest/XPack/Ilm/Actions/ForceMergeAction.cs
Labels: backport 7.x, backport master, v7.7.0

#4574 implement IPercentageScoreHeuristic on PercentageScoreHeuristic
  src/Nest/Aggregations/Bucket/SignificantTerms/Heuristics/PercentageScoreHeuristic.cs
  tests/Tests.Reproduce/GitHubIssue4573.cs
Labels: Bug, backport 7.7, backport master, v7.7.0

#4596 Add max_children to Nested Sort
  docs/search/request/sort-usage.asciidoc
  src/Nest/Search/Search/Sort/NestedSort.cs
  tests/Tests/Search/Request/SortUsageTests.cs
Labels: Feature, backport 7.7, backport 7.x, v6.8.6, v7.7.0

#4600 Change SumOfDocumentFrequencies and SumOfTotalTermFrequencies to long
  src/Nest/Document/Single/TermVectors/FieldStatistics.cs
Labels: Breaking, Bug, backport 7.7, backport 7.x, v7.7.0

#4602 Regnerate from new specifications
  src/ApiGenerator/RestSpecification/Core/cluster.delete_component_template.json
  src/ApiGenerator/RestSpecification/Core/cluster.get_component_template.json
  src/ApiGenerator/RestSpecification/Core/cluster.put_component_template.json
  src/ApiGenerator/RestSpecification/Core/nodes.reload_secure_settings.json
  src/ApiGenerator/RestSpecification/Core/root.html
  src/ApiGenerator/RestSpecification/XPack/root.html
  src/ApiGenerator/Views/LowLevel/Client/Implementation/ElasticLowLevelClient.Namespace.cshtml
  src/Elasticsearch.Net/ElasticLowLevelClient.AsyncSearch.cs
  src/Elasticsearch.Net/ElasticLowLevelClient.Autoscaling.cs
  src/Elasticsearch.Net/ElasticLowLevelClient.Cat.cs
  src/Elasticsearch.Net/ElasticLowLevelClient.Cluster.cs
  src/Elasticsearch.Net/ElasticLowLevelClient.CrossClusterReplication.cs
  src/Elasticsearch.Net/ElasticLowLevelClient.Enrich.cs
  src/Elasticsearch.Net/ElasticLowLevelClient.Eql.cs
  src/Elasticsearch.Net/ElasticLowLevelClient.Graph.cs
  src/Elasticsearch.Net/ElasticLowLevelClient.IndexLifecycleManagement.cs
  src/Elasticsearch.Net/ElasticLowLevelClient.Indices.cs
  src/Elasticsearch.Net/ElasticLowLevelClient.Ingest.cs
  src/Elasticsearch.Net/ElasticLowLevelClient.License.cs
  src/Elasticsearch.Net/ElasticLowLevelClient.MachineLearning.cs
  src/Elasticsearch.Net/ElasticLowLevelClient.Migration.cs
  src/Elasticsearch.Net/ElasticLowLevelClient.Nodes.Patch.cs
  src/Elasticsearch.Net/ElasticLowLevelClient.Nodes.cs
  src/Elasticsearch.Net/ElasticLowLevelClient.Rollup.cs
  src/Elasticsearch.Net/ElasticLowLevelClient.Security.cs
  src/Elasticsearch.Net/ElasticLowLevelClient.Snapshot.cs
  src/Elasticsearch.Net/ElasticLowLevelClient.SnapshotLifecycleManagement.cs
  src/Elasticsearch.Net/ElasticLowLevelClient.Sql.cs
  src/Elasticsearch.Net/ElasticLowLevelClient.Tasks.cs
  src/Elasticsearch.Net/ElasticLowLevelClient.Transform.cs
  src/Elasticsearch.Net/ElasticLowLevelClient.Watcher.cs
  src/Elasticsearch.Net/ElasticLowLevelClient.XPack.cs
Labels: backport 7.x, v7.7.0

#4593 Implement ConstantKeyword property
  src/Nest/Mapping/DynamicTemplate/SingleMapping.cs
  src/Nest/Mapping/Types/FieldType.cs
  src/Nest/Mapping/Types/Properties.cs
  src/Nest/Mapping/Types/PropertyFormatter.cs
  src/Nest/Mapping/Types/Specialized/ConstantKeyword/ConstantKeywordAttribute.cs
  src/Nest/Mapping/Types/Specialized/ConstantKeyword/ConstantKeywordProperty.cs
  src/Nest/Mapping/Visitor/IMappingVisitor.cs
  src/Nest/Mapping/Visitor/IPropertyVisitor.cs
  src/Nest/Mapping/Visitor/MappingWalker.cs
  src/Nest/Mapping/Visitor/NoopPropertyVisitor.cs
  tests/Tests.Core/ManagedElasticsearch/NodeSeeders/DefaultSeeder.cs
  tests/Tests.Domain/Project.cs
  tests/Tests/Indices/MappingManagement/GetMapping/GetMappingApiTest.cs
  tests/Tests/Indices/MappingManagement/PutMapping/PutMappingApiTest.cs
  tests/Tests/Mapping/Types/Specialized/ConstantKeyword/ConstantKeywordAttributeTests.cs
  tests/Tests/Mapping/Types/Specialized/ConstantKeyword/ConstantKeywordPropertyTests.cs
Labels: Feature, backport 7.7, backport 7.x, v7.7.0

#4599 Implement hidden indices and aliases
  src/Nest/IndexModules/IndexSettings/Settings/FixedIndexSettings.cs
  src/Nest/IndexModules/IndexSettings/Settings/IndexSettings.cs
  src/Nest/IndexModules/IndexSettings/Settings/IndexSettingsFormatter.cs
  src/Nest/Indices/AliasManagement/Alias.cs
  src/Nest/Indices/AliasManagement/Alias/Actions/AliasAdd.cs
  src/Nest/Indices/AliasManagement/Alias/Actions/AliasAddOperation.cs
  tests/Tests/Indices/IndexManagement/CreateIndex/CreateIndexApiTests.cs
Labels: Feature, backport 7.7, backport 7.x, v7.7.0

#4601 Integration tests and docs for circle and multipoint geoshape queries
  docs/query-dsl/geo/geo-shape/geo-shape-query-usage.asciidoc
  docs/query-dsl/specialized/shape/shape-query-usage.asciidoc
  tests/Tests/QueryDsl/Geo/GeoShape/GeoShapeQueryUsageTests.cs
  tests/Tests/QueryDsl/Specialized/Shape/ShapeQueryUsageTests.cs
Labels: Feature, backport 7.7, backport 7.x, v7.7.0

#4592 Implement Boxplot aggregation
  docs/aggregations.asciidoc
  docs/aggregations/metric/boxplot/boxplot-aggregation-usage.asciidoc
  src/Nest/Aggregations/AggregateDictionary.cs
  src/Nest/Aggregations/AggregateFormatter.cs
  src/Nest/Aggregations/AggregationContainer.cs
  src/Nest/Aggregations/Metric/Boxplot/BoxplotAggregate.cs
  src/Nest/Aggregations/Metric/Boxplot/BoxplotAggregation.cs
  src/Nest/Aggregations/Visitor/AggregationVisitor.cs
  src/Nest/Aggregations/Visitor/AggregationWalker.cs
  tests/Tests/Aggregations/AggregationUsageTestBase.cs
  tests/Tests/Aggregations/Metric/Boxplot/BoxplotAggregationUsageTests.cs
Labels: Feature, backport 7.7, backport 7.x, v7.7.0

#4632 Fixes integration tests for the discard_punctuation nori tokeniser feature
  src/Nest/Analysis/Tokenizers/NoriTokenizer.cs
  tests/Tests/Analysis/Tokenizers/TokenizerTests.cs
Labels: backport 7.x, backport master

#4579 Use `params` modifier for methods in RequestDescriptorBase
  src/ApiGenerator/Domain/Specification/QueryParameters.cs
  src/ApiGenerator/Views/HighLevel/Descriptors/RequestDescriptorBase.cshtml
  src/Nest/Descriptors.cs
Labels: Feature, backport 7.7, backport 7.x, v7.7.0

#4640 Clean spec folder before downloading a fresh copy
  src/ApiGenerator/RestSpecDownloader.cs
Labels: Infra, backport 7.7, backport 7.x

#4641 run documentation target on master branch
  docs/aggregations/bucket/parent/parent-aggregation-usage.asciidoc
  docs/aggregations/writing-aggregations.asciidoc
  docs/client-concepts/connection-pooling/building-blocks/connection-pooling.asciidoc
  docs/client-concepts/connection-pooling/exceptions/unexpected-exceptions.asciidoc
  docs/client-concepts/connection-pooling/exceptions/unrecoverable-exceptions.asciidoc
  docs/client-concepts/connection-pooling/max-retries/respects-max-retry.asciidoc
  docs/client-concepts/connection-pooling/pinging/first-usage.asciidoc
  docs/client-concepts/connection-pooling/request-overrides/disable-sniff-ping-per-request.asciidoc
  docs/client-concepts/connection-pooling/round-robin/skip-dead-nodes.asciidoc
  docs/client-concepts/connection-pooling/sniffing/on-connection-failure.asciidoc
  docs/client-concepts/connection-pooling/sniffing/on-startup.asciidoc
  docs/client-concepts/connection-pooling/sniffing/role-detection.asciidoc
  docs/client-concepts/high-level/analysis/writing-analyzers.asciidoc
  docs/client-concepts/high-level/getting-started.asciidoc
  docs/client-concepts/high-level/indexing/indexing-documents.asciidoc
  docs/client-concepts/high-level/indexing/ingest-nodes.asciidoc
  docs/client-concepts/high-level/indexing/pipelines.asciidoc
  docs/client-concepts/high-level/inference/field-inference.asciidoc
  docs/client-concepts/high-level/inference/index-name-inference.asciidoc
  docs/client-concepts/high-level/inference/indices-paths.asciidoc
  docs/client-concepts/high-level/mapping/auto-map.asciidoc
  docs/client-concepts/high-level/mapping/fluent-mapping.asciidoc
  docs/client-concepts/high-level/mapping/ignoring-properties.asciidoc
  docs/client-concepts/high-level/mapping/multi-fields.asciidoc
  docs/client-concepts/high-level/mapping/parent-child-relationships.asciidoc
  docs/client-concepts/high-level/mapping/visitor-pattern-mapping.asciidoc
  docs/client-concepts/low-level/getting-started.asciidoc
  docs/client-concepts/troubleshooting/diagnostic-source.asciidoc
  docs/client-concepts/troubleshooting/logging-with-on-request-completed.asciidoc
  docs/query-dsl.asciidoc
  docs/query-dsl/bool-dsl/bool-dsl.asciidoc
  docs/search/returned-fields.asciidoc
  docs/search/writing-queries.asciidoc
Labels: Docs

#4639 Attempting to apply a license file to a snapshot build results in an invalid license file response.
  tests/Tests.Core/ManagedElasticsearch/Clusters/XPackCluster.cs
Labels: backport 7.7, backport 7.x

#4647 Update low level client on `master`
  src/ApiGenerator/Configuration/CodeConfiguration.cs
  src/ApiGenerator/RestSpecification/Core/bulk.json
  src/ApiGenerator/RestSpecification/Core/create.json
  src/ApiGenerator/RestSpecification/Core/index.json
  src/ApiGenerator/RestSpecification/Core/indices.create.json
  src/ApiGenerator/RestSpecification/Core/indices.exists_index_template.json
  src/ApiGenerator/RestSpecification/Core/indices.flush_synced.json
  src/ApiGenerator/RestSpecification/Core/indices.rollover.json
  src/ApiGenerator/RestSpecification/Core/indices.stats.json
  src/ApiGenerator/RestSpecification/Core/nodes.hot_threads.json
  src/ApiGenerator/RestSpecification/Core/nodes.reload_secure_settings.json
  src/ApiGenerator/RestSpecification/Core/nodes.stats.json
  src/ApiGenerator/RestSpecification/Core/root.html
  src/ApiGenerator/RestSpecification/Core/scripts_painless_context.json
  src/ApiGenerator/RestSpecification/Core/update.json
  src/ApiGenerator/RestSpecification/XPack/MachineLearning/xpack.ml.get_calendars.patch.json
  src/ApiGenerator/RestSpecification/XPack/data_frame.delete_data_frame_transform.json
  src/ApiGenerator/RestSpecification/XPack/data_frame.get_data_frame_transform.json
  src/ApiGenerator/RestSpecification/XPack/data_frame.get_data_frame_transform_stats.json
  src/ApiGenerator/RestSpecification/XPack/data_frame.preview_data_frame_transform.json
  src/ApiGenerator/RestSpecification/XPack/data_frame.put_data_frame_transform.json
  src/ApiGenerator/RestSpecification/XPack/data_frame.start_data_frame_transform.json
  src/ApiGenerator/RestSpecification/XPack/data_frame.stop_data_frame_transform.json
  src/ApiGenerator/RestSpecification/XPack/data_frame.update_data_frame_transform.json
  src/ApiGenerator/RestSpecification/XPack/ml.estimate_memory_usage.json
  src/ApiGenerator/RestSpecification/XPack/root.html
  src/ApiGenerator/RestSpecification/XPack/searchable_snapshots.clear_cache.json
  src/ApiGenerator/RestSpecification/XPack/searchable_snapshots.mount.json
  src/ApiGenerator/RestSpecification/XPack/searchable_snapshots.repository_stats.json
  src/ApiGenerator/RestSpecification/XPack/searchable_snapshots.stats.json
  src/ApiGenerator/RestSpecification/XPack/transform.cat_transform.json
  src/Elasticsearch.Net/Api/RequestParameters/RequestParameters.Indices.cs
  src/Elasticsearch.Net/Api/RequestParameters/RequestParameters.MachineLearning.cs
  src/Elasticsearch.Net/Api/RequestParameters/RequestParameters.NoNamespace.cs
  src/Elasticsearch.Net/Api/RequestParameters/RequestParameters.Nodes.cs
  src/Elasticsearch.Net/Api/RequestParameters/RequestParameters.SearchableSnapshots.cs
  src/Elasticsearch.Net/Api/RequestParameters/RequestParameters.Transform.cs
  src/Elasticsearch.Net/ElasticLowLevelClient.DataFrame.cs
  src/Elasticsearch.Net/ElasticLowLevelClient.Indices.cs
  src/Elasticsearch.Net/ElasticLowLevelClient.MachineLearning.cs
  src/Elasticsearch.Net/ElasticLowLevelClient.NoNamespace.cs
  src/Elasticsearch.Net/ElasticLowLevelClient.Nodes.cs
  src/Elasticsearch.Net/ElasticLowLevelClient.SearchableSnapshots.cs
  src/Elasticsearch.Net/ElasticLowLevelClient.Transform.cs
  src/Elasticsearch.Net/IElasticLowLevelClient.Generated.cs
  src/Nest/Descriptors.Indices.cs
  src/Nest/ElasticClient.Indices.cs
  src/Nest/Indices/StatusManagement/SyncedFlush/SyncedFlushRequest.cs
  src/Nest/Indices/StatusManagement/SyncedFlush/SyncedFlushResponse.cs
  src/Nest/Requests.Indices.cs
  tests/Tests/Indices/StatusManagement/SyncedFlush/SyncedFlushUrlTests.cs
  tests/Tests/Indices/StatusManagement/SyncedFlush/SyncedFushApiTests.cs
Labels: Sync Upstream

#4649 PrimitiveObjectFormatter eagerly reads integer where double could be preferred.
  src/Elasticsearch.Net/Utf8Json/Formatters/PrimitiveObjectFormatter.cs
  tests/Tests.YamlRunner/Commands.fs
Labels: Bug, Infra, Self Reviewed, backport 7.7, backport 7.x

#4653 update documentation for 7.7
  docs/aggregations/bucket/parent/parent-aggregation-usage.asciidoc
  docs/aggregations/writing-aggregations.asciidoc
  docs/client-concepts/connection-pooling/building-blocks/connection-pooling.asciidoc
  docs/client-concepts/connection-pooling/exceptions/unexpected-exceptions.asciidoc
  docs/client-concepts/connection-pooling/exceptions/unrecoverable-exceptions.asciidoc
  docs/client-concepts/connection-pooling/max-retries/respects-max-retry.asciidoc
  docs/client-concepts/connection-pooling/pinging/first-usage.asciidoc
  docs/client-concepts/connection-pooling/request-overrides/disable-sniff-ping-per-request.asciidoc
  docs/client-concepts/connection-pooling/round-robin/skip-dead-nodes.asciidoc
  docs/client-concepts/connection-pooling/sniffing/on-connection-failure.asciidoc
  docs/client-concepts/connection-pooling/sniffing/on-startup.asciidoc
  docs/client-concepts/connection-pooling/sniffing/role-detection.asciidoc
  docs/client-concepts/high-level/analysis/writing-analyzers.asciidoc
  docs/client-concepts/high-level/getting-started.asciidoc
  docs/client-concepts/high-level/indexing/indexing-documents.asciidoc
  docs/client-concepts/high-level/indexing/ingest-nodes.asciidoc
  docs/client-concepts/high-level/indexing/pipelines.asciidoc
  docs/client-concepts/high-level/inference/field-inference.asciidoc
  docs/client-concepts/high-level/inference/index-name-inference.asciidoc
  docs/client-concepts/high-level/inference/indices-paths.asciidoc
  docs/client-concepts/high-level/mapping/auto-map.asciidoc
  docs/client-concepts/high-level/mapping/fluent-mapping.asciidoc
  docs/client-concepts/high-level/mapping/ignoring-properties.asciidoc
  docs/client-concepts/high-level/mapping/multi-fields.asciidoc
  docs/client-concepts/high-level/mapping/parent-child-relationships.asciidoc
  docs/client-concepts/high-level/mapping/visitor-pattern-mapping.asciidoc
  docs/client-concepts/low-level/getting-started.asciidoc
  docs/client-concepts/troubleshooting/diagnostic-source.asciidoc
  docs/client-concepts/troubleshooting/logging-with-on-request-completed.asciidoc
  docs/query-dsl.asciidoc
  docs/query-dsl/bool-dsl/bool-dsl.asciidoc
  docs/search/returned-fields.asciidoc
  docs/search/writing-queries.asciidoc
Labels: Docs, Self Reviewed, v7.7.0

#4655 Fix bug in IsLong implementation
  src/Elasticsearch.Net/Extensions/ArraySegmentBytesExtensions.cs
  src/Elasticsearch.Net/Utf8Json/Formatters/PrimitiveObjectFormatter.cs
  tests/Tests/CodeStandards/Serialization/PrimitiveObjectFormatterTests.cs
Labels: Bug, backport 7.7, backport 7.x, v7.7.0

#4657 Add RequestParams overload without optional content type
  src/Elasticsearch.Net/ElasticLowLevelClient.cs
  src/Elasticsearch.Net/NamespacedClientProxy.cs
Labels: backport 7.7

#4656 Don't sanitize the keys for Filters aggregation named buckets
  src/Nest/Aggregations/Bucket/Filters/FiltersAggregate.cs
  tests/Tests.Reproduce/GithubIssue4582.cs
Labels: Bug, backport 6.x, backport 7.7, backport 7.x, v7.7.0

#4663 Fix check for agressive connectionlimit
  src/Elasticsearch.Net/Configuration/ConnectionConfiguration.cs
Labels: Bug, backport 6.x, backport 7.7, backport 7.x, v7.7.0

#4666 Mute CsvProcessor tests
  tests/Tests/Ingest/ProcessorAssertions.cs
  tests/Tests/Ingest/PutPipeline/PutPipelineApiTests.cs
Labels: backport 7.7, backport 7.x, v7.7.0

#4665 Make assertions on job created in test
  tests/Tests/XPack/MachineLearning/GetJobStats/GetJobStatsApiTests.cs
  tests/Tests/XPack/MachineLearning/MachineLearningCluster.cs
Labels: Flakey test, backport 7.7, backport 7.x, v7.7.0

#4669 [Backport 6x] Fix check for agressive connectionlimit
  src/Elasticsearch.Net/Configuration/ConnectionConfiguration.cs
Labels: Bug, v6.8.6

#4675 Fix F# project warnings
  build/scripts/Building.fs
  build/scripts/Targets.fs
  build/scripts/Tooling.fs
  build/scripts/Versioning.fs
  build/scripts/XmlDocPatcher.fs
  build/scripts/scripts.fsproj
  tests/Tests.YamlRunner/AsyncExtensions.fs
  tests/Tests.YamlRunner/DoMapper.fs
  tests/Tests.YamlRunner/Models.fs
  tests/Tests.YamlRunner/OperationExecutor.fs
  tests/Tests.YamlRunner/Program.fs
  tests/Tests.YamlRunner/Stashes.fs
  tests/Tests.YamlRunner/TestsDownloader.fs
  tests/Tests.YamlRunner/TestsExporter.fs
  tests/Tests.YamlRunner/TestsLocator.fs
  tests/Tests.YamlRunner/TestsRunner.fs
Labels: Infra, Self Reviewed, backport 7.x

#4673 Allow HttpClient instances to be refreshed periodically
  src/Elasticsearch.Net/Configuration/ConnectionConfiguration.cs
  src/Elasticsearch.Net/Configuration/IConnectionConfigurationValues.cs
  src/Elasticsearch.Net/Connection/HandlerTracking/ActiveHandlerTrackingEntry.cs
  src/Elasticsearch.Net/Connection/HandlerTracking/ExpiredHandlerTrackingEntry.cs
  src/Elasticsearch.Net/Connection/HandlerTracking/LifetimeTrackingHttpMessageHandler.cs
  src/Elasticsearch.Net/Connection/HandlerTracking/RequestDataHttpClientFactory.cs
  src/Elasticsearch.Net/Connection/HandlerTracking/ValueStopWatch.cs
  src/Elasticsearch.Net/Connection/HttpConnection.cs
  src/Elasticsearch.Net/Connection/HttpWebRequestConnection.cs
  src/Elasticsearch.Net/Transport/Pipeline/RequestData.cs
  tests/Tests.Configuration/tests.default.yaml
  tests/Tests.ScratchPad/Program.cs
  tests/Tests/ClientConcepts/Connection/HttpConnectionTests.cs
  tests/Tests/Framework/EndpointTests/ApiIntegrationTestBase.cs
  tests/Tests/Search/Search/InvalidSearchApiTests.cs
Labels: Feature, backport 6.x, backport 7.x, v6.8.7, v7.8.0

#4685 Feature/master/yaml completeness
  tests/Tests.YamlRunner/Models.fs
  tests/Tests.YamlRunner/OperationExecutor.fs
  tests/Tests.YamlRunner/Program.fs
  tests/Tests.YamlRunner/SkipList.fs
  tests/Tests.YamlRunner/TestSuiteBootstrap.fs
  tests/Tests.YamlRunner/TestsDownloader.fs
  tests/Tests.YamlRunner/TestsLocator.fs
  tests/Tests.YamlRunner/TestsReader.fs
Labels: Infra, Self Reviewed, backport 7.x, v7.8.0, v8.0.0-alpha1

#4678 [Backport 6.x] Reimplement #4673 manually
  dotnet-tools.json
  src/Elasticsearch.Net/Configuration/ConnectionConfiguration.cs
  src/Elasticsearch.Net/Configuration/IConnectionConfigurationValues.cs
  src/Elasticsearch.Net/Connection/HandlerTracking/ActiveHandlerTrackingEntry.cs
  src/Elasticsearch.Net/Connection/HandlerTracking/ExpiredHandlerTrackingEntry.cs
  src/Elasticsearch.Net/Connection/HandlerTracking/LifetimeTrackingHttpMessageHandler.cs
  src/Elasticsearch.Net/Connection/HandlerTracking/RequestDataHttpClientFactory.cs
  src/Elasticsearch.Net/Connection/HandlerTracking/ValueStopWatch.cs
  src/Elasticsearch.Net/Connection/HttpConnection-CoreFx.cs
  src/Elasticsearch.Net/Transport/Pipeline/RequestData.cs
Labels: Feature, v6.8.7
