Repository elastic/elasticsearch-net, pull requests merged in 2020-09, with the labels that each got.

#4993 Add tests to ensure we can deal with trailing $ in encoded cloud ids.
  tests/Tests/ClientConcepts/ConnectionPooling/BuildingBlocks/ConnectionPooling.doc.cs
Labels: backport 7.9, backport 7.x

#4999 Fix formatting conventions.
  .editorconfig
Labels: backport 6.x, backport 7.9, backport 7.x, backport master

#4996 Serialize Epoch milliseconds as a string
  src/Nest/CommonAbstractions/SerializationBehavior/JsonFormatters/DateTimeOffsetEpochMillisecondsFormatter.cs
  tests/Tests/XPack/MachineLearning/GetAnomalyRecords/GetAnomalyRecordsApiTests.cs
  tests/Tests/XPack/MachineLearning/GetInfluencers/GetInfluencersApiTests.cs
  tests/Tests/XPack/MachineLearning/GetModelSnapshots/GetModelSnapshotsApiTests.cs
  tests/Tests/XPack/MachineLearning/StartDatafeed/StartDatafeedApiTests.cs
Labels: Bug, backport 7.9, backport 7.x, v7.9.1

#5002 Short circuit in ToUrl to remove allocations when possible.
  src/Nest/CommonAbstractions/Request/UrlLookup.cs
Labels: Performance, backport 7.9, backport 7.x, v7.9.1

#5003 Enable TCP states and ThreadPool stats
  docs/client-concepts/connection/configuration-options.asciidoc
  docs/client-concepts/troubleshooting/debug-information.asciidoc
  docs/client-concepts/troubleshooting/debug-mode.asciidoc
  docs/troubleshooting.asciidoc
  src/Elasticsearch.Net/Configuration/ConnectionConfiguration.cs
  src/Elasticsearch.Net/Configuration/IConnectionConfigurationValues.cs
  src/Elasticsearch.Net/Configuration/RequestConfiguration.cs
  src/Elasticsearch.Net/Connection/HttpConnection.cs
  src/Elasticsearch.Net/Connection/HttpWebRequestConnection.cs
  src/Elasticsearch.Net/Diagnostics/TcpStats.cs
  src/Elasticsearch.Net/Diagnostics/ThreadpoolStats.cs
  src/Elasticsearch.Net/Responses/ElasticsearchResponse.cs
  src/Elasticsearch.Net/Responses/HttpDetails/ApiCallDetails.cs
  src/Elasticsearch.Net/Responses/HttpDetails/IApiCallDetails.cs
  src/Elasticsearch.Net/Responses/ResponseStatics.cs
  src/Elasticsearch.Net/Transport/Pipeline/RequestData.cs
  tests/Tests/ClientConcepts/Troubleshooting/DebugInformation.doc.cs
  tests/Tests/ClientConcepts/Troubleshooting/DebugMode.doc.cs
  tests/Tests/Framework/DocumentationTests/IntegrationDocumentationTestBase.cs
  tests/Tests/troubleshooting.asciidoc
Labels: Feature, backport 7.9, backport 7.x, v7.9.1

#5010 Add Visit methods for derived IProperty types
  src/Nest/Mapping/Visitor/IPropertyVisitor.cs
  src/Nest/Mapping/Visitor/NoopPropertyVisitor.cs
  tests/Tests/CodeStandards/Parity/ParityTests.cs
Labels: Bug, backport 7.9, backport 7.x, v7.9.1

#4735 Add Point property for mapping point datatype
  src/Nest.JsonNetSerializer/Converters/HandleNestTypesOnSourceJsonConverter.cs
  src/Nest/Mapping/DynamicTemplate/SingleMapping.cs
  src/Nest/Mapping/Types/FieldType.cs
  src/Nest/Mapping/Types/Properties.cs
  src/Nest/Mapping/Types/PropertyFormatter.cs
  src/Nest/Mapping/Types/Specialized/Point/PointAttribute.cs
  src/Nest/Mapping/Types/Specialized/Point/PointProperty.cs
  src/Nest/Mapping/Visitor/IMappingVisitor.cs
  src/Nest/Mapping/Visitor/IPropertyVisitor.cs
  src/Nest/Mapping/Visitor/MappingWalker.cs
  src/Nest/Mapping/Visitor/NoopPropertyVisitor.cs
  src/Nest/QueryDsl/Geo/Shape/GeoShapeBase.cs
  src/Nest/QueryDsl/Geo/WKT/GeoWKTException.cs
  src/Nest/QueryDsl/Geo/WKT/GeoWKTReader.cs
  src/Nest/QueryDsl/Specialized/Shape/CartesianPoint.cs
  tests/Tests/Indices/MappingManagement/GetMapping/GetMappingApiTest.cs
  tests/Tests/Mapping/Types/Specialized/Point/CartesianPointSerializationTests.cs
  tests/Tests/Mapping/Types/Specialized/Point/PointAttributeTests.cs
  tests/Tests/Mapping/Types/Specialized/Point/PointPropertyTests.cs
Labels: Feature, backport 7.x, v7.10.0

#5017 Mark all Visit methods virtual on NoopPropertyVisitor
  src/Nest/Mapping/Visitor/NoopPropertyVisitor.cs
  tests/Tests/CodeStandards/Parity/ParityTests.cs
Labels: Bug

#5020 Remove ILRepack
  build/scripts/Building.fs
  build/scripts/Tooling.fs
  build/scripts/scripts.fsproj
  dotnet-tools.json
Labels: backport 7.9, backport 7.x

#5024 Fail the yaml runner if no folders are found
  tests/Tests.YamlRunner/Commands.fs
  tests/Tests.YamlRunner/SkipList.fs
  tests/Tests.YamlRunner/TestsLocator.fs
  tests/Tests.YamlRunner/TestsReader.fs
Labels: backport 7.9, backport 7.x
