Repository elastic/elasticsearch-net, pull requests merged in 2020-05, with the labels that each got.

#4690 Add script to add file license headers
  build/add-headers.sh
  build/file-header.txt
Labels: Infra, backport 7.x

#4711 regenerate low level client from latest master specification
  src/ApiGenerator/RestSpecification/Core/bulk.json
  src/ApiGenerator/RestSpecification/Core/cat.thread_pool.json
  src/ApiGenerator/RestSpecification/Core/cluster.delete_component_template.json
  src/ApiGenerator/RestSpecification/Core/cluster.delete_voting_config_exclusions.json
  src/ApiGenerator/RestSpecification/Core/cluster.exists_component_template.json
  src/ApiGenerator/RestSpecification/Core/cluster.get_component_template.json
  src/ApiGenerator/RestSpecification/Core/cluster.post_voting_config_exclusions.json
  src/ApiGenerator/RestSpecification/Core/cluster.put_component_template.json
  src/ApiGenerator/RestSpecification/Core/create.json
  src/ApiGenerator/RestSpecification/Core/index.json
  src/ApiGenerator/RestSpecification/Core/indices.create.json
  src/ApiGenerator/RestSpecification/Core/indices.get_data_stream.json
  src/ApiGenerator/RestSpecification/Core/indices.put_index_template.json
  src/ApiGenerator/RestSpecification/Core/indices.rollover.json
  src/ApiGenerator/RestSpecification/Core/indices.simulate_index_template.json
  src/ApiGenerator/RestSpecification/Core/indices.simulate_template.json
  src/ApiGenerator/RestSpecification/Core/root.html
  src/ApiGenerator/RestSpecification/Core/snapshot.cleanup_repository.json
  src/ApiGenerator/RestSpecification/Core/snapshot.delete_repository.json
  src/ApiGenerator/RestSpecification/Core/update.json
  src/ApiGenerator/RestSpecification/XPack/autoscaling.delete_autoscaling_policy.json
  src/ApiGenerator/RestSpecification/XPack/autoscaling.get_autoscaling_policy.json
  src/ApiGenerator/RestSpecification/XPack/autoscaling.put_autoscaling_policy.json
  src/ApiGenerator/RestSpecification/XPack/eql.search.json
  src/ApiGenerator/RestSpecification/XPack/ml.delete_expired_data.json
  src/ApiGenerator/RestSpecification/XPack/ml.validate.json
  src/ApiGenerator/RestSpecification/XPack/ml.validate_detector.json
  src/ApiGenerator/RestSpecification/XPack/root.html
  src/ApiGenerator/RestSpecification/XPack/searchable_snapshots.clear_cache.json
  src/ApiGenerator/RestSpecification/XPack/searchable_snapshots.mount.json
  src/ApiGenerator/RestSpecification/XPack/searchable_snapshots.repository_stats.json
  src/ApiGenerator/RestSpecification/XPack/searchable_snapshots.stats.json
  src/Elasticsearch.Net/Api/Enums.Generated.cs
  src/Elasticsearch.Net/Api/RequestParameters/RequestParameters.Cat.cs
  src/Elasticsearch.Net/Api/RequestParameters/RequestParameters.Cluster.cs
  src/Elasticsearch.Net/Api/RequestParameters/RequestParameters.Eql.cs
  src/Elasticsearch.Net/Api/RequestParameters/RequestParameters.Indices.cs
  src/Elasticsearch.Net/Api/RequestParameters/RequestParameters.MachineLearning.cs
  src/Elasticsearch.Net/Api/RequestParameters/RequestParameters.NoNamespace.cs
  src/Elasticsearch.Net/Api/RequestParameters/RequestParameters.Snapshot.cs
  src/Elasticsearch.Net/ElasticLowLevelClient.Cluster.cs
  src/Elasticsearch.Net/ElasticLowLevelClient.Eql.cs
  src/Elasticsearch.Net/ElasticLowLevelClient.Indices.cs
  src/Elasticsearch.Net/ElasticLowLevelClient.MachineLearning.cs
  src/Elasticsearch.Net/ElasticLowLevelClient.Snapshot.cs
  src/Nest/Descriptors.Cat.cs
  src/Nest/Requests.Cat.cs
  tests/Tests.YamlRunner/TestSuiteBootstrap.fs
Labels: Sync Upstream

#4683 Add support for Transforms APIs
  src/ApiGenerator/Configuration/CodeConfiguration.cs
  src/Nest/CommonAbstractions/Infer/Indices/IndicesFormatter.cs
  src/Nest/CommonOptions/DateMath/DateMathTime.cs
  src/Nest/Descriptors.Transform.cs
  src/Nest/ElasticClient.NoNamespace.cs
  src/Nest/ElasticClient.Transform.cs
  src/Nest/IElasticClient.Generated.cs
  src/Nest/Requests.Transform.cs
  src/Nest/XPack/Transform/DeleteTransform/DeleteTransformRequest.cs
  src/Nest/XPack/Transform/DeleteTransform/DeleteTransformResponse.cs
  src/Nest/XPack/Transform/GetTransform/GetTransformRequest.cs
  src/Nest/XPack/Transform/GetTransform/GetTransformResponse.cs
  src/Nest/XPack/Transform/GetTransformStats/GetTransformStatsRequest.cs
  src/Nest/XPack/Transform/GetTransformStats/GetTransformStatsResponse.cs
  src/Nest/XPack/Transform/Pivot/DateHistogramGroupSource.cs
  src/Nest/XPack/Transform/Pivot/HistogramGroupSource.cs
  src/Nest/XPack/Transform/Pivot/SingleGroupSource.cs
  src/Nest/XPack/Transform/Pivot/TermsGroupSource.cs
  src/Nest/XPack/Transform/Pivot/TransformPivot.cs
  src/Nest/XPack/Transform/PreviewTransform/PreviewTransformRequest.cs
  src/Nest/XPack/Transform/PreviewTransform/PreviewTransformResponse.cs
  src/Nest/XPack/Transform/PutTransform/PutTransformRequest.cs
  src/Nest/XPack/Transform/PutTransform/PutTransformResponse.cs
  src/Nest/XPack/Transform/StartTransform/StartTransformRequest.cs
  src/Nest/XPack/Transform/StartTransform/StartTransformResponse.cs
  src/Nest/XPack/Transform/StopTransform/StopTransformRequest.cs
  src/Nest/XPack/Transform/StopTransform/StopTransformResponse.cs
  src/Nest/XPack/Transform/Transform.cs
  src/Nest/XPack/Transform/TransformDestination.cs
  src/Nest/XPack/Transform/TransformSource.cs
  src/Nest/XPack/Transform/TransformSync.cs
  src/Nest/XPack/Transform/UpdateTransform/UpdateTransformRequest.cs
  src/Nest/XPack/Transform/UpdateTransform/UpdateTransformResponse.cs
  tests/Tests.Domain/Project.cs
  tests/Tests/XPack/AsyncSearch/AsyncSearchTests.cs
  tests/Tests/XPack/AsyncSearch/Delete/AsyncSearchDeleteTests.cs
  tests/Tests/XPack/AsyncSearch/Get/AsyncSearchGetTests.cs
  tests/Tests/XPack/AsyncSearch/Submit/AsyncSearchSubmitTests.cs
  tests/Tests/XPack/Transform/TransformApiTests.cs
Labels: Feature

#4714 Fix api url lookups
  src/ApiGenerator/Domain/Code/CsharpNames.cs
  src/ApiGenerator/Views/HighLevel/Requests/ApiUrlsLookup.cshtml
  src/Elasticsearch.Net/Api/RequestParameters/RequestParameters.Indices.cs
  src/Elasticsearch.Net/ElasticLowLevelClient.Indices.cs
  src/Nest/Descriptors.cs
  src/Nest/_Generated/ApiUrlsLookup.generated.cs
Labels: Bug, backport 7.7, backport master, v7.7.1

#4705 update CatAllocationRecord
  src/Nest/Cat/CatAllocation/CatAllocationRecord.cs
  tests/Tests/Cat/CatAllocation/CatAllocationApiTests.cs
Labels: Bug

#4713 Add special serialization handling for nullable ValueTuples
  src/Elasticsearch.Net/Utf8Json/Resolvers/DynamicGenericResolver.cs
  tests/Tests.Reproduce/GithubIssue4703.cs
Labels: Bug, backport 7.7, backport 7.x, v7.7.1
