Repository elastic/elasticsearch-net, pull requests merged in 2020-07, with the labels that each got.

#4835 Add ScrollAllObservable docs
  docs/client-concepts/high-level/indexing/indexing-documents.asciidoc
  docs/high-level.asciidoc
  docs/search/scrolling-documents.asciidoc
  tests/Tests/ClientConcepts/HighLevel/Indexing/IndexingDocuments.doc.cs
  tests/Tests/Search/ScrollingDocuments.doc.cs
  tests/Tests/high-level.asciidoc
Labels: Docs, backport 7.8, backport 7.x, v7.8.2

#4834 Check _cleanupTimer is not null when disposing
  src/Elasticsearch.Net/Connection/HandlerTracking/RequestDataHttpClientFactory.cs
  tests/Tests.Reproduce/GitHubIssue4818.cs
Labels: Bug, backport 7.8, backport 7.x, v7.8.2

#4833 Deserialize enums in fallback Enum.Parse as case insensitive
  src/Elasticsearch.Net/Utf8Json/Formatters/EnumFormatter.cs
  tests/Tests.Reproduce/GitHubIssue4817.cs
Labels: Bug, backport 7.8, backport 7.x, v7.8.2

#4846 client.Timeout was not being set after refactoring introduced in #4673
  src/Elasticsearch.Net/Connection/HandlerTracking/RequestDataHttpClientFactory.cs
  src/Elasticsearch.Net/Connection/HttpConnection.cs
Labels: Bug, Self Reviewed, backport 7.8, backport 7.x

#4853 Fix script compilation settings
  tests/Tests.Core/ManagedElasticsearch/Clusters/ClientTestClusterBase.cs
Labels: Infra, backport 7.x

#4856 Fix DateHistogram aggregation intervals
  docs/aggregations/bucket/date-histogram/date-histogram-aggregation-usage.asciidoc
  src/Nest/Aggregations/Bucket/DateHistogram/DateHistogramAggregation.cs
  tests/Tests/Aggregations/Bucket/DateHistogram/DateHistogramAggregationUsageTests.cs
Labels: Bug, backport 7.8, backport 7.x, v7.8.2

#4854 Fix ScriptCacheStats
  src/Nest/Cluster/NodesStats/NodeStats.cs
  tests/Tests/Cluster/NodesStats/NodesStatsApiTests.cs
Labels: Breaking, Bug, backport 7.8, backport 7.x, v7.8.2

#4864 Fix integration tests
  tests/Tests/Cluster/NodesStats/NodesStatsApiTests.cs
  tests/Tests/Document/Multiple/DeleteByQuery/DeleteByQueryApiTests.cs
  tests/Tests/Document/Multiple/UpdateByQuery/UpdateByQueryApiTests.cs
  tests/Tests/Mapping/Types/Core/Binary/BinaryPropertyTests.cs
  tests/Tests/Mapping/Types/Core/Boolean/BooleanPropertyTests.cs
  tests/Tests/XPack/MachineLearning/DeleteForecast/DeleteForecastApiTests.cs
  tests/Tests/XPack/MachineLearning/GetJobs/GetJobsApiTests.cs
  tests/Tests/XPack/Security/User/InvalidateUserAccessToken/InvalidateUserAccessTokenApiTests.cs
  tests/Tests/XPack/Transform/TransformApiTests.cs
Labels: Flakey test, backport 7.9, backport 7.x

#4863 Add global highlight_query
  docs/search/request/highlighting-usage.asciidoc
  src/Nest/Search/Search/Highlighting/Highlight.cs
  tests/Tests/Search/Request/HighlightingUsageTests.cs
Labels: Feature, backport 7.9, backport 7.x, v7.9.0

#4877 Remove similarity from Date property integration tests
  tests/Tests/Mapping/Types/Core/Date/DateAttributeTests.cs
  tests/Tests/Mapping/Types/Core/Date/DatePropertyTests.cs
  tests/Tests/Mapping/Types/Core/DateNanos/DateNanosAttributeTests.cs
  tests/Tests/Mapping/Types/Core/DateNanos/DateNanosPropertyTests.cs
Labels: Flakey test, backport 7.9, backport 7.x

#4870 Implement dangling indices APIs
  src/ApiGenerator/Configuration/CodeConfiguration.cs
  src/ApiGenerator/Domain/Specification/UrlPart.cs
  src/Nest/CommonAbstractions/Infer/IndexUuid/IndexUuid.cs
  src/Nest/CommonAbstractions/Request/RouteValues.cs
  src/Nest/DanglingIndices/Delete/DeleteDanglingIndexRequest.cs
  src/Nest/DanglingIndices/Delete/DeleteDanglingIndexResponse.cs
  src/Nest/DanglingIndices/Import/ImportDanglingIndexRequest.cs
  src/Nest/DanglingIndices/Import/ImportDanglingIndexResponse.cs
  src/Nest/DanglingIndices/List/ListDanglingIndicesRequest.cs
  src/Nest/DanglingIndices/List/ListDanglingIndicesResponse.cs
  src/Nest/Descriptors.DanglingIndices.cs
  src/Nest/ElasticClient.DanglingIndices.cs
  src/Nest/ElasticClient.NoNamespace.cs
  src/Nest/IElasticClient.Generated.cs
  src/Nest/Requests.DanglingIndices.cs
  src/Nest/_Generated/ApiUrlsLookup.generated.cs
  tests/Tests/DanglingIndices/Delete/DeleteDanglingIndexApiTests.cs
  tests/Tests/DanglingIndices/Delete/DeleteDanglingIndexUrlTests.cs
  tests/Tests/DanglingIndices/Import/ImportDanglingIndexApiTests.cs
  tests/Tests/DanglingIndices/Import/ImportDanglingIndexUrlTests.cs
  tests/Tests/DanglingIndices/List/ListDanglingIndicesApiTests.cs
  tests/Tests/DanglingIndices/List/ListDanglingIndicesUrlTests.cs
Labels: Feature, backport 7.9, backport 7.x, v7.9.0

#4871 Add description to ingest processors
  src/Nest/Ingest/Processor.cs
  tests/Tests/Ingest/ProcessorAssertions.cs
Labels: Feature, backport 7.9, backport 7.x, v7.9.0

#4873 Add index block API
  src/ApiGenerator/Configuration/CodeConfiguration.cs
  src/ApiGenerator/Domain/Specification/UrlPart.cs
  src/Elasticsearch.Net/Api/RequestParameters/RequestParameters.Indices.cs
  src/Elasticsearch.Net/ElasticLowLevelClient.Indices.cs
  src/Nest/Descriptors.Indices.cs
  src/Nest/ElasticClient.Indices.cs
  src/Nest/Indices/IndexManagement/AddBlock/AddIndexBlockRequest.cs
  src/Nest/Indices/IndexManagement/AddBlock/AddIndexBlockResponse.cs
  src/Nest/Indices/IndexManagement/AddBlock/IndexBlock.cs
  src/Nest/Requests.Indices.cs
  src/Nest/_Generated/ApiUrlsLookup.generated.cs
  tests/Tests/Indices/IndexManagement/AddBlock/AddIndexBlockApiTests.cs
  tests/Tests/Indices/IndexManagement/AddBlock/AddIndexBlockUrlTests.cs
Labels: Feature, backport 7.9, backport 7.x, v7.9.0

#4838 Introduce .ci/make.sh
  .ci/DockerFile
  .ci/Jenkins.csproj
  .ci/make.sh
  .dockerignore
  .gitignore
  build/scripts/Commandline.fs
  build/scripts/ReposTooling.fs
  build/scripts/Targets.fs
  build/scripts/Versioning.fs
  build/scripts/scripts.fsproj
  dotnet-tools.json
Labels: Infra, backport 7.x

#4674 Fix #4298 be less strict about `Operations` on `IBulkRequest`
  src/Nest/Document/Multiple/Bulk/BulkOperation/BulkOperationsCollection.cs
  src/Nest/Document/Multiple/Bulk/BulkRequest.cs
  tests/Tests.Benchmarking/BulkCreationBenchmarkTests.cs
Labels: Feature, v8.0.0-alpha1

#4886 Add normalize aggregation
  docs/aggregations.asciidoc
  docs/aggregations/pipeline/normalize/normalize-aggregation-usage.asciidoc
  docs/code-standards/descriptors.asciidoc
  src/Nest/Aggregations/AggregateDictionary.cs
  src/Nest/Aggregations/AggregationContainer.cs
  src/Nest/Aggregations/Pipeline/Normalize/NormalizeAggregation.cs
  src/Nest/Aggregations/Visitor/AggregationVisitor.cs
  src/Nest/Aggregations/Visitor/AggregationWalker.cs
  tests/Tests/Aggregations/Pipeline/Normalize/NormalizeAggregationUsageTests.cs
  tests/Tests/CodeStandards/Descriptors.doc.cs
Labels: Feature, backport 7.9, backport 7.x, v7.9.0

#4888 Add index filter to field_caps API
  src/Nest/Search/FieldCapabilities/FieldCapabilitiesRequest.cs
  tests/Tests/Search/FieldCapabilities/FieldCapabilitiesApiTests.cs
Labels: Feature, backport 7.9, backport 7.x, v7.9.0

#4890 Add support for wildcard property
  src/Nest/Mapping/DynamicTemplate/SingleMapping.cs
  src/Nest/Mapping/Types/FieldType.cs
  src/Nest/Mapping/Types/Properties.cs
  src/Nest/Mapping/Types/PropertyFormatter.cs
  src/Nest/Mapping/Types/Specialized/Wildcard/WildcardAttribute.cs
  src/Nest/Mapping/Types/Specialized/Wildcard/WildcardProperty.cs
  tests/Tests/Mapping/Types/Specialized/Wildcard/WildcardAttributeTests.cs
  tests/Tests/Mapping/Types/Specialized/Wildcard/WildcardPropertyTests.cs
Labels: Feature, backport 7.9, backport 7.x, v7.9.0

#4891 Add standard deviation / variance sampling to extended stats
  src/Nest/Aggregations/AggregateFormatter.cs
  src/Nest/Aggregations/Metric/ExtendedStats/ExtendedStatsAggregate.cs
  tests/Tests/Aggregations/Metric/ExtendedStats/ExtendedStatsAggregationUsageTests.cs
Labels: Feature, backport 7.9, backport 7.x, v7.9.0

#4894 [Docs] order `anchor-list` output explicitly.
  docs/aggregations.asciidoc
  docs/query-dsl.asciidoc
  src/DocGenerator/AsciiDoc/RawAsciidocVisitor.cs
Labels: Docs, backport 6.x, backport 7.9, backport 7.x

#4874 Add indices resolve index API
  src/ApiGenerator/Configuration/CodeConfiguration.cs
  src/Nest/Descriptors.Indices.cs
  src/Nest/ElasticClient.Indices.cs
  src/Nest/Indices/IndexManagement/ResolveIndex/ResolveIndexRequest.cs
  src/Nest/Indices/IndexManagement/ResolveIndex/ResolveIndexResponse.cs
  src/Nest/Requests.Indices.cs
  src/Nest/_Generated/ApiUrlsLookup.generated.cs
  tests/Tests/Indices/IndexManagement/ResolveIndex/ResolveIndexApiTests.cs
  tests/Tests/Indices/IndexManagement/ResolveIndex/ResolveIndexUrlTests.cs
Labels: Feature, backport 7.9, backport 7.x, v7.9.0

#4887 Add moving_percentiles aggregation
  docs/aggregations.asciidoc
  docs/aggregations/pipeline/moving-percentiles/moving-percentiles-aggregation-usage.asciidoc
  src/Nest/Aggregations/AggregateDictionary.cs
  src/Nest/Aggregations/AggregationContainer.cs
  src/Nest/Aggregations/Pipeline/MovingPercentiles/MovingPercentilesAggregation.cs
  src/Nest/Aggregations/Visitor/AggregationVisitor.cs
  src/Nest/Aggregations/Visitor/AggregationWalker.cs
  tests/Tests/Aggregations/Pipeline/MovingPercentiles/MovingPercentilesAggregationUsageTests.cs
Labels: Feature, backport 7.9, backport 7.x, v7.9.0
