Repository elastic/elasticsearch-net, pull requests merged in 2020-02, with the labels that each got.

#4329 Pass base64 encoded API key on Connectionsettings
  src/Elasticsearch.Net/Configuration/ConnectionConfiguration.cs
Labels: Port to master, v7.6.0

#4343 Fix typo in code that cause the docs stale check to trigger
  Directory.Build.props
  Directory.Build.targets
  build/scripts/ReposTooling.fs
  docs/client-concepts/connection/configuration-options.asciidoc
  src/DocGenerator/AsciiDoc/GeneratedAsciidocVisitor.cs
  src/Elasticsearch.Net.VirtualizedCluster/Elasticsearch.Net.VirtualizedCluster.csproj
  src/Elasticsearch.Net/Elasticsearch.Net.csproj
  src/Nest.JsonNetSerializer/Nest.JsonNetSerializer.csproj
  src/Nest/Nest.csproj
  tests/Tests/ClientConcepts/HighLevel/GettingStarted.doc.cs
Labels: Infra, Port to 7.x, Self Reviewed

#4344 Fix typo in code that cause the docs stale check to trigger (#4343)
  Directory.Build.props
  Directory.Build.targets
  build/scripts/ReposTooling.fs
  docs/client-concepts/connection/configuration-options.asciidoc
  src/DocGenerator/AsciiDoc/GeneratedAsciidocVisitor.cs
  src/Elasticsearch.Net.VirtualizedCluster/Elasticsearch.Net.VirtualizedCluster.csproj
  src/Elasticsearch.Net/Elasticsearch.Net.csproj
  src/Nest.JsonNetSerializer/Nest.JsonNetSerializer.csproj
  src/Nest/Nest.csproj
  tests/Tests/ClientConcepts/HighLevel/GettingStarted.doc.cs
Labels: Infra, Self Reviewed

#4345 Shared CI 1.0.1
  .ci/jobs/elastic+elasticsearch-net+pull-request.yml
  .ci/run-elasticsearch.sh
Labels: Infra, Self Reviewed

#4350 Change IEnumerable on DynamicDictionary to enumerate over key value pairs
  src/Elasticsearch.Net/Responses/Dynamic/DynamicDictionary.cs
Labels: Breaking

#4349 Low level client should sent null for dictionary values.
  src/Elasticsearch.Net/Utf8Json/Formatters/DictionaryFormatter.cs
  tests/Tests.Core/Serialization/RoundtripperDsl.cs
  tests/Tests/Framework/SerializationTests/DictionarySerializationTests.cs
Labels: Breaking, v8.0.0

#4348 Allow headers to be specified on a per request basis
  src/Elasticsearch.Net/Configuration/RequestConfiguration.cs
  src/Elasticsearch.Net/Connection/HttpConnection.cs
  src/Elasticsearch.Net/Transport/Pipeline/RequestData.cs
Labels: Feature, Port to 7.x

#4351 DynamicValue can now dispatch into arrays
  docs/client-concepts/low-level/low-level-response-types.asciidoc
  src/Elasticsearch.Net/Responses/Dynamic/DynamicValue.cs
  tests/Tests/ClientConcepts/LowLevel/LowLevelResponseTypes.doc.cs
Labels: Feature, Port to 7.x

#4361 Give AzureDevops its own .runsettings so that it picks up the tests a…
  Elasticsearch.sln
  azure-pipelines.yml
  build/scripts/Commandline.fs
  build/scripts/Testing.fs
  tests/.ci.runsettings
Labels: Infra, Port to 7.x

#4352 Update rest-spec runner to completion
  .ci/jobs/elastic+elasticsearch-net+pull-request.yml
  .ci/run-repository.sh
  .ci/test-matrix.yml
  src/Elasticsearch.Net/Responses/ServerException/Error.cs
  tests/Tests.YamlRunner/Commands.fs
  tests/Tests.YamlRunner/DoMapper.fs
  tests/Tests.YamlRunner/Models.fs
  tests/Tests.YamlRunner/OperationExecutor.fs
  tests/Tests.YamlRunner/Program.fs
  tests/Tests.YamlRunner/SkipList.fs
  tests/Tests.YamlRunner/Tests.YamlRunner.fsproj
  tests/Tests.YamlRunner/TestsDownloader.fs
  tests/Tests.YamlRunner/TestsExporter.fs
  tests/Tests.YamlRunner/TestsLocator.fs
  tests/Tests.YamlRunner/TestsReader.fs
  tests/Tests.YamlRunner/TestsRunner.fs
Labels: Feature, Port to 7.x

#4360 [7.x] Allow the code generator to generate only the low level client
  src/ApiGenerator/Configuration/CodeConfiguration.cs
  src/ApiGenerator/Configuration/GeneratorLocations.cs
  src/ApiGenerator/Domain/RestApiSpec.cs
  src/ApiGenerator/Domain/Specification/ApiEndpoint.cs
  src/ApiGenerator/Generator/ApiGenerator.cs
  src/ApiGenerator/Generator/Razor/DescriptorsGenerator.cs
  src/ApiGenerator/Generator/Razor/HighLevelClientImplementationGenerator.cs
  src/ApiGenerator/Generator/Razor/LowLevelClientImplementationGenerator.cs
  src/ApiGenerator/Generator/Razor/RequestParametersGenerator.cs
  src/ApiGenerator/Generator/Razor/RequestsGenerator.cs
  src/ApiGenerator/Program.cs
  src/ApiGenerator/Views/HighLevel/Client/Implementation/ElasticClient.cshtml
  src/ApiGenerator/Views/HighLevel/Client/Interface/IElasticClient.cshtml
  src/ApiGenerator/Views/HighLevel/Client/Usings.cshtml
  src/ApiGenerator/Views/HighLevel/Requests/ApiUrlsLookup.cshtml
Labels: Feature, v7.6.0

#4359 [7.x] Allow headers to be specified on a per request basis (#4348)
  src/Elasticsearch.Net/Configuration/RequestConfiguration.cs
  src/Elasticsearch.Net/Connection/HttpConnection.cs
  src/Elasticsearch.Net/Transport/Pipeline/RequestData.cs
Labels: Feature, v7.6.0

#4363 Add support for multiple versions in restspec runner
  src/Elasticsearch.Net/Serialization/Formatters/DynamicDictionaryFormatter.cs
  tests/Tests.YamlRunner/Models.fs
  tests/Tests.YamlRunner/OperationExecutor.fs
  tests/Tests.YamlRunner/SkipList.fs
  tests/Tests.YamlRunner/TestsReader.fs
Labels: Infra

#4365 Integration tests: wait for green at startup
  tests/Tests.Core/ManagedElasticsearch/Clusters/ClientTestClusterBase.cs
  tests/Tests.Core/ManagedElasticsearch/Clusters/CrossCluster.cs
  tests/Tests.Core/ManagedElasticsearch/Clusters/ReadOnlyCluster.cs
  tests/Tests.Core/ManagedElasticsearch/Clusters/TimeSeriesCluster.cs
  tests/Tests.Core/ManagedElasticsearch/Clusters/UnbalancedCluster.cs
  tests/Tests.Core/ManagedElasticsearch/Clusters/WritableCluster.cs
  tests/Tests.Core/ManagedElasticsearch/Clusters/XPackCluster.cs
  tests/Tests/ClientConcepts/Certificates/SslAndKpiXPackCluster.cs
  tests/Tests/Document/Multiple/Reindex/ReindexApiTests.cs
  tests/Tests/QueryDsl/BoolDsl/BoolApiTests.cs
  tests/Tests/XPack/MachineLearning/MachineLearningCluster.cs
Labels: Infra

#4364 [test] Unknown query now returns a different error
  tests/Tests/Search/SearchTemplate/SearchTemplateApiTests.cs
Labels: Infra, Port to 7.x

#4368 Fix integration tests in 7.x
  tests/Tests/Search/SearchTemplate/SearchTemplateApiTests.cs
  tests/Tests/XPack/Slm/SlmApiTests.cs
Labels: Flakey test, Infra

#4328 Serialize custom ITokenFilter and ICharFilter implementations
  src/Nest/Analysis/CharFilters/CharFilterFormatter.cs
  src/Nest/Analysis/TokenFilters/TokenFilterFormatter.cs
  tests/Tests/Analysis/CharFilters/CharFilterTests.cs
  tests/Tests/Analysis/TokenFilters/TokenFilterTests.cs
Labels: Feature, v7.6.0

#4331 Add format to metric aggregations that support it
  src/Nest/Aggregations/Aggregation.cs
  src/Nest/Aggregations/Metric/Average/AverageAggregation.cs
  src/Nest/Aggregations/Metric/ExtendedStats/ExtendedStatsAggregation.cs
  src/Nest/Aggregations/Metric/Max/MaxAggregation.cs
  src/Nest/Aggregations/Metric/MedianAbsoluteDeviation/MedianAbsoluteDeviationAggregation.cs
  src/Nest/Aggregations/Metric/MetricAggregation.cs
  src/Nest/Aggregations/Metric/Min/MinAggregation.cs
  src/Nest/Aggregations/Metric/PercentileRanks/PercentileRanksAggregation.cs
  src/Nest/Aggregations/Metric/PercentileRanks/PercentileRanksAggregationFormatter.cs
  src/Nest/Aggregations/Metric/Percentiles/PercentilesAggregation.cs
  src/Nest/Aggregations/Metric/Percentiles/PercentilesAggregationFormatter.cs
  src/Nest/Aggregations/Metric/Stats/StatsAggregation.cs
  src/Nest/Aggregations/Metric/Sum/SumAggregation.cs
  src/Nest/Aggregations/Metric/ValueCount/ValueCountAggregation.cs
  tests/Tests/Aggregations/Metric/Min/MinAggregationUsageTests.cs
Labels: Feature, v7.6.0

#4357 Deprecate sort on ReindexOnServer
  src/Nest/Document/Multiple/ReindexOnServer/ReindexSource.cs
  tests/Tests/Document/Multiple/ReindexOnServer/ReindexOnServerApiTests.cs
  tests/Tests/Document/Multiple/ReindexOnServer/ReindexOnServerSliceApiTests.cs
Labels: Deprecation, Port to master, v7.6.0

#4366 Add missing datatype members to IPropertiesDescriptor
  src/Nest/Mapping/DynamicTemplate/SingleMapping.cs
  src/Nest/Mapping/Types/Complex/Nested/NestedProperty.cs
  src/Nest/Mapping/Types/Complex/Object/ObjectProperty.cs
  src/Nest/Mapping/Types/Core/Binary/BinaryProperty.cs
  src/Nest/Mapping/Types/Core/Boolean/BooleanProperty.cs
  src/Nest/Mapping/Types/Core/Date/DateProperty.cs
  src/Nest/Mapping/Types/Core/DateNanos/DateNanosProperty.cs
  src/Nest/Mapping/Types/Core/Join/JoinProperty.cs
  src/Nest/Mapping/Types/Core/Keyword/KeywordProperty.cs
  src/Nest/Mapping/Types/Core/Number/NumberProperty.cs
  src/Nest/Mapping/Types/Core/Percolator/PercolatorProperty.cs
  src/Nest/Mapping/Types/Core/Range/DateRange/DateRangeProperty.cs
  src/Nest/Mapping/Types/Core/Range/DoubleRange/DoubleRangeProperty.cs
  src/Nest/Mapping/Types/Core/Range/FloatRange/FloatRangeProperty.cs
  src/Nest/Mapping/Types/Core/Range/IntegerRange/IntegerRangeProperty.cs
  src/Nest/Mapping/Types/Core/Range/IpRange/IpRangeAttribute.cs
  src/Nest/Mapping/Types/Core/Range/IpRange/IpRangeProperty.cs
  src/Nest/Mapping/Types/Core/Range/LongRange/LongRangeProperty.cs
  src/Nest/Mapping/Types/Core/Text/TextProperty.cs
  src/Nest/Mapping/Types/Geo/GeoPoint/GeoPointProperty.cs
  src/Nest/Mapping/Types/Properties.cs
  src/Nest/Mapping/Types/Specialized/FieldAlias/FieldAliasProperty.cs
  src/Nest/Mapping/Types/Specialized/Generic/GenericProperty.cs
  src/Nest/Mapping/Types/Specialized/Ip/IpProperty.cs
  src/Nest/Mapping/Types/Specialized/TokenCount/TokenCountProperty.cs
  tests/Tests/Mapping/PropertyDescriptorTests.cs
Labels: Bug, v7.6.0

#4370 Add StringStats aggregation
  src/Nest/Aggregations/AggregateDictionary.cs
  src/Nest/Aggregations/AggregateFormatter.cs
  src/Nest/Aggregations/AggregationContainer.cs
  src/Nest/Aggregations/Metric/StringStats/StringStatsAggregate.cs
  src/Nest/Aggregations/Metric/StringStats/StringStatsAggregation.cs
  src/Nest/Aggregations/Visitor/AggregationVisitor.cs
  tests/Tests/Aggregations/Metric/StringStats/StringStatsAggregationUsageTests.cs
Labels: Feature, v7.6.0

#4371 Add Estonian language analyzer
  src/Nest/Analysis/Languages/Language.cs
Labels: Feature, v7.6.0

#4373 Remove edgengram tokenizer spelling
  src/Nest/Analysis/Tokenizers/TokenizerFormatter.cs
Labels: v8.0.0

#4375 Add WaitForSnapshot ILM lifecycle action
  src/Nest/XPack/Ilm/Actions/WaitForSnapshotLifecycleAction.cs
  src/Nest/XPack/Ilm/LifecycleActions.cs
Labels: Feature, v7.6.0

#4374 Add Csv processor
  src/Nest/Ingest/ProcessorFormatter.cs
  src/Nest/Ingest/Processors/CsvProcessor.cs
  src/Nest/Ingest/ProcessorsDescriptor.cs
  tests/Tests/Ingest/ProcessorAssertions.cs
Labels: Feature, v7.6.0

#4372 Add missing visit methods to aggregation visitor
  src/Nest/Aggregations/Visitor/AggregationVisitor.cs
  tests/Tests/Aggregations/AggregationVisitorTests.cs
Labels: Bug, v7.6.0, v8.0.0

#4376 Add per-field metadata
  src/Nest/Mapping/AttributeBased/ElasticsearchPropertyAttributeBase.cs
  src/Nest/Mapping/Types/PropertyBase.cs
  src/Nest/Mapping/Types/PropertyDescriptorBase.cs
  src/Nest/Mapping/Types/PropertyFormatter.cs
  src/Nest/Search/FieldCapabilities/FieldCapabilitiesResponse.cs
  tests/Tests/ClientConcepts/HighLevel/Serialization/ExtendingNestTypes.doc.cs
  tests/Tests/Mapping/LocalMetadata/LocalMetadataVisitorTests.cs
  tests/Tests/Mapping/Meta/MetaMappingApiTests.cs
  tests/Tests/Mapping/Metafields/MetafieldsMappingApiTestsBase.cs
Labels: Feature, v7.6.0

#4367 Add histogram datatype
  src/Nest/Mapping/DynamicTemplate/SingleMapping.cs
  src/Nest/Mapping/Types/FieldType.cs
  src/Nest/Mapping/Types/Properties.cs
  src/Nest/Mapping/Types/PropertyFormatter.cs
  src/Nest/Mapping/Types/Specialized/Histogram/HistogramAttribute.cs
  src/Nest/Mapping/Types/Specialized/Histogram/HistogramProperty.cs
  src/Nest/Mapping/Visitor/IMappingVisitor.cs
  src/Nest/Mapping/Visitor/IPropertyVisitor.cs
  src/Nest/Mapping/Visitor/MappingWalker.cs
  src/Nest/Mapping/Visitor/NoopPropertyVisitor.cs
  tests/Tests/Indices/MappingManagement/GetMapping/GetMappingApiTest.cs
  tests/Tests/Mapping/Types/Specialized/Histogram/HistogramAttributeTests.cs
  tests/Tests/Mapping/Types/Specialized/Histogram/HistogramPropertyTests.cs
Labels: Feature, v7.6.0

#4384 Support custom token chars in (edge)ngram tokenizer
  src/Nest/Analysis/Tokenizers/NGram/EdgeNGramTokenizer.cs
  src/Nest/Analysis/Tokenizers/NGram/NGramTokenizer.cs
  src/Nest/Analysis/Tokenizers/NGram/TokenChar.cs
  tests/Tests/Analysis/Tokenizers/TokenizerTests.cs
Labels: Feature, v7.6.0

#4383 Use correct IJsonFormatter<T> in attributes
  src/Nest/Ingest/Processors/ScriptProcessor.cs
  src/Nest/Modules/SnapshotAndRestore/Repositories/VerifyRepository/VerifyRepositoryResponse.cs
  src/Nest/XPack/MachineLearning/UpdateJob/UpdateJobRequest.cs
  src/Nest/XPack/Watcher/Action/ActionBase.cs
  src/Nest/XPack/Watcher/Action/Actions.cs
  src/Nest/XPack/Watcher/Transform/ScriptTransformBase.cs
  tests/Tests.Reproduce/GitHubIssue4382.cs
  tests/Tests/CodeStandards/Serialization/Formatters.doc.cs
Labels: Bug, v7.6.0

#4379 Add support for fuzzy intervals in interval query
  src/Nest/QueryDsl/FullText/Intervals/IntervalsFuzzy.cs
  src/Nest/QueryDsl/FullText/Intervals/IntervalsQuery.cs
  tests/Tests/QueryDsl/FullText/Intervals/IntervalsUsageTests.cs
Labels: Feature, v7.6.0

#4378 Create exception formatters for different exceptions
  src/Elasticsearch.Net/Serialization/Formatters/ExceptionFormatter.cs
  tests/Tests.Reproduce/GitHubIssue4294.cs
Labels: Bug, Port to master, v7.6.0

#4393 Function is optional for rank_feature query
  src/Nest/QueryDsl/Specialized/RankFeature/RankFeatureQuery.cs
  tests/Tests/QueryDsl/Specialized/RankFeature/RankFeatureQueryUsageTests.cs
Labels: Bug, Port to 7.x, v7.6.0

#4391 Add retry count and is retryable to ILM explain
  src/Nest/XPack/Ilm/ExplainLifecycle/ExplainLifecycleResponse.cs
Labels: Feature, v7.6.0

#4353 Return distinct items from GetMany and SourceMany
  src/Nest/Document/Multiple/MultiGet/Request/MultiGetRequestFormatter.cs
  src/Nest/Document/Multiple/MultiGet/Response/MultiGetHitJsonConverter.cs
  src/Nest/Document/Multiple/MultiGet/Response/MultiGetResponse.cs
  tests/Tests/Document/Multiple/MultiGet/GetManyApiTests.cs
Labels: Bug, v7.6.0

#4400 Return distinct items from GetMany and SourceMany (#4353)
  docs/aggregations/bucket/terms/terms-aggregation-usage.asciidoc
  docs/search/request/suggest-usage.asciidoc
  docs/search/writing-queries.asciidoc
  src/Nest/Document/Multiple/MultiGet/ElasticClient-GetMany.cs
  src/Nest/Document/Multiple/MultiGet/ElasticClient-SourceMany.cs
  src/Nest/Document/Multiple/MultiGet/Request/MultiGetRequestJsonConverter.cs
  src/Nest/Document/Multiple/MultiGet/Response/MultiGetResponse.cs
  src/Tests/Tests/Document/Multiple/MultiGet/GetManyApiTests.cs
Labels: Bug, v6.8.4

#4405 Add Github Actions automations
  .github/auto-label.json
  .github/workflows/auto-label.yml
  .github/workflows/backport.yml
  .github/workflows/yaml-runner.yml
  build/scripts/Versioning.fs
  build/scripts/scripts.fsproj
  global.json
Labels: backport 6.x, backport 7.6, backport 7.x

#4409 Add flattened usage field count
  src/Nest/XPack/Info/XPackUsage/XPackUsageResponse.cs
  tests/Tests/XPack/Info/XPackInfoApiTests.cs
Labels: Feature, backport 7.6, v7.6.0

#4408 Add categorization analyzer to defaults on ml info response
  src/Nest/XPack/MachineLearning/MachineLearningInfo/MachineLearningInfoResponse.cs
  tests/Tests/XPack/MachineLearning/MachineLearningInfo/MachineLearningInfoApiTests.cs
Labels: Feature, backport 7.6, v7.6.0

#4407 Add ingest info to Cluster Stats response
  src/Nest/Cluster/ClusterStats/ClusterNodesStats.cs
  tests/Tests/Cluster/ClusterStats/ClusterStatsApiTests.cs
Labels: Feature, backport 7.6, v7.6.0

#4406 Support Enterprise license type
  src/Nest/XPack/License/GetLicense/GetLicenseResponse.cs
  src/Nest/XPack/License/GetLicense/LicenseType.cs
Labels: Feature, backport 7.6, v7.6.0

#4401 Add index.final_pipeline index setting
  src/Nest/IndexModules/IndexSettings/Settings/DynamicIndexSettings.cs
  src/Nest/IndexModules/IndexSettings/Settings/IndexSettingsFormatter.cs
  src/Nest/IndexModules/IndexSettings/Settings/UpdatableIndexSettings.cs
  tests/Tests/IndexModules/IndexSettings/Settings/TypedIndexSettings.cs
Labels: Deprecation, backport 7.6, v7.6.0

#4411 Deprecate index soft delete enabled setting
  src/Nest/IndexModules/IndexSettings/Settings/IndexSettingsFormatter.cs
  src/Nest/IndexModules/IndexSettings/SoftDeletes/ISoftDeleteSettings.cs
  tests/Tests/XPack/CrossClusterReplication/CrossClusterReplicationFollowTests.cs
Labels: Deprecation, backport 7.6, v7.6.0

#4410 Add first_only to geoip processor
  src/Nest/Ingest/Processors/Plugins/GeoIpProcessor.cs
Labels: Feature, backport 7.6, v7.6.0

#4395 Update low level client on 7.x
  src/ApiGenerator/Domain/Specification/Documentation.cs
  src/ApiGenerator/RestSpecification/Core/root.html
  src/ApiGenerator/RestSpecification/XPack/cat.ml_data_frame_analytics.json
  src/ApiGenerator/RestSpecification/XPack/eql.search.json
  src/ApiGenerator/RestSpecification/XPack/root.html
  src/ApiGenerator/RestSpecification/XPack/slm.execute_lifecycle.json
  src/ApiGenerator/RestSpecification/XPack/slm.get_status.json
  src/ApiGenerator/RestSpecification/XPack/slm.start.json
  src/ApiGenerator/RestSpecification/XPack/slm.stop.json
  src/Elasticsearch.Net/Api/RequestParameters/RequestParameters.Cat.cs
  src/Elasticsearch.Net/Api/RequestParameters/RequestParameters.MachineLearning.cs
  src/Elasticsearch.Net/Api/RequestParameters/RequestParameters.SnapshotLifecycleManagement.cs
  src/Elasticsearch.Net/ElasticLowLevelClient.Cat.cs
  src/Elasticsearch.Net/ElasticLowLevelClient.MachineLearning.cs
  src/Elasticsearch.Net/ElasticLowLevelClient.SnapshotLifecycleManagement.cs
Labels: Infra, Sync Upstream

#4399 Update documentation on 7.6
  docs/aggregations.asciidoc
  docs/aggregations/metric/min/min-aggregation-usage.asciidoc
  docs/aggregations/metric/string-stats/string-stats-aggregation-usage.asciidoc
  docs/client-concepts/high-level/serialization/extending-nest-types.asciidoc
  docs/code-standards/serialization/formatters.asciidoc
  docs/query-dsl/full-text/intervals/intervals-usage.asciidoc
  src/DocGenerator/StringExtensions.cs
Labels: Docs

#4398 Update documentation on 7.x
  docs/aggregations.asciidoc
  docs/aggregations/metric/min/min-aggregation-usage.asciidoc
  docs/aggregations/metric/string-stats/string-stats-aggregation-usage.asciidoc
  docs/client-concepts/high-level/serialization/extending-nest-types.asciidoc
  docs/code-standards/serialization/formatters.asciidoc
  docs/query-dsl/full-text/intervals/intervals-usage.asciidoc
  src/DocGenerator/StringExtensions.cs
Labels: Docs

#4397 Update documentation on master
  docs/code-standards/serialization/formatters.asciidoc
  docs/query-dsl.asciidoc
  docs/query-dsl/full-text/intervals/intervals-usage.asciidoc
  src/DocGenerator/StringExtensions.cs
Labels: Docs

#4396 Update low level client on master
  src/ApiGenerator/Domain/Specification/Documentation.cs
  src/ApiGenerator/RestSpecification/Core/root.html
  src/ApiGenerator/RestSpecification/XPack/cat.ml_data_frame_analytics.json
  src/ApiGenerator/RestSpecification/XPack/root.html
  src/Elasticsearch.Net/Api/RequestParameters/RequestParameters.Cat.cs
  src/Elasticsearch.Net/Api/RequestParameters/RequestParameters.MachineLearning.cs
  src/Elasticsearch.Net/ElasticLowLevelClient.Cat.cs
  src/Elasticsearch.Net/ElasticLowLevelClient.MachineLearning.cs
Labels: Sync Upstream

#4404 Ability to only run one test section in file in yaml test runner
  build/scripts/Commandline.fs
  tests/Tests.YamlRunner/Commands.fs
  tests/Tests.YamlRunner/Program.fs
  tests/Tests.YamlRunner/TestsRunner.fs
Labels: Infra, backport 7.6, backport master

#4403 Add support for bounds in geohash_grid aggregation
  src/Nest/Aggregations/Bucket/GeoHashGrid/GeoHashGridAggregation.cs
  tests/Tests/Aggregations/Bucket/GeoHashGrid/GeoHashGridAggregationUsageTests.cs
Labels: Feature, backport 7.6, v7.6.0

#4402 Add preserve_trailing to Split processor
  src/Nest/Ingest/Processors/SplitProcessor.cs
Labels: Feature, backport 7.6, v7.6.0

#4427 Update version for SearchTemplate error message
  tests/Tests/Search/SearchTemplate/SearchTemplateApiTests.cs
Labels: backport 7.6, v7.6.0

#4428 Avoid multiple enumeration of IEnumerable PostData
  src/Elasticsearch.Net/Transport/PostData.cs
Labels: Performance, backport 7.6, backport 7.x, v7.6.0

#4429 Use XPackCluster for PutPipeline API tests
  tests/Tests.Core/ManagedElasticsearch/Clusters/XPackCluster.cs
  tests/Tests/Ingest/PutPipeline/PutPipelineApiTests.cs
Labels: Flakey test, backport 7.6, backport 7.x, v7.6.0

#4426 Implement _source parameter on action and doc lines (#4339)
  src/Nest/Aggregations/AggregateJsonConverter.cs
  src/Nest/Aggregations/Metric/TopHits/TopHitsAggregate.cs
  src/Nest/CommonAbstractions/Fields/FieldValuesJsonConverter.cs
  src/Nest/CommonAbstractions/LazyDocument/LazyDocument.cs
  src/Nest/CommonAbstractions/LazyDocument/LazyDocumentJsonConverter.cs
  src/Nest/Document/Multiple/Bulk/BulkOperation/BulkUpdate.cs
  src/Nest/Document/Multiple/Bulk/BulkOperation/BulkUpdateBody.cs
  src/Nest/Document/Multiple/Bulk/BulkResponseItem/BulkResponseItemBase.cs
  src/Nest/Document/Multiple/MultiGet/Response/MultiGetHitJsonConverter.cs
  src/Nest/XPack/Sql/QuerySql/SqlValue.cs
  src/Tests/Tests/Document/Multiple/Bulk/BulkSourceDeserialize.cs
Labels: Feature, v6.8.4

#4436 Wait for .security index to be green
  build/scripts/Testing.fs
  tests/Tests.Core/ManagedElasticsearch/Clusters/XPackCluster.cs
Labels: backport 7.6, backport master

#4435 Use MachineLearningDateTimeFormatter
  src/Nest/CommonAbstractions/SerializationBehavior/Attributes/MachineLearningDateTimeAttribute.cs
  src/Nest/CommonAbstractions/SerializationBehavior/JsonFormatters/NestFormatterResolver.cs
Labels: backport 7.x, backport master

#4437 update docs on the 7.x branch
  docs/aggregations/bucket/geo-hash-grid/geo-hash-grid-aggregation-usage.asciidoc
  docs/query-dsl/specialized/rank-feature/rank-feature-query-usage.asciidoc
Labels: Docs, backport 7.6

#4447 Fix yaml tests not deleting newly defined hidden indices
  tests/Tests.YamlRunner/Commands.fs
  tests/Tests.YamlRunner/TestSuiteBootstrap.fs
  tests/Tests.YamlRunner/Tests.YamlRunner.fsproj
  tests/Tests.YamlRunner/TestsReader.fs
Labels: backport 7.6, backport master

#4438 add 7.6.0 to the azure devops pipeline
  azure-pipelines.yml
Labels: backport 7.6

#4446 Move intrusive xpack tests to own cluster
  build/scripts/scripts.fsproj
  docs/aggregations/bucket/geo-hash-grid/geo-hash-grid-aggregation-usage.asciidoc
  docs/query-dsl/specialized/rank-feature/rank-feature-query-usage.asciidoc
  tests/Tests.Configuration/Tests.Configuration.csproj
  tests/Tests.Core/Extensions/ClientExtensions.cs
  tests/Tests.Core/ManagedElasticsearch/Clusters/XPackCluster.cs
  tests/Tests.Core/Tests.Core.csproj
  tests/Tests.Domain/Tests.Domain.csproj
  tests/Tests/Modules/SnapshotAndRestore/Repositories/CleanupRepository/CleanupRepositoryApiTests.cs
  tests/Tests/Modules/SnapshotAndRestore/Repositories/GetRepository/GetRepositoryApiTests.cs
  tests/Tests/XPack/Enrich/DeletePolicy/DeletePolicyApiTests.cs
  tests/Tests/XPack/Enrich/EnrichApiTests.cs
  tests/Tests/XPack/Enrich/EnrichCluster.cs
  tests/Tests/XPack/Enrich/ExecutePolicy/ExecutePolicyApiTests.cs
  tests/Tests/XPack/Enrich/GetPolicy/GetPolicyApiTests.cs
  tests/Tests/XPack/Enrich/PutPolicy/PutPolicyApiTests.cs
  tests/Tests/XPack/Enrich/Stats/StatsApiTests.cs
  tests/Tests/XPack/Security/Security.cs
  tests/Tests/XPack/Security/User/GetUserAccessToken/GetUserAccessTokenApiTests.cs
  tests/Tests/XPack/Security/User/InvalidateUserAccessToken/InvalidateUserAccessTokenApiTests.cs
  tests/Tests/XPack/Security/User/PutUser/PutUserApiTests.cs
  tests/Tests/XPack/Security/User/UserCrudTests.cs
  tests/Tests/XPack/Slm/SlmApiTests.cs
  tests/Tests/XPack/Slm/SlmCluster.cs
  tests/Tests/XPack/Watcher/AcknowledgeWatch/AcknowledgeWatchApiTests.cs
  tests/Tests/XPack/Watcher/ActivateWatch/ActivateWatchApiTests.cs
  tests/Tests/XPack/Watcher/DeactivateWatch/DeactivateWatchApiTests.cs
  tests/Tests/XPack/Watcher/DeleteWatch/DeleteWatchApiTests.cs
  tests/Tests/XPack/Watcher/ExecuteWatch/ExecuteWatchApiTests.cs
  tests/Tests/XPack/Watcher/GetWatch/GetWatchApiTests.cs
  tests/Tests/XPack/Watcher/PutWatch/PutWatchApiTests.cs
  tests/Tests/XPack/Watcher/WatcherCluster.cs
  tests/Tests/XPack/Watcher/WatcherStats/WatcherStatsApiTests.cs
Labels: Infra

#4453 Remove pre-release reference for Microsoft.CSharp
  src/Elasticsearch.Net/Elasticsearch.Net.csproj
Labels: backport 7.6, backport 7.x, v7.6.0

#4459 Ignore experimental APIs from 7.6.0
  src/ApiGenerator/Configuration/CodeConfiguration.cs
  src/Elasticsearch.Net/Api/Enums.Generated.cs
  src/Elasticsearch.Net/Api/RequestParameters/RequestParameters.MachineLearning.cs
  src/Elasticsearch.Net/Api/RequestParameters/RequestParameters.NoNamespace.cs
  src/Elasticsearch.Net/Api/RequestParameters/RequestParameters.Transform.cs
  src/Elasticsearch.Net/ElasticLowLevelClient.MachineLearning.cs
  src/Elasticsearch.Net/ElasticLowLevelClient.NoNamespace.cs
  src/Elasticsearch.Net/ElasticLowLevelClient.Transform.cs
  src/Elasticsearch.Net/IElasticLowLevelClient.Generated.cs
  src/Nest/Requests.cs
  src/Nest/_Generated/ApiUrlsLookup.generated.cs
  tests/Tests.YamlRunner/TestSuiteBootstrap.fs
Labels: v7.6.0

#4463 Fix GetMany when no default index is set
  src/Nest/Document/Multiple/Bulk/ElasticClient-DeleteMany.cs
  src/Nest/Document/Multiple/MultiGet/ElasticClient-GetMany.cs
  src/Nest/Document/Multiple/MultiGet/ElasticClient-SourceMany.cs
  tests/Tests.Reproduce/GitHubIssue4462.cs
Labels: Bug, backport 6.x, backport 7.6, backport master, v6.8.5, v7.6.1
