Repository elastic/elasticsearch-net, pull requests merged in 2020-10, with the labels that each got.

#5044 Removes Tests.TestLogger and depends on nullean/vstest-pretty-logger instead
  Elasticsearch.sln
  tests/.runsettings
  tests/Examples/Examples.csproj
  tests/Tests.Core/Tests.Core.csproj
  tests/Tests.TestLogger/PrettyLogger.cs
  tests/Tests.TestLogger/StringExtensions.cs
  tests/Tests.TestLogger/Tests.TestLogger.csproj
  tests/Tests.TestLogger/WordWrapper.cs
Labels: Refactoring, backport 7.x

#5042 [DOCS] Reorganizes Overview and Installation chapters in Test folder
  docs/high-level.asciidoc
  docs/index.asciidoc
  docs/installation.asciidoc
  docs/intro.asciidoc
  docs/introduction.asciidoc
  docs/low-level.asciidoc
  tests/Tests/high-level.asciidoc
  tests/Tests/index.asciidoc
  tests/Tests/installation.asciidoc
  tests/Tests/intro.asciidoc
  tests/Tests/introduction.asciidoc
  tests/Tests/low-level.asciidoc
Labels: Docs, backport 7.x, v7.10.0, v8.0.0-alpha1

#5059 add 7.10 to jobs and remove 7.8
  .ci/jobs/elastic+elasticsearch-net+7.10.yml
Labels: backport 7.10, backport 7.9, backport 7.x

#5053 [7.x][DOCS] Reorganizes Overview and Installation chapters in Test folder
  docs/high-level.asciidoc
  docs/index.asciidoc
  docs/installation.asciidoc
  docs/intro.asciidoc
  docs/introduction.asciidoc
  docs/low-level.asciidoc
  tests/Tests/high-level.asciidoc
  tests/Tests/index.asciidoc
  tests/Tests/installation.asciidoc
  tests/Tests/intro.asciidoc
  tests/Tests/introduction.asciidoc
  tests/Tests/low-level.asciidoc
Labels: Docs, backport 7.10

#5031 Added diversified sampler aggregation
  src/Nest/Aggregations/AggregateDictionary.cs
  src/Nest/Aggregations/AggregationContainer.cs
  src/Nest/Aggregations/Bucket/DiversifiedSampler/DiversifiedSamplerAggregation.cs
  src/Nest/Aggregations/Bucket/DiversifiedSampler/DiversifiedSamplerAggregationExecutionHint.cs
  src/Nest/Aggregations/Visitor/AggregationVisitor.cs
  tests/Examples/Aggregations/Bucket/DiversifiedSamplerAggregationPage.cs
  tests/Tests/Aggregations/Bucket/DiversifiedSampler/DiversifiedSamplerAggregationUsageTests.cs
Labels: Feature, backport 7.10, backport 7.9, backport 7.x

#5032 Updated sampler aggregation
  src/Nest/Aggregations/Bucket/Sampler/SamplerAggregation.cs
  src/Nest/Aggregations/Bucket/Sampler/SamplerAggregationExecutionHint.cs
  tests/Examples/Aggregations/Bucket/SamplerAggregationPage.cs
Labels: Breaking, Bug, v8.0.0-alpha1

#5064 Obsolete options on SamplerAggregation
  src/Nest/Aggregations/Bucket/Sampler/SamplerAggregation.cs
Labels: Bug, backport 7.10, backport 7.9

#5065 Allow custom tokenizers to be serialized fully
  src/Nest/Analysis/Tokenizers/TokenizerFormatter.cs
  tests/Tests.Reproduce/GithubPR5039.cs
Labels: Bug, backport 7.10, backport 7.9, backport 7.x
