Repository elastic/elasticsearch-net, pull requests merged in 2020-11, with the labels that each got.

#5078 Make API generation non interactive
  src/ApiGenerator/ApiGenerator.csproj
  src/ApiGenerator/Configuration/GeneratorLocations.cs
  src/ApiGenerator/Generator/ApiEndpointFactory.cs
  src/ApiGenerator/Generator/ApiGenerator.cs
  src/ApiGenerator/Generator/Razor/ApiUrlsLookupsGenerator.cs
  src/ApiGenerator/Generator/Razor/DescriptorsGenerator.cs
  src/ApiGenerator/Generator/Razor/EnumsGenerator.cs
  src/ApiGenerator/Generator/Razor/HighLevelClientImplementationGenerator.cs
  src/ApiGenerator/Generator/Razor/HighLevelClientInterfaceGenerator.cs
  src/ApiGenerator/Generator/Razor/LowLevelClientImplementationGenerator.cs
  src/ApiGenerator/Generator/Razor/LowLevelClientInterfaceGenerator.cs
  src/ApiGenerator/Generator/Razor/RazorGeneratorBase.cs
  src/ApiGenerator/Generator/Razor/RequestParametersGenerator.cs
  src/ApiGenerator/Generator/Razor/RequestsGenerator.cs
  src/ApiGenerator/Program.cs
  src/ApiGenerator/RestSpecDownloader.cs
  src/ApiGenerator/RestSpecification/Core/root.html
  src/ApiGenerator/RestSpecification/XPack/root.html
Labels: Feature, backport 6.x, backport 7.10, backport 7.x, v7.10.0

#5079 update low lowlevel client with latest changes from 7.10
  src/ApiGenerator/RestSpecification/Core/snapshot.clone.json
  src/ApiGenerator/last_downloaded_version.txt
  src/Elasticsearch.Net/Api/RequestParameters/RequestParameters.Snapshot.cs
  src/Elasticsearch.Net/ElasticLowLevelClient.Snapshot.cs
Labels: Self Reviewed

#5081 update low lowlevel client with latest changes from master
  src/ApiGenerator/RestSpecification/Core/cat.indices.json
  src/ApiGenerator/RestSpecification/Core/cat.shards.json
  src/ApiGenerator/RestSpecification/Core/snapshot.clone.json
  src/ApiGenerator/RestSpecification/XPack/async_search.status.json
  src/ApiGenerator/RestSpecification/XPack/autoscaling.get_autoscaling_capacity.json
  src/ApiGenerator/RestSpecification/XPack/autoscaling.get_autoscaling_decision.json
  src/ApiGenerator/RestSpecification/XPack/data_frame_transform_deprecated.get_transform.json
  src/ApiGenerator/RestSpecification/XPack/indices.delete_data_stream.json
  src/ApiGenerator/RestSpecification/XPack/indices.get_data_stream.json
  src/ApiGenerator/RestSpecification/XPack/indices.migrate_to_data_stream.json
  src/ApiGenerator/RestSpecification/XPack/ml.delete_data_frame_analytics.json
  src/ApiGenerator/RestSpecification/XPack/ml.delete_trained_model.json
  src/ApiGenerator/RestSpecification/XPack/ml.evaluate_data_frame.json
  src/ApiGenerator/RestSpecification/XPack/ml.explain_data_frame_analytics.json
  src/ApiGenerator/RestSpecification/XPack/ml.get_data_frame_analytics.json
  src/ApiGenerator/RestSpecification/XPack/ml.get_data_frame_analytics_stats.json
  src/ApiGenerator/RestSpecification/XPack/ml.get_datafeeds.json
  src/ApiGenerator/RestSpecification/XPack/ml.get_jobs.json
  src/ApiGenerator/RestSpecification/XPack/ml.get_trained_models.json
  src/ApiGenerator/RestSpecification/XPack/ml.get_trained_models_stats.json
  src/ApiGenerator/RestSpecification/XPack/ml.put_data_frame_analytics.json
  src/ApiGenerator/RestSpecification/XPack/ml.put_trained_model.json
  src/ApiGenerator/RestSpecification/XPack/ml.start_data_frame_analytics.json
  src/ApiGenerator/RestSpecification/XPack/ml.stop_data_frame_analytics.json
  src/ApiGenerator/RestSpecification/XPack/ml.update_data_frame_analytics.json
  src/ApiGenerator/RestSpecification/XPack/transform.get_transform.json
  src/ApiGenerator/last_downloaded_version.txt
  src/Elasticsearch.Net/Api/RequestParameters/RequestParameters.AsyncSearch.cs
  src/Elasticsearch.Net/Api/RequestParameters/RequestParameters.Autoscaling.cs
  src/Elasticsearch.Net/Api/RequestParameters/RequestParameters.Cat.cs
  src/Elasticsearch.Net/Api/RequestParameters/RequestParameters.Indices.cs
  src/Elasticsearch.Net/Api/RequestParameters/RequestParameters.MachineLearning.cs
  src/Elasticsearch.Net/Api/RequestParameters/RequestParameters.Snapshot.cs
  src/Elasticsearch.Net/Api/RequestParameters/RequestParameters.Transform.cs
  src/Elasticsearch.Net/ElasticLowLevelClient.AsyncSearch.cs
  src/Elasticsearch.Net/ElasticLowLevelClient.Autoscaling.cs
  src/Elasticsearch.Net/ElasticLowLevelClient.Indices.cs
  src/Elasticsearch.Net/ElasticLowLevelClient.MachineLearning.cs
  src/Elasticsearch.Net/ElasticLowLevelClient.Snapshot.cs
Labels: Self Reviewed

#5085 Add support for the new `data_*` roles.
  src/Nest/Cluster/NodesInfo/NodeRole.cs
Labels: Feature, backport 7.x, backport master, v7.10.0

#5077 Fixing BulkAll indefinitely hanging when failing
  src/Nest/Document/Multiple/BulkAll/BulkAllObservable.cs
Labels: Bug, backport 7.10, backport 7.x, v7.10.0

#5089 Mapping time boost was removed in 7.10
  src/Nest/Mapping/Types/Core/Number/NumberAttribute.cs
  src/Nest/Mapping/Types/Core/Number/NumberProperty.cs
  src/Nest/Mapping/Types/Core/Range/RangePropertyAttributeBase.cs
  src/Nest/Mapping/Types/Core/Range/RangePropertyBase.cs
  src/Nest/Mapping/Types/Specialized/Ip/IpAttribute.cs
  src/Nest/Mapping/Types/Specialized/Ip/IpProperty.cs
  src/Nest/Mapping/Types/Specialized/TokenCount/TokenCountAttribute.cs
  src/Nest/Mapping/Types/Specialized/TokenCount/TokenCountProperty.cs
  tests/Tests/ClientConcepts/Troubleshooting/DebuggerDisplayTests.cs
  tests/Tests/Mapping/Types/Core/Number/NumberPropertyTests.cs
  tests/Tests/Mapping/Types/Core/Range/DateRange/DateRangePropertyTests.cs
  tests/Tests/Mapping/Types/Core/Range/DoubleRange/DoubleRangePropertyTests.cs
  tests/Tests/Mapping/Types/Core/Range/FloatRange/FloatRangePropertyTests.cs
  tests/Tests/Mapping/Types/Core/Range/IntegerRange/IntegerRangePropertyTests.cs
  tests/Tests/Mapping/Types/Core/Range/IpRange/IpRangePropertyTests.cs
  tests/Tests/Mapping/Types/Core/Range/LongRange/LongRangePropertyTests.cs
  tests/Tests/Mapping/Types/Specialized/Ip/IpAttributeTests.cs
  tests/Tests/Mapping/Types/Specialized/Ip/IpPropertyTests.cs
  tests/Tests/Mapping/Types/Specialized/TokenCount/TokenCountPropertyTests.cs
Labels: Bug, backport 7.x, backport master, v7.10.0

#5088 Remove performance counters from RecyclableMemoryStream
  src/Elasticsearch.Net/Providers/RecyclableMemoryStreamManager-Events.cs
  src/Elasticsearch.Net/Providers/RecyclableMemoryStreamManager.cs
Labels: Bug, backport 7.10, backport 7.x, backport master, v7.10.0

#5099 Update to .NET 5 SDK
  .ci/DockerFile
  .ci/Jenkins.csproj
  .ci/make.sh
  .ci/readme.md
  .ci/run-repository.ps1
  .ci/run-repository.sh
  .ci/run-tests.ps1
  .ci/test-matrix.yml
  Directory.Build.targets
  appveyor.yml
  azure-pipelines.yml
  build/scripts/Benchmarking.fs
  build/scripts/Documentation.fs
  build/scripts/ReposTooling.fs
  build/scripts/scripts.fsproj
  dotnet-tools.json
  global.json
  src/ApiGenerator/ApiGenerator.csproj
  src/DocGenerator/DocGenerator.csproj
  src/Elastic.Transport/Responses/ServerException/ServerError.cs
  src/ExamplesGenerator/ExamplesGenerator.csproj
  src/Nest/Nest.csproj
  tests/Elastic.Transport.Tests/Elastic.Transport.Tests.csproj
  tests/Examples/Examples.csproj
  tests/Tests.Benchmarking/Tests.Benchmarking.csproj
  tests/Tests.ClusterLauncher/Tests.ClusterLauncher.csproj
  tests/Tests.Reproduce/Tests.Reproduce.csproj
  tests/Tests.ScratchPad/Tests.ScratchPad.csproj
  tests/Tests.YamlRunner/Tests.YamlRunner.fsproj
  tests/Tests/Tests.csproj
Labels: Infra, backport 7.10, backport 7.x, v7.10.1

#5098 Add hard_bounds for histograms
  src/Nest/Aggregations/Bucket/DateHistogram/DateHistogramAggregation.cs
  src/Nest/Aggregations/Bucket/Histogram/HardBounds.cs
  src/Nest/Aggregations/Bucket/Histogram/HistogramAggregation.cs
  tests/Tests/Aggregations/Bucket/DateHistogram/DateHistogramAggregationUsageTests.cs
  tests/Tests/Aggregations/Bucket/Histogram/HistogramAggregationUsageTests.cs
Labels: Feature, backport 7.10, backport 7.x, v7.10.1

#5101 Update VS image for AppVeyor
  appveyor.yml
Labels: Infra, backport 7.10, backport 7.x

#5107 [Backport 7.x] Update to .NET 5 SDK (#5099)
  .ci/DockerFile
  .ci/Jenkins.csproj
  .ci/make.sh
  .ci/readme.md
  .ci/run-repository.ps1
  .ci/run-repository.sh
  .ci/run-tests.ps1
  .ci/test-matrix.yml
  Directory.Build.targets
  appveyor.yml
  azure-pipelines.yml
  build/scripts/Benchmarking.fs
  build/scripts/Documentation.fs
  build/scripts/ReposTooling.fs
  build/scripts/scripts.fsproj
  dotnet-tools.json
  global.json
  src/ApiGenerator/ApiGenerator.csproj
  src/DocGenerator/DocGenerator.csproj
  src/Elasticsearch.Net/Elasticsearch.Net.csproj
  src/Elasticsearch.Net/Responses/ServerException/ServerError.cs
  src/Nest/Nest.csproj
  tests/Tests.Benchmarking/Tests.Benchmarking.csproj
  tests/Tests.ClusterLauncher/Tests.ClusterLauncher.csproj
  tests/Tests.Reproduce/Tests.Reproduce.csproj
  tests/Tests.ScratchPad/Tests.ScratchPad.csproj
  tests/Tests.YamlRunner/Tests.YamlRunner.fsproj
  tests/Tests/Tests.csproj
Labels: Infra

#5100 [Backport 7.10] Update to .NET 5 SDK (#5099)
  .ci/DockerFile
  .ci/Jenkins.csproj
  .ci/make.sh
  .ci/readme.md
  .ci/run-repository.ps1
  .ci/run-repository.sh
  .ci/run-tests.ps1
  .ci/test-matrix.yml
  Directory.Build.targets
  appveyor.yml
  azure-pipelines.yml
  build/scripts/Benchmarking.fs
  build/scripts/Documentation.fs
  build/scripts/ReposTooling.fs
  build/scripts/scripts.fsproj
  dotnet-tools.json
  global.json
  src/ApiGenerator/ApiGenerator.csproj
  src/DocGenerator/DocGenerator.csproj
  src/Elasticsearch.Net/Elasticsearch.Net.csproj
  src/Elasticsearch.Net/Responses/ServerException/ServerError.cs
  src/Nest/Nest.csproj
  tests/Tests.Benchmarking/Tests.Benchmarking.csproj
  tests/Tests.ClusterLauncher/Tests.ClusterLauncher.csproj
  tests/Tests.Reproduce/Tests.Reproduce.csproj
  tests/Tests.ScratchPad/Tests.ScratchPad.csproj
  tests/Tests.YamlRunner/Tests.YamlRunner.fsproj
  tests/Tests/Tests.csproj
Labels: Infra

#5111 Docs generator producing bad line endings
  src/DocGenerator/AsciiDoc/GeneratedAsciidocVisitor.cs
  src/DocGenerator/Documentation/Blocks/CSharpBlock.cs
Labels: Bug, Infra, backport 7.10, backport 7.x

#5116 Add authentication type to AuthenticateResponse
  src/Nest/XPack/Security/Authenticate/AuthenticateResponse.cs
Labels: Feature, backport 7.10, backport 7.x, v7.10.1

#5123 Generate initial NEST code for 7.10.1
  src/ApiGenerator/RestSpecification/_Patches/indices.flush_synced.patch.json
  src/Nest/Descriptors.Security.cs
  src/Nest/ElasticClient.Security.cs
  src/Nest/Requests.Security.cs
Labels: Feature, backport 7.x, backport master, v7.10.1

#5121 Add ignore_keywords flag to word delimiter graph
  src/Nest/Analysis/TokenFilters/WordDelimiterGraph/WordDelimiterGraphTokenFilter.cs
  tests/Tests/Analysis/TokenFilters/TokenFilterTests.cs
  tests/Tests/Analysis/TokenFilters/TokenFilterUsageTests.cs
Labels: Feature, backport 7.x, backport master, v7.10.1

#5109 [DOCS] Update date histogram doc
  docs/aggregations/bucket/date-histogram/date-histogram-aggregation-usage.asciidoc
Labels: Docs

#5108 [DOCS] Update date histogram doc
  docs/aggregations/bucket/date-histogram/date-histogram-aggregation-usage.asciidoc
Labels: Docs, backport 7.10

#5120 Fix missing deprecated attributes on low-level
  src/ApiGenerator/ApiGenerator.csproj
  src/ApiGenerator/Domain/Specification/UrlInformation.cs
  src/ApiGenerator/Program.cs
Labels: Bug, Infra, backport 7.x, backport master

#5104 Add QueryCache columns to CatNodesRecord
  src/Nest/Cat/CatNodes/CatNodesRecord.cs
Labels: Feature, backport 7.10, backport 7.x, v7.10.1

#5133 Update BoxplotAggregate response
  src/Nest/Aggregations/AggregateFormatter.cs
  src/Nest/Aggregations/Metric/Boxplot/BoxplotAggregate.cs
  tests/Tests/Aggregations/Metric/Boxplot/BoxplotAggregationUsageTests.cs
Labels: Feature, backport 7.x, v7.11.0

#5141 Update boxplot usage doc
  docs/aggregations/metric/boxplot/boxplot-aggregation-usage.asciidoc
Labels: Docs, Self Reviewed

#5139 Handle additional JSON properties
  src/Nest/Aggregations/AggregateFormatter.cs
Labels: Bug

#5137 Add point in time APIs
  src/ApiGenerator/last_downloaded_version.txt
  src/Nest/Descriptors.NoNamespace.cs
  src/Nest/ElasticClient.NoNamespace.cs
  src/Nest/IElasticClient.Generated.cs
  src/Nest/Requests.NoNamespace.cs
  src/Nest/Search/Search/PointInTime/Close/ClosePointInTimeRequest.cs
  src/Nest/Search/Search/PointInTime/Close/ClosePointInTimeResponse.cs
  src/Nest/Search/Search/PointInTime/Open/OpenPointInTimeRequest.cs
  src/Nest/Search/Search/PointInTime/Open/OpenPointInTimeResponse.cs
  src/Nest/_Generated/ApiUrlsLookup.generated.cs
  tests/Tests/Search/PointInTime/Close/ClosePointInTimeApiTests.cs
  tests/Tests/Search/PointInTime/Close/ClosePointInTimeUrlTests.cs
  tests/Tests/Search/PointInTime/Open/OpenPointInTimeApiTests.cs
  tests/Tests/Search/PointInTime/Open/OpenPointInTimeUrlTests.cs
Labels: Feature, backport 7.x, backport master, v7.10.1
