Repository elastic/elasticsearch-net, pull requests merged in 2020-08, with the labels that each got.

#4905 Add addition settings to s3 repository
  src/Nest/Modules/SnapshotAndRestore/Repositories/S3Repository.cs
  tests/Tests/Modules/SnapshotAndRestore/Repositories/CreateRepository/CreateRepositoryApiTests.cs
Labels: Feature, backport 7.9, backport 7.x, v7.9.0

#4910 Handle ISO8601 basic format offsets
  src/Elasticsearch.Net/Utf8Json/Formatters/DateTimeFormatter.cs
  tests/Tests.Reproduce/GitHubIssue4876.cs
Labels: Bug, backport 7.9, backport 7.x, v7.9.0

#4911 Add max_token_length to chargroup tokenizer
  src/Nest/Analysis/Tokenizers/CharGroupTokenizer.cs
  tests/Tests/Analysis/Tokenizers/TokenizerTests.cs
Labels: Feature, backport 7.9, backport 7.x, v7.9.0

#4912 Add discard_compound_token to kuromoji tokenizer
  src/Nest/Analysis/Plugins/Kuromoji/KuromojiTokenizer.cs
  tests/Tests/Analysis/Tokenizers/TokenizerTests.cs
Labels: Feature, backport 7.9, backport 7.x, v7.9.0

#4914 Add must_exist to alias remove
  src/Nest/Indices/AliasManagement/Alias/Actions/AliasRemoveOperation.cs
Labels: Feature, backport 7.9, backport 7.x, v7.9.0

#4915 Add ignore_empty_value to set processor
  src/Nest/Ingest/Processors/SetProcessor.cs
Labels: Feature, backport 7.9, backport 7.x, v7.9.0

#4917 Add geotile_grid transform group by
  src/Nest/XPack/Transform/Pivot/GeoTileGridGroupSource.cs
  src/Nest/XPack/Transform/Pivot/SingleGroupSource.cs
  tests/Tests/XPack/Transform/TransformApiTests.cs
Labels: Feature, backport 7.9, backport 7.x, v7.9.0

#4918 Add reserved, reserved_in_bytes to node stats response
  src/Nest/CommonOptions/Stats/StoreStats.cs
  tests/Tests/Cluster/NodesStats/NodesStatsApiTests.cs
Labels: Feature, backport 7.9, backport 7.x, v7.9.0

#4919 Add annotations_enabled to model config
  src/Nest/XPack/MachineLearning/Job/Config/ModelPlotConfig.cs
Labels: Feature, backport 7.9, backport 7.x, v7.9.0

#4934 Fix date format use in SearchApiDocValueFieldsTests
  tests/Tests/Search/Search/SearchApiTests.cs
Labels: backport 7.9, backport 7.x

#4943 Skip DateHistogram aggregations for <7.2.0
  tests/Tests/Aggregations/Bucket/DateHistogram/DateHistogramAggregationUsageTests.cs
Labels: backport 7.9

#4948 Consistent file string comparison across Windows and Linux
  docs/aggregations.asciidoc
  docs/query-dsl.asciidoc
  src/DocGenerator/AsciiDoc/RawAsciidocVisitor.cs
  src/DocGenerator/Program.cs
  src/DocGenerator/StringExtensions.cs
  src/DocGenerator/SyntaxNodeExtensions.cs
Labels: Docs, backport 7.9, backport 7.x

#4921 [DOCS] Fixes broken link to sliced scroll
  docs/search/scrolling-documents.asciidoc
  tests/Tests/Search/ScrollingDocuments.doc.cs
Labels: Docs, backport 7.9, backport 7.x, v7.9.0, v8.0.0-alpha1

#4953 Increase YAML test frequency to twice a day
  .ci/jobs/elastic+elasticsearch-net+7.8.yml
  .ci/jobs/elastic+elasticsearch-net+7.9.yml
  .ci/jobs/elastic+elasticsearch-net+7.x.yml
  .ci/jobs/elastic+elasticsearch-net+master.yml
Labels: Infra, backport 7.x

#4952 NameValueCollection.ToQueryString performance optimisation
  src/Elasticsearch.Net/Elasticsearch.Net.csproj
  src/Elasticsearch.Net/Extensions/NameValueCollectionExtensions.cs
  tests/Tests/Extensions/NameValueCollectionExtensionsTests.cs
Labels: backport 7.x, v7.10.0, v8.0.0-alpha1

#4956 Update build recipient for yaml rest tests
  .ci/jobs/defaults.yml
Labels: Infra, backport 6.x, backport 7.8, backport 7.9, backport 7.x

#4947 Add settings to create follow index and create auto follow pattern APIs
  src/Nest/XPack/CrossClusterReplication/AutoFollow/CreateAutoFollowPattern/CreateAutoFollowPatternRequest.cs
  src/Nest/XPack/CrossClusterReplication/AutoFollow/GetAutoFollowPattern/GetAutoFollowPatternResponse.cs
  src/Nest/XPack/CrossClusterReplication/Follow/CreateFollowIndex/CreateFollowIndexRequest.cs
  tests/Tests/XPack/CrossClusterReplication/AutoFollow/CreateAutoFollowPattern/CreateAutoFollowPatternApiTests.cs
  tests/Tests/XPack/CrossClusterReplication/AutoFollow/CreateAutoFollowPattern/CreateAutoFollowPatternUrlTests.cs
  tests/Tests/XPack/CrossClusterReplication/Follow/CreateFollowIndex/CreateFollowIndexApiTests.cs
  tests/Tests/XPack/CrossClusterReplication/Follow/CreateFollowIndex/CreateFollowIndexUrlTests.cs
Labels: Feature, backport 7.9, backport 7.x, v7.9.0

#4972 Make rules in VirtualCluster explicit
  src/Elasticsearch.Net.VirtualizedCluster/Audit/Auditor.cs
  src/Elasticsearch.Net.VirtualizedCluster/Audit/Audits.cs
  src/Elasticsearch.Net.VirtualizedCluster/Rules/RuleBase.cs
  src/Elasticsearch.Net.VirtualizedCluster/VirtualClusterConnection.cs
  src/Elasticsearch.Net/Connection/InMemoryConnection.cs
  src/Nest/CommonAbstractions/Response/ResponseBase.cs
  src/Nest/Document/Multiple/Bulk/BulkResponse.cs
  tests/Tests.Core/Tests.Core.csproj
  tests/Tests/ClientConcepts/ConnectionPooling/Failover/FallingOver.doc.cs
  tests/Tests/ClientConcepts/ConnectionPooling/Pinging/FirstUsage.doc.cs
  tests/Tests/ClientConcepts/ConnectionPooling/RequestOverrides/DisableSniffPingPerRequest.doc.cs
  tests/Tests/ClientConcepts/ConnectionPooling/Sniffing/OnConnectionFailure.doc.cs
  tests/Tests/ClientConcepts/ConnectionPooling/Sniffing/OnStartup.doc.cs
  tests/Tests/ClientConcepts/ConnectionPooling/Sniffing/RoleDetection.doc.cs
  tests/Tests/ClientConcepts/ConnectionPooling/Sticky/StickySniffingConnectionPool.doc.cs
  tests/Tests/ClientConcepts/VirtualClusterTests.cs
Labels: Breaking, Feature, backport 7.9, backport 7.x

#4978 Fix field value factor serialization
  src/Nest/QueryDsl/Compound/FunctionScore/Functions/ScoreFunctionJsonFormatter.cs
  tests/Tests/QueryDsl/Compound/FunctionScore/FunctionScoreQueryUsageTests.cs
Labels: Bug, backport 7.9, backport 7.x, v7.9.1

#4979 Use SourceSerializer when deserializing Source API response
  src/Elasticsearch.Net/Serialization/CustomResponseBuilderBase.cs
  src/Nest/Document/Single/Source/SourceRequestResponseBuilder.cs
  tests/Tests/Document/Single/Source/SourceApiTests.cs
Labels: Bug, backport 7.9, backport 7.x, v7.9.1

#4988 Add documentation for reindexing documents
  docs/client-concepts/connection-pooling/pinging/first-usage.asciidoc
  docs/client-concepts/connection-pooling/request-overrides/disable-sniff-ping-per-request.asciidoc
  docs/client-concepts/connection-pooling/sniffing/on-connection-failure.asciidoc
  docs/client-concepts/connection-pooling/sniffing/on-startup.asciidoc
  docs/client-concepts/connection-pooling/sniffing/role-detection.asciidoc
  docs/client-concepts/connection-pooling/sticky/sticky-sniffing-connection-pool.asciidoc
  docs/client-concepts/high-level/indexing/indexing-documents.asciidoc
  docs/client-concepts/high-level/indexing/reindexing-documents.asciidoc
  docs/high-level.asciidoc
  tests/Tests/ClientConcepts/HighLevel/Indexing/IndexingDocuments.doc.cs
  tests/Tests/ClientConcepts/HighLevel/Indexing/ReindexingDocuments.doc.cs
  tests/Tests/high-level.asciidoc
Labels: Docs, backport 7.9, backport 7.x

#4648 Selective inclusion of new API's in the high level code generator
  src/ApiGenerator/Configuration/CodeConfiguration.cs
  src/ApiGenerator/Domain/RestApiSpec.cs
  src/ApiGenerator/Generator/ApiGenerator.cs
  src/ApiGenerator/Program.cs
  src/ApiGenerator/Views/HighLevel/Requests/ApiUrlsLookup.cshtml
  src/Nest/Cluster/Ping/PingRequest.cs
  src/Nest/Document/Multiple/Bulk/BulkRequest.cs
  src/Nest/Document/Multiple/DeleteByQuery/DeleteByQueryRequest.cs
  src/Nest/Document/Multiple/ReindexRethrottle/ReindexRethrottleRequest.cs
  src/Nest/Document/Multiple/UpdateByQuery/UpdateByQueryRequest.cs
  src/Nest/Document/Single/Get/GetRequest.cs
  src/Nest/Document/Single/Index/IndexRequest.cs
  src/Nest/Document/Single/Update/UpdateRequest.cs
  src/Nest/Search/Scroll/Scroll/ScrollRequest.cs
  src/Nest/Search/Search/SearchRequest.cs
  src/Nest/Search/SearchShards/SearchShardsRequest.cs
  src/Nest/Search/SearchTemplate/RenderSearchTemplate/RenderSearchTemplateRequest.cs
  src/Nest/Search/SearchTemplate/SearchTemplateRequest.cs
Labels: Feature, Infra, backport 7.x
