Repository elastic/elasticsearch-net, pull requests merged in 2020-12, with the labels that each got.

#5143 [DOCS] Update boxplot usage doc
  docs/aggregations/metric/boxplot/boxplot-aggregation-usage.asciidoc
Labels: Docs

#5140 Update System.Diagnostics.DiagnosticSource
  src/Elasticsearch.Net/Diagnostics/Diagnostic.cs
  src/Elasticsearch.Net/Elasticsearch.Net.csproj
  tests/Tests.ScratchPad/Tests.ScratchPad.csproj
Labels: Infra, backport 7.x, backport master, v7.10.1

#5142 Implement grant API key
  src/Nest/Descriptors.Security.cs
  src/Nest/ElasticClient.Security.cs
  src/Nest/Requests.Security.cs
  src/Nest/XPack/Security/ApiKey/GrantApiKey/ApiKey.cs
  src/Nest/XPack/Security/ApiKey/GrantApiKey/GrantApiKeyRequest.cs
  src/Nest/XPack/Security/ApiKey/GrantApiKey/GrantApiKeyResponse.cs
  src/Nest/XPack/Security/ApiKey/GrantApiKey/GrantType.cs
  src/Nest/_Generated/ApiUrlsLookup.generated.cs
  tests/Tests/XPack/Security/ApiKey/GrantApiKey/GrantApiKeyTests.cs
  tests/Tests/XPack/Security/ApiKey/GrantApiKey/GrantApiKeyUrlTests.cs
Labels: Feature, backport 7.x, backport master, v7.10.1

#5148 Support indexing pressure on NodeStats
  src/Nest/Cluster/NodesStats/NodeStats.cs
  tests/Tests/Cluster/NodesStats/NodesStatsApiTests.cs
Labels: Feature, backport 7.x, backport master, v7.10.1

#5151 Support point in time searches
  src/Nest/CommonAbstractions/Request/ApiUrls.cs
  src/Nest/CommonAbstractions/Request/RequestBase.cs
  src/Nest/Search/Search/PointInTime/PointInTime.cs
  src/Nest/Search/Search/SearchRequest.cs
  src/Nest/Search/Search/SearchResponse.cs
  tests/Tests/Search/PointInTime/Close/ClosePointInTimeApiTests.cs
  tests/Tests/Search/PointInTime/Open/OpenPointInTimeApiTests.cs
  tests/Tests/Search/PointInTime/Open/OpenPointInTimeUrlTests.cs
  tests/Tests/Search/PointInTime/PointInTimeApiTests.cs
  tests/Tests/Search/PointInTime/PointInTimeUrlTests.cs
  tests/Tests/Search/Request/PointInTimeUsageTests.cs
  tests/Tests/Search/Search/SearchApiTests.cs
  tests/Tests/Search/Search/SearchUrlTests.cs
Labels: Feature, backport 7.x, backport master, v7.10.1

#5147 Support clear api key cache
  src/ApiGenerator/Domain/Specification/UrlPart.cs
  src/ApiGenerator/RestSpecification/_Patches/security.clear_api_key_cache.patch.json
  src/Elasticsearch.Net/ElasticLowLevelClient.Security.cs
  src/Nest/Descriptors.Security.cs
  src/Nest/ElasticClient.Security.cs
  src/Nest/Requests.Security.cs
  src/Nest/XPack/Security/ApiKey/ClearApiKeyCache/ClearApiKeyCacheRequest.cs
  src/Nest/XPack/Security/ApiKey/ClearApiKeyCache/ClearApiKeyCacheResponse.cs
  src/Nest/_Generated/ApiUrlsLookup.generated.cs
  tests/Tests/XPack/Security/ApiKey/SecurityApiKeyTests.cs
  tests/Tests/XPack/Security/ApiKey/SecurityApiKeyUrlTests.cs
Labels: Feature, backport 7.x, backport master, v7.10.1

#5160 [Backport master] Support indexing pressure on NodeStats (#5148)
  src/Nest/Cluster/NodesStats/NodeStats.cs
  tests/Tests/Cluster/NodesStats/NodesStatsApiTests.cs
Labels: Self Reviewed

#5161 Fix flaky test assertion for pit search
  tests/Tests/Search/PointInTime/PointInTimeApiTests.cs
Labels: Flakey test, backport 7.x, backport master

#5165 [Backport master] Support clear api key cache
  src/ApiGenerator/Domain/Specification/UrlPart.cs
  src/ApiGenerator/RestSpecification/_Patches/security.clear_api_key_cache.patch.json
  src/Elasticsearch.Net/ElasticLowLevelClient.Security.cs
  src/Nest/Descriptors.Security.cs
  src/Nest/ElasticClient.Security.cs
  src/Nest/Requests.Security.cs
  src/Nest/XPack/Security/ApiKey/ClearApiKeyCache/ClearApiKeyCacheRequest.cs
  src/Nest/XPack/Security/ApiKey/ClearApiKeyCache/ClearApiKeyCacheResponse.cs
  src/Nest/_Generated/ApiUrlsLookup.generated.cs
  tests/Tests/XPack/Security/ApiKey/SecurityApiKeyTests.cs
  tests/Tests/XPack/Security/ApiKey/SecurityApiKeyUrlTests.cs
Labels: Self Reviewed

#5097 Introduce assemble of SNAPSHOT builds
  build/scripts/Versioning.fs
Labels: Infra, backport 7.10, backport 7.x

#5180 Tweaks .ci/make.sh to clean up after itself
  .ci/make.sh
  Directory.Build.props
  appveyor.yml
  build/scripts/Building.fs
  build/scripts/Paths.fs
  build/scripts/Targets.fs
  build/scripts/Testing.fs
  build/scripts/Versioning.fs
  build/scripts/scripts.fsproj
Labels: Infra, backport 7.10, backport 7.x

#5163 Update with additional sdk version properties
  build/scripts/Versioning.fs
Labels: Infra, backport 7.10, backport 7.x

#5115 Support call outs in JSON (JavaScript) blocks.
  src/DocGenerator/DocGenerator.csproj
  src/DocGenerator/Documentation/Blocks/BlockCallOutHelper.cs
  src/DocGenerator/Documentation/Blocks/CSharpBlock.cs
  src/DocGenerator/Documentation/Blocks/JavaScriptBlock.cs
  src/DocGenerator/Walkers/Constants.cs
  src/DocGenerator/Walkers/JsonCallOutHelper.cs
  src/DocGenerator/Walkers/UsageTestsWalker.cs
Labels: Infra, backport 7.10, backport 7.x

#5177 TcpStats.GetStats() now handles error when host cannot disclose information
  docs/analysis/token-filters/token-filter-usage.asciidoc
  docs/client-concepts/troubleshooting/debug-information.asciidoc
  docs/search.asciidoc
  docs/search/request/point-in-time-usage.asciidoc
  src/Elastic.Transport/Diagnostics/TcpStats.cs
  tests/Tests/ClientConcepts/Troubleshooting/DebugInformation.doc.cs
Labels: Bug, backport 7.11, backport 7.x, v7.11.0

#5188 adding support for enable_position_increments property on ITokenCountProperty
  src/Nest/Mapping/Types/Specialized/TokenCount/TokenCountAttribute.cs
  src/Nest/Mapping/Types/Specialized/TokenCount/TokenCountProperty.cs
  tests/Tests/Mapping/Types/Specialized/TokenCount/TokenCountAttributeTests.cs
  tests/Tests/Mapping/Types/Specialized/TokenCount/TokenCountPropertyTests.cs
Labels: Feature, backport 7.11, backport 7.x, v7.11.0

#5191 Updated CI jobs
  .ci/jobs/elastic+elasticsearch-net+7.11.yml
Labels: Infra, backport 7.11, backport 7.x

#5209 Fix failing transform tests and support dates_as_epoch_millis
  src/Nest/XPack/Transform/TransformSettings.cs
  tests/Tests.Domain/Project.cs
  tests/Tests/XPack/Transform/TransformApiTests.cs
  tests/Tests/XPack/Transform/TransformApiWithSettingsTests.cs
Labels: Feature, backport 7.x, backport master, tests, v7.11.0

#5187 Remove mention of type from Getting Started docs
  docs/client-concepts/high-level/getting-started.asciidoc
  docs/client-concepts/high-level/inference/document-paths.asciidoc
  tests/Tests/ClientConcepts/HighLevel/GettingStarted.doc.cs
  tests/Tests/ClientConcepts/HighLevel/Inference/DocumentPaths.doc.cs
Labels: Docs, backport 7.x

#5213 Fix broken yaml test bootstrap
  tests/Tests.YamlRunner/TestSuiteBootstrap.fs
Labels: Self Reviewed, backport 7.11, backport 7.x, tests

#5216 Skip 20_fvh.yml temporarily while we wait for the fix to land
  tests/Tests.YamlRunner/SkipList.fs
Labels: backport 7.10, backport 7.11, tests

#5219 Add assertions to ScriptFieldsUsageTests
  tests/Tests/Search/Request/ScriptFieldsUsageTests.cs
Labels: backport 7.11, backport 7.x
