Repository elastic/elasticsearch-net, pull requests merged in 2020-06, with the labels that each got.

#4692 Correct grammar on MatchQuery CutoffFrequency
  src/Nest/QueryDsl/Abstractions/Container/QueryContainerDescriptor.cs
  src/Nest/QueryDsl/FullText/Match/MatchQuery.cs
Labels: Docs, backport 7.7, backport 7.8, backport 7.x

#4719 Update REST api specs against 7.8 branch
  src/ApiGenerator/Configuration/Overrides/EndpointOverridesBase.cs
  src/ApiGenerator/Generator/ApiEndpointFactory.cs
  src/ApiGenerator/Generator/ApiGenerator.cs
  src/ApiGenerator/RestSpecification/Core/cat.thread_pool.json
  src/ApiGenerator/RestSpecification/Core/indices.get_data_streams.json
  src/ApiGenerator/RestSpecification/Core/indices.put_mapping.json
  src/ApiGenerator/RestSpecification/Core/indices.simulate_template.json
  src/ApiGenerator/RestSpecification/Core/root.html
  src/ApiGenerator/RestSpecification/XPack/root.html
  src/ApiGenerator/RestSpecification/_Patches/indices.get_data_streams.patch.json
  src/ApiGenerator/last_downloaded_version.txt
  src/Elasticsearch.Net/Api/RequestParameters/RequestParameters.Cat.cs
  src/Elasticsearch.Net/Api/RequestParameters/RequestParameters.Indices.cs
  src/Elasticsearch.Net/ElasticLowLevelClient.Indices.cs
  src/Nest/Descriptors.Cat.cs
  src/Nest/Requests.Cat.cs
Labels: Feature, Self Reviewed, v7.8.0

#4731 Add 7.8 job to Jenkins CI
  .ci/jobs/elastic+elasticsearch-net+7.8.yml
Labels: Infra

#4710 Elasticsearch always returns a 400 now for our invalid search
  azure-pipelines.yml
  tests/Tests/Search/Search/InvalidSearchApiTests.cs
Labels: Flakey test, backport 7.7, backport 7.8

#4726 Unmute CsvProcessor
  tests/Tests/Ingest/ProcessorAssertions.cs
  tests/Tests/Ingest/PutPipeline/PutPipelineApiTests.cs
Labels: Flakey test, backport 7.8, backport 7.x, v7.8.0

#4727 Add PreserveOriginal to EdgeNgramTokenFilter
  src/Nest/Analysis/TokenFilters/EdgeNGram/EdgeNGramTokenFilter.cs
  tests/Tests/Analysis/TokenFilters/TokenFilterTests.cs
Labels: Feature, backport 7.8, backport 7.x, v7.8.0

#4728 Add analytics to xpack usage
  src/Nest/XPack/Info/XPackUsage/XPackUsageResponse.cs
  tests/Tests/XPack/Info/XPackInfoApiTests.cs
Labels: Feature, backport 7.8, backport 7.x, v7.8.0

#4736 Add PreserveOriginal to NGramTokenFilter
  src/Nest/Analysis/TokenFilters/NgramTokenFilter.cs
  tests/Tests/Analysis/TokenFilters/TokenFilterTests.cs
Labels: Feature, backport 7.8, backport 7.x, v7.8.0

#4737 Add aggregation usage to nodes usage
  src/Nest/Cluster/NodesUsage/NodeUsageInformation.cs
  tests/Tests/Cluster/NodesUsage/NodesUsageApiTests.cs
Labels: Feature, backport 7.8, backport 7.x, v7.8.0

#4729 Add Transform settings
  src/Nest/XPack/Transform/PreviewTransform/PreviewTransformRequest.cs
  src/Nest/XPack/Transform/PutTransform/PutTransformRequest.cs
  src/Nest/XPack/Transform/Transform.cs
  src/Nest/XPack/Transform/TransformSettings.cs
  src/Nest/XPack/Transform/UpdateTransform/UpdateTransformRequest.cs
  tests/Tests/XPack/Transform/TransformApiWithSettingsTests.cs
Labels: Feature, backport 7.8, backport 7.x

#4741 Fix Ids overloads on PinnedQuery
  src/Nest/QueryDsl/Specialized/Pinned/PinnedQuery.cs
  tests/Tests.Reproduce/GithubIssue4733.cs
Labels: Bug, backport 7.8, backport 7.x, v7.8.0

#4743 Add rewrite to RegExp query
  docs/query-dsl/term-level/regexp/regexp-query-usage.asciidoc
  src/Nest/QueryDsl/TermLevel/Regexp/RegexpQuery.cs
  tests/Tests/QueryDsl/TermLevel/Regexp/RegexpQueryUsageTests.cs
Labels: Feature, backport 7.8, backport 7.x, v7.8.0

#4732 Add support for T-Test aggregations
  docs/aggregations.asciidoc
  docs/aggregations/metric/t-test/t-test-aggregation-usage.asciidoc
  src/Nest/Aggregations/AggregateDictionary.cs
  src/Nest/Aggregations/AggregationContainer.cs
  src/Nest/Aggregations/Metric/TTest/TTestAggregation.cs
  src/Nest/Aggregations/Metric/TTest/TTestGroup.cs
  src/Nest/Aggregations/Metric/ValueAggregate.cs
  src/Nest/Aggregations/Visitor/AggregationVisitor.cs
  src/Nest/Aggregations/Visitor/AggregationWalker.cs
  tests/Tests/Aggregations/Metric/TTest/TTestAggregationUsageTests.cs
Labels: Feature, backport 7.8, backport 7.x, v7.8.0

#4744 Add script_cache to Node Stats API
  src/Nest/Cluster/NodesStats/NodeStats.cs
  tests/Tests/Cluster/NodesStats/NodesStatsApiTests.cs
Labels: backport 7.8, backport 7.x, v7.8.0

#4738 Add Voting Config Exclusions APIs
  src/Nest/Cluster/VotingConfigExclusions/DeleteVotingConfigExclusions/DeleteVotingConfigExclusionsRequest.cs
  src/Nest/Cluster/VotingConfigExclusions/DeleteVotingConfigExclusions/DeleteVotingConfigExclusionsResponse.cs
  src/Nest/Cluster/VotingConfigExclusions/PostVotingConfigExclusions/PostVotingConfigExclusionsRequest.cs
  src/Nest/Cluster/VotingConfigExclusions/PostVotingConfigExclusions/PostVotingConfigExclusionsResponse.cs
  src/Nest/Descriptors.Cluster.cs
  src/Nest/ElasticClient.Cluster.cs
  src/Nest/Requests.Cluster.cs
  tests/Tests/Cluster/VotingConfigExclusions/DeleteVotingConfigExclusions/DeleteVotingConfigExclusionsApiTests.cs
  tests/Tests/Cluster/VotingConfigExclusions/DeleteVotingConfigExclusions/DeleteingVotingConfigExclusionsTests.cs
  tests/Tests/Cluster/VotingConfigExclusions/PostVotingConfigExclusions/PostVotingConfigExclusionsApiTests.cs
  tests/Tests/Cluster/VotingConfigExclusions/PostVotingConfigExclusions/PostingVotingConfigExclusionsTests.cs
Labels: Feature, backport 7.8, backport 7.x, v7.8.0

#4725 AutoDateHistogramAggregate Interval should be DateMathTime
  src/Nest/Aggregations/AggregateFormatter.cs
  src/Nest/Aggregations/Bucket/AutoDateHistogram/AutoDateHistogramBucket.cs
  src/Nest/Aggregations/Bucket/BucketAggregate.cs
  tests/Tests.Reproduce/GitHubIssue4333.cs
Labels: Bug, v6.8.7, v7.8.0

#4771 Force stop transform and wait for completion
  tests/Tests.Domain/Project.cs
  tests/Tests/XPack/Transform/TransformApiTests.cs
Labels: Flakey test, backport 7.7, backport 7.8, backport 7.x

#4777 More lenient extended_stats deserialization
  src/Nest/Aggregations/AggregateFormatter.cs
  src/Nest/Aggregations/Metric/ExtendedStats/ExtendedStatsAggregate.cs
Labels: Flakey test, Self Reviewed, backport 7.x

#4772 Add FixedInterval and CalendarInterval to IDateHistogramCompositeAggr…
  docs/aggregations/bucket/composite/composite-aggregation-usage.asciidoc
  src/Nest/Aggregations/Bucket/Composite/DateHistogramCompositeAggregationSource.cs
  tests/Tests/Aggregations/Bucket/Composite/CompositeAggregationUsageTests.cs
Labels: Feature, backport 7.8, backport 7.x, v7.8.0

#4780 Remove increment inside loop when validating intermediate CA
  src/Elasticsearch.Net/Connection/CertificateValidations.cs
Labels: Bug, backport 7.8, backport 7.x, v7.8.0

#4790 Update with latest 7.8 REST specs
  src/ApiGenerator/RestSpecification/Core/indices.simulate_index_template.json
  src/ApiGenerator/RestSpecification/Core/root.html
  src/ApiGenerator/RestSpecification/XPack/ml.delete_data_frame_analytics.json
  src/ApiGenerator/RestSpecification/XPack/root.html
  src/Elasticsearch.Net/Api/RequestParameters/RequestParameters.MachineLearning.cs
  src/Elasticsearch.Net/ElasticLowLevelClient.Indices.cs
Labels: Self Reviewed, v7.8.0

#4792 Change default ModelSnapshotRetentionDays
  tests/Tests/XPack/MachineLearning/GetJobs/GetJobsApiTests.cs
  tests/Tests/XPack/MachineLearning/MachineLearningInfo/MachineLearningInfoApiTests.cs
  tests/Tests/XPack/MachineLearning/PutJob/PutJobApiTests.cs
Labels: Flakey test, Self Reviewed, v7.8.0

#4789 Ignore ContainsMetadata field when automapping Attachment
  src/Nest/Mapping/Types/Specialized/Attachment/Attachment.cs
  src/Nest/Mapping/Visitor/NoopPropertyVisitor.cs
Labels: Bug, Self Reviewed, backport 7.8, backport 7.x, v7.8.0

#4798 Remove MapsApi from DeleteExpiredData overload
  src/Elasticsearch.Net/Patch.ElasticLowLevelClient.MachineLearning.cs
Labels: Self Reviewed, backport 7.8

#4801 Obsolete Clients property on HttpConnection
  src/Elasticsearch.Net/Connection/HttpConnection.cs
Labels: Self Reviewed, backport 7.8

#4799 Add .gitattributes
  .gitattributes
Labels: backport 7.8, backport 7.x

#4805 Use format that null_value conforms to
  tests/Tests/Mapping/Types/Core/Date/DateAttributeTests.cs
  tests/Tests/Mapping/Types/Core/Date/DatePropertyTests.cs
  tests/Tests/Mapping/Types/Core/DateNanos/DateNanosAttributeTests.cs
  tests/Tests/Mapping/Types/Core/DateNanos/DateNanosPropertyTests.cs
Labels: Flakey test, Self Reviewed, backport 7.8, backport 7.x, v7.8.1

#4814 Add effective max model memory limit to ML info
  src/Nest/XPack/MachineLearning/MachineLearningInfo/MachineLearningInfoResponse.cs
  tests/Tests/XPack/MachineLearning/MachineLearningInfo/MachineLearningInfoApiTests.cs
Labels: Feature, Self Reviewed, backport 7.8, backport 7.x, v7.8.1

#4804 Parent-Child Documentation: Fixed spelling error on "IndexResponse"
  docs/client-concepts/high-level/mapping/parent-child-relationships.asciidoc
  tests/Tests/ClientConcepts/HighLevel/Mapping/ParentChildRelationships.doc.cs
Labels: Docs, backport 7.8, backport 7.x

#4807 Do not wrap null ISourceFilter in Union
  src/Nest/Search/Search/SearchRequest.cs
  tests/Tests.Reproduce/GithubIssue4787.cs
Labels: Bug, Self Reviewed, backport 7.8, backport 7.x, v7.8.1

#4813 Add FailedCategoryCount to ModelSizeStats
  src/Nest/XPack/MachineLearning/Job/Config/JobStats.cs
  src/Nest/XPack/MachineLearning/Job/Process/ModelSizeStats.cs
Labels: Feature, Self Reviewed, backport 7.8, backport 7.x, v7.8.1

#4815 Add assigned node to OpenJob/StartDatafeed response
  src/Nest/XPack/MachineLearning/OpenJob/OpenJobResponse.cs
  src/Nest/XPack/MachineLearning/StartDatafeed/StartDatafeedResponse.cs
  tests/Tests/XPack/MachineLearning/OpenJob/OpenJobApiTests.cs
  tests/Tests/XPack/MachineLearning/StartDatafeed/StartDatafeedApiTests.cs
Labels: Feature, Self Reviewed, backport 7.8, backport 7.x, v7.8.1

#4806 Deserialize sort short forms
  src/Nest/CommonOptions/Sorting/SortFormatter.cs
  tests/Tests.Reproduce/GitHubIssue4797.cs
Labels: Bug, Self Reviewed, backport 7.8, backport 7.x, v7.8.1

#4812 Add DailyModelSnapshotRetentionAfterDays to ml jobs
  src/Nest/XPack/MachineLearning/Job/Config/Job.cs
  src/Nest/XPack/MachineLearning/MachineLearningInfo/MachineLearningInfoResponse.cs
  src/Nest/XPack/MachineLearning/PutJob/PutJobRequest.cs
  src/Nest/XPack/MachineLearning/UpdateJob/UpdateJobRequest.cs
  tests/Tests/XPack/MachineLearning/MachineLearningInfo/MachineLearningInfoApiTests.cs
Labels: Feature, Self Reviewed, backport 7.8, backport 7.x, v7.8.1

#4816 Add Indices and Aliases in BulkAlias API
  src/Nest/Indices/AliasManagement/Alias/Actions/AliasAdd.cs
  src/Nest/Indices/AliasManagement/Alias/Actions/AliasAddOperation.cs
  src/Nest/Indices/AliasManagement/Alias/Actions/AliasRemove.cs
  src/Nest/Indices/AliasManagement/Alias/Actions/AliasRemoveOperation.cs
  src/Nest/Indices/AliasManagement/Alias/Actions/IAliasAction.cs
  src/Nest/Indices/AliasManagement/Alias/BulkAliasRequest.cs
  tests/Tests/Indices/AliasManagement/Alias/AliasApiTests.cs
Labels: Feature, Self Reviewed, backport 7.8, backport 7.x, v7.8.1
