Repository elastic/elasticsearch-net, pull requests merged in 2020-01, with the labels that each got.

#4301 updates the .ci scripts to latest greatest
  .ci/run-elasticsearch.sh
  .ci/run-repository.sh
  .ci/run-tests
Labels: Infra, Port to 7.x

#4296 [DOCS] Fix search request body links
  docs/search/request/fields-usage.asciidoc
  docs/search/request/highlighting-usage.asciidoc
  docs/search/request/inner-hits-usage.asciidoc
  docs/search/request/script-fields-usage.asciidoc
  docs/search/request/source-filtering-usage.asciidoc
  tests/Tests/Search/Request/FieldsUsageTests.cs
  tests/Tests/Search/Request/HighlightingUsageTests.cs
  tests/Tests/Search/Request/InnerHitsUsageTests.cs
  tests/Tests/Search/Request/ScriptFieldsUsageTests.cs
  tests/Tests/Search/Request/SourceFilteringUsageTests.cs
Labels: Docs, Port to 7.x, v8.0.0

#4302 Documentation generation improvements
  .gitignore
  azure-pipelines.yml
  build/scripts/Commandline.fs
  build/scripts/Documentation.fs
  build/scripts/Paths.fs
  build/scripts/Targets.fs
  build/scripts/Tooling.fs
  src/DocGenerator/AsciiDoc/RawAsciidocVisitor.cs
  src/DocGenerator/Documentation/Files/DocumentationFile.cs
  src/DocGenerator/Documentation/Files/ImageDocumentationFile.cs
  src/DocGenerator/Documentation/Files/RawDocumentationFile.cs
  src/DocGenerator/LitUp.cs
  src/DocGenerator/Program.cs
Labels: Infra, Port to 7.x

#4303 [DOCS] [7.x] Fix search request body links (#4296)
  docs/search/request/fields-usage.asciidoc
  docs/search/request/highlighting-usage.asciidoc
  docs/search/request/inner-hits-usage.asciidoc
  docs/search/request/script-fields-usage.asciidoc
  docs/search/request/source-filtering-usage.asciidoc
  tests/Tests/Search/Request/FieldsUsageTests.cs
  tests/Tests/Search/Request/HighlightingUsageTests.cs
  tests/Tests/Search/Request/InnerHitsUsageTests.cs
  tests/Tests/Search/Request/ScriptFieldsUsageTests.cs
  tests/Tests/Search/Request/SourceFilteringUsageTests.cs
Labels: Docs

#4305 update doc_current and doc_branch when calling release
  build/scripts/Versioning.fs
  global.json
Labels: Docs, Port to 6.x, Port to master

#4309 Add run-repository powershell script
  .ci/run-elasticsearch.ps1
  .ci/run-repository.ps1
  .ci/run-tests.ps1
Labels: Infra, Port to 7.x

#4312 Several improvements to PostData
  docs/client-concepts/low-level/post-data.asciidoc
  src/Elasticsearch.Net/Transport/PostData.cs
  src/Elasticsearch.Net/Transport/SerializableData.cs
  src/Elasticsearch.Net/Transport/StreamableData.cs
  tests/Tests.Benchmarking/BenchmarkProgram.cs
  tests/Tests.Benchmarking/BulkBenchmarkLowLevelTests.cs
  tests/Tests.Benchmarking/BulkBenchmarkTests.cs
  tests/Tests.Benchmarking/Tests.Benchmarking.csproj
  tests/Tests/ClientConcepts/LowLevel/PostData.doc.cs
Labels: 7.6.0, Performance, Port to 7.x

#4313 Additional UTF8Json overloads, consolidate how we tell it to write/serialize.
  src/Elasticsearch.Net/Serialization/DiagnosticsSerializerProxy.cs
  src/Elasticsearch.Net/Serialization/ElasticsearchSerializerExtensions.cs
  src/Elasticsearch.Net/Serialization/IInternalSerializerWithFormatter.cs
  src/Elasticsearch.Net/Serialization/LowLevelRequestResponseSerializer.cs
  src/Elasticsearch.Net/Transport/PostData.cs
  src/Elasticsearch.Net/Utf8Json/IJsonFormatterResolver.cs
  src/Elasticsearch.Net/Utf8Json/Internal/UnsafeMemory.Low.cs
  src/Elasticsearch.Net/Utf8Json/JsonWriter.cs
  src/Elasticsearch.Net/Utf8Json/Resolvers/CompositeResolver.cs
  src/Nest/CommonAbstractions/Extensions/TypeExtensions.cs
  src/Nest/CommonAbstractions/SerializationBehavior/DefaultHighLevelSerializer.cs
  src/Nest/CommonAbstractions/SerializationBehavior/JsonFormatters/ProxyRequestFormatterBase.cs
  src/Nest/CommonAbstractions/SerializationBehavior/JsonFormatters/SourceFormatter.cs
  src/Nest/CommonAbstractions/SerializationBehavior/SourceValueWriteConverter.cs
  src/Nest/CommonAbstractions/SerializationBehavior/StatefulSerializerExtensions.cs
  src/Nest/Document/Multiple/Bulk/BulkRequestFormatter.cs
  src/Nest/Search/MultiSearch/MultiSearchFormatter.cs
  src/Nest/Search/MultiSearchTemplate/MultiSearchTemplateJsonConverter.cs
  src/Nest/XPack/MachineLearning/PostJobData/PostJobDataRequest.cs
  tests/Tests.Benchmarking/BulkBenchmarkLowLevelTests.cs
  tests/Tests.Core/Serialization/SerializationTester.cs
Labels: 7.6.0, Performance

#4314 Backport PostData performance fixes and new features
  docs/client-concepts/low-level/post-data.asciidoc
  src/Elasticsearch.Net/Serialization/DiagnosticsSerializerProxy.cs
  src/Elasticsearch.Net/Serialization/ElasticsearchSerializerExtensions.cs
  src/Elasticsearch.Net/Serialization/IInternalSerializerWithFormatter.cs
  src/Elasticsearch.Net/Serialization/LowLevelRequestResponseSerializer.cs
  src/Elasticsearch.Net/Transport/PostData.cs
  src/Elasticsearch.Net/Transport/SerializableData.cs
  src/Elasticsearch.Net/Transport/StreamableData.cs
  src/Elasticsearch.Net/Utf8Json/IJsonFormatterResolver.cs
  src/Elasticsearch.Net/Utf8Json/Internal/UnsafeMemory.Low.cs
  src/Elasticsearch.Net/Utf8Json/JsonWriter.cs
  src/Elasticsearch.Net/Utf8Json/Resolvers/CompositeResolver.cs
  src/Nest/CommonAbstractions/Extensions/TypeExtensions.cs
  src/Nest/CommonAbstractions/SerializationBehavior/DefaultHighLevelSerializer.cs
  src/Nest/CommonAbstractions/SerializationBehavior/JsonFormatters/ProxyRequestFormatterBase.cs
  src/Nest/CommonAbstractions/SerializationBehavior/JsonFormatters/SourceFormatter.cs
  src/Nest/CommonAbstractions/SerializationBehavior/SourceValueWriteConverter.cs
  src/Nest/CommonAbstractions/SerializationBehavior/StatefulSerializerExtensions.cs
  src/Nest/Document/Multiple/Bulk/BulkRequestFormatter.cs
  src/Nest/Search/MultiSearch/MultiSearchFormatter.cs
  src/Nest/Search/MultiSearchTemplate/MultiSearchTemplateJsonConverter.cs
  src/Nest/XPack/MachineLearning/PostJobData/PostJobDataRequest.cs
  tests/Tests.Benchmarking/BenchmarkProgram.cs
  tests/Tests.Benchmarking/BulkBenchmarkLowLevelTests.cs
  tests/Tests.Benchmarking/BulkBenchmarkTests.cs
  tests/Tests.Benchmarking/Tests.Benchmarking.csproj
  tests/Tests.Core/Serialization/SerializationTester.cs
  tests/Tests/ClientConcepts/LowLevel/PostData.doc.cs
Labels: 7.6.0, Performance

#4322 Handle StartObject or StartArray when reading QueryContainer collection
  src/Nest/QueryDsl/Abstractions/Container/QueryContainerJsonConverter.cs
  src/Tests/Tests.Reproduce/GitHubIssue4311.cs
Labels: Bug, v6.8.4

#4325 Add index setting method for index.blocks.read_only_allow_delete
  src/Nest/IndexModules/IndexSettings/Settings/DynamicIndexSettings.cs
  src/Nest/IndexModules/IndexSettings/Settings/IndexSettingsFormatter.cs
  src/Nest/IndexModules/IndexSettings/Settings/UpdatableIndexSettings.cs
  tests/Tests/IndexModules/IndexSettings/Settings/TypedIndexSettings.cs
Labels: Feature, Port to master, v7.6.0

#4320 Additional client examples
  examples/Aggregations/Bucket/TermsAggregationPage/028f6d6ac2594e20b78b8a8f8cbad49d.asciidoc
  examples/Aggregations/Bucket/TermsAggregationPage/033778305d52746f5ce0a2a922c8e521.asciidoc
  examples/Aggregations/Bucket/TermsAggregationPage/0afaf1cad692e6201aa574c8feb6e622.asciidoc
  examples/Aggregations/Bucket/TermsAggregationPage/34efeade38445b2834749ced59782e25.asciidoc
  examples/Aggregations/Bucket/TermsAggregationPage/35e8da9410b8432cf4095f2541ad7b1d.asciidoc
  examples/Aggregations/Bucket/TermsAggregationPage/4646764bf09911fee7d58630c72d3137.asciidoc
  examples/Aggregations/Bucket/TermsAggregationPage/527324766814561b75aaee853ede49a7.asciidoc
  examples/Aggregations/Bucket/TermsAggregationPage/5d9d7b84e2fec7ecd832145cbb951cf1.asciidoc
  examples/Aggregations/Bucket/TermsAggregationPage/6a4679531e64c492fce16dc12de6dcb0.asciidoc
  examples/Aggregations/Bucket/TermsAggregationPage/71b5b2ba9557d0f296ff2de91727d2f6.asciidoc
  examples/Aggregations/Bucket/TermsAggregationPage/774d715155cd13713e6e327adf6ce328.asciidoc
  examples/Aggregations/Bucket/TermsAggregationPage/7f28f8ae8fcdbd807dadde0b5b007a6d.asciidoc
  examples/Aggregations/Bucket/TermsAggregationPage/93f1bdd72e79827dcf9a34efa02fd977.asciidoc
  examples/Aggregations/Bucket/TermsAggregationPage/98b121bf47cebd85671a2cb519688d28.asciidoc
  examples/Aggregations/Bucket/TermsAggregationPage/9a8995fd31351045d99c78e40444c8ea.asciidoc
  examples/Aggregations/Bucket/TermsAggregationPage/a49169b4622918992411fab4ec48191b.asciidoc
  examples/Aggregations/Bucket/TermsAggregationPage/cd5bc5bf7cd58d7b1492c9c298b345f6.asciidoc
  examples/Aggregations/Bucket/TermsAggregationPage/d50a3835bf5795ac73e58906a3413544.asciidoc
  examples/Aggregations/Bucket/TermsAggregationPage/dc15e2373e5ecbe09b4ea0858eb63d47.asciidoc
  examples/Aggregations/Bucket/TermsAggregationPage/f085fb032dae56a3b104ab874eaea2ad.asciidoc
  examples/Docs/UpdateByQueryPage/4acf902c2598b2558f34f20c1744c433.asciidoc
  examples/Indices/CreateIndexPage/1c23507edd7a3c18538b68223378e4ab.asciidoc
  examples/Indices/CreateIndexPage/4d46dbb96125b27f46299547de9d8709.asciidoc
  examples/Indices/CreateIndexPage/4d56b179242fed59e3d6476f817b6055.asciidoc
  examples/Indices/CreateIndexPage/b9c5d7ca6ca9c6f747201f45337a4abf.asciidoc
  examples/Indices/CreateIndexPage/dfef545b1e2c247bafd1347e8e807ac1.asciidoc
  examples/Indices/CreateIndexPage/e5d2172b524332196cac0f031c043659.asciidoc
  examples/Indices/CreateIndexPage/fabe14480624a99e8ee42c7338672058.asciidoc
  examples/QueryDsl/BoolQueryPage/06afce2955f9094d96d27067ebca32e8.asciidoc
  examples/QueryDsl/BoolQueryPage/162b5b693b713f0bfab1209d59443c46.asciidoc
  examples/QueryDsl/BoolQueryPage/f70a54cd9a9f4811bf962e469f2ca2ea.asciidoc
  examples/QueryDsl/BoolQueryPage/fa88f6f5a7d728ec4f1d05244228cb09.asciidoc
  examples/QueryDsl/MatchQueryPage/0ac9916f47a2483b89c1416684af322a.asciidoc
  examples/QueryDsl/MatchQueryPage/5043b83a89091fa00edb341ddf7ba370.asciidoc
  examples/QueryDsl/MatchQueryPage/6138d6919f3cbaaf61e1092f817d295c.asciidoc
  examples/QueryDsl/MatchQueryPage/7f56755fb6c42f7e6203339a6d0cb6e6.asciidoc
  examples/QueryDsl/MatchQueryPage/e0d6e02b998bdea99c9c08dcc3630c5e.asciidoc
  examples/QueryDsl/MatchQueryPage/fa2fe60f570bd930d2891778c6efbfe6.asciidoc
  examples/QueryDsl/QueryStringQueryPage/ad6ea0c1e46712aa1fd6d3bfa0ec979e.asciidoc
  examples/QueryDsl/RangeQueryPage/4466d410e06712c63328de4db249e6da.asciidoc
  examples/QueryDsl/RangeQueryPage/5d13a71fa7fda73b15111803b1c7cfd3.asciidoc
  examples/QueryDsl/RangeQueryPage/97bcd92ef148312d41e69f0d18284327.asciidoc
  examples/Root/MappingPage/609260ad1d5998be2ca09ff1fe237efa.asciidoc
  examples/Root/MappingPage/71ba9033107882f61cdc3b32fc73568d.asciidoc
  examples/Root/MappingPage/99a52be903945b17e734a1d02a57e958.asciidoc
  examples/Root/MappingPage/d8b2a88b5eca99d3691ad3cd40266736.asciidoc
  examples/Root/SearchPage/014b788c879e4aaa1020672e45e25473.asciidoc
  examples/Root/SearchPage/189a921df2f5b1fe580937210ce9c1c2.asciidoc
  examples/Root/SearchPage/8acc1d67b152e7027e0f0e1a8b4b2431.asciidoc
  src/ExamplesGenerator/ExampleLocation.cs
  tests/Examples/Aggregations/Bucket/TermsAggregationPage.cs
  tests/Examples/Indices/CreateIndexPage.cs
  tests/Examples/QueryDsl/MatchQueryPage.cs
  tests/Examples/QueryDsl/RangeQueryPage.cs
Labels: Docs

#4323 Handle short form queries
  src/Nest/CommonAbstractions/SerializationBehavior/GenericJsonConverters/FromJson.cs
  src/Nest/QueryDsl/Abstractions/FieldName/FieldNameQueryJsonConverter.cs
  src/Tests/Tests/QueryDsl/FullText/Match/MatchUsageTests.cs
  src/Tests/Tests/QueryDsl/FullText/MatchPhrase/MatchPhraseUsageTests.cs
  src/Tests/Tests/QueryDsl/FullText/MatchPhrasePrefix/MatchPhrasePrefixUsageTests.cs
  src/Tests/Tests/QueryDsl/QueryDslUsageTestsBase.cs
  src/Tests/Tests/QueryDsl/TermLevel/Prefix/PrefixQueryUsageTests.cs
  src/Tests/Tests/QueryDsl/TermLevel/Term/TermQueryUsageTests.cs
Labels: Feature, v6.8.4

#4324 Handle short form queries
  src/Nest/QueryDsl/Abstractions/FieldName/FieldNameQueryFormatter.cs
  tests/Tests/QueryDsl/FullText/Match/MatchUsageTests.cs
  tests/Tests/QueryDsl/FullText/MatchBoolPrefix/MatchBoolPrefixUsageTests.cs
  tests/Tests/QueryDsl/FullText/MatchPhrase/MatchPhraseUsageTests.cs
  tests/Tests/QueryDsl/FullText/MatchPhrasePrefix/MatchPhrasePrefixUsageTests.cs
  tests/Tests/QueryDsl/QueryDslUsageTestsBase.cs
  tests/Tests/QueryDsl/TermLevel/Prefix/PrefixQueryUsageTests.cs
  tests/Tests/QueryDsl/TermLevel/Term/TermQueryUsageTests.cs
Labels: Feature, Port to master, v7.6.0
