Repository elastic/elasticsearch-net, pull requests merged in 2021-08, with the labels that each got.

#5930 Rename InvalidProductException to UnsupportedProductException
  src/Elasticsearch.Net/Transport/Pipeline/RequestPipeline.cs
  src/Elasticsearch.Net/Transport/Pipeline/UnsupportedProductException.cs
  tests/Tests/ClientConcepts/ProductCheckTests.cs
Labels: backport 7.x

#5932 Update compatibility matrix to reflect supported versions
  readme.md
Labels: Docs, backport master, backport 7.x

#5927 - then to than
  tests/Tests/ClientConcepts/HighLevel/Inference/FieldInference.doc.cs
Labels: Docs, backport 7.x, backport 7.14

#5935 [Backport 7.x] Fix docs - then to than
  docs/client-concepts/connection-pooling/product-checking/product-check-at-startup.asciidoc
  docs/client-concepts/high-level/inference/field-inference.asciidoc
  tests/Tests/ClientConcepts/HighLevel/Inference/FieldInference.doc.cs
Labels: Docs

#5940 Fix bug with case-sensitive header comparisions
  src/Elasticsearch.Net/Connection/HttpWebRequestConnection.cs
Labels: bug, backport 7.x, v7.14.1

#5947 Add guidance for using client in FaaS environments
  docs/client-concepts/connection/function-as-a-service-environments.asciidoc
  docs/client-concepts/high-level/getting-started.asciidoc
  docs/client-concepts/high-level/inference/field-inference.asciidoc
  docs/high-level.asciidoc
  tests/Tests/ClientConcepts/Connection/FunctionAsAServiceEnvironments.doc.cs
  tests/Tests/ClientConcepts/HighLevel/GettingStarted.doc.cs
  tests/Tests/high-level.asciidoc
Labels: Docs
