Repository elastic/elasticsearch-net, pull requests merged in 2021-03, with the labels that each got.

#5353 Add rollover API support for max_primary_shard_size
  src/Nest/Indices/IndexManagement/RolloverIndex/RolloverConditions.cs
  tests/Tests/Indices/IndexManagement/RolloverIndex/RolloverIndexApiTests.cs
Labels: Feature, backport 7.x, backport master, v7.12.0

#5354 Add frozen tier support to ILM phases
  src/Nest/XPack/Ilm/Phases.cs
Labels: Feature, backport 7.x, backport master, v7.12.0

#5360 Add network direction ingest processor
  src/Nest/Ingest/ProcessorFormatter.cs
  src/Nest/Ingest/Processors/NetworkDirectionProcessor.cs
  src/Nest/Ingest/ProcessorsDescriptor.cs
  tests/Tests/Ingest/ProcessorAssertions.cs
Labels: Feature, backport 7.x, backport master, v7.12.0

#5371 Unify most of our CI under github actions
  .ci/packages.lock.json
  .editorconfig
  .github/workflows/integration-jobs.yml
  .github/workflows/stale-jobs.yml
  .github/workflows/test-jobs.yml
  Directory.Build.props
  Elasticsearch.sln
  appveyor.yml
  azure-pipelines.yml
  build/scripts/Commandline.fs
  build/scripts/Targets.fs
  build/scripts/Testing.fs
  build/scripts/Tooling.fs
  build/scripts/packages.lock.json
  build/scripts/scripts.fsproj
  nuget.config
  src/ApiGenerator/packages.lock.json
  src/DocGenerator/packages.lock.json
  src/Elasticsearch.Net.VirtualizedCluster/packages.lock.json
  src/Elasticsearch.Net/packages.lock.json
  src/Nest.JsonNetSerializer/packages.lock.json
  src/Nest/packages.lock.json
  tests/.ci.runsettings
  tests/Tests.Benchmarking/Tests.Benchmarking.csproj
  tests/Tests.Benchmarking/packages.lock.json
  tests/Tests.ClusterLauncher/packages.lock.json
  tests/Tests.Configuration/packages.lock.json
  tests/Tests.Core/Tests.Core.csproj
  tests/Tests.Core/packages.lock.json
  tests/Tests.Domain/packages.lock.json
  tests/Tests.Reproduce/packages.lock.json
  tests/Tests.ScratchPad/packages.lock.json
  tests/Tests.YamlRunner/packages.lock.json
  tests/Tests/Tests.csproj
  tests/Tests/packages.lock.json
Labels: Infra, Refactoring, backport 7.12

#5380 Always include ReferenceAssemblies
  .ci/packages.lock.json
  Directory.Build.props
  build/scripts/packages.lock.json
  src/ApiGenerator/packages.lock.json
  src/DocGenerator/packages.lock.json
  tests/Tests.Benchmarking/packages.lock.json
  tests/Tests.ClusterLauncher/packages.lock.json
  tests/Tests.Configuration/packages.lock.json
  tests/Tests.Core/packages.lock.json
  tests/Tests.Domain/packages.lock.json
  tests/Tests.Reproduce/packages.lock.json
  tests/Tests.ScratchPad/packages.lock.json
  tests/Tests.YamlRunner/packages.lock.json
  tests/Tests/packages.lock.json
Labels: Infra, backport 7.12

#5383 Add max_analyzed_offset to highlight
  src/Nest/Search/Search/Highlighting/Highlight.cs
Labels: Feature, backport 7.x, backport master, v7.12.0

#5386 Update locked mode settings
  Directory.Build.props
  build/scripts/Building.fs
  build/scripts/Targets.fs
  build/scripts/Testing.fs
Labels: Infra, backport 7.x, backport master

#5382 [Backport master] Unify most of our CI under github actions
  .ci/packages.lock.json
  .editorconfig
  .github/workflows/integration-jobs.yml
  .github/workflows/stale-jobs.yml
  .github/workflows/test-jobs.yml
  Directory.Build.props
  Elasticsearch.sln
  appveyor.yml
  azure-pipelines.yml
  build/scripts/Commandline.fs
  build/scripts/Targets.fs
  build/scripts/Testing.fs
  build/scripts/Tooling.fs
  build/scripts/packages.lock.json
  build/scripts/scripts.fsproj
  nuget.config
  src/ApiGenerator/packages.lock.json
  src/DocGenerator/packages.lock.json
  src/Elasticsearch.Net/packages.lock.json
  src/ExamplesGenerator/packages.lock.json
  src/Nest.JsonNetSerializer/packages.lock.json
  src/Nest/packages.lock.json
  tests/.ci.runsettings
  tests/Directory.Build.props
  tests/Examples/packages.lock.json
  tests/Tests.Benchmarking/BulkBenchmarkTests.cs
  tests/Tests.Benchmarking/BulkCreationBenchmarkTests.cs
  tests/Tests.Benchmarking/Tests.Benchmarking.csproj
  tests/Tests.Benchmarking/packages.lock.json
  tests/Tests.ClusterLauncher/packages.lock.json
  tests/Tests.Configuration/packages.lock.json
  tests/Tests.Core/Tests.Core.csproj
  tests/Tests.Core/packages.lock.json
  tests/Tests.Domain/packages.lock.json
  tests/Tests.Reproduce/packages.lock.json
  tests/Tests.ScratchPad/packages.lock.json
  tests/Tests.YamlRunner/packages.lock.json
  tests/Tests/Tests.csproj
  tests/Tests/packages.lock.json
Labels: Infra

#5372 Add multi terms aggregation
  docs/aggregations.asciidoc
  docs/aggregations/bucket/multi-terms/multi-terms-aggregation-usage.asciidoc
  src/Nest/Aggregations/AggregateDictionary.cs
  src/Nest/Aggregations/AggregateFormatter.cs
  src/Nest/Aggregations/AggregationContainer.cs
  src/Nest/Aggregations/Bucket/MultiTerms/MultiTermsAggregate.cs
  src/Nest/Aggregations/Bucket/MultiTerms/MultiTermsAggregation.cs
  src/Nest/Aggregations/Bucket/MultiTerms/MultiTermsBucket.cs
  src/Nest/Aggregations/Bucket/MultiTerms/Term.cs
  src/Nest/Aggregations/Bucket/Terms/TermsInclude.cs
  src/Nest/Aggregations/Visitor/AggregationVisitor.cs
  src/Nest/Aggregations/Visitor/AggregationWalker.cs
  tests/Tests/Aggregations/Bucket/MultiTerms/MultiTermsAggregationUsageTests.cs
Labels: Feature, backport 7.x, backport master, v7.12.0

#5373 Add linear function to rank_feature query
  docs/query-dsl/specialized/rank-feature/rank-feature-query-usage.asciidoc
  src/Nest/QueryDsl/Specialized/RankFeature/RankFeatureQuery.cs
  tests/Tests/QueryDsl/Specialized/RankFeature/RankFeatureQueryUsageTests.cs
Labels: Feature, backport 7.x, backport master, v7.12.0

#5374 Add support for _shard_doc sort with pit
  src/Nest/Search/Search/Sort/FieldSort.cs
  src/Nest/Search/Search/Sort/SortSpecialField.cs
  tests/Tests/Search/PointInTime/PointInTimeApiTests.cs
  tests/Tests/Search/Request/SortUsageTests.cs
Labels: Feature, backport 7.x, backport master, v7.12.0

#5377 Support runtime fields on transforms
  src/Nest/XPack/Transform/TransformSource.cs
  tests/Tests/XPack/Transform/TransformApiWithSettingsTests.cs
Labels: Feature, backport 7.x, backport master, v7.12.0

#5364 Generate low level client code for 7.12
  .ci/test-matrix.yml
  src/ApiGenerator/Domain/ApiQueryParametersPatcher.cs
  src/ApiGenerator/RestSpecification/Core/indices.close.json
  src/ApiGenerator/RestSpecification/Core/search.json
  src/ApiGenerator/RestSpecification/Core/snapshot.get_features.json
  src/ApiGenerator/RestSpecification/XPack/autoscaling.delete_autoscaling_policy.json
  src/ApiGenerator/RestSpecification/XPack/autoscaling.get_autoscaling_capacity.json
  src/ApiGenerator/RestSpecification/XPack/autoscaling.get_autoscaling_policy.json
  src/ApiGenerator/RestSpecification/XPack/autoscaling.put_autoscaling_policy.json
  src/ApiGenerator/RestSpecification/XPack/eql.get_status.json
  src/ApiGenerator/RestSpecification/XPack/logstash.delete_pipeline.json
  src/ApiGenerator/RestSpecification/XPack/logstash.get_pipeline.json
  src/ApiGenerator/RestSpecification/XPack/logstash.put_pipeline.json
  src/ApiGenerator/RestSpecification/XPack/searchable_snapshots.mount.json
  src/ApiGenerator/RestSpecification/XPack/searchable_snapshots.stats.json
  src/ApiGenerator/RestSpecification/XPack/text_structure.find_structure.json
  src/ApiGenerator/last_downloaded_version.txt
  src/Elasticsearch.Net/Api/Enums.Generated.cs
  src/Elasticsearch.Net/Api/RequestParameters/RequestParameters.Eql.cs
  src/Elasticsearch.Net/Api/RequestParameters/RequestParameters.Indices.cs
  src/Elasticsearch.Net/Api/RequestParameters/RequestParameters.Logstash.cs
  src/Elasticsearch.Net/Api/RequestParameters/RequestParameters.MachineLearning.cs
  src/Elasticsearch.Net/Api/RequestParameters/RequestParameters.NoNamespace.cs
  src/Elasticsearch.Net/Api/RequestParameters/RequestParameters.SearchableSnapshots.cs
  src/Elasticsearch.Net/Api/RequestParameters/RequestParameters.Snapshot.cs
  src/Elasticsearch.Net/Api/RequestParameters/RequestParameters.TextStructure.cs
  src/Elasticsearch.Net/ElasticLowLevelClient.Autoscaling.cs
  src/Elasticsearch.Net/ElasticLowLevelClient.Eql.cs
  src/Elasticsearch.Net/ElasticLowLevelClient.Logstash.cs
  src/Elasticsearch.Net/ElasticLowLevelClient.MachineLearning.cs
  src/Elasticsearch.Net/ElasticLowLevelClient.NoNamespace.cs
  src/Elasticsearch.Net/ElasticLowLevelClient.Snapshot.cs
  src/Elasticsearch.Net/ElasticLowLevelClient.TextStructure.cs
  src/Elasticsearch.Net/IElasticLowLevelClient.Generated.cs
  tests/Tests.YamlRunner/Models.fs
  tests/Tests.YamlRunner/SkipList.fs
  tests/Tests.YamlRunner/TestsReader.fs
Labels: backport 7.x, code-gen, v7.12.0

#5378 Update get token response to include auth info
  src/Nest/XPack/Security/User/GetUserAccessToken/GetUserAccessTokenResponse.cs
  tests/Tests/XPack/Security/User/GetUserAccessToken/GetUserAccessTokenApiTests.cs
Labels: Feature, backport 7.x, backport master, v7.12.0

#5404 Handle "NaN" in sampling fields
  src/Nest/Aggregations/AggregateFormatter.cs
  src/Nest/Aggregations/Metric/ExtendedStats/ExtendedStatsAggregate.cs
Labels: Bug, backport 7.12, backport 7.x

#5409 Fix make assemble to produce zip
  .ci/make.sh
  .github/workflows/unified-release.yml
  build/scripts/Targets.fs
  build/scripts/scripts.fsproj
Labels: Infra, backport 7.12, backport 7.x

#5419 Fix namespace after backport
  src/Nest/Aggregations/Metric/ExtendedStats/ExtendedStatsAggregate.cs
Labels: Self Reviewed, backport 7.x

#5417 enhancement/ienumerable searchafter descriptor
  src/Nest/Search/Search/SearchRequest.cs
  tests/Tests/Search/Request/SearchAfterUsageTests.cs
Labels: backport 7.x, backport master, enhancement, v7.12.0

#5413 Add explicit stop method to Auditable
  src/Elasticsearch.Net/Auditing/Auditable.cs
  src/Elasticsearch.Net/Transport/Pipeline/RequestPipeline.cs
  tests/Tests.Reproduce/GitHubIssue5363.cs
Labels: Bug, backport 7.x, backport master, v7.12.0

#5402 Add variable width histogram aggregation
  docs/aggregations.asciidoc
  docs/aggregations/bucket/multi-terms/multi-terms-aggregation-usage.asciidoc
  docs/aggregations/bucket/variable-width-histogram/variable-width-histogram-usage.asciidoc
  src/Nest/Aggregations/AggregateDictionary.cs
  src/Nest/Aggregations/AggregateFormatter.cs
  src/Nest/Aggregations/AggregationContainer.cs
  src/Nest/Aggregations/Bucket/VariableWidthHistogram/VariableWidthHistogramAggregation.cs
  src/Nest/Aggregations/Bucket/VariableWidthHistogram/VariableWidthHistogramBucket.cs
  src/Nest/Aggregations/Visitor/AggregationVisitor.cs
  src/Nest/Aggregations/Visitor/AggregationWalker.cs
  tests/Tests/Aggregations/Bucket/MultiTerms/MultiTermsAggregationUsageTests.cs
  tests/Tests/Aggregations/Bucket/VariableWidthHistogram/VariableWidthHistogramUsageTests.cs
Labels: Feature, backport 7.x, backport master, v7.12.0

#5403 Add applications to get role response
  src/Nest/XPack/Security/Role/GetRole/Role.cs
Labels: Feature, backport 7.x, backport master, v7.12.0

#5412 Support case_insensitive on term-based queries
  src/Nest/QueryDsl/Span/Term/SpanTermQuery.cs
  src/Nest/QueryDsl/TermLevel/Prefix/PrefixQuery.cs
  src/Nest/QueryDsl/TermLevel/Term/TermQuery.cs
  src/Nest/QueryDsl/TermLevel/Wildcard/WildcardQuery.cs
  tests/Tests/QueryDsl/TermLevel/Term/TermQueryUsageTests.cs
Labels: Feature, backport 7.x, backport master, v7.12.0

#5429 Avoid global state in snapshot
  tests/Tests/Modules/SnapshotAndRestore/Snapshot/CoordinatedSnapshotTests.cs
Labels: Self Reviewed, backport 7.x, backport master, tests

#5435 Deserialise analyzers without a type
  src/Nest/Analysis/Analyzers/AnalyzerFormatter.cs
  tests/Tests.Reproduce/GitHubIssue5432.cs
Labels: Bug, backport 7.x, backport master, v7.12.0

#5444 Final code-gen for API changes
  src/ApiGenerator/RestSpecification/Core/features.get_features.json
  src/ApiGenerator/last_downloaded_version.txt
  src/Elasticsearch.Net/Api/RequestParameters/RequestParameters.Features.cs
  src/Elasticsearch.Net/Api/RequestParameters/RequestParameters.Snapshot.cs
  src/Elasticsearch.Net/ElasticLowLevelClient.Features.cs
  src/Elasticsearch.Net/ElasticLowLevelClient.NoNamespace.cs
  src/Elasticsearch.Net/ElasticLowLevelClient.Snapshot.cs
  src/Elasticsearch.Net/IElasticLowLevelClient.Generated.cs
Labels: Self Reviewed, code-gen, v7.12.0

#5445 Introduce automated scheduled codegeneration
  .ci/make.sh
  .github/workflows/make-codegen.yml
  build/scripts/Commandline.fs
  build/scripts/ReposTooling.fs
  build/scripts/Targets.fs
  build/scripts/scripts.fsproj
  src/ApiGenerator/Configuration/GeneratorLocations.cs
  src/ApiGenerator/Configuration/ViewLocations.cs
Labels: backport 7.11, backport 7.12, backport 7.x

#5450 Check the code generation workflow
  .ci/make.sh
  .github/workflows/make-codegen.yml
Labels: backport 7.11, backport 7.12, backport 7.x

#5459 Update DockerFile so that ownership of new files does not default to root
  .ci/DockerFile
  .ci/make.sh
  .ci/run-repository.sh
  .github/workflows/make-codegen.yml
  src/ApiGenerator/Configuration/GeneratorLocations.cs
  src/ApiGenerator/last_downloaded_version.txt
Labels: backport 7.11, backport 7.12, backport 7.x

#5461 move dotnet tool restore down after setting usr
  .ci/DockerFile
  .ci/make.sh
Labels: backport 7.11, backport 7.12, backport 7.x

#5468 Update code gen task to not rely on User in Dockerfile
  .ci/make.sh
  .github/workflows/make-codegen.yml
Labels: backport 7.11, backport 7.12, backport 7.x

#5462 Less flaky test assertions
  tests/Tests/Search/Search/SearchApiTests.cs
Labels: backport 7.x, backport master, tests, v7.12.1

#5467 Doc fixes for 7.x
  docs/client-concepts/low-level/getting-started.asciidoc
  docs/search/request/search-after-usage.asciidoc
  tests/Tests/ClientConcepts/LowLevel/GettingStarted.doc.cs
  tests/Tests/Search/Request/SearchAfterUsageTests.cs
Labels: Docs, Self Reviewed

#5478 Fixes the passing of args to assemble
  .ci/make.sh
  .github/workflows/unified-release.yml
Labels: Infra, backport 7.11, backport 7.12, backport 7.x

#5489 Update make.sh with skeleton from clients team
  .ci/make.sh
  build/scripts/Commandline.fs
  build/scripts/Targets.fs
Labels: Infra, backport 7.11, backport 7.12, backport 7.x

#5493 Create version bump automation
  .ci/make.sh
  .github/workflows/make-bump.yml
  build/scripts/Commandline.fs
  build/scripts/Targets.fs
  build/scripts/Versioning.fs
  build/scripts/scripts.fsproj
  dotnet-tools.json
Labels: Infra, backport 7.11, backport 7.12, backport 7.x
