Repository elastic/elasticsearch-net, pull requests merged in 2021-04, with the labels that each got.

#5499 Correct the JSON name for the position length on tokens
  src/Nest/Indices/Analyze/AnalyzeToken.cs
Labels: backport 7.11, backport 7.12, backport 7.x, v7.12.1

#5483 Move tests to rest-resources-zip.zip
  tests/Tests.YamlRunner/Commands.fs
  tests/Tests.YamlRunner/Program.fs
  tests/Tests.YamlRunner/SkipList.fs
  tests/Tests.YamlRunner/TestSuiteBootstrap.fs
  tests/Tests.YamlRunner/Tests.YamlRunner.fsproj
  tests/Tests.YamlRunner/TestsDownloader.fs
  tests/Tests.YamlRunner/TestsExporter.fs
  tests/Tests.YamlRunner/TestsLocator.fs
  tests/Tests.YamlRunner/TestsReader.fs
Labels: backport 7.x, tests

#5514 Add back missing CI jobs
  .ci/jobs/elastic+elasticsearch-net+6.x.yml
  .ci/jobs/elastic+elasticsearch-net+7.11.yml
  .gitignore
  tests/Tests.YamlRunner/SkipList.fs
Labels: Infra

#5513 Move tests to rest-resources-zip.zip (#5483)
  tests/Tests.YamlRunner/Commands.fs
  tests/Tests.YamlRunner/Program.fs
  tests/Tests.YamlRunner/SkipList.fs
  tests/Tests.YamlRunner/TestSuiteBootstrap.fs
  tests/Tests.YamlRunner/Tests.YamlRunner.fsproj
  tests/Tests.YamlRunner/TestsDownloader.fs
  tests/Tests.YamlRunner/TestsExporter.fs
  tests/Tests.YamlRunner/TestsLocator.fs
  tests/Tests.YamlRunner/TestsReader.fs
Labels: Infra, tests

#5520 Update .ci/run-elasticsearch.sh
  .ci/run-elasticsearch.ps1
  .ci/run-elasticsearch.sh
  tests/Tests.YamlRunner/SkipList.fs
Labels: Infra

#5521 Fix scheduled release notes generation
  .github/workflows/make-release-notes.yml
  .gitignore
Labels: Infra, backport 7.11, backport 7.x, backport master

#5527 Implement wipe cluster settings for YAML tests
  tests/Tests.YamlRunner/SkipList.fs
  tests/Tests.YamlRunner/TestSuiteBootstrap.fs
Labels: backport 7.11, backport 7.12, backport 7.x

#5530 Check _cleanupTimer is not null when disposing (backport fix/4818 to 6.x)
  src/Elasticsearch.Net/Connection/HandlerTracking/RequestDataHttpClientFactory.cs
Labels: Bug, v6.8.8

#5531 [Backport 7.x] Implement wipe cluster settings for YAML tests
  tests/Tests.YamlRunner/SkipList.fs
  tests/Tests.YamlRunner/TestSuiteBootstrap.fs
Labels: Infra, backport 7.11, backport 7.12

#5532 Skip ml.find_file_structure.json
  src/ApiGenerator/Configuration/CodeConfiguration.cs
Labels: backport 7.11, backport 7.12, code-gen

#5536 Fix up incorrectly removed endpoint in 7.11
  src/ApiGenerator/Configuration/CodeConfiguration.cs
  src/Elasticsearch.Net/Api/Enums.Generated.cs
  src/Elasticsearch.Net/Api/RequestParameters/RequestParameters.MachineLearning.cs
  src/Elasticsearch.Net/ElasticLowLevelClient.MachineLearning.cs
  tests/Tests.YamlRunner/SkipList.fs
Labels: code-gen

#5541 Add fallback when detected runtime version is invalid
  src/Elasticsearch.Net/Connection/MetaData/MetaDataHeader.cs
  src/Elasticsearch.Net/Connection/MetaData/RuntimeVersionInfo.cs
  src/Elasticsearch.Net/Connection/MetaData/VersionInfo.cs
  tests/Tests/Connection/MetaData/MetaHeaderProviderTests.cs
  tests/Tests/Connection/MetaData/VersionInfoTests.cs
Labels: Bug, backport 7.12, v7.12.1

#5546 Update RuntimeField to use IInlineScript
  src/Nest/CommonOptions/Scripting/InlineScript.cs
  src/Nest/Mapping/RuntimeFields/RuntimeField.cs
  tests/Tests/ClientConcepts/HighLevel/Mapping/FluentMapping.doc.cs
  tests/Tests/Indices/MappingManagement/PutMapping/PutMappingApiTest.cs
  tests/Tests/Mapping/RuntimeFields/RuntimeFieldsTests.cs
  tests/Tests/Search/Search/SearchApiTests.cs
  tests/Tests/Search/SearchingRuntimeFields.doc.cs
  tests/Tests/XPack/Transform/TransformApiWithSettingsTests.cs
Labels: Breaking, Bug, v7.13.0

#5488 Add NOTICE.txt for 7.x integration branches
  NOTICE.txt
Labels: backport 7.11, backport 7.12

#5547 Improve date histogram hard bounds test reliability on non-UTC systems
  tests/Tests/Aggregations/Bucket/DateHistogram/DateHistogramAggregationUsageTests.cs
Labels: Flakey test

#5550 [Backport 7.x] Improve reliability on non-UTC systems
  tests/Tests/Aggregations/Bucket/DateHistogram/DateHistogramAggregationUsageTests.cs
Labels: Flakey test, backport 7.11, backport master

#5560 Update generated documentation
  docs/client-concepts/connection/configuration-options.asciidoc
  docs/client-concepts/high-level/mapping/fluent-mapping.asciidoc
  docs/search/searching-runtime-fields.asciidoc
Labels: Docs

#5558 Fixes incorrect reference in documentation
  docs/client-concepts/high-level/serialization/custom-serialization.asciidoc
  tests/Tests/ClientConcepts/HighLevel/Serialization/CustomSerialization.doc.cs
Labels: Docs

#5563 [Api Generator] Add mechanism to escape C# keywords for path parts
  src/ApiGenerator/Domain/Code/LowLevel/LowLevelClientMethod.cs
  src/ApiGenerator/Domain/Specification/UrlPart.cs
  src/ApiGenerator/Domain/Specification/UrlPath.cs
  src/ApiGenerator/Extensions.cs
Labels: Infra, backport master, code-gen

#5564 [Docs Generator] Add step to preserve release notes folder during doc gen
  src/DocGenerator/LitUp.cs
Labels: Docs, Infra, backport 7.11, backport 7.12, backport master

#5576 [7.13] Add 7.13.0 to stack version matrix
  .github/workflows/integration-jobs.yml
Labels: Infra

#5574 [7.x] Add 7.13.0 to stack version matrix
  .github/workflows/integration-jobs.yml
Labels: Infra

#5572 Fix client exception message to avoid double period on .NET Framework
  src/Elasticsearch.Net/Transport/Pipeline/RequestPipeline.cs
Labels: Bug, backport 7.12, backport 7.13, v7.13.0

#5582 Catch exceptions when detecting runtime version
  src/Elasticsearch.Net/Connection/MetaData/RuntimeVersionInfo.cs
Labels: Bug, backport 7.12, backport 7.13, v7.12.2

#5587 Update docs in master
  docs/aggregations/bucket/multi-terms/multi-terms-aggregation-usage.asciidoc
  docs/search/request/search-after-usage.asciidoc
  tests/Tests/Search/Request/SearchAfterUsageTests.cs
Labels: Docs

#5588 Add IP type to convert processor
  src/Nest/Ingest/Processors/ConvertProcessor.cs
Labels: backport 7.x, backport master, v7.13.0

#5595 Extend ping timeout in EnableDebugMode test
  tests/Tests/ClientConcepts/Troubleshooting/DebugMode.doc.cs
Labels: Flakey test, backport 7.12, backport 7.x, backport master

#5599 Update status badges to use GitHub actions
  readme.md
Labels: Infra, backport 7.12, backport 7.13, backport 7.x

#5603 Support network direction processor additions
  src/Nest/Ingest/Processors/NetworkDirectionProcessor.cs
  tests/Tests/Ingest/ProcessorAssertions.cs
Labels: Feature, backport 7.x, backport master, v7.13.0

#5606 Support new queryable "_tier" metadata field
  src/Nest/Search/FieldCapabilities/FieldCapabilitiesResponse.cs
Labels: Feature, backport 7.x, backport master, v7.13.0

#5607 Add positive_score_impact to rank_features property
  src/Nest/Mapping/Types/Core/RankFeatures/RankFeaturesAttribute.cs
  src/Nest/Mapping/Types/Core/RankFeatures/RankFeaturesProperty.cs
Labels: Feature, backport 7.x, backport master, v7.13.0

#5610 Allow formatting of sort values
  src/Nest/Search/Search/Sort/SortBase.cs
  tests/Tests/Search/Search/SearchApiTests.cs
Labels: Feature, backport 7.x, backport master, v7.13.0

#5615 Skip service accounts YAML tests
  tests/Tests.YamlRunner/SkipList.fs
Labels: tests

#5616 Add registered domain ingest processor
  src/Nest/Ingest/ProcessorFormatter.cs
  src/Nest/Ingest/Processors/NetworkDirectionProcessor.cs
  src/Nest/Ingest/Processors/RegisteredDomainProcoessor.cs
  src/Nest/Ingest/ProcessorsDescriptor.cs
  tests/Tests/Ingest/ProcessorAssertions.cs
Labels: Feature, backport 7.x, backport master, v7.13.0

#5619 Add support for combined fields query
  src/Nest/QueryDsl/Abstractions/Container/IQueryContainer.cs
  src/Nest/QueryDsl/Abstractions/Container/QueryContainer-Assignments.cs
  src/Nest/QueryDsl/Abstractions/Container/QueryContainerDescriptor.cs
  src/Nest/QueryDsl/FullText/CombinedFields/CombinedFieldsQuery.cs
  src/Nest/QueryDsl/Query.cs
  src/Nest/QueryDsl/Visitor/DslPrettyPrintVisitor.cs
  src/Nest/QueryDsl/Visitor/QueryVisitor.cs
  src/Nest/QueryDsl/Visitor/QueryWalker.cs
  tests/Tests/QueryDsl/FullText/CombinedFields/CombinedFieldsUsageTests.cs
Labels: Feature, backport 7.x, backport master, v7.13.0

#5622 Support for calculated numeric fields
  src/Nest/CommonOptions/Scripting/OnScriptError.cs
  src/Nest/Mapping/Types/Core/Number/NumberAttribute.cs
  src/Nest/Mapping/Types/Core/Number/NumberProperty.cs
  tests/Tests/Mapping/Types/Core/Number/NumberPropertyTests.cs
Labels: Feature, backport 7.x, backport master, v7.13.0

#5627 Initial NEST code gen
  src/Nest/Descriptors.Cat.cs
  src/Nest/Descriptors.Cluster.cs
  src/Nest/Descriptors.Indices.cs
  src/Nest/Descriptors.Ingest.cs
  src/Nest/Descriptors.MachineLearning.cs
  src/Nest/Descriptors.NoNamespace.cs
  src/Nest/Descriptors.Nodes.cs
  src/Nest/Descriptors.Snapshot.cs
  src/Nest/ElasticClient.Cluster.cs
  src/Nest/ElasticClient.MachineLearning.cs
  src/Nest/Requests.Cat.cs
  src/Nest/Requests.Cluster.cs
  src/Nest/Requests.Indices.cs
  src/Nest/Requests.Ingest.cs
  src/Nest/Requests.MachineLearning.cs
  src/Nest/Requests.NoNamespace.cs
  src/Nest/Requests.Nodes.cs
  src/Nest/Requests.Snapshot.cs
  src/Nest/Requests.cs
  tests/Tests/XPack/MachineLearning/PreviewDataFeed/PreviewDataFeedApiTests.cs
  tests/Tests/XPack/MachineLearning/PreviewDataFeed/PreviewDataFeedUrlTests.cs
Labels: backport 7.x, code-gen

#5624 Support runtime mappings for SQL
  src/Nest/Mapping/RuntimeFields/RuntimeFields.cs
  src/Nest/XPack/Sql/ISqlRequest.cs
  src/Nest/XPack/Sql/QuerySql/QuerySqlRequest.cs
  src/Nest/XPack/Sql/TranslateSql/TranslateSqlRequest.cs
  tests/Tests/XPack/Sql/QuerySql/QuerySqlApiTests.cs
Labels: Feature, backport 7.x, backport master, v7.13.0

#5633 Add migrate to data stream API in NEST
  src/Nest/Descriptors.Indices.cs
  src/Nest/ElasticClient.Indices.cs
  src/Nest/Requests.Indices.cs
  src/Nest/XPack/DataStreams/Migrate/MigrateToDataStreamRequest.cs
  src/Nest/XPack/DataStreams/Migrate/MigrateToDataStreamResponse.cs
  src/Nest/_Generated/ApiUrlsLookup.generated.cs
  tests/Tests/XPack/DataStreams/DataStreamsApiTests.cs
  tests/Tests/XPack/DataStreams/Migrate/MigrateToDataStreamUrlTests.cs
Labels: Feature, backport 7.x, backport master, v7.13.0

#5636 Add promote data stream API to NEST
  src/Nest/Descriptors.Indices.cs
  src/Nest/ElasticClient.Indices.cs
  src/Nest/Requests.Indices.cs
  src/Nest/XPack/DataStreams/Promote/PromoteDataStreamRequest.cs
  src/Nest/XPack/DataStreams/Promote/PromoteDataStreamResponse.cs
  src/Nest/_Generated/ApiUrlsLookup.generated.cs
  tests/Tests/XPack/DataStreams/Promote/PromoteDataStreamUrlTests.cs
Labels: Feature, backport 7.x, backport master, v7.13.0

#5643 Update license header
  src/ApiGenerator/Views/GeneratorNotice.cshtml
Labels: backport 7.13, backport master, code-gen

#5649 Tweak license header scripts
  .github/add-license-headers.sh
  .github/license-header.txt
Labels: Infra, backport 7.13, backport master

#5648 Skip ENV VAR tests for compatibility header on <7.13.0 and run in intrusive operation cluster
  tests/Tests/ClientConcepts/Connection/HttpConnectionTests.cs
Labels: Flakey test, backport 7.13

#5656 [Backport 7.13] Skip service accounts YAML tests (#5615)
  tests/Tests.YamlRunner/SkipList.fs
Labels: backport 7.x, tests
