Repository elastic/elasticsearch-net, pull requests merged in 2021-06, with the labels that each got.

#5718 Add NuGet.org to package sources
  nuget.config
Labels: Infra, backport 7.13

#5729 Reorder cleanup steps for YAML tests
  tests/Tests.YamlRunner/TestSuiteBootstrap.fs
Labels: backport master, tests

#5733 Fix typo and regen documentation
  docs/query-dsl.asciidoc
  docs/query-dsl/full-text/combined-fields/combined-fields-usage.asciidoc
  docs/query-dsl/term-level/terms/terms-query-usage.asciidoc
  tests/Tests/QueryDsl/TermLevel/Terms/TermsQueryUsageTests.cs
Labels: Docs

#5731 [Backport 7.x] NameValueCollection.ToQueryString performance optimisation
  src/Elasticsearch.Net.VirtualizedCluster/packages.lock.json
  src/Elasticsearch.Net/Elasticsearch.Net.csproj
  src/Elasticsearch.Net/Extensions/NameValueCollectionExtensions.cs
  src/Elasticsearch.Net/packages.lock.json
  src/Nest.JsonNetSerializer/packages.lock.json
  src/Nest/packages.lock.json
  tests/Tests.Core/packages.lock.json
  tests/Tests.Domain/packages.lock.json
  tests/Tests/Extensions/NameValueCollectionExtensionsTests.cs
Labels: Performance, v7.14.0

#5691 Fix ReSharper's "Convert 'as' expression type check and the following…
  src/DocGenerator/XmlDocs/XmlDocsVisitor.cs
  src/Nest/QueryDsl/MultiTermQueryRewrite/RewriteMultiTerm.cs
  src/Nest/XPack/Security/RoleMapping/Rules/Role/RoleMappingRuleBase.cs
  src/Nest/XPack/Watcher/Action/Actions.cs
Labels: Cleanup

#5735 Skip MIME type validation when no body
  src/Elasticsearch.Net/Transport/Pipeline/ResponseBuilder.cs
  tests/Tests.Reproduce/GitHubIssue5730.cs
Labels: bug, v7.13.1

#5737 Adjust delete alias test to specify the index
  tests/Tests/Indices/AliasManagement/DeleteAlias/AliasDeleteApiTests.cs
Labels: backport master, tests

#5739 Update integration test matrix
  .github/workflows/integration-jobs.yml
Labels: Infra

#5740 Change default IMemoryStreamFactory
  docs/release-notes/release-notes-7.14.0-human.asciidoc
  src/Elasticsearch.Net/Configuration/ConnectionConfiguration.cs
Labels: enhancement, v7.14.0

#5743 Fix weekly schedule deserialisation
  src/Nest/XPack/Watcher/Schedule/Day.cs
  src/Nest/XPack/Watcher/Watch.cs
  tests/Tests/XPack/Watcher/PutWatch/PutWatchApiTests.cs
  tests/Tests/XPack/Watcher/WatcherCluster.cs
  tests/Tests/XPack/Watcher/WatcherCoordinatedTests.cs
Labels: backport master, bug, v7.14.0

#5750 [6.x] Switch default memory stream factory
  azure-pipelines.yml
  src/Elasticsearch.Net/Configuration/ConnectionConfiguration.cs
  src/Elasticsearch.Net/Configuration/IConnectionConfigurationValues.cs
  src/Elasticsearch.Net/Providers/MemoryStreamFactory.cs
  src/Elasticsearch.Net/Providers/RecyclableMemoryStreamFactory.cs
Labels: Performance, enhancement, v6.8.9

#5723 Update editor config naming rules
  .editorconfig
Labels: backport 7.x

#5755 Add readonly property to FS repository settings
  src/Nest/Modules/SnapshotAndRestore/Repositories/FileSystemRepository.cs
  tests/Tests/Modules/SnapshotAndRestore/Repositories/RepositoryCrudTests.cs
Labels: backport master, enhancement, v7.14.0

#5763 Remove deprecated type property from GeoBoundingBox
  src/Nest/QueryDsl/Geo/BoundingBox/GeoBoundingBoxQuery.cs
  src/Nest/QueryDsl/Geo/BoundingBox/GeoExecution.cs
  tests/Tests/QueryDsl/Geo/BoundingBox/GeoBoundingBoxQueryUsageTests.cs
Labels: tests, v8.0.0-alpha1

#5764 Disable GeoIP database
  .ci/run-elasticsearch.ps1
  .ci/run-elasticsearch.sh
Labels: backport master, tests

#5766 Skip analytics histogram failing YAML test
  tests/Tests.YamlRunner/SkipList.fs
Labels: tests
