Repository elastic/elasticsearch-net, pull requests merged in 2021-02, with the labels that each got.

#5290 Update CI
  .ci/functions/imports.sh
  .ci/readme.md
  .ci/run-elasticsearch.ps1
  .ci/run-elasticsearch.sh
  .ci/run-repository.sh
  .ci/run-tests.ps1
  .ci/test-matrix.yml
Labels: Infra

#5287 Update CI scripts
  .ci/functions/imports.sh
  .ci/readme.md
  .ci/run-elasticsearch.ps1
  .ci/run-elasticsearch.sh
  .ci/run-repository.sh
  .ci/run-tests.ps1
  .ci/test-matrix.yml
Labels: Infra, backport 7.x

#5294 Fix size overflow in StringToDoubleConverter
  src/Elasticsearch.Net/Utf8Json/Internal/DoubleConversion/StringToDoubleConverter.cs
Labels: Bug, backport 7.11, backport master, v7.11.0

#5293 Optimise RouteValues
  src/Nest/CommonAbstractions/Request/RouteValues.cs
  src/Nest/Document/Single/Index/IndexRequest.cs
Labels: backport master, v7.12.0

#5296 Update YAML tests and SDK Docker image
  .ci/DockerFile
  tests/Tests.YamlRunner/Models.fs
  tests/Tests.YamlRunner/OperationExecutor.fs
  tests/Tests.YamlRunner/Program.fs
  tests/Tests.YamlRunner/TestSuiteBootstrap.fs
  tests/Tests.YamlRunner/TestsDownloader.fs
  tests/Tests.YamlRunner/TestsRunner.fs
Labels: Infra, backport 7.x, backport master

#5302 [Backport 6.x] Implement meta header for client requests
  docs/client-concepts/connection/configuration-options.asciidoc
  src/Elasticsearch.Net/Configuration/ConnectionConfiguration.cs
  src/Elasticsearch.Net/Configuration/IConnectionConfigurationValues.cs
  src/Elasticsearch.Net/Configuration/RequestConfiguration.cs
  src/Elasticsearch.Net/Configuration/RequestConfigurationExtensions.cs
  src/Elasticsearch.Net/Configuration/RequestMetaData.cs
  src/Elasticsearch.Net/Connection/ConnectionInfo.cs
  src/Elasticsearch.Net/Connection/HttpConnection-CoreFx.cs
  src/Elasticsearch.Net/Connection/HttpWebRequestConnection.cs
  src/Elasticsearch.Net/Connection/MetaData/ClientVersionInfo.cs
  src/Elasticsearch.Net/Connection/MetaData/MetaDataHeader.cs
  src/Elasticsearch.Net/Connection/MetaData/MetaHeaderProvider.cs
  src/Elasticsearch.Net/Connection/MetaData/RuntimeVersionInfo.cs
  src/Elasticsearch.Net/Connection/MetaData/VersionInfo.cs
  src/Elasticsearch.Net/Domain/RequestParameters/RequestParametersExtensions.cs
  src/Elasticsearch.Net/Extensions/Extensions.cs
  src/Elasticsearch.Net/Transport/Pipeline/RequestData.cs
  src/Nest/Document/Multiple/BulkAll/BulkAllObservable.cs
  src/Nest/Document/Multiple/BulkAll/BulkAllRequest.cs
  src/Nest/Document/Multiple/Reindex/ReindexObservable.cs
  src/Nest/Document/Multiple/ScrollAll/ScrollAllObservable.cs
  src/Nest/Document/Multiple/ScrollAll/ScrollAllRequest.cs
  src/Nest/Helpers/HelperIdentifiers.cs
  src/Nest/Helpers/IHelperCallable.cs
  src/Nest/Helpers/RequestMetaDataExtensions.cs
  src/Nest/Modules/SnapshotAndRestore/Restore/RestoreObservable/RestoreObservable.cs
  src/Nest/Modules/SnapshotAndRestore/Snapshot/SnapshotObservable/SnapshotObservable.cs
  src/Tests/Tests/ClientConcepts/Connection/HttpConnectionTests.cs
  src/Tests/Tests/Connection/MetaData/MetaHeaderHelperTests.cs
  src/Tests/Tests/Connection/MetaData/MetaHeaderProviderTests.cs
  src/Tests/Tests/Connection/MetaData/VersionInfoTests.cs
  src/Tests/Tests/Search/Request/SortUsageTests.cs
Labels: Feature, v6.8.7

#5310 Update docs
  docs/aggregations/metric/geo-line/geo-line-aggregation-usage.asciidoc
  docs/aggregations/metric/rate/rate-aggregation-usage.asciidoc
  docs/client-concepts/high-level/mapping/fluent-mapping.asciidoc
  docs/high-level.asciidoc
  docs/search/searching-runtime-fields.asciidoc
Labels: Docs

#5309 Update stale docs
  docs/client-concepts/high-level/mapping/fluent-mapping.asciidoc
  docs/high-level.asciidoc
Labels: Docs, Self Reviewed

#5306 Add missing integration test versions
  .ci/make.sh
  .ci/readme.md
  .ci/run-repository.ps1
  .ci/run-repository.sh
  .ci/run-tests.ps1
  .ci/test-matrix.yml
  appveyor.yml
  azure-pipelines.yml
Labels: Infra, tests

#5307 Update SDK to latest patch
  .ci/make.sh
  .ci/readme.md
  .ci/run-repository.ps1
  .ci/run-repository.sh
  .ci/run-tests.ps1
  .ci/test-matrix.yml
  appveyor.yml
  azure-pipelines.yml
Labels: Infra, tests

#5308 Update stale docs
  docs/aggregations/metric/geo-line/geo-line-aggregation-usage.asciidoc
  docs/aggregations/metric/rate/rate-aggregation-usage.asciidoc
  docs/client-concepts/high-level/mapping/fluent-mapping.asciidoc
  docs/high-level.asciidoc
  docs/search/searching-runtime-fields.asciidoc
Labels: Docs

#5313 Skip cat template YAML test
  tests/Tests.YamlRunner/SkipList.fs
Labels: backport 7.x, backport master, tests

#5315 Fix parsing of some yaml tests on master
  tests/Tests.YamlRunner/Models.fs
  tests/Tests.YamlRunner/SkipList.fs
  tests/Tests.YamlRunner/TestsReader.fs
Labels: Bug, tests

#5317 Support multiple expand_wildcards
  src/Nest/XPack/Watcher/Input/ExpandWildcardsFormatter.cs
  src/Nest/XPack/Watcher/Input/IndicesOptions.cs
  tests/Tests/XPack/Watcher/GetWatch/GetWatchApiTests.cs
  tests/Tests/XPack/Watcher/PutWatch/PutWatchApiTests.cs
Labels: Breaking, Feature, backport 7.x, backport master

#5320 Reintroduce set for JsonParsingException.ActualChar (#5090)
  src/Elasticsearch.Net/Utf8Json/JsonReader.cs
Labels: Self Reviewed, backport 7.x

#5323 Regnerate low-level client code on master
  src/ApiGenerator/RestSpecification/Core/search.json
  src/ApiGenerator/RestSpecification/XPack/autoscaling.delete_autoscaling_policy.json
  src/ApiGenerator/RestSpecification/XPack/autoscaling.get_autoscaling_capacity.json
  src/ApiGenerator/RestSpecification/XPack/autoscaling.get_autoscaling_policy.json
  src/ApiGenerator/RestSpecification/XPack/autoscaling.put_autoscaling_policy.json
  src/ApiGenerator/RestSpecification/XPack/logstash.delete_pipeline.json
  src/ApiGenerator/RestSpecification/XPack/logstash.get_pipeline.json
  src/ApiGenerator/RestSpecification/XPack/logstash.put_pipeline.json
  src/ApiGenerator/RestSpecification/XPack/searchable_snapshots.mount.json
  src/ApiGenerator/RestSpecification/XPack/searchable_snapshots.stats.json
  src/ApiGenerator/RestSpecification/XPack/text_structure.find_structure.json
  src/ApiGenerator/last_downloaded_version.txt
  src/Elasticsearch.Net/Api/Enums.Generated.cs
  src/Elasticsearch.Net/Api/RequestParameters/RequestParameters.Logstash.cs
  src/Elasticsearch.Net/Api/RequestParameters/RequestParameters.MachineLearning.cs
  src/Elasticsearch.Net/Api/RequestParameters/RequestParameters.NoNamespace.cs
  src/Elasticsearch.Net/Api/RequestParameters/RequestParameters.SearchableSnapshots.cs
  src/Elasticsearch.Net/Api/RequestParameters/RequestParameters.TextStructure.cs
  src/Elasticsearch.Net/ElasticLowLevelClient.Autoscaling.cs
  src/Elasticsearch.Net/ElasticLowLevelClient.Logstash.cs
  src/Elasticsearch.Net/ElasticLowLevelClient.MachineLearning.cs
  src/Elasticsearch.Net/ElasticLowLevelClient.NoNamespace.cs
  src/Elasticsearch.Net/ElasticLowLevelClient.TextStructure.cs
  src/Elasticsearch.Net/IElasticLowLevelClient.Generated.cs
Labels: code-gen

#5322 Add data_frozen node role
  src/Nest/Cluster/NodesInfo/NodeRole.cs
Labels: Feature, backport master, v7.12.0

#5325 Update versions matrix for Azure Pipelines
  azure-pipelines.yml
Labels: Infra

#5326 Fix Client Diagnostics following upgrade to DiagnosticSource 5.0.0
  src/Elasticsearch.Net/Diagnostics/Diagnostic.cs
Labels: Bug, backport 7.11

#5304 Implement URI parts ingest processor
  src/Nest/Ingest/ProcessorFormatter.cs
  src/Nest/Ingest/Processors/UriPartsProcessor.cs
  src/Nest/Ingest/ProcessorsDescriptor.cs
  tests/Tests/Ingest/ProcessorAssertions.cs
Labels: Feature, backport master, v7.12.0

#5330 Bump testing abstraction and fix cluster run command
  build/scripts/Paths.fs
  build/scripts/ReposTooling.fs
  build/scripts/scripts.fsproj
  nuget.config
  tests/Tests.ClusterLauncher/ClusterLaunchProgram.cs
  tests/Tests.Configuration/Tests.Configuration.csproj
  tests/Tests.Core/Tests.Core.csproj
  tests/Tests.Domain/Tests.Domain.csproj
Labels: backport 7.11, backport master

#5340 Update abstractions dependencies
  build/scripts/scripts.fsproj
  tests/Tests.Configuration/Tests.Configuration.csproj
  tests/Tests.Core/Tests.Core.csproj
  tests/Tests.Domain/Tests.Domain.csproj
Labels: Infra, backport 7.12, backport 7.x

#5342 Update code gen for master with latest APIs
  src/ApiGenerator/RestSpecification/Core/snapshot.get_features.json
  src/ApiGenerator/RestSpecification/XPack/eql.get_status.json
  src/ApiGenerator/RestSpecification/XPack/ml.delete_trained_model_alias.json
  src/ApiGenerator/RestSpecification/XPack/ml.put_trained_model_alias.json
  src/ApiGenerator/last_downloaded_version.txt
  src/Elasticsearch.Net/Api/RequestParameters/RequestParameters.Eql.cs
  src/Elasticsearch.Net/Api/RequestParameters/RequestParameters.MachineLearning.cs
  src/Elasticsearch.Net/Api/RequestParameters/RequestParameters.Snapshot.cs
  src/Elasticsearch.Net/ElasticLowLevelClient.Eql.cs
  src/Elasticsearch.Net/ElasticLowLevelClient.MachineLearning.cs
  src/Elasticsearch.Net/ElasticLowLevelClient.Snapshot.cs
Labels: Self Reviewed, code-gen

#5345 Add Fingerprint ingest processor
  src/Nest/Ingest/ProcessorFormatter.cs
  src/Nest/Ingest/Processors/FingerprintProcessor.cs
  src/Nest/Ingest/ProcessorsDescriptor.cs
  tests/Tests/Ingest/ProcessorAssertions.cs
Labels: Feature, backport 7.x, backport master, v7.12.0

#5341 Update Jenkins for 7.12
  .ci/jobs/elastic+elasticsearch-net+7.10.yml
  .ci/jobs/elastic+elasticsearch-net+7.12.yml
Labels: Infra

#5338 Add architecture stats to cluster node stats
  src/Nest/Cluster/ClusterStats/ClusterNodesStats.cs
  tests/Tests/Cluster/ClusterStats/ClusterStatsApiTests.cs
Labels: Feature, backport 7.x, backport master, v7.12.0

#5303 Adds back additional information when running our tests
  tests/Tests.Core/Client/Settings/TestConnectionSettings.cs
  tests/Tests.Core/Xunit/NestXunitRunOptions.cs
Labels: Feature, backport 7.12, backport 7.x

#5355 Update Azure Pipelines VMs to latest
  .ci/DockerFile
  .ci/make.sh
  .ci/readme.md
  .ci/run-repository.ps1
  .ci/run-repository.sh
  .ci/run-tests.ps1
  .ci/test-matrix.yml
  appveyor.yml
  azure-pipelines.yml
  build/scripts/Commandline.fs
  build/scripts/Testing.fs
  build/scripts/Tooling.fs
Labels: Infra, backport 7.12, backport master

#5347 Add network community ID ingest processor
  src/Nest/Ingest/ProcessorFormatter.cs
  src/Nest/Ingest/Processors/NetworkCommunityIdProcessor.cs
  src/Nest/Ingest/ProcessorsDescriptor.cs
  tests/Tests/Ingest/ProcessorAssertions.cs
Labels: Feature, backport 7.x, backport master, v7.12.0

#5361 Fix incorrect model for cluster stats
  src/Nest/Cluster/ClusterStats/ClusterNodesStats.cs
  tests/Tests/Cluster/ClusterStats/ClusterStatsApiTests.cs
Labels: Self Reviewed, backport 7.x
