Repository elastic/elasticsearch-net, pull requests merged in 2021-01, with the labels that each got.

#5228 Fix deserialisation of aggs in Translate response
  src/Nest/Aggregations/AggregationContainer.cs
  src/Nest/Search/Search/SearchRequest.cs
  tests/Tests.Reproduce/GithubIssue5201.cs
Labels: Bug, backport 7.x, backport master, v7.11.0

#5230 Support mapping runtime fields
  src/Nest/Indices/MappingManagement/PutMapping/PutMappingRequest.cs
  src/Nest/Mapping/Mappings.cs
  src/Nest/Mapping/RuntimeFields/RuntimeField.cs
  src/Nest/Mapping/RuntimeFields/RuntimeFields.cs
  src/Nest/Mapping/TypeMapping.cs
  src/Nest/Search/Search/SearchRequest.cs
  tests/Tests/Indices/MappingManagement/PutMapping/PutMappingApiTest.cs
  tests/Tests/Mapping/RuntimeFields/RuntimeFieldsTests.cs
Labels: Feature, backport 7.x, backport master, v7.11.0

#5225 Generate initial 7.11 NEST code
  src/ApiGenerator/Views/HighLevel/Descriptors/Descriptor.cshtml
  src/ApiGenerator/last_downloaded_version.txt
  src/Nest/Descriptors.Cat.cs
  src/Nest/Descriptors.Indices.cs
  src/Nest/Descriptors.MachineLearning.cs
  src/Nest/Descriptors.Transform.cs
  src/Nest/Requests.Cat.cs
  src/Nest/Requests.Indices.cs
  src/Nest/Requests.MachineLearning.cs
  src/Nest/Requests.Tasks.cs
  src/Nest/Requests.Transform.cs
Labels: Feature, v7.11.0

#5190 Add metadata header on requests
  docs/client-concepts/connection/configuration-options.asciidoc
  src/Elasticsearch.Net/Api/RequestParameters/RequestParametersExtensions.cs
  src/Elasticsearch.Net/Configuration/ConnectionConfiguration.cs
  src/Elasticsearch.Net/Configuration/IConnectionConfigurationValues.cs
  src/Elasticsearch.Net/Configuration/RequestConfiguration.cs
  src/Elasticsearch.Net/Configuration/RequestConfigurationExtensions.cs
  src/Elasticsearch.Net/Configuration/RequestMetaData.cs
  src/Elasticsearch.Net/Connection/ConnectionInfo.cs
  src/Elasticsearch.Net/Connection/HttpConnection.cs
  src/Elasticsearch.Net/Connection/HttpWebRequestConnection.cs
  src/Elasticsearch.Net/Connection/MetaData/ClientVersionInfo.cs
  src/Elasticsearch.Net/Connection/MetaData/MetaDataHeader.cs
  src/Elasticsearch.Net/Connection/MetaData/MetaHeaderProvider.cs
  src/Elasticsearch.Net/Connection/MetaData/RuntimeVersionInfo.cs
  src/Elasticsearch.Net/Connection/MetaData/VersionInfo.cs
  src/Elasticsearch.Net/Transport/Pipeline/RequestData.cs
  src/Nest/Document/Multiple/BulkAll/BulkAllObservable.cs
  src/Nest/Document/Multiple/BulkAll/BulkAllRequest.cs
  src/Nest/Document/Multiple/Reindex/ReindexObservable.cs
  src/Nest/Document/Multiple/Reindex/ReindexRequest.cs
  src/Nest/Document/Multiple/ScrollAll/ScrollAllObservable.cs
  src/Nest/Document/Multiple/ScrollAll/ScrollAllRequest.cs
  src/Nest/Helpers/HelperIdentifiers.cs
  src/Nest/Helpers/IHelperCallable.cs
  src/Nest/Helpers/RequestMetaDataExtensions.cs
  src/Nest/Modules/SnapshotAndRestore/Restore/RestoreObservable/RestoreObservable.cs
  src/Nest/Modules/SnapshotAndRestore/Snapshot/SnapshotObservable/SnapshotObservable.cs
  tests/Tests/ClientConcepts/Connection/HttpConnectionTests.cs
  tests/Tests/Connection/MetaData/MetaHeaderProviderTests.cs
  tests/Tests/Connection/MetaData/VersionInfoTests.cs
  tests/Tests/MetaHeader/MetaHeaderHelperTests.cs
Labels: Feature, backport 7.x, v7.11.0

#5237 Fix version and line break for obsolete attribute
  src/ApiGenerator/Views/HighLevel/Descriptors/Descriptor.cshtml
Labels: Infra, Self Reviewed

#5206 Add support for rate aggregation
  docs/aggregations.asciidoc
  docs/aggregations/metric/rate/rate-aggregation-usage.asciidoc
  src/Nest/Aggregations/AggregateDictionary.cs
  src/Nest/Aggregations/AggregationContainer.cs
  src/Nest/Aggregations/Metric/Rate/RateAggregation.cs
  src/Nest/Aggregations/Visitor/AggregationVisitor.cs
  src/Nest/Aggregations/Visitor/AggregationWalker.cs
  tests/Tests/Aggregations/Metric/Rate/RateAggregationUsageTests.cs
Labels: Feature, backport 7.x, backport master, v7.11.0

#5208 Support allow_duplicates on append processor
  src/Nest/Ingest/Processors/AppendProcessor.cs
  tests/Tests/Ingest/ProcessorAssertions.cs
Labels: Feature, backport 7.x, backport master, v7.11.0

#5200 Implement version field type
  src/Nest/Mapping/DynamicTemplate/SingleMapping.cs
  src/Nest/Mapping/Types/FieldType.cs
  src/Nest/Mapping/Types/Properties.cs
  src/Nest/Mapping/Types/PropertyFormatter.cs
  src/Nest/Mapping/Types/Specialized/Version/VersionAttribute.cs
  src/Nest/Mapping/Types/Specialized/Version/VersionProperty.cs
  src/Nest/Mapping/Visitor/IMappingVisitor.cs
  src/Nest/Mapping/Visitor/IPropertyVisitor.cs
  src/Nest/Mapping/Visitor/MappingWalker.cs
  src/Nest/Mapping/Visitor/NoopPropertyVisitor.cs
  src/Nest/Search/FieldCapabilities/FieldCapabilitiesResponse.cs
  tests/Tests/Indices/MappingManagement/GetMapping/GetMappingApiTest.cs
  tests/Tests/Mapping/Types/Specialized/Version/VersionAttributeTests.cs
  tests/Tests/Mapping/Types/Specialized/Version/VersionPropertyTests.cs
Labels: backport 7.x, backport master, v7.11.0

#5240 Implement Clone Snapshot API
  src/ApiGenerator/Domain/Specification/UrlPart.cs
  src/Elasticsearch.Net/Api/RequestParameters/RequestParameters.Snapshot.cs
  src/Elasticsearch.Net/ElasticLowLevelClient.Snapshot.cs
  src/Nest/Descriptors.Snapshot.cs
  src/Nest/ElasticClient.Snapshot.cs
  src/Nest/Modules/SnapshotAndRestore/Snapshot/Clone/CloneSnapshotRequest.cs
  src/Nest/Modules/SnapshotAndRestore/Snapshot/Clone/CloneSnapshotResponse.cs
  src/Nest/Requests.Snapshot.cs
  src/Nest/_Generated/ApiUrlsLookup.generated.cs
  tests/Tests/Framework/EndpointTests/ApiTestBase.cs
  tests/Tests/Modules/SnapshotAndRestore/Snapshot/CloneSnapshot/CloneSnapshotApiTests.cs
  tests/Tests/Modules/SnapshotAndRestore/Snapshot/CloneSnapshot/CloneSnapshotUrlTests.cs
  tests/Tests/Modules/SnapshotAndRestore/Snapshot/CoordinatedSnapshotTests.cs
  tests/Tests/Modules/SnapshotAndRestore/Snapshot/SnapshotCrudTests.cs
Labels: Feature, backport 7.x, backport master, v7.11.0

#5243 Add Nest.Utf8Json using directives to razor files
  src/ApiGenerator/Views/HighLevel/Descriptors/Descriptors.cshtml
  src/ApiGenerator/Views/HighLevel/Requests/Requests.cshtml
Labels: Infra, Self Reviewed

#5260 Fix bug in AutoExpandReplicas.Create
  src/Nest/IndexModules/IndexSettings/Settings/AutoExpandReplicas.cs
  tests/Tests/CommonOptions/AutoExpandReplicas/AutoExpandReplicasTests.cs
Labels: Bug, backport 7.x, backport master, v7.11.0

#5257 Disable translate API test
  tests/Tests/XPack/Sql/TranslateSql/TranslateSqlQueryApiTests.cs
Labels: tests

#5252 Update docs for master
  docs/aggregations/bucket/auto-date-histogram/auto-date-histogram-aggregation-usage.asciidoc
  docs/aggregations/bucket/date-histogram/date-histogram-aggregation-usage.asciidoc
  docs/search/request/script-fields-usage.asciidoc
Labels: Docs

#5248 Update 7.x documentation
  docs/aggregations/bucket/auto-date-histogram/auto-date-histogram-aggregation-usage.asciidoc
  docs/aggregations/bucket/date-histogram/date-histogram-aggregation-usage.asciidoc
  docs/search/request/point-in-time-usage.asciidoc
  docs/search/request/script-fields-usage.asciidoc
Labels: Docs

#5253 Code gen for NEST to support backporting APIs
  src/ApiGenerator/last_downloaded_version.txt
  src/Nest/Descriptors.AsyncSearch.cs
  src/Nest/Descriptors.Cat.cs
  src/Nest/Requests.Cat.cs
  src/Nest/Requests.Indices.cs
  src/Nest/Requests.Nodes.cs
  src/Nest/Requests.Tasks.cs
Labels: code-gen

#5205 Support resource_name on AttachmentProcessor
  src/Nest/Ingest/Processors/Plugins/AttachmentProcessor.cs
  tests/Tests/Ingest/ProcessorAssertions.cs
Labels: Feature, backport 7.x, backport master, v7.11.0

#5259 Implement runtime fields on searches
  docs/client-concepts/high-level/mapping/fluent-mapping.asciidoc
  docs/high-level.asciidoc
  docs/search/searching-runtime-fields.asciidoc
  src/Nest/Indices/MappingManagement/PutMapping/PutMappingRequest.cs
  src/Nest/Mapping/RuntimeFields/RuntimeFields.cs
  src/Nest/Mapping/TypeMapping.cs
  src/Nest/Search/Search/SearchRequest.cs
  tests/Tests.Core/ManagedElasticsearch/NodeSeeders/DefaultSeeder.cs
  tests/Tests.Domain/Project.cs
  tests/Tests/ClientConcepts/HighLevel/Mapping/FluentMapping.doc.cs
  tests/Tests/Search/Search/SearchApiTests.cs
  tests/Tests/Search/SearchingRuntimeFields.doc.cs
Labels: Feature, backport 7.x, backport master, v7.11.0

#5271 Fix GetRoleMappings when multiple distinguished names returned
  src/Nest/XPack/Security/RoleMapping/Rules/Field/DistinguishedNameRule.cs
  src/Nest/XPack/Security/RoleMapping/Rules/Field/FieldRuleBase.cs
  src/Nest/XPack/Security/RoleMapping/Rules/Field/FieldRuleBaseFormatter.cs
  src/Nest/XPack/Security/RoleMapping/Rules/Role/RoleMappingRulesDescriptor.cs
  tests/Tests.Reproduce/GitHubIssue5270.cs
  tests/Tests/XPack/Security/RoleMapping/DistinguishedNamesRoleMappingsTests.cs
Labels: Bug, backport 7.11, backport master, v7.11.0

#5275 Implement unsigned long numeric field
  src/Nest/Mapping/Types/Core/Number/NumberType.cs
  src/Nest/Mapping/Types/FieldType.cs
  src/Nest/Mapping/Types/PropertyFormatter.cs
  tests/Tests/Mapping/Types/Core/Number/NumberPropertyTests.cs
Labels: Feature, backport 7.x, backport master, v7.11.0

#5235 Add a table of contents to readme.md
  readme.md
Labels: Docs, backport 7.11, backport 7.x
