Repository elastic/elasticsearch-net, pull requests merged in 2022-06, with the labels that each got.

#6427 Update autolabel version on the 8.3 branch
  .github/auto-label.json
Labels: bug, Infra

#6429 Regenerate from 8.3 spec branch
  src/Elastic.Clients.Elasticsearch/_Generated/Api/Enrich/EnrichPutPolicyRequest.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Enrich/Configuration.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Enums/Enums.Security.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Migration/MigrationFeature.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Ml/ClassificationInferenceOptions.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Ml/FillMaskInferenceUpdateOptions.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Ml/InferenceConfigCreateContainer.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Ml/InferenceConfigUpdateContainer.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Ml/NerInferenceUpdateOptions.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Ml/NlpTokenizationUpdateOptions.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Ml/PassThroughInferenceUpdateOptions.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Ml/QuestionAnsweringInferenceOptions.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Ml/QuestionAnsweringInferenceUpdateOptions.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Ml/RegressionInferenceOptions.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Ml/TextClassificationInferenceUpdateOptions.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Ml/TextEmbeddingInferenceUpdateOptions.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Ml/TrainedModelDeploymentNodesStats.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Ml/TrainedModelDeploymentStats.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Ml/ZeroShotClassificationInferenceUpdateOptions.g.cs
Labels: backport 8.0, backport 8.1, 8.x, backport 8.2, backport 8.3, v8.0.0-alpha.11

#6441 Fix global.json version
  global.json
Labels: Infra, 8.x

#6445 Add support for MSearch
  build/scripts/scripts.fsproj
  src/Elastic.Clients.Elasticsearch/Types/Documents/MultiSearch/MultiSearchRequest.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/ApiUrlsLookup.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/MultiSearchRequest.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/MultiSearchResponse.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Client/ElasticsearchClient.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/ErrorResponseBase.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Mapping/Properties.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/MultiSearchItem.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/MultisearchBody.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/MultisearchHeader.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/ResponseBody.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/SearchResponseItem.g.cs
  tests/Tests.Configuration/tests.default.yaml
  tests/Tests/Document/Multiple/MultiGet/MultiGetApiTests.cs
  tests/Tests/Document/Multiple/MultiSearch/MultiSearchApiTests.cs
  tests/Tests/Framework/EndpointTests/ApiTestBase.cs
  tests/Tests/Serialization/Documents/MSearchSerialization.cs
  tests/Tests/_VerifySnapshots/MSearchSerialization.SerializesRequest.verified.txt
  tests/Tests/_VerifySnapshots/MultiSearchApiTests.VerifyDescriptorNdJson.verified.txt
  tests/Tests/_VerifySnapshots/MultiSearchApiTests.VerifyInitializerNdJson.verified.txt
Labels: enhancement, backport 8.0, backport 8.1, 8.x, backport 8.2, backport 8.3, v8.0.0-alpha.11

#6450 Remove helpers namespace
  benchmarks/Profiling/Program.cs
  src/Elastic.Clients.Elasticsearch/Client/ElasticsearchClient-BulkAll.cs
  src/Elastic.Clients.Elasticsearch/Helpers/BlockingSubscribeExtensions.cs
  src/Elastic.Clients.Elasticsearch/Helpers/BulkAllObservable.cs
  src/Elastic.Clients.Elasticsearch/Helpers/BulkAllObserver.cs
  src/Elastic.Clients.Elasticsearch/Helpers/BulkAllRequest.cs
  src/Elastic.Clients.Elasticsearch/Helpers/BulkAllResponse.cs
  src/Elastic.Clients.Elasticsearch/Helpers/CoordinatedRequestDefaults.cs
  src/Elastic.Clients.Elasticsearch/Helpers/CoordinatedRequestObserverBase.cs
  src/Elastic.Clients.Elasticsearch/Helpers/HelperIdentifiers.cs
  src/Elastic.Clients.Elasticsearch/Helpers/IBulkAllRequest.cs
  src/Elastic.Clients.Elasticsearch/Helpers/IHelperCallable.cs
  src/Elastic.Clients.Elasticsearch/Helpers/PartitionHelper.cs
  src/Elastic.Clients.Elasticsearch/Helpers/ProducerConsumerBackPressure.cs
  src/Elastic.Clients.Elasticsearch/Helpers/RequestMetaDataExtensions.cs
  src/Elastic.Clients.Elasticsearch/Helpers/RequestMetaDataFactory.cs
  src/Elastic.Clients.Elasticsearch/Helpers/RequestParametersExtensions.cs
  tests/Tests.Core/ManagedElasticsearch/NodeSeeders/DefaultSeeder.cs
  tests/Tests.Core/ManagedElasticsearch/NodeSeeders/TimeSeriesSeeder.cs
  tests/Tests/ClientConcepts/HighLevel/Indexing/IndexingDocuments.doc.cs
  tests/Tests/Document/Multiple/BulkAll/BulkAllCancellationTokenApiTests.cs
  tests/Tests/Document/Multiple/BulkAll/BulkAllDeallocationApiTests.cs
  tests/Tests/Document/Multiple/BulkAll/BulkAllDisposeApiTests.cs
  tests/Tests/Document/Multiple/BulkAll/BulkOnErrorApiTests.cs
Labels: enhancement, backport 8.0, backport 8.1, backport 8.2, backport 8.3, v8.0.0-alpha.12

#6455 Simplify Indices type and API
  src/Elastic.Clients.Elasticsearch/Common/Infer/Indices/Indices.cs
  src/Elastic.Clients.Elasticsearch/Common/Infer/Indices/IndicesExtensions.cs
  tests/Tests.Configuration/tests.default.yaml
  tests/Tests/ClientConcepts/HighLevel/Inference/Equality/IndicesEqualityTests.cs
  tests/Tests/ClientConcepts/HighLevel/Inference/ImplicitConversionTests.cs
  tests/Tests/ClientConcepts/HighLevel/Inference/IndexNameInference.doc.cs
  tests/Tests/Common/Infer/Indices/IndicesTests.cs
  tests/Tests/Common/TimeUnit/TimeUnits.cs
  tests/Tests/_VerifySnapshots/IndicesSerializationTests.Deserializes_All_Correctly.verified.txt
  tests/Tests/_VerifySnapshots/IndicesSerializationTests.Serializes_All_Correctly.verified.txt
  tests/Tests/_VerifySnapshots/IndicesSerializationTests.Serializes_Correctly.verified.txt
Labels: enhancement, backport 8.0, backport 8.1, 8.x, backport 8.2, backport 8.3, v8.0.0-alpha.12

#6474 Bump newtonsoft dependency to 13.0.1 to respond to vulnerability
  build/scripts/packages.lock.json
  build/scripts/scripts.fsproj
  src/Elastic.Clients.Elasticsearch.JsonNetSerializer/Elastic.Clients.Elasticsearch.JsonNetSerializer.csproj
  src/Elastic.Clients.Elasticsearch.JsonNetSerializer/packages.lock.json
  src/Playground/packages.lock.json
  tests/Tests.ClusterLauncher/packages.lock.json
  tests/Tests.Core/packages.lock.json
  tests/Tests.Domain/Tests.Domain.csproj
  tests/Tests.Domain/packages.lock.json
  tests/Tests/packages.lock.json
Labels: backport 8.0, dependencies, backport 8.1, 8.x, backport 8.2, backport 8.3, v8.0.0-beta.1

#6473 Bump newtonsoft dependency to 13.0.1 to respond to vulnerability
  .ci/DockerFile
  .ci/make.sh
  .ci/readme.md
  .ci/run-repository.ps1
  .ci/run-repository.sh
  .ci/run-tests.ps1
  .ci/test-matrix.yml
  .github/workflows/integration-jobs.yml
  .github/workflows/make-bump.yml
  .github/workflows/make-release-notes.yml
  .github/workflows/stale-jobs.yml
  .github/workflows/test-jobs.yml
  .github/workflows/unified-release.yml
  build/scripts/packages.lock.json
  build/scripts/scripts.fsproj
  global.json
  src/ApiGenerator/ApiGenerator.csproj
  src/ApiGenerator/packages.lock.json
  src/DocGenerator/DocGenerator.csproj
  src/DocGenerator/packages.lock.json
  src/Nest.JsonNetSerializer/Nest.JsonNetSerializer.csproj
  src/Nest.JsonNetSerializer/packages.lock.json
  tests/Tests.Benchmarking/packages.lock.json
  tests/Tests.ClusterLauncher/packages.lock.json
  tests/Tests.Configuration/tests.default.yaml
  tests/Tests.Core/packages.lock.json
  tests/Tests.Domain/Tests.Domain.csproj
  tests/Tests.Domain/packages.lock.json
  tests/Tests.Reproduce/packages.lock.json
  tests/Tests.ScratchPad/packages.lock.json
  tests/Tests.YamlRunner/Tests.YamlRunner.fsproj
  tests/Tests.YamlRunner/packages.lock.json
  tests/Tests/Tests.csproj
  tests/Tests/packages.lock.json
Labels: 7.x, dependencies, v7.17.3

#6425 Update README.md
  README.md
Labels: Docs

#6479 Fix duplicate object serialization of aggregations
  src/Nest/Aggregations/AggregationContainer.cs
  src/Nest/Search/Search/SearchRequest.cs
  src/Nest/XPack/AsyncSearch/Submit/AsyncSearchSubmitRequest.cs
  tests/Tests.Configuration/tests.default.yaml
  tests/Tests/Aggregations/SearchAggregationSerializationTests.cs
Labels: bug, 7.x, v7.17.4

#6480 Avoid simplifying scroll IDs on responses
  src/Elastic.Clients.Elasticsearch/Common/Infer/IndexName/IndexName.cs
  src/Elastic.Clients.Elasticsearch/Common/UrlParameters/Username/Username.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/ScrollResponse.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/SearchResponse.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/AsyncSearch/AsyncSearch.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Enums/Enums.Security.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Migration/MigrationFeature.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/ResponseBody.g.cs
  tests/Tests/AsyncSearch/AsyncSearchApiTests.cs
  tests/Tests/Common/Infer/Indices/IndicesTests.cs
  tests/Tests/Serialization/Documents/MGetSerialization.cs
  tests/Tests/_VerifySnapshots/IndicesSerializationTests.Deserializes_All_Correctly.verified.txt
  tests/Tests/_VerifySnapshots/MGetSerialization.DeserializesError.verified.txt
Labels: enhancement, backport 8.0, backport 8.1, 8.x, backport 8.2, backport 8.3, v8.0.0-beta.1
