Repository elastic/elasticsearch-net, pull requests merged in 2022-10, with the labels that each got.

#6697 Improvements for open enumeration types
  src/Elastic.Clients.Elasticsearch/Serialization/StringAliasConverter.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Enums/Enums.NoNamespace.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Highlight.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/HighlightField.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/InlineScript.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/LanguageContext.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Security/RoleTemplateInlineScript.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/StoredScript.g.cs
Labels: enhancement, backport 8.0, backport 8.1, 8.x, backport 8.2, backport 8.3, backport 8.4, backport 8.5, v8.0.0-beta.6

#6711 Fixes for UpdateRequest
  src/Elastic.Clients.Elasticsearch/Api/UpdateRequestDescriptor.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/UpdateRequest.g.cs
  tests/Tests/Document/Single/Update/UpdateDocumentsCoordinatedTests.cs
Labels: enhancement, backport 8.0, backport 8.1, 8.x, backport 8.2, backport 8.3, backport 8.4, backport 8.5, v8.0.0-beta.6

#6725 Add more integration and unit tests
  src/Elastic.Clients.Elasticsearch/Common/UrlParameters/TaskId/TaskId.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/ClearScrollRequest.g.cs
  tests/Tests.Configuration/tests.default.yaml
  tests/Tests.Core/ManagedElasticsearch/Clusters/ReindexCluster.cs
  tests/Tests/AsyncSearch/AsyncSearchApiTests.cs
  tests/Tests/Document/Multiple/DeleteByQuery/DeleteByQueryApiTests.cs
  tests/Tests/Document/Multiple/DeleteByQuery/DeleteByQueryUrlTests.cs
  tests/Tests/Document/Multiple/DeleteByQueryRethrottle/DeleteByQueryRethrottleApiTests.cs
  tests/Tests/Document/Multiple/DeleteByQueryRethrottle/DeleteByQueryRethrottleUrlTests.cs
  tests/Tests/Search/Scroll/ClearScroll/ClearScrollApiTests.cs
  tests/Tests/Search/Scroll/ClearScroll/ClearScrollUrlTests.cs
  tests/Tests/Search/Scroll/Scroll/ScrollApiTests.cs
  tests/Tests/Search/Scroll/Scroll/ScrollUrlTests.cs
  tests/Tests/Search/Scroll/Scroll/SlicedScrollSearchApiTests.cs
Labels: enhancement, backport 8.0, backport 8.1, 8.x, backport 8.2, backport 8.3, backport 8.4, backport 8.5, v8.0.0-beta.6

#6748 Refine AggregationDictionary
  src/Elastic.Clients.Elasticsearch/Common/Aggregations/AggregationDictionary.cs
  tests/Tests/Serialization/Aggregations/WritingAggregationsTests.cs
Labels: enhancement, backport 8.0, backport 8.1, 8.x, backport 8.2, backport 8.3, backport 8.4, backport 8.5, v8.0.0-rc.1

#6770 Update ubuntu version for backport action
  .github/workflows/backport.yml
Labels: Infra

#6779 Code gen for internally tagged union variant converters
  src/Elastic.Clients.Elasticsearch/Types/Mapping/Properties.cs
  src/Elastic.Clients.Elasticsearch/Types/Mapping/PropertyBase.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Aggregations/AggregateDictionary.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Analysis/Analyzers.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Analysis/CharFilterDefinitions.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Analysis/Normalizers.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Analysis/TokenFilterDefinitions.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Analysis/TokenizerDefinitions.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Mapping/Properties.g.cs
  tests/Tests/IndexManagement/IndexSettingsSerializationTests.cs
  tests/Tests/Serialization/Indices/IndexSettingsSerialisationTests.cs
  tests/Tests/_VerifySnapshots/IndexSettingsSerializationTests.CanSerializerIndexSettingsWithCustomAnalyzer.verified.txt
Labels: bug, backport 8.0, backport 8.1, 8.x, backport 8.2, backport 8.3, backport 8.4, backport 8.5, v8.0.0-rc.1

#6801 Fix dropped doc callback for retried docs
  .editorconfig
  src/Elastic.Clients.Elasticsearch/Helpers/BulkAllObservable.cs
  tests/Tests/Document/Multiple/BulkAll/BulkAllForEachAsyncApiTests.cs
  tests/Tests/Document/Multiple/BulkAll/BulkAllRetryTests.cs
Labels: bug, backport 8.0, backport 8.1, 8.x, backport 8.2, backport 8.3, backport 8.4, backport 8.5, v8.0.0-rc.2

#6809 Update ubuntu version for backport action
  .github/workflows/backport.yml
Labels: Infra, backport 8.0, backport 8.1, backport 8.2, backport 8.3, backport 8.4

#6648 Add script property to variable width histogram
  src/Nest/Aggregations/Bucket/VariableWidthHistogram/VariableWidthHistogramAggregation.cs
  tests/Tests/Aggregations/Bucket/VariableWidthHistogram/VariableWidthHistogramUsageTests.cs
Labels: Feature, 7.x

#6495 Update problematic versions for VS restore
  .ci/packages.lock.json
  .github/workflows/backport.yml
  .github/workflows/integration-jobs.yml
  Directory.Build.props
  build/scripts/packages.lock.json
  build/scripts/scripts.fsproj
  global.json
  src/ApiGenerator/packages.lock.json
  src/DocGenerator/packages.lock.json
  src/Elasticsearch.Net.VirtualizedCluster/packages.lock.json
  src/Elasticsearch.Net/packages.lock.json
  src/Nest.JsonNetSerializer/packages.lock.json
  src/Nest/packages.lock.json
  tests/Tests.Benchmarking/packages.lock.json
  tests/Tests.ClusterLauncher/packages.lock.json
  tests/Tests.Configuration/packages.lock.json
  tests/Tests.Core/Tests.Core.csproj
  tests/Tests.Core/packages.lock.json
  tests/Tests.Domain/packages.lock.json
  tests/Tests.Reproduce/packages.lock.json
  tests/Tests.ScratchPad/packages.lock.json
  tests/Tests.YamlRunner/packages.lock.json
  tests/Tests/Framework/EndpointTests/RequestResponseApiTestBase.cs
  tests/Tests/packages.lock.json
Labels: Infra, 7.x, dependencies

#6815 Fix dropped doc callback for retried docs
  .ci/packages.lock.json
  Directory.Build.props
  build/scripts/packages.lock.json
  src/ApiGenerator/packages.lock.json
  src/DocGenerator/packages.lock.json
  src/Elasticsearch.Net.VirtualizedCluster/packages.lock.json
  src/Elasticsearch.Net/packages.lock.json
  src/Nest.JsonNetSerializer/packages.lock.json
  src/Nest/Document/Multiple/BulkAll/BulkAllObservable.cs
  src/Nest/packages.lock.json
  tests/Tests.Benchmarking/packages.lock.json
  tests/Tests.ClusterLauncher/packages.lock.json
  tests/Tests.Configuration/packages.lock.json
  tests/Tests.Core/Tests.Core.csproj
  tests/Tests.Core/packages.lock.json
  tests/Tests.Domain/packages.lock.json
  tests/Tests.Reproduce/packages.lock.json
  tests/Tests.ScratchPad/packages.lock.json
  tests/Tests.YamlRunner/packages.lock.json
  tests/Tests/Document/Multiple/BulkAll/BulkAllRetryTests.cs
  tests/Tests/packages.lock.json
Labels: bug, 7.x, v7.17.5

#6816 Remove geo-dependant types until code-gen is implemented
  src/Elastic.Clients.Elasticsearch/_Generated/Api/SearchResponse.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Enums/Enums.NoNamespace.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Enums/Enums.QueryDsl.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/GeoDistanceSort.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/QueryDsl/GeoBoundingBoxQuery.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/QueryDsl/GeoDistanceQuery.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/QueryDsl/GeoPolygonPoints.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/QueryDsl/GeoPolygonQuery.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/QueryDsl/GeoShapeFieldQuery.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/QueryDsl/GeoShapeQuery.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/QueryDsl/QueryContainer.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/SortOptions.g.cs
  tests/Tests/Serialization/Aggregations/GeoBoundsAggregateDeserializationTests.cs
Labels: Feature, backport 8.0, backport 8.1, 8.x, backport 8.2, backport 8.3, backport 8.4, backport 8.5, v8.0.0-rc.2

#6824 Sort simplification
  src/Elastic.Clients.Elasticsearch/Serialization/SingleOrManySerializationHelper.cs
  src/Elastic.Clients.Elasticsearch/Types/FieldSort.cs
  src/Elastic.Clients.Elasticsearch/Types/SortCombinations.cs
  src/Elastic.Clients.Elasticsearch/Types/SortOptions.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/AsyncSearch/AsyncSearchSubmitRequest.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/SearchRequest.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Aggregations/TopHitsAggregation.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Aggregations/TopMetricsAggregation.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Core/MSearch/MultisearchBody.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Core/Reindex/Source.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Core/Search/InnerHits.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/SortCombinations.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/SortConverter.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/SortOptions.g.cs
  tests/Tests/Search/Scroll/Scroll/SlicedScrollSearchApiTests.cs
  tests/Tests/Search/Search/BasicSortUsageTests.cs
  tests/Tests/Search/Search/SortUsageTests.cs
  tests/Tests/Serialization/SortCombinationsSerializationTests.cs
  tests/Tests/Serialization/Types/SortOptionsSerializationTests.cs
Labels: Feature, backport 8.0, backport 8.1, 8.x, backport 8.2, backport 8.3, backport 8.4, backport 8.5, v8.0.0-rc.2

#6852 Prefer Fields type over IEnumerable<Field>
  src/Elastic.Clients.Elasticsearch/_Generated/Types/QueryDsl/CombinedFieldsQuery.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/QueryDsl/LikeDocument.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/QueryDsl/MoreLikeThisQuery.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/QueryDsl/QueryStringQuery.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/QueryDsl/SimpleQueryStringQuery.g.cs
Labels: bug, backport 8.0, backport 8.1, 8.x, backport 8.2, backport 8.3, backport 8.4, backport 8.5, v8.0.0-rc.2

#6867 Port TermsInclude type
  src/Elastic.Clients.Elasticsearch/Types/Aggregations/TermsAggregationDescriptor.cs
  src/Elastic.Clients.Elasticsearch/Types/Aggregations/TermsExclude.cs
  src/Elastic.Clients.Elasticsearch/Types/Aggregations/TermsInclude.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Aggregations/TermsAggregation.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Aggregations/TermsPartition.g.cs
  tests/Tests/AsyncSearch/AsyncSearchApiTests.cs
  tests/Tests/Types/Aggregations/TermsExcludeSerializationTests.cs
  tests/Tests/Types/Aggregations/TermsIncludeSerializationTests.cs
  tests/Tests/_VerifySnapshots/TermsExcludeSerializationTests.RoundTripSerialize_TermsExcludeWithRegexPattern.verified.txt
  tests/Tests/_VerifySnapshots/TermsExcludeSerializationTests.RoundTripSerialize_TermsExcludeWithValues.verified.txt
  tests/Tests/_VerifySnapshots/TermsIncludeSerializationTests.RoundTripSerialize_TermsIncludeWithPartition.verified.txt
  tests/Tests/_VerifySnapshots/TermsIncludeSerializationTests.RoundTripSerialize_TermsIncludeWithRegexPattern.verified.txt
  tests/Tests/_VerifySnapshots/TermsIncludeSerializationTests.RoundTripSerialize_TermsIncludeWithValues.verified.txt
Labels: enhancement, backport 8.0, backport 8.1, 8.x, backport 8.2, backport 8.3, backport 8.4, backport 8.5, v8.0.0-rc.2
