Repository elastic/elasticsearch-net, pull requests merged in 2022-03, with the labels that each got.

#6153 [DOCS] WIP - Connection to v8
  docs/client-concepts/certificates/working-with-certificates.asciidoc
  docs/client-concepts/connection/connecting-to-elasticsearch-v8.asciidoc
  docs/high-level.asciidoc
  docs/query-dsl/geo/bounding-box/geo-bounding-box-query-usage.asciidoc
  docs/query-dsl/geo/distance/geo-distance-query-usage.asciidoc
  docs/query-dsl/geo/polygon/geo-polygon-query-usage.asciidoc
  tests/Tests/ClientConcepts/Certificates/WorkingWithCertificates.doc.cs
  tests/Tests/ClientConcepts/Connection/ConnectingToElasticsearchV8.doc.cs
  tests/Tests/high-level.asciidoc
Labels: Docs, WIP

#6156 Fix broken link to contributing.md
  README.md
Labels: Docs, backport 8.0, backport 7.17, backport 8.1

#6165 Add SQL APIs
  build/scripts/Targets.fs
  src/Elastic.Clients.Elasticsearch/Api/SqlGetAsyncResponse.cs
  src/Elastic.Clients.Elasticsearch/Common/LazyDocument.cs
  src/Elastic.Clients.Elasticsearch/FutureGenerated/FutureGenerated.cs
  src/Elastic.Clients.Elasticsearch/Serialization/DictionaryConverter.cs
  src/Elastic.Clients.Elasticsearch/Serialization/UnionConverter.cs
  src/Elastic.Clients.Elasticsearch/Types/Sql/SqlRow.cs
  src/Elastic.Clients.Elasticsearch/Types/Sql/SqlValue.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/ApiUrlsLookup.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/SourceRequest.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/Sql/SqlClearCursorRequest.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/Sql/SqlClearCursorResponse.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/Sql/SqlDeleteAsyncRequest.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/Sql/SqlDeleteAsyncResponse.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/Sql/SqlGetAsyncRequest.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/Sql/SqlGetAsyncResponse.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/Sql/SqlGetAsyncStatusRequest.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/Sql/SqlGetAsyncStatusResponse.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/Sql/SqlQueryRequest.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/Sql/SqlQueryResponse.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Client/ElasticsearchClient.Sql.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Client/ElasticsearchClient.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Sql/Column.g.cs
  tests/Tests/Eql/EqlSearchApiCoordinatedTests.cs
  tests/Tests/Sql/ClearSqlCursorApiTests.cs
  tests/Tests/Sql/SqlSearchApiCoordinatedTests.cs
Labels: enhancement, backport 8.0, backport 8.1

#6168 Respond to schema changes
  src/Elastic.Clients.Elasticsearch/Api/GetAsyncSearchResponse.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/AsyncSearch/AsyncSearchStatusResponse.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/AsyncSearch/DeleteAsyncSearchResponse.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/CreateResponse.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/DeleteResponse.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/Eql/DeleteEqlResponse.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/IndexManagement/DeleteResponse.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/IndexManagement/RefreshResponse.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/IndexResponse.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/OpenPointInTimeRequest.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/Sql/SqlDeleteAsyncResponse.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/UpdateResponse.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/AcknowledgedResponseBase.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/IndicesResponseBase.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/ShardsOperationResponseBase.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/WriteResponseBase.g.cs
Labels: backport 8.0, backport 8.1

#6177 Add code generated Task API
  src/Elastic.Clients.Elasticsearch/Common/Infer/TaskId/TaskId.cs
  src/Elastic.Clients.Elasticsearch/Serialization/DictionaryConverter.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/ApiUrlsLookup.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/Tasks/GetTasksRequest.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/Tasks/GetTasksResponse.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/Tasks/TasksCancelRequest.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/Tasks/TasksCancelResponse.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/Tasks/TasksListRequest.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/Tasks/TasksListResponse.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Client/ElasticsearchClient.Tasks.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Client/ElasticsearchClient.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Enums/Enums.Tasks.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Retries.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/TaskFailure.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Tasks/NodeTasks.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Tasks/ParentTaskInfo.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Tasks/TaskInfo.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Tasks/TaskInfos.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Tasks/TaskStatus.g.cs
  src/Playground/Program.cs
Labels: enhancement, backport 8.0, backport 8.1, v8.0.0-alpha.4

#6180 Enable more CI integration test clusters
  .github/workflows/integration-jobs.yml
Labels: tests, backport 8.0, backport 8.1

#6184 Ensure async search descriptors use typed_keys
  src/Elastic.Clients.Elasticsearch/FutureGenerated/FutureGenerated.cs
Labels: backport 8.0, backport 8.1

#6183 [DOCS] Adds Connecting section to docs
  docs/connecting.asciidoc
  docs/high-level.asciidoc
  docs/index.asciidoc
Labels: Docs, backport 8.0, backport 8.1, 8.x

#6191 Respond to transport refactoring
  benchmarks/Benchmarks/packages.lock.json
  benchmarks/Profiling/packages.lock.json
  src/Elastic.Clients.Elasticsearch.JsonNetSerializer/packages.lock.json
  src/Elastic.Clients.Elasticsearch/Common/ElasticsearchClientProductRegistration.cs
  src/Elastic.Clients.Elasticsearch/Common/Infer/Inferrer.cs
  src/Elastic.Clients.Elasticsearch/Common/Response/ExistsResponseBase.cs
  src/Elastic.Clients.Elasticsearch/Elastic.Clients.Elasticsearch.csproj
  src/Elastic.Clients.Elasticsearch/Helpers/BulkAllObservable.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/AsyncSearch/AsyncSearchStatusResponse.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/AsyncSearch/DeleteAsyncSearchResponse.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/BulkResponse.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/ClosePointInTimeResponse.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/Cluster/ClusterAllocationExplainResponse.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/Cluster/ClusterHealthResponse.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/Cluster/ClusterPendingTasksResponse.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/Cluster/ClusterStateResponse.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/CountResponse.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/CreateResponse.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/DeleteResponse.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/Eql/DeleteEqlResponse.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/Eql/EqlGetStatusResponse.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/GetResponse.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/IndexManagement/DeleteResponse.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/IndexManagement/RefreshResponse.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/IndexResponse.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/OpenPointInTimeResponse.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/PingResponse.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/SearchResponse.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/SourceResponse.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/Sql/SqlClearCursorResponse.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/Sql/SqlDeleteAsyncResponse.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/Sql/SqlGetAsyncResponse.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/Sql/SqlGetAsyncStatusResponse.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/Sql/SqlQueryResponse.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/Tasks/GetTasksResponse.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/Tasks/TasksCancelResponse.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/Tasks/TasksListResponse.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/UpdateResponse.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/AsyncSearch/AsyncSearchResponseBase.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Eql/EqlSearchResponseBase.g.cs
  src/Elastic.Clients.Elasticsearch/packages.lock.json
  src/Playground/packages.lock.json
  tests/Tests.ClusterLauncher/packages.lock.json
  tests/Tests.Core/Extensions/ShouldExtensions.cs
  tests/Tests.Core/Serialization/JsonRoundTripper.cs
  tests/Tests.Core/packages.lock.json
  tests/Tests.Domain/packages.lock.json
  tests/Tests/Framework/EndpointTests/ApiIntegrationTestBase.cs
  tests/Tests/Framework/EndpointTests/ApiTestBase.cs
  tests/Tests/Framework/EndpointTests/CoordinatedIntegrationTestBase.cs
  tests/Tests/Framework/EndpointTests/CoordinatedUsage.cs
  tests/Tests/Framework/EndpointTests/RequestResponseApiTestBase.cs
  tests/Tests/Framework/EndpointTests/TestState/EndpointUsage.cs
  tests/Tests/Framework/EndpointTests/TestState/LazyResponses.cs
  tests/Tests/Framework/EndpointTests/UrlTester.cs
  tests/Tests/Framework/EndpointTests/UrlTesterExtensions.cs
  tests/Tests/packages.lock.json
Labels: backport 8.0, backport 8.1

#6188 [DOCS] Removes low-level client docs and references
  docs/client-concepts/connection-pooling/building-blocks/connection-pooling.asciidoc
  docs/client-concepts/connection/configuration-options.asciidoc
  docs/client-concepts/high-level/getting-started.asciidoc
  docs/client-concepts/low-level/class.png
  docs/client-concepts/low-level/getting-started.asciidoc
  docs/client-concepts/low-level/lifetimes.asciidoc
  docs/client-concepts/low-level/low-level-response-types.asciidoc
  docs/client-concepts/low-level/pipeline.png
  docs/client-concepts/low-level/post-data.asciidoc
  docs/conventions.asciidoc
  docs/high-level.asciidoc
  docs/index.asciidoc
  docs/installation.asciidoc
  docs/introduction.asciidoc
  docs/low-level.asciidoc
Labels: Docs, backport 8.0, backport 8.1, 8.x

#6192 [8.1][DOCS] Adds Connecting section to docs (#6183)
  docs/connecting.asciidoc
  docs/high-level.asciidoc
  docs/index.asciidoc
Labels: Docs

#6193 [8.0][DOCS] Adds Connecting section to docs (#6183)
  docs/connecting.asciidoc
  docs/high-level.asciidoc
  docs/index.asciidoc
Labels: Docs, v8.0.0

#6197 [8.1][DOCS] Removes low-level client docs and references (#6188)
  docs/client-concepts/connection-pooling/building-blocks/connection-pooling.asciidoc
  docs/client-concepts/connection/configuration-options.asciidoc
  docs/client-concepts/high-level/getting-started.asciidoc
  docs/client-concepts/low-level/class.png
  docs/client-concepts/low-level/getting-started.asciidoc
  docs/client-concepts/low-level/lifetimes.asciidoc
  docs/client-concepts/low-level/low-level-response-types.asciidoc
  docs/client-concepts/low-level/pipeline.png
  docs/client-concepts/low-level/post-data.asciidoc
  docs/conventions.asciidoc
  docs/high-level.asciidoc
  docs/index.asciidoc
  docs/installation.asciidoc
  docs/introduction.asciidoc
  docs/low-level.asciidoc
Labels: Docs

#6198 [DOCS] Removes low-level client docs and references (#6188)
  docs/client-concepts/connection-pooling/building-blocks/connection-pooling.asciidoc
  docs/client-concepts/connection/configuration-options.asciidoc
  docs/client-concepts/high-level/getting-started.asciidoc
  docs/client-concepts/low-level/class.png
  docs/client-concepts/low-level/getting-started.asciidoc
  docs/client-concepts/low-level/lifetimes.asciidoc
  docs/client-concepts/low-level/low-level-response-types.asciidoc
  docs/client-concepts/low-level/pipeline.png
  docs/client-concepts/low-level/post-data.asciidoc
  docs/conventions.asciidoc
  docs/high-level.asciidoc
  docs/index.asciidoc
  docs/installation.asciidoc
  docs/introduction.asciidoc
  docs/low-level.asciidoc
Labels: Docs, v8.0.0

#6200 Add graph explore API
  src/Elastic.Clients.Elasticsearch/_Generated/Api/ApiUrlsLookup.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/Graph/GraphExploreRequest.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/Graph/GraphExploreResponse.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Client/ElasticsearchClient.Graph.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Client/ElasticsearchClient.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Graph/Connection.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Graph/ExploreControls.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Graph/Hop.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Graph/SampleDiversity.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Graph/Vertex.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Graph/VertexDefinition.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Graph/VertexInclude.g.cs
Labels: enhancement, backport 8.0, backport 8.1

#6203 Add enrich APIs
  src/Elastic.Clients.Elasticsearch/Common/Infer/Fields/Fields.cs
  src/Elastic.Clients.Elasticsearch/Common/Infer/Indices/Indices.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/ApiUrlsLookup.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/Enrich/EnrichDeletePolicyRequest.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/Enrich/EnrichDeletePolicyResponse.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/Enrich/EnrichExecutePolicyRequest.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/Enrich/EnrichExecutePolicyResponse.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/Enrich/EnrichGetPolicyRequest.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/Enrich/EnrichGetPolicyResponse.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/Enrich/EnrichPutPolicyRequest.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/Enrich/EnrichPutPolicyResponse.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/Enrich/EnrichStatsRequest.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/Enrich/EnrichStatsResponse.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Client/ElasticsearchClient.Enrich.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Client/ElasticsearchClient.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Enrich/CacheStats.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Enrich/Configuration.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Enrich/CoordinatorStats.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Enrich/ExecuteEnrichPolicyStatus.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Enrich/ExecutingPolicy.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Enrich/Policy.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Enrich/Summary.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Enums/Enums.Enrich.ExecutePolicy.g.cs
Labels: enhancement, backport 8.0, backport 8.1, v8.0.0-alpha.4

#6214 Add Searchable Snapshots APIs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/ApiUrlsLookup.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/SearchableSnapshots/SearchableSnapshotsCacheStatsRequest.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/SearchableSnapshots/SearchableSnapshotsCacheStatsResponse.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/SearchableSnapshots/SearchableSnapshotsClearCacheRequest.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/SearchableSnapshots/SearchableSnapshotsClearCacheResponse.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/SearchableSnapshots/SearchableSnapshotsMountRequest.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/SearchableSnapshots/SearchableSnapshotsMountResponse.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/SearchableSnapshots/SearchableSnapshotsStatsRequest.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/SearchableSnapshots/SearchableSnapshotsStatsResponse.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Client/ElasticsearchClient.SearchableSnapshots.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Client/ElasticsearchClient.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Enums/Enums.SearchableSnapshots.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/SearchableSnapshots/MountedSnapshot.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/SearchableSnapshots/Node.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/SearchableSnapshots/Shared.g.cs
Labels: enhancement, backport 8.0, backport 8.1, 8.x, v8.0.0-alpha.4

#6223 Add various indices APIs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/ApiUrlsLookup.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/IndexManagement/AliasRequest.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/IndexManagement/AliasResponse.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/IndexManagement/CloseRequest.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/IndexManagement/CloseResponse.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/IndexManagement/CreateDataStreamRequest.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/IndexManagement/CreateDataStreamResponse.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/IndexManagement/DataStreamRequest.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/IndexManagement/DataStreamResponse.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/IndexManagement/DeleteAliasRequest.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/IndexManagement/DeleteAliasResponse.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/IndexManagement/DeleteDataStreamRequest.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/IndexManagement/DeleteDataStreamResponse.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/IndexManagement/ExistsAliasRequest.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/IndexManagement/ExistsAliasResponse.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/IndexManagement/MigrateToDataStreamRequest.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/IndexManagement/MigrateToDataStreamResponse.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/IndexManagement/OpenRequest.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/IndexManagement/OpenResponse.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/IndexManagement/PromoteDataStreamRequest.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/IndexManagement/PromoteDataStreamResponse.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/IndexManagement/PutAliasRequest.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/IndexManagement/PutAliasResponse.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/IndexManagement/ShrinkRequest.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/IndexManagement/ShrinkResponse.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/IndexManagement/SplitRequest.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/IndexManagement/SplitResponse.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/IndexManagement/UpdateAliasesRequest.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/IndexManagement/UpdateAliasesResponse.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Client/ElasticsearchClient.IndexManagement.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/IndexManagement/Action.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/IndexManagement/AddAction.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/IndexManagement/Alias.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/IndexManagement/CloseIndexResult.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/IndexManagement/CloseShardResult.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/IndexManagement/IndicesGetDataStreamItem.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/IndexManagement/IndicesGetDataStreamItemIndex.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/IndexManagement/IndicesGetDataStreamItemTimestampField.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/IndexManagement/RemoveAction.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/IndexManagement/RemoveIndexAction.g.cs
Labels: enhancement, backport 8.0, backport 8.1, 8.x, v8.0.0-alpha.4

#6226 Add various global APIs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/ApiUrlsLookup.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/DeleteByQueryRequest.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/DeleteByQueryResponse.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/DeleteByQueryRethrottleRequest.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/DeleteByQueryRethrottleResponse.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/PutScriptRequest.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/PutScriptResponse.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/ReindexRequest.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/ReindexResponse.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/ReindexRethrottleRequest.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/ReindexRethrottleResponse.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/UpdateByQueryRequest.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/UpdateByQueryResponse.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/UpdateByQueryRethrottleRequest.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/UpdateByQueryRethrottleResponse.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Client/ElasticsearchClient.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/BulkIndexByScrollFailure.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Destination.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Enums/Enums.NoNamespace.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/ReindexNode.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/ReindexStatus.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/ReindexTask.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/RemoteSource.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Source.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/SpecUtils/BaseNode.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/StoredScript.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/UpdateByQueryRethrottleNode.g.cs
Labels: enhancement, backport 8.0, backport 8.1, 8.x, v8.0.0-alpha.4

#6229 Add additional global APIs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/ApiUrlsLookup.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/ExistsSourceRequest.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/ExistsSourceResponse.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/FieldCapsRequest.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/FieldCapsResponse.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/InfoRequest.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/InfoResponse.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/KnnSearchRequest.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/KnnSearchResponse.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/RankEvalRequest.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/RankEvalResponse.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/ScriptContextRequest.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/ScriptContextResponse.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/ScriptLanguagesRequest.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/ScriptLanguagesResponse.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/SearchShardsRequest.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/SearchShardsResponse.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/TermsEnumRequest.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/TermsEnumResponse.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Client/ElasticsearchClient.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Context.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/ContextMethod.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/ContextMethodParam.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/DocumentRating.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/ElasticsearchVersionInfo.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Enums/Enums.Mapping.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/FieldCapability.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/LanguageContext.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/NodeAttributes.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/NodeShard.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Query.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/RankEvalHit.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/RankEvalHitItem.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/RankEvalMetric.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/RankEvalMetricBase.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/RankEvalMetricDetail.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/RankEvalMetricDiscountedCumulativeGain.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/RankEvalMetricExpectedReciprocalRank.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/RankEvalMetricMeanReciprocalRank.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/RankEvalMetricPrecision.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/RankEvalMetricRatingTreshold.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/RankEvalMetricRecall.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/RankEvalQuery.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/RankEvalRequestItem.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/ShardStoreIndex.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/UnratedDocument.g.cs
Labels: enhancement, backport 8.0, backport 8.1, 8.x, v8.0.0-alpha.4

#6232 Add CCR APIs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/ApiUrlsLookup.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/Ccr/CcrDeleteAutoFollowPatternRequest.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/Ccr/CcrDeleteAutoFollowPatternResponse.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/Ccr/CcrFollowInfoRequest.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/Ccr/CcrFollowInfoResponse.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/Ccr/CcrFollowRequest.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/Ccr/CcrFollowResponse.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/Ccr/CcrFollowStatsRequest.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/Ccr/CcrFollowStatsResponse.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/Ccr/CcrForgetFollowerRequest.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/Ccr/CcrForgetFollowerResponse.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/Ccr/CcrGetAutoFollowPatternRequest.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/Ccr/CcrGetAutoFollowPatternResponse.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/Ccr/CcrPauseAutoFollowPatternRequest.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/Ccr/CcrPauseAutoFollowPatternResponse.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/Ccr/CcrPauseFollowRequest.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/Ccr/CcrPauseFollowResponse.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/Ccr/CcrPutAutoFollowPatternRequest.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/Ccr/CcrPutAutoFollowPatternResponse.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/Ccr/CcrResumeAutoFollowPatternRequest.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/Ccr/CcrResumeAutoFollowPatternResponse.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/Ccr/CcrResumeFollowRequest.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/Ccr/CcrResumeFollowResponse.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/Ccr/CcrStatsRequest.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/Ccr/CcrStatsResponse.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/Ccr/CcrUnfollowRequest.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/Ccr/CcrUnfollowResponse.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Client/ElasticsearchClient.Ccr.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Client/ElasticsearchClient.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Ccr/AutoFollowPattern.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Ccr/AutoFollowPatternSummary.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Ccr/AutoFollowStats.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Ccr/AutoFollowedCluster.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Ccr/FollowIndexStats.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Ccr/FollowStats.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Ccr/FollowerIndex.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Ccr/FollowerIndexParameters.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Ccr/ReadException.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Ccr/ShardStats.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Enums/Enums.Ccr.FollowInfo.g.cs
Labels: enhancement, backport 8.0, backport 8.1, 8.x, v8.0.0-alpha.4

#6240 Add Get Mapping API
  src/Elastic.Clients.Elasticsearch/_Generated/Api/ApiUrlsLookup.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/IndexManagement/MappingRequest.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/IndexManagement/MappingResponse.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Client/ElasticsearchClient.IndexManagement.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Client/ElasticsearchClient.g.cs
Labels: enhancement, backport 8.0, backport 8.1, 8.x, backport 8.2
