Repository elastic/elasticsearch-net, pull requests merged in 2022-04, with the labels that each got.

#6248 Add Index Template APIs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/ApiUrlsLookup.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/IndexManagement/DeleteIndexTemplateRequest.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/IndexManagement/DeleteIndexTemplateResponse.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/IndexManagement/ExistsIndexTemplateRequest.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/IndexManagement/ExistsIndexTemplateResponse.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/IndexManagement/IndexTemplateRequest.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/IndexManagement/IndexTemplateResponse.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/IndexManagement/PutIndexTemplateRequest.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/IndexManagement/PutIndexTemplateResponse.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Client/ElasticsearchClient.IndexManagement.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/IndexManagement/DataStream.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/IndexManagement/IndexTemplate.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/IndexManagement/IndexTemplateItem.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/IndexManagement/IndexTemplateMapping.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/IndexManagement/IndexTemplateSummary.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Mapping/AllField.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Mapping/DataStreamTimestamp.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Mapping/IndexField.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Mapping/SizeField.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Mapping/TypeMapping.g.cs
  src/Playground/Program.cs
Labels: enhancement, backport 8.0, backport 8.1, 8.x, backport 8.2, v8.0.0-alpha.5

#6252 Rename `IndexManagement` client property to `Indices`
  src/Elastic.Clients.Elasticsearch/Helpers/BulkAllObservable.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Client/ElasticsearchClient.Indices.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Client/ElasticsearchClient.g.cs
  tests/Tests.Core/ManagedElasticsearch/NodeSeeders/DefaultSeeder.cs
Labels: enhancement, backport 8.0, backport 8.1, 8.x, backport 8.2, v8.0.0-alpha.5

#6263 Fix API versioning validation on NETFX
  src/Elasticsearch.Net/Transport/Pipeline/RequestData.cs
Labels: bug, v7.17.1

#6265 Minor corrections to v8 compatibility doc
  docs/client-concepts/connection/connecting-to-elasticsearch-v8.asciidoc
  tests/Tests/ClientConcepts/Connection/ConnectingToElasticsearchV8.doc.cs
Labels: Docs, backport 7.x, 7.x

#6267 Update connecting guide to document pre-release packages
  docs/client-concepts/high-level/mapping/parent-child-relationships.asciidoc
  docs/connecting.asciidoc
  docs/install.asciidoc
Labels: Docs, backport 8.0, backport 8.1, 8.x, backport 8.2

#6271 Update to 0.3.1 abstractions
  tests/Tests.ClusterLauncher/packages.lock.json
  tests/Tests.Configuration/Tests.Configuration.csproj
  tests/Tests.Configuration/packages.lock.json
  tests/Tests.Core/Tests.Core.csproj
  tests/Tests.Core/packages.lock.json
  tests/Tests.Domain/Tests.Domain.csproj
  tests/Tests.Domain/packages.lock.json
  tests/Tests/packages.lock.json
Labels: Infra, backport 8.0, backport 8.1, backport 8.2

#6259 Fix PositionLength JSON name on AnalyzeToken
  src/Nest/Indices/Analyze/AnalyzeToken.cs
Labels: bug, 6.x, v6.8.11

#6275 Add searchable snapshot action for ILM
  src/Nest/XPack/Ilm/Actions/SearchableSnapshotAction.cs
  src/Nest/XPack/Ilm/LifecycleActions.cs
Labels: 7.x, enhancement, v7.17.2

#6276 Add CopyFrom to SetProcessor
  src/Nest/Ingest/Processors/SetProcessor.cs
Labels: 7.x, enhancement, v7.17.2

#6277 Respond to updated schema response inheritance removal
  src/Elastic.Clients.Elasticsearch/Api/GetAsyncSearchResponse.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/AsyncSearch/AsyncSearchSubmitResponse.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/AsyncSearch/GetAsyncSearchResponse.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/Eql/EqlSearchResponse.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/Eql/GetEqlResponse.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/AsyncSearch/AsyncSearchDocumentResponseBase.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/AsyncSearch/AsyncSearchResponseBase.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Eql/EqlSearchResponseBase.g.cs
Labels: backport 8.0, backport 8.1, 8.x, backport 8.2, v8.0.0-alpha.6

#6285 Add component template APIs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/ApiUrlsLookup.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/Cluster/ClusterDeleteComponentTemplateRequest.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/Cluster/ClusterDeleteComponentTemplateResponse.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/Cluster/ClusterExistsComponentTemplateRequest.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/Cluster/ClusterExistsComponentTemplateResponse.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/Cluster/ClusterGetComponentTemplateRequest.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/Cluster/ClusterGetComponentTemplateResponse.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/Cluster/ClusterPutComponentTemplateRequest.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/Cluster/ClusterPutComponentTemplateResponse.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Client/ElasticsearchClient.Cluster.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Cluster/ComponentTemplate.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Cluster/ComponentTemplateNode.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Cluster/ComponentTemplateSummary.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/IndexManagement/AliasDefinition.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/IndexManagement/IndexState.g.cs
Labels: enhancement, backport 8.0, backport 8.1, 8.x, backport 8.2, v8.0.0-alpha.6

#6289 Add Snapshot APIs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/ApiUrlsLookup.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/Snapshot/CreateSnapshotRequest.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/Snapshot/CreateSnapshotResponse.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/Snapshot/DeleteSnapshotRequest.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/Snapshot/DeleteSnapshotResponse.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/Snapshot/GetSnapshotRequest.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/Snapshot/GetSnapshotResponse.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/Snapshot/SnapshotCleanupRepositoryRequest.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/Snapshot/SnapshotCleanupRepositoryResponse.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/Snapshot/SnapshotCloneRequest.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/Snapshot/SnapshotCloneResponse.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/Snapshot/SnapshotCreateRepositoryRequest.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/Snapshot/SnapshotCreateRepositoryResponse.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/Snapshot/SnapshotDeleteRepositoryRequest.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/Snapshot/SnapshotDeleteRepositoryResponse.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/Snapshot/SnapshotGetRepositoryRequest.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/Snapshot/SnapshotGetRepositoryResponse.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/Snapshot/SnapshotRestoreRequest.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/Snapshot/SnapshotRestoreResponse.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/Snapshot/SnapshotStatusRequest.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/Snapshot/SnapshotStatusResponse.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/Snapshot/SnapshotVerifyRepositoryRequest.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/Snapshot/SnapshotVerifyRepositoryResponse.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Client/ElasticsearchClient.Snapshot.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Client/ElasticsearchClient.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Enums/Enums.Snapshot.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Snapshot/CleanupRepositoryResults.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Snapshot/CompactNodeInfo.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Snapshot/FileCountSnapshotStats.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Snapshot/IndexDetails.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Snapshot/InfoFeatureState.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Snapshot/RepositorySettings.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Snapshot/ShardsStats.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Snapshot/ShardsStatsSummary.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Snapshot/ShardsStatsSummaryItem.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Snapshot/SnapshotIndexStats.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Snapshot/SnapshotInfo.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Snapshot/SnapshotResponseItem.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Snapshot/SnapshotRestore.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Snapshot/SnapshotShardFailure.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Snapshot/SnapshotShardsStatus.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Snapshot/SnapshotStats.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Snapshot/Status.g.cs
Labels: enhancement, backport 8.0, backport 8.1, 8.x, backport 8.2, v8.0.0-alpha.6

#6297 Reintroduce AssemblyInfos target
  Directory.Build.targets
Labels: Infra, 7.x

#6298 Add Autoscaling APIs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/ApiUrlsLookup.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/Autoscaling/AutoscalingDeleteAutoscalingPolicyRequest.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/Autoscaling/AutoscalingDeleteAutoscalingPolicyResponse.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/Autoscaling/AutoscalingGetAutoscalingCapacityRequest.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/Autoscaling/AutoscalingGetAutoscalingCapacityResponse.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/Autoscaling/AutoscalingGetAutoscalingPolicyRequest.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/Autoscaling/AutoscalingGetAutoscalingPolicyResponse.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/Autoscaling/AutoscalingPutAutoscalingPolicyRequest.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/Autoscaling/AutoscalingPutAutoscalingPolicyResponse.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Client/ElasticsearchClient.Autoscaling.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Client/ElasticsearchClient.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Autoscaling/AutoscalingCapacity.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Autoscaling/AutoscalingDecider.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Autoscaling/AutoscalingDeciders.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Autoscaling/AutoscalingNode.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Autoscaling/AutoscalingResources.g.cs
Labels: enhancement, backport 8.0, backport 8.1, 8.x, backport 8.2, v8.0.0-alpha.6

#6302 Add remaining Cluster APIs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/ApiUrlsLookup.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/Cluster/ClusterDeleteVotingConfigExclusionsRequest.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/Cluster/ClusterDeleteVotingConfigExclusionsResponse.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/Cluster/ClusterGetSettingsRequest.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/Cluster/ClusterGetSettingsResponse.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/Cluster/ClusterPostVotingConfigExclusionsRequest.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/Cluster/ClusterPostVotingConfigExclusionsResponse.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/Cluster/ClusterPutSettingsRequest.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/Cluster/ClusterPutSettingsResponse.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/Cluster/ClusterRemoteInfoRequest.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/Cluster/ClusterRemoteInfoResponse.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/Cluster/ClusterRerouteRequest.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/Cluster/ClusterRerouteResponse.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/Cluster/ClusterStatsRequest.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/Cluster/ClusterStatsResponse.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Client/ElasticsearchClient.Cluster.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Cluster/CharFilterTypes.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Cluster/ClusterFileSystem.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Cluster/ClusterIndices.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Cluster/ClusterIndicesShards.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Cluster/ClusterIndicesShardsIndex.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Cluster/ClusterIngest.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Cluster/ClusterJvm.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Cluster/ClusterJvmMemory.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Cluster/ClusterJvmVersion.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Cluster/ClusterNetworkTypes.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Cluster/ClusterNodeCount.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Cluster/ClusterNodes.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Cluster/ClusterOperatingSystem.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Cluster/ClusterOperatingSystemArchitecture.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Cluster/ClusterOperatingSystemName.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Cluster/ClusterOperatingSystemPrettyName.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Cluster/ClusterProcess.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Cluster/ClusterProcessCpu.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Cluster/ClusterProcessOpenFileDescriptors.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Cluster/ClusterProcessor.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Cluster/ClusterShardMetrics.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Cluster/Command.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Cluster/CommandAllocatePrimaryAction.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Cluster/CommandAllocateReplicaAction.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Cluster/CommandCancelAction.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Cluster/CommandMoveAction.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Cluster/FieldTypes.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Cluster/FieldTypesMappings.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Cluster/IndexingPressure.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Cluster/IndexingPressureMemory.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Cluster/IndexingPressureMemorySummary.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Cluster/IndicesVersions.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Cluster/NodePackagingType.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Cluster/OperatingSystemMemoryInfo.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Cluster/RerouteDecision.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Cluster/RerouteExplanation.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Cluster/RerouteParameters.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Cluster/RuntimeFieldTypes.g.cs
Labels: enhancement, backport 8.0, backport 8.1, 8.x, backport 8.2, v8.0.0-alpha.6

#6306 Add List Dandling Indices API
  src/Elastic.Clients.Elasticsearch/_Generated/Api/ApiUrlsLookup.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/DanglingIndices/DanglingIndicesListDanglingIndicesRequest.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/DanglingIndices/DanglingIndicesListDanglingIndicesResponse.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Client/ElasticsearchClient.DanglingIndices.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Client/ElasticsearchClient.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/DanglingIndices/DanglingIndex.g.cs
Labels: 7.x, enhancement, backport 8.0, backport 8.1, backport 8.2, v8.0.0-alpha.6

#6310 Add Features APIs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/ApiUrlsLookup.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/Features/FeaturesGetFeaturesRequest.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/Features/FeaturesGetFeaturesResponse.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/Features/FeaturesResetFeaturesRequest.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/Features/FeaturesResetFeaturesResponse.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Client/ElasticsearchClient.Features.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Client/ElasticsearchClient.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Features/Feature.g.cs
Labels: enhancement, backport 8.0, backport 8.1, 8.x, backport 8.2, v8.0.0-alpha.6

#6318 Add License APIs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/ApiUrlsLookup.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/License/DeleteLicenseRequest.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/License/DeleteLicenseResponse.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/License/GetLicenseRequest.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/License/GetLicenseResponse.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/License/LicenseGetBasicStatusRequest.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/License/LicenseGetBasicStatusResponse.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/License/LicenseGetTrialStatusRequest.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/License/LicenseGetTrialStatusResponse.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/License/LicensePostRequest.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/License/LicensePostResponse.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/License/LicensePostStartBasicRequest.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/License/LicensePostStartBasicResponse.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/License/LicensePostStartTrialRequest.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/License/LicensePostStartTrialResponse.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Client/ElasticsearchClient.License.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Client/ElasticsearchClient.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/License/Acknowledgement.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/License/License.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/License/LicenseInformation.g.cs
Labels: enhancement, backport 8.0, backport 8.1, 8.x, backport 8.2, v8.0.0-alpha.6

#6326 Add Transform APIs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/ApiUrlsLookup.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/TransformManagement/TransformDeleteTransformRequest.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/TransformManagement/TransformDeleteTransformResponse.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/TransformManagement/TransformGetTransformRequest.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/TransformManagement/TransformGetTransformResponse.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/TransformManagement/TransformGetTransformStatsRequest.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/TransformManagement/TransformGetTransformStatsResponse.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/TransformManagement/TransformPreviewTransformRequest.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/TransformManagement/TransformPreviewTransformResponse.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/TransformManagement/TransformPutTransformRequest.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/TransformManagement/TransformPutTransformResponse.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/TransformManagement/TransformStartTransformRequest.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/TransformManagement/TransformStartTransformResponse.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/TransformManagement/TransformStopTransformRequest.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/TransformManagement/TransformStopTransformResponse.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/TransformManagement/TransformUpdateTransformRequest.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/TransformManagement/TransformUpdateTransformResponse.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/TransformManagement/TransformUpgradeTransformsRequest.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/TransformManagement/TransformUpgradeTransformsResponse.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Client/ElasticsearchClient.TransformManagement.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Client/ElasticsearchClient.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/TransformManagement/CheckpointStats.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/TransformManagement/Checkpointing.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/TransformManagement/Destination.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/TransformManagement/Latest.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/TransformManagement/Pivot.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/TransformManagement/RetentionPolicy.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/TransformManagement/RetentionPolicyContainer.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/TransformManagement/Settings.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/TransformManagement/Source.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/TransformManagement/SyncContainer.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/TransformManagement/TimeSync.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/TransformManagement/TransformIndexerStats.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/TransformManagement/TransformProgress.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/TransformManagement/TransformStats.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/TransformManagement/TransformSummary.g.cs
Labels: enhancement, backport 8.0, backport 8.1, 8.x, backport 8.2, v8.0.0-alpha.6

#6338 Adds DeleteScript and Explain APIs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/ApiUrlsLookup.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/DeleteScriptRequest.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/DeleteScriptResponse.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/ExplainRequest.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/ExplainResponse.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/ScriptRequest.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/ScriptResponse.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/ScriptsPainlessExecuteRequest.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/ScriptsPainlessExecuteResponse.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Client/ElasticsearchClient.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/PainlessContextSetup.g.cs
Labels: enhancement, backport 8.0, backport 8.1, 8.x, backport 8.2, v8.0.0-alpha.6

#6343 Minor API fixes
  .ci/DockerFile
  .ci/make.sh
  .ci/readme.md
  .ci/run-repository.ps1
  .ci/run-repository.sh
  .ci/run-tests.ps1
  .ci/test-matrix.yml
  .github/workflows/integration-jobs.yml
  .github/workflows/make-bump.yml
  .github/workflows/make-release-notes.yml
  .github/workflows/stale-jobs.yml
  .github/workflows/test-jobs.yml
  .github/workflows/unified-release.yml
  build/scripts/packages.lock.json
  global.json
  src/Elastic.Clients.Elasticsearch/Api/SqlQueryResponse.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/ApiUrlsLookup.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/Ml/MlGetTrainedModelsRequest.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/Ml/MlGetTrainedModelsResponse.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/Snapshot/SnapshotRestoreRequest.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/Sql/SqlQueryResponse.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Client/ElasticsearchClient.Ml.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Enums/Enums.Ml.g.cs
Labels: enhancement, backport 8.0, backport 8.1, 8.x, backport 8.2, v8.0.0-alpha.7

#6355 Fix nuget cmd after SDK update
  .github/workflows/test-jobs.yml
Labels: Infra, backport 8.0, backport 8.1, 8.x, backport 8.2

#6359 Async fixes
  build/scripts/scripts.fsproj
  src/Elastic.Clients.Elasticsearch/Elastic.Clients.Elasticsearch.csproj
  src/Elastic.Clients.Elasticsearch/Helpers/BulkAllObservable.cs
  src/Elastic.Clients.Elasticsearch/packages.lock.json
Labels: Infra, backport 8.0, backport 8.1, 8.x, backport 8.2

#6363 Remove non-stable APIs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/ApiUrlsLookup.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/Features/FeaturesResetFeaturesRequest.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/Features/FeaturesResetFeaturesResponse.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/IndexManagement/DiskUsageRequest.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/IndexManagement/DiskUsageResponse.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/IndexManagement/FieldUsageStatsRequest.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/IndexManagement/FieldUsageStatsResponse.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/KnnSearchRequest.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/KnnSearchResponse.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/Ml/MlInferTrainedModelDeploymentRequest.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/Ml/MlInferTrainedModelDeploymentResponse.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/Ml/MlPutTrainedModelVocabularyRequest.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/Ml/MlPutTrainedModelVocabularyResponse.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/Ml/MlStartTrainedModelDeploymentRequest.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/Ml/MlStartTrainedModelDeploymentResponse.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/Ml/MlStopTrainedModelDeploymentRequest.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/Ml/MlStopTrainedModelDeploymentResponse.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/ScriptsPainlessExecuteRequest.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/ScriptsPainlessExecuteResponse.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/SearchableSnapshots/SearchableSnapshotsCacheStatsRequest.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/SearchableSnapshots/SearchableSnapshotsCacheStatsResponse.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/SearchableSnapshots/SearchableSnapshotsClearCacheRequest.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/SearchableSnapshots/SearchableSnapshotsClearCacheResponse.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/Tasks/GetTasksRequest.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/Tasks/GetTasksResponse.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/Tasks/TasksCancelRequest.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/Tasks/TasksCancelResponse.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/Tasks/TasksListRequest.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/Tasks/TasksListResponse.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Client/ElasticsearchClient.Features.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Client/ElasticsearchClient.Indices.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Client/ElasticsearchClient.Ml.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Client/ElasticsearchClient.SearchableSnapshots.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Client/ElasticsearchClient.Tasks.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Client/ElasticsearchClient.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Enums/Enums.Ml.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Enums/Enums.Tasks.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Ml/PredictedValue.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Ml/TopClassEntry.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Ml/TrainedModelAllocation.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Ml/TrainedModelAllocationRoutingTable.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Ml/TrainedModelAllocationTaskParameters.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Ml/TrainedModelEntities.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/PainlessContextSetup.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Query.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/SearchableSnapshots/Node.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/SearchableSnapshots/Shared.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/TaskFailure.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Tasks/NodeTasks.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Tasks/ParentTaskInfo.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Tasks/TaskInfos.g.cs
Labels: backport 8.0, backport 8.1, 8.x, backport 8.2, v8.0.0-alpha.8

#6367 Fully implement and test DataStreamName(s)
  src/Elastic.Clients.Elasticsearch/Common/DataStreamNames/DataStreamName.cs
  src/Elastic.Clients.Elasticsearch/Common/DataStreamNames/DataStreamNames.cs
  src/Elastic.Clients.Elasticsearch/Common/Infer/DataStreamName/DataStreamNames.cs
  src/Elastic.Clients.Elasticsearch/Common/Infer/Field/Field.cs
  src/Elastic.Clients.Elasticsearch/Common/Infer/Fields/Fields.cs
  src/Elastic.Clients.Elasticsearch/Common/Infer/Id/Id.cs
  src/Elastic.Clients.Elasticsearch/Common/Infer/Id/Ids.cs
  src/Elastic.Clients.Elasticsearch/Common/Infer/Indices/Indices.cs
  src/Elastic.Clients.Elasticsearch/Common/Infer/Inferrer.cs
  src/Elastic.Clients.Elasticsearch/Common/Infer/JoinFieldRouting/Routing.cs
  src/Elastic.Clients.Elasticsearch/Common/Infer/Name/Name.cs
  src/Elastic.Clients.Elasticsearch/Common/Infer/Name/Names.cs
  src/Elastic.Clients.Elasticsearch/Common/Infer/NodeId/NodeIds.cs
  src/Elastic.Clients.Elasticsearch/Common/Infer/PropertyName/PropertyName.cs
  src/Elastic.Clients.Elasticsearch/Common/Infer/RelationName/RelationName.cs
  src/Elastic.Clients.Elasticsearch/FutureGenerated/CommonOptions/TimeUnit/Time.cs
  src/Elastic.Clients.Elasticsearch/FutureGenerated/FutureGenerated.cs
  tests/Tests.Configuration/tests.default.yaml
  tests/Tests/Common/DataStreamNames/DataStreamNameTests.cs
  tests/Tests/Common/DataStreamNames/DataStreamNamesTests.cs
  tests/Tests/Common/TimeUnit/TimeUnits.doc.cs
  tests/Tests/_VerifySnapshots/DataStreamNameTests.DataStreamName_SerialisationTest.verified.txt
  tests/Tests/_VerifySnapshots/DataStreamNamesTests.DataStreamNames_SerialisationTest.verified.txt
Labels: backport 8.1, 8.x, backport 8.2, v8.0.0-alpha.8

#6388 Cleanup property mapping types
  src/Elastic.Clients.Elasticsearch.JsonNetSerializer/ConnectionSettingsAwareSerializerBase.PropertyMappingProvider.cs
  src/Elastic.Clients.Elasticsearch.JsonNetSerializer/Elastic.Clients.Elasticsearch.JsonNetSerializer.csproj
  src/Elastic.Clients.Elasticsearch.JsonNetSerializer/packages.lock.json
  src/Elastic.Clients.Elasticsearch/Common/Configuration/ClrPropertyMapping.cs
  src/Elastic.Clients.Elasticsearch/Common/Configuration/ElasticsearchClientSettings.cs
  src/Elastic.Clients.Elasticsearch/Common/Configuration/IElasticsearchClientSettings.cs
  src/Elastic.Clients.Elasticsearch/Common/Infer/DefaultPropertyMappingProvider.cs
  src/Elastic.Clients.Elasticsearch/Common/Infer/Field/FieldExpressionVisitor.cs
  src/Elastic.Clients.Elasticsearch/Common/Infer/IPropertyMapping.cs
  src/Elastic.Clients.Elasticsearch/Common/Infer/IPropertyMappingProvider.cs
  src/Elastic.Clients.Elasticsearch/Common/Infer/PropertyMapping.cs
  src/Elastic.Clients.Elasticsearch/CrossPlatform/IsExternalInit.cs
  src/Elastic.Clients.Elasticsearch/Serialization/IgnoreAttribute.cs
  src/Playground/Person.cs
  src/Playground/Program.cs
  tests/Tests.Core/Xunit/ElasticsearchXunitRunOptions.cs
  tests/Tests.Domain/SourceOnlyObject.cs
  tests/Tests.Domain/SourceOnlyUsingBuiltInConverter.cs
  tests/Tests/XunitBootstrap.cs
Labels: enhancement, backport 8.0, backport 8.1, 8.x, backport 8.2, v8.0.0-alpha.9

#6392 Tweak benchmark setup
  benchmarks/Benchmarks/Program.cs
Labels: Infra, backport 8.0, backport 8.1, 8.x, backport 8.2, v8.0.0-alpha.9

#6396 Complete JoinFieldConverter
  src/Elastic.Clients.Elasticsearch/Client/ElasticsearchClient-Manual.cs
  src/Elastic.Clients.Elasticsearch/Common/Infer/JoinFieldConverter.cs
  src/Elastic.Clients.Elasticsearch/Serialization/DefaultRequestResponseSerializer.cs
  src/Elastic.Clients.Elasticsearch/Serialization/DefaultSourceSerializer.cs
  src/Elastic.Clients.Elasticsearch/Types/Mapping/Properties.cs
  src/PlaygroundV7x/Person.cs
  src/PlaygroundV7x/Program.cs
  tests/Tests.Configuration/tests.default.yaml
  tests/Tests/ClientConcepts/HighLevel/Mapping/AutoMap.doc.cs
  tests/Tests/ClientConcepts/HighLevel/Mapping/ParentChildRelationships.doc.cs
  tests/Tests/Tests.csproj
Labels: enhancement, backport 8.0, backport 8.1, 8.x, backport 8.2, v8.0.0-alpha.9
