Repository elastic/elasticsearch-net, pull requests merged in 2022-01, with the labels that each got.

#6070 Add IgnoreUnmapped to GeoDistanceQuery, GeoBoundingBoxQuery and GeoPolygon
  src/Nest/QueryDsl/Geo/BoundingBox/GeoBoundingBoxQuery.cs
  src/Nest/QueryDsl/Geo/Distance/GeoDistanceQuery.cs
  src/Nest/QueryDsl/Geo/Polygon/GeoPolygonQuery.cs
  tests/Tests/QueryDsl/Geo/BoundingBox/GeoBoundingBoxQueryUsageTests.cs
  tests/Tests/QueryDsl/Geo/Distance/GeoDistanceQueryUsageTests.cs
  tests/Tests/QueryDsl/Geo/Polygon/GeoPolygonQueryUsageTests.cs
Labels: Feature, v7.17.0, backport 7.17

#6085 Support version on ingest pipelines
  build/scripts/ReleaseNotes.fs
  build/scripts/XmlDocPatcher.fs
  src/Nest/Ingest/Pipeline.cs
  src/Nest/Ingest/Processor.cs
  src/Nest/Ingest/PutPipeline/PutPipelineRequest.cs
  tests/Tests.Configuration/tests.default.yaml
  tests/Tests.YamlRunner/SkipList.fs
  tests/Tests/Ingest/PipelineCrudTests.cs
Labels: bug, backport 7.x, v7.17.0

#6088 Add missing fields for IpProperty
  src/Nest/Mapping/Types/Specialized/Ip/IpAttribute.cs
  src/Nest/Mapping/Types/Specialized/Ip/IpProperty.cs
Labels: bug, backport 7.x, v7.17.0

#6090 Support deserialisation of simple scripts
  src/Nest/CommonOptions/Scripting/ScriptFormatter.cs
  tests/Tests.Reproduce/GitHubIssue5684.cs
Labels: bug, backport 7.x, v7.17.0

#6091 Add missing TermVectorOption
  src/Nest/Mapping/TermVectorOption.cs
Labels: bug, backport 7.x, v7.17.0

#6094 Add shard_stats to primary index stats
  src/Nest/Indices/Monitoring/IndicesStats/IndexStats.cs
  src/Nest/Indices/Monitoring/IndicesStats/ShardTotalStats.cs
Labels: Feature, backport 7.x, v7.17.0

#6095 Update boxplot to handle non-numeric values
  src/Nest/Aggregations/AggregateFormatter.cs
  src/Nest/Aggregations/Metric/Boxplot/BoxplotAggregate.cs
  src/Nest/CommonAbstractions/SerializationBehavior/JsonFormatters/NullableStringBooleanFormatter.cs
  tests/Tests.Reproduce/GitHubIssue6050.cs
Labels: bug, backport 7.x, v7.17.0
