Repository elastic/elasticsearch-net, pull requests merged in 2023-08, with the labels that each got.

#7869 Add support for `SimpleQueryStringQuery.flags` property
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Enums/Enums.Aggregations.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Enums/Enums.Analysis.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Enums/Enums.Cluster.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Enums/Enums.Core.Search.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Enums/Enums.Enrich.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Enums/Enums.Eql.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Enums/Enums.IndexManagement.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Enums/Enums.Ingest.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Enums/Enums.Mapping.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Enums/Enums.Ml.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Enums/Enums.NoNamespace.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Enums/Enums.QueryDsl.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Enums/Enums.Tasks.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Enums/Enums.Watcher.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/QueryDsl/SimpleQueryStringQuery.g.cs
Labels: Feature, 8.x, backport 8.9, v8.9.2

#7875 Regenerate client using latest spec
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Core/MSearch/MultisearchBody.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Core/Search/PointInTimeReference.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/IndexManagement/IndexSettings.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/IndexManagement/IndexingSlowlogSettings.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/IndexManagement/IndexingSlowlogTresholds.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/IndexManagement/SlowlogTresholds.g.cs
Labels: bug, 8.x, backport 8.9, v8.9.2

#7880 Refactor client overloads
  src/Elastic.Clients.Elasticsearch/Client/ElasticsearchClient.cs
  src/Elastic.Clients.Elasticsearch/Client/NamespacedClientProxy.cs
Labels: bug, 8.x, backport 8.9, v8.9.2

#7883 Remove leading `/` character from API urls
  src/Elastic.Clients.Elasticsearch/Client/ElasticsearchClient.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/ApiUrlLookup.g.cs
Labels: bug, 8.x, backport 8.9, v8.9.2

#7891 Add release notes for 8.9.2
  docs/release-notes/release-notes-8.9.2.asciidoc
  docs/release-notes/release-notes.asciidoc
Labels: Docs, 8.x, backport 8.9

#7893 Add basic NEST -> v8 migration guide
  docs/index.asciidoc
  docs/migration-guide.asciidoc
Labels: Docs, backport 8.0, backport 8.1, 8.x, backport 8.2, backport 8.3, backport 8.4, backport 8.5, backport 8.6, backport 8.7, backport 8.8, backport 8.9

#7914 Update `Elastic.Transport` dependency
  benchmarks/Benchmarks/packages.lock.json
  benchmarks/Profiling/packages.lock.json
  src/Elastic.Clients.Elasticsearch.JsonNetSerializer/packages.lock.json
  src/Elastic.Clients.Elasticsearch/Elastic.Clients.Elasticsearch.csproj
  src/Elastic.Clients.Elasticsearch/packages.lock.json
  src/Playground/packages.lock.json
  tests/Tests.ClusterLauncher/packages.lock.json
  tests/Tests.Core/packages.lock.json
  tests/Tests.Domain/packages.lock.json
  tests/Tests/Tests.csproj
  tests/Tests/packages.lock.json
Labels: 8.x, backport 8.9, v8.9.3, backport 8.10
