Repository elastic/elasticsearch-net, pull requests merged in 2023-07, with the labels that each got.

#7764 [DOCS] Adds getting started content based on the template
  docs/getting-started.asciidoc
  docs/images/create-api-key.png
  docs/images/es-endpoint.jpg
  docs/index.asciidoc
Labels: Docs, 8.x, backport 8.8, backport 8.9

#7766 [DOCS] Adds getting started content based on the template (#7764)
  docs/getting-started.asciidoc
  docs/images/create-api-key.png
  docs/images/es-endpoint.jpg
  docs/index.asciidoc
Labels: Docs, 8.x

#7770 [Backport 8.7][DOCS] Adds getting started content based on the template
  docs/getting-started.asciidoc
  docs/images/create-api-key.png
  docs/images/es-endpoint.jpg
  docs/index.asciidoc
Labels: Docs, backport 8.1, 8.x, backport 8.2, backport 8.3, backport 8.4, backport 8.5, backport 8.6

#7768 [DOCS] Changes getting started button link on landing page
  docs/index-custom-title-page.html
Labels: Docs, 8.x, backport 8.8, backport 8.9

#7753 Number converters should not fall through and throw exceptions in non NETCore builds
  src/Elastic.Clients.Elasticsearch/Serialization/DoubleWithFractionalPortionConverter.cs
  src/Elastic.Clients.Elasticsearch/Serialization/FloatWithFractionalPortionConverter.cs
Labels: bug, backport 8.1, 8.x, backport 8.2, backport 8.3, backport 8.4, backport 8.5, backport 8.6, backport 8.7, backport 8.8

#7738 Complted buckets JSON converter
  src/Elastic.Clients.Elasticsearch/Serialization/UnionConverter.cs
Labels: bug, backport 8.1, 8.x, backport 8.2, backport 8.3, backport 8.4, backport 8.5, backport 8.6, backport 8.7, backport 8.8, v8.1.2

#7737 Boosted non-exhaustive enum deserialization
  src/Elastic.Clients.Elasticsearch/Core/IEnumStruct.cs
  src/Elastic.Clients.Elasticsearch/Serialization/EnumStructConverter.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Enums/Enums.Aggregations.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Enums/Enums.Analysis.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Enums/Enums.Cluster.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Enums/Enums.Core.Search.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Enums/Enums.Enrich.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Enums/Enums.Eql.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Enums/Enums.IndexManagement.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Enums/Enums.Ingest.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Enums/Enums.Mapping.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Enums/Enums.Ml.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Enums/Enums.NoNamespace.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Enums/Enums.QueryDsl.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Enums/Enums.Tasks.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Enums/Enums.Watcher.g.cs
Labels: bug, enhancement, backport 8.1, 8.x, backport 8.2, backport 8.3, backport 8.4, backport 8.5, backport 8.6, backport 8.7, backport 8.8, v8.1.2

#7736 Optimized `FieldConverter`
  src/Elastic.Clients.Elasticsearch/Core/Infer/Field/FieldConverter.cs
Labels: enhancement, backport 8.1, 8.x, backport 8.2, backport 8.3, backport 8.4, backport 8.5, backport 8.6, backport 8.7, backport 8.8

#7735 Removed unused `JsonIgnore`
  src/Elastic.Clients.Elasticsearch/Core/Infer/Field/Field.cs
Labels: enhancement, backport 8.1, 8.x, backport 8.2, backport 8.3, backport 8.4, backport 8.5, backport 8.6, backport 8.7, backport 8.8

#7733 Fixed the equality contract on Metrics type
  src/Elastic.Clients.Elasticsearch/Core/Infer/Metric/Metrics.cs
Labels: bug, backport 8.1, 8.x, backport 8.2, backport 8.3, backport 8.4, backport 8.5, backport 8.6, backport 8.7, backport 8.8

#7730 Refactoring and tiny behavior fix for Ids
  src/Elastic.Clients.Elasticsearch/Core/Infer/Id/Ids.cs
  src/Elastic.Clients.Elasticsearch/Core/Infer/Id/IdsConverter.cs
Labels: enhancement, backport 8.1, 8.x, backport 8.2, backport 8.3, backport 8.4, backport 8.5, backport 8.6, backport 8.7, backport 8.8

#7790 Add release notes for 8.1.2
  docs/release-notes/release-notes-8.1.2.asciidoc
  docs/release-notes/release-notes.asciidoc
Labels: Docs, backport 8.1, 8.x, backport 8.2, backport 8.3, backport 8.4, backport 8.5, backport 8.6, backport 8.7, backport 8.8, backport 8.9

#7793 Community backports for 8.1.3
  src/Elastic.Clients.Elasticsearch/Api/ResponseItem.cs
  src/Elastic.Clients.Elasticsearch/Core/IEnumStruct.cs
  src/Elastic.Clients.Elasticsearch/Core/Infer/Field/Field.cs
  src/Elastic.Clients.Elasticsearch/Core/Infer/Field/FieldConverter.cs
  src/Elastic.Clients.Elasticsearch/Core/Infer/Id/Ids.cs
  src/Elastic.Clients.Elasticsearch/Core/Infer/Id/IdsConverter.cs
  src/Elastic.Clients.Elasticsearch/Core/Infer/Metric/Metrics.cs
  src/Elastic.Clients.Elasticsearch/Serialization/DoubleWithFractionalPortionConverter.cs
  src/Elastic.Clients.Elasticsearch/Serialization/EnumStructConverter.cs
  src/Elastic.Clients.Elasticsearch/Serialization/FloatWithFractionalPortionConverter.cs
  src/Elastic.Clients.Elasticsearch/Serialization/UnionConverter.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Enums/Enums.Aggregations.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Enums/Enums.Analysis.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Enums/Enums.Cluster.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Enums/Enums.Core.Search.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Enums/Enums.Enrich.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Enums/Enums.Eql.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Enums/Enums.IndexManagement.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Enums/Enums.Ingest.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Enums/Enums.Mapping.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Enums/Enums.Ml.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Enums/Enums.NoNamespace.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Enums/Enums.QueryDsl.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Enums/Enums.Tasks.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Enums/Enums.Watcher.g.cs
Labels: 8.x, backport 8.2, backport 8.3, backport 8.4, backport 8.5, backport 8.6, backport 8.7, backport 8.8, backport 8.9

#7811 Fix localization issue with floating-point deserialization from string
  src/Elastic.Clients.Elasticsearch/Core/Fields/FieldValue.cs
  src/Elastic.Clients.Elasticsearch/Serialization/DoubleWithFractionalPortionConverter.cs
  src/Elastic.Clients.Elasticsearch/Serialization/FloatWithFractionalPortionConverter.cs
Labels: bug, backport 8.1, 8.x, backport 8.2, backport 8.3, backport 8.4, backport 8.5, backport 8.6, backport 8.7, backport 8.8, backport 8.9, v8.1.3

#7824 Add release notes for 8.1.3
  docs/release-notes/release-notes-8.1.3.asciidoc
  docs/release-notes/release-notes.asciidoc
Labels: backport 8.1, 8.x, backport 8.2, backport 8.3, backport 8.4, backport 8.5, backport 8.6, backport 8.7, backport 8.8, backport 8.9

#7843 [DOCS] Restructures repo README
  README.md
  docs/getting-started.asciidoc
Labels: Docs, backport 8.1, backport 8.2, backport 8.3, backport 8.4, backport 8.5, backport 8.6, backport 8.7, backport 8.8, backport 8.9

#7847 [8.7][DOCS] Restructures repo README
  README.md
  docs/getting-started.asciidoc
Labels: Docs, backport 8.1, backport 8.2, backport 8.3, backport 8.4, backport 8.5, backport 8.6

#7840 Update `Elastic.*` dependencies
  benchmarks/Benchmarks/packages.lock.json
  benchmarks/Profiling/packages.lock.json
  build/scripts/packages.lock.json
  build/scripts/scripts.fsproj
  src/Elastic.Clients.Elasticsearch.JsonNetSerializer/packages.lock.json
  src/Elastic.Clients.Elasticsearch/Elastic.Clients.Elasticsearch.csproj
  src/Elastic.Clients.Elasticsearch/packages.lock.json
  src/Playground/packages.lock.json
  tests/Tests.ClusterLauncher/packages.lock.json
  tests/Tests.Configuration/Tests.Configuration.csproj
  tests/Tests.Configuration/packages.lock.json
  tests/Tests.Core/ManagedElasticsearch/Clusters/ClientTestClusterBase.cs
  tests/Tests.Core/Tests.Core.csproj
  tests/Tests.Core/packages.lock.json
  tests/Tests.Domain/Tests.Domain.csproj
  tests/Tests.Domain/packages.lock.json
  tests/Tests/Tests.csproj
  tests/Tests/packages.lock.json
Labels: bug, 8.x, backport 8.9, v8.9.0

#7841 Fix typing of `BulkUpdateOperation.RetryOnConflict`
  src/Elastic.Clients.Elasticsearch/Types/Core/Bulk/BulkUpdateOperation.cs
Labels: bug, 8.x, backport 8.9, v8.9.0

#7839 Use `Stringified<boolean>` for `preserve_original` and `indexing_complete`
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Analysis/AsciiFoldingTokenFilter.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Analysis/EdgeNGramTokenFilter.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Analysis/MultiplexerTokenFilter.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Analysis/NGramTokenFilter.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Analysis/PatternCaptureTokenFilter.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Analysis/WordDelimiterGraphTokenFilter.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Analysis/WordDelimiterTokenFilter.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Enums/Enums.Aggregations.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Enums/Enums.Analysis.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Enums/Enums.Cluster.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Enums/Enums.Core.Search.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Enums/Enums.Enrich.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Enums/Enums.Eql.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Enums/Enums.IndexManagement.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Enums/Enums.Ingest.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Enums/Enums.Mapping.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Enums/Enums.Ml.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Enums/Enums.NoNamespace.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Enums/Enums.QueryDsl.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Enums/Enums.Tasks.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Enums/Enums.Watcher.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/IndexManagement/IndexSettingsLifecycle.g.cs
Labels: bug, 8.x, backport 8.9, v8.9.0

#7864 Fix `TextExpansionQuery` definition
  src/Elastic.Clients.Elasticsearch/_Generated/Types/QueryDsl/TextExpansionQuery.g.cs
Labels: bug, 8.x, backport 8.9, v8.9.1
