Repository elastic/elasticsearch-net, pull requests merged in 2023-11, with the labels that each got.

#7965 Fix `Stringified` converters
  src/Elastic.Clients.Elasticsearch.Shared/Serialization/Stringified.cs
Labels: 8.x, backport 8.10, backport 8.11

#7979 Add workaround for stringified properties which are not marked properly in specification
  src/Elastic.Clients.Elasticsearch.Shared/Serialization/DefaultRequestResponseSerializer.cs
Labels: bug, 8.x, backport 8.11, v8.11.0

#7984 Add release notes for 8.11.0
  docs/release-notes/release-notes-8.11.0.asciidoc
  docs/release-notes/release-notes.asciidoc
Labels: Docs, 8.x, backport 8.11

#7989 [DOCS] Adds a signpost for downloading ES or signing-up for ESS
  README.md
Labels: Docs, backport 8.11
