Repository elastic/elasticsearch-net, pull requests merged in 2023-03, with the labels that each got.

#7311 Add support for range queries (date and numeric).
  Elasticsearch.sln
  exclusion.dic
  src/Elastic.Clients.Elasticsearch/Core/Exceptions/ThrowHelper.cs
  src/Elastic.Clients.Elasticsearch/Serialization/TermsAggregateSerializationHelper.cs
  src/Elastic.Clients.Elasticsearch/Types/Aggregations/AggregateDictionaryConverter.cs
  src/Elastic.Clients.Elasticsearch/Types/QueryDsl/RangeQuery.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Enums/Enums.QueryDsl.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/QueryDsl/DateRangeQuery.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/QueryDsl/NumberRangeQuery.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/QueryDsl/Query.g.cs
  tests/Tests/Serialization/Queries/RangeQuerySerializationTests.cs
  tests/Tests/Serialization/SerializerTestBase.cs
  tests/Tests/Serialization/SuggesterSerializationTests.cs
  tests/Tests/_VerifySnapshots/RangeQuerySerializationTests.DateRangeQuery_QueryContainer_SerializesCorrectly.verified.txt
  tests/Tests/_VerifySnapshots/RangeQuerySerializationTests.DateRangeQuery_SerializesCorrectly.verified.txt
  tests/Tests/_VerifySnapshots/RangeQuerySerializationTests.DateRangeQuery_WithFormat_SerializesCorrectly.verified.txt
  tests/Tests/_VerifySnapshots/RangeQuerySerializationTests.Fluent_DateRangeQuery_QueryContainer_SerializesCorrectly.verified.txt
  tests/Tests/_VerifySnapshots/RangeQuerySerializationTests.Fluent_NumberRangeQuery_QueryContainer_SerializesCorrectly.verified.txt
  tests/Tests/_VerifySnapshots/RangeQuerySerializationTests.NumberRangeQuery_QueryContainer_SerializesCorrectly.verified.txt
  tests/Tests/_VerifySnapshots/RangeQuerySerializationTests.NumberRangeQuery_SerializesCorrectly.verified.txt
Labels: enhancement, backport 8.0, backport 8.1, 8.x, backport 8.2, backport 8.3, backport 8.4, backport 8.5, backport 8.6, v8.1.0, backport 8.7

#7320 Add support for bucket sort aggregation.
  src/Elastic.Clients.Elasticsearch/Types/Aggregations/AggregateDictionaryConverter.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Aggregations/Aggregation.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Aggregations/BucketSortAggregation.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Aggregations/TopHitsAggregation.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Aggregations/TopMetricsAggregation.g.cs
  tests/Tests/Aggregations/Pipeline/BucketSortAggregationUsageTests.cs
Labels: enhancement, backport 8.1, 8.x, backport 8.2, backport 8.3, backport 8.4, backport 8.5, backport 8.6, v8.1.0, backport 8.7

#7337 Fix code-gen for dynamic_templates.
  .github/workflows/integration-jobs.yml
  src/Elastic.Clients.Elasticsearch/_Generated/Types/AggregateOrderConverter.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Aggregations/AggregateDictionary.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Aggregations/Buckets.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Aggregations/FieldDateMath.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Aggregations/Percentiles.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Analysis/Analyzers.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Analysis/CharFilters.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Analysis/Normalizers.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Analysis/TokenFilters.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Analysis/Tokenizers.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/ByteSize.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Core/Context.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Core/MultiGetResponseItem.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Core/MultiSearchResponseItem.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Core/SourceConfig.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Core/SourceConfigParam.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Core/TrackHits.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/ExpandWildcardsConverter.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/FeaturesConverter.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Fuzziness.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/GeoHashPrecision.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/GeoLocation.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Mapping/Properties.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Mapping/TypeMapping.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/QueryDsl/Like.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/QueryDsl/TermsQueryField.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Script.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Slices.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/StopWordsConverter.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Tasks/TaskInfos.g.cs
  tests/Tests/IndexManagement/CreateIndexSerializationTests.cs
  tests/Tests/IndexManagement/GetIndexSerializationTests.cs
  tests/Tests/_VerifySnapshots/CreateIndexSerializationTests.CreateIndexWithDynamicTemplates_SerializesCorrectly.verified.txt
Labels: bug, backport 8.0, backport 8.1, 8.x, backport 8.2, backport 8.3, backport 8.4, backport 8.5, backport 8.6, backport 8.7, v8.0.7

#7347 Add release notes for 8.0.7.
  docs/release-notes/release-notes-8.0.7.asciidoc
  docs/release-notes/release-notes.asciidoc
Labels: Docs, backport 8.0, backport 8.1, 8.x, backport 8.2, backport 8.3, backport 8.4, backport 8.5, backport 8.6, backport 8.7

#7364 Add support for raw JSON query.
  src/Elastic.Clients.Elasticsearch/Types/QueryDsl/Query.cs
  src/Elastic.Clients.Elasticsearch/Types/QueryDsl/QueryDescriptor.cs
  src/Elastic.Clients.Elasticsearch/Types/QueryDsl/RangeQuery.cs
  src/Elastic.Clients.Elasticsearch/Types/QueryDsl/RawJsonQuery.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/QueryDsl/Query.g.cs
  tests/Tests/QueryDsl/RawJsonQueryUsageTests.cs
  tests/Tests/_VerifySnapshots/RawJsonQueryUsageTests.VerifyDescriptorJson.verified.txt
  tests/Tests/_VerifySnapshots/RawJsonQueryUsageTests.VerifyInitializerJson.verified.txt
Labels: enhancement, backport 8.1, 8.x, backport 8.2, backport 8.3, backport 8.4, backport 8.5, backport 8.6, v8.1.0, backport 8.7

#7372 Add support for GeoDistance and GeoPolygon queries.
  src/Elastic.Clients.Elasticsearch/_Generated/Types/QueryDsl/GeoDistanceQuery.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/QueryDsl/GeoPolygonPoints.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/QueryDsl/GeoPolygonQuery.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/QueryDsl/Query.g.cs
  tests/Tests/QueryDsl/Geo/GeoDistanceQueryUsageTests.cs
  tests/Tests/QueryDsl/Geo/GeoPolygonQueryUsageTests.cs
  tests/Tests/_VerifySnapshots/GeoDistanceQueryUsageTests.VerifyDescriptorJson.verified.txt
  tests/Tests/_VerifySnapshots/GeoDistanceQueryUsageTests.VerifyInitializerJson.verified.txt
  tests/Tests/_VerifySnapshots/GeoPolygonQueryUsageTests.VerifyDescriptorJson.verified.txt
  tests/Tests/_VerifySnapshots/GeoPolygonQueryUsageTests.VerifyInitializerJson.verified.txt
Labels: enhancement, backport 8.1, 8.x, backport 8.2, backport 8.3, backport 8.4, backport 8.5, backport 8.6, v8.1.0, backport 8.7

#7380 Add support for update aliases endpoint.
  src/Elastic.Clients.Elasticsearch/_Generated/Api/ApiUrlsLookup.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/IndexManagement/UpdateAliasesRequest.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/IndexManagement/UpdateAliasesResponse.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Client/ElasticsearchClient.Indices.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/IndexManagement/Action.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/IndexManagement/AddAction.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/IndexManagement/RemoveAction.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/IndexManagement/RemoveIndexAction.g.cs
  tests/Tests/IndexManagement/AliasManagement/UpdateAliasesRequestSerializationTests.cs
  tests/Tests/_VerifySnapshots/UpdateAliasesRequestSerializationTests.UpdateAliasesRequest_SerializesCorrectly.verified.txt
Labels: enhancement, backport 8.1, 8.x, backport 8.2, backport 8.3, backport 8.4, backport 8.5, backport 8.6, v8.1.0, backport 8.7

#7412 Update GitHub action versions in workflows.
  .github/workflows/auto-label.yml
  .github/workflows/integration-jobs.yml
  .github/workflows/license.yml
  .github/workflows/make-bump.yml
  .github/workflows/make-codegen.yml
  .github/workflows/make-release-notes.yml
  .github/workflows/stale-jobs.yml
  .github/workflows/test-jobs.yml
  .github/workflows/unified-release.yml
Labels: Infra, backport 8.0, backport 8.1, 8.x, backport 8.2, backport 8.3, backport 8.4, backport 8.5, backport 8.6, backport 8.7

#7429 Support weight score on FunctionScore.
  src/Elastic.Clients.Elasticsearch/Types/QueryDsl/FunctionScore.cs
  src/Elastic.Clients.Elasticsearch/Types/Scripting/InlineScript.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Aggregations/Aggregation.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Aggregations/InferenceConfig.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Core/Search/FieldSuggester.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Core/Search/SmoothingModel.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/IndexManagement/Action.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Ingest/InferenceConfig.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Ingest/Processor.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Ml/InferenceConfigCreate.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Ml/InferenceConfigUpdate.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Ml/TokenizationConfig.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/QueryDsl/FunctionScore.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/QueryDsl/Intervals.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/QueryDsl/IntervalsFilter.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/QueryDsl/IntervalsQuery.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/QueryDsl/Query.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/QueryDsl/SpanQuery.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/TransformManagement/PivotGroupBy.g.cs
  tests/Tests/Framework/EndpointTests/ApiTestBase.cs
  tests/Tests/QueryDsl/Compound/BoolQueryUsageTests.cs
  tests/Tests/QueryDsl/Compound/FunctionScoreQueryUsageTests.cs
  tests/Tests/_VerifySnapshots/FunctionScoreQueryUsageTests.VerifyDescriptorJson.verified.txt
  tests/Tests/_VerifySnapshots/FunctionScoreQueryUsageTests.VerifyInitializerJson.verified.txt
Labels: enhancement, backport 8.1, 8.x, backport 8.2, backport 8.3, backport 8.4, backport 8.5, backport 8.6, v8.1.0, backport 8.7

#7328 Fix typo.
  README.md
Labels: Docs

#7446 Fix byte properties in index stats types.
  src/Elastic.Clients.Elasticsearch/_Generated/Types/QueryCacheStats.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/SegmentsStats.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/StoreStats.g.cs
Labels: bug, backport 8.0, backport 8.1, 8.x, backport 8.2, backport 8.3, backport 8.4, backport 8.5, backport 8.6, backport 8.7, v8.0.8

#7456 Fix CompletionSuggester based on spec fixes.
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Core/Search/CompletionSuggester.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Core/Search/RegexOptions.g.cs
Labels: bug, backport 8.0, backport 8.1, 8.x, backport 8.2, backport 8.3, backport 8.4, backport 8.5, backport 8.6, backport 8.7, v8.0.8

#7467 Source serialization always sends fractional format for double and floats.
  exclusion.dic
  src/Elastic.Clients.Elasticsearch/Serialization/DefaultSourceSerializer.cs
  src/Elastic.Clients.Elasticsearch/Serialization/DoubleWithFractionalPortionConverter.cs
  src/Elastic.Clients.Elasticsearch/Serialization/FloatWithFractionalPortionConverter.cs
  src/Elastic.Clients.Elasticsearch/Serialization/JsonConstants.cs
  tests/Tests/Serialization/SerializerTestBase.cs
  tests/Tests/Serialization/SourceSerializationForNumericPropertiesTests.cs
Labels: enhancement, backport 8.0, backport 8.1, 8.x, backport 8.2, backport 8.3, backport 8.4, backport 8.5, backport 8.6, backport 8.7, v8.0.9

#7465 Add release notes for 8.0.8.
  docs/release-notes/release-notes-8.0.8.asciidoc
  docs/release-notes/release-notes.asciidoc
Labels: Docs, backport 8.0, backport 8.1, 8.x, backport 8.2, backport 8.3, backport 8.4, backport 8.5, backport 8.6, backport 8.7

#7495 Fix release notes for 8.0.8.
  docs/release-notes/release-notes-8.0.8.asciidoc
Labels: Docs, backport 8.0, backport 8.1, 8.x, backport 8.2, backport 8.3, backport 8.4, backport 8.5, backport 8.6

#7504 [8.7] [DOCS] Creates custom landing page for the .NET client book
  docs/index-custom-title-page.html
Labels: Docs
