Repository elastic/elasticsearch-net, pull requests merged in 2023-02, with the labels that each got.

#7223 Add Buildkite skeleton
  .buildkite/pipeline.yml
Labels: Infra, backport 8.0, backport 7.17, backport 8.1, backport 8.2, backport 8.3, backport 8.4, backport 8.5, backport 8.6, backport 8.7

#7253 Fix code-gen for enums with aliases.
  .github/workflows/integration-jobs.yml
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Enums/Enums.Aggregations.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Enums/Enums.IndexManagement.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Enums/Enums.Mapping.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Enums/Enums.NoNamespace.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Enums/Enums.QueryDsl.g.cs
  tests/Tests/IndexManagement/DataStreamManagement/GetDataStreamSerializationTests.cs
Labels: bug, backport 8.0, backport 8.1, 8.x, backport 8.2, backport 8.3, backport 8.4, backport 8.5, backport 8.6, backport 8.7, v8.0.6

#7262 Update to Elastic.Transport 0.4.7.
  benchmarks/Benchmarks/packages.lock.json
  benchmarks/Profiling/packages.lock.json
  src/Elastic.Clients.Elasticsearch.JsonNetSerializer/packages.lock.json
  src/Elastic.Clients.Elasticsearch/Elastic.Clients.Elasticsearch.csproj
  src/Elastic.Clients.Elasticsearch/packages.lock.json
  src/Playground/packages.lock.json
  tests/Tests.ClusterLauncher/packages.lock.json
  tests/Tests.Core/packages.lock.json
  tests/Tests.Domain/packages.lock.json
  tests/Tests/packages.lock.json
Labels: Infra, backport 8.0, backport 8.1, 8.x, backport 8.2, backport 8.3, backport 8.4, backport 8.5, backport 8.6, backport 8.7, v8.0.6
