Repository elastic/elasticsearch-net, pull requests merged in 2024-03, with the labels that each got.

#8045 [DOCS] Adds compatibility matrix to the docs and readme
  README.md
  docs/install.asciidoc
Labels: Docs, backport 8.12, backport 8.13

#8052 Update TargetFrameworks
  .buildkite/DockerFile
  .buildkite/pipeline.yml
  .buildkite/run-repository.ps1
  .buildkite/run-repository.sh
  .buildkite/run-tests.ps1
  .ci/DockerFile
  .ci/make.sh
  .ci/readme.md
  .ci/run-repository.ps1
  .ci/run-repository.sh
  .ci/run-tests.ps1
  .ci/test-matrix.yml
  .github/workflows/integration-jobs.yml
  .github/workflows/make-bump.yml
  .github/workflows/make-release-notes.yml
  .github/workflows/stale-jobs.yml
  .github/workflows/test-jobs.yml
  .github/workflows/unified-release.yml
  build/scripts/Benchmarking.fs
  build/scripts/Documentation.fs
  build/scripts/packages.lock.json
  build/scripts/scripts.fsproj
  global.json
  src/Elastic.Clients.Elasticsearch.JsonNetSerializer/Elastic.Clients.Elasticsearch.JsonNetSerializer.csproj
  src/Elastic.Clients.Elasticsearch.JsonNetSerializer/packages.lock.json
  src/Elastic.Clients.Elasticsearch.Serverless/Elastic.Clients.Elasticsearch.Serverless.csproj
  src/Elastic.Clients.Elasticsearch.Serverless/packages.lock.json
  src/Elastic.Clients.Elasticsearch/Elastic.Clients.Elasticsearch.csproj
  src/Elastic.Clients.Elasticsearch/packages.lock.json
  tests/Tests.ClusterLauncher/Tests.ClusterLauncher.csproj
  tests/Tests.ClusterLauncher/packages.lock.json
  tests/Tests/Tests.csproj
  tests/Tests/packages.lock.json
Labels: enhancement, 8.x, backport 8.12, backport 8.13, v8.13.0

#8053 Use JsonPropertyName in Ranges
  src/Elastic.Clients.Elasticsearch.Shared/Types/Ranges.cs
Labels: bug, 8.x, backport 8.12, backport 8.13, v8.13.0

#8051 Fix RawJsonString serialization
  src/Elastic.Clients.Elasticsearch.Shared/Core/RawJsonString.cs
  tests/Tests/_VerifySnapshots/ScriptParamsSerializationTests.SerializesRawJson.verified.txt
Labels: bug, 8.x, backport 8.12, backport 8.13, v8.13.0

#8059 Update `Elastic.Transport` dependency
  benchmarks/Benchmarks/packages.lock.json
  benchmarks/Profiling/packages.lock.json
  src/Elastic.Clients.Elasticsearch.JsonNetSerializer/packages.lock.json
  src/Elastic.Clients.Elasticsearch.Serverless/Client/ElasticsearchClient.cs
  src/Elastic.Clients.Elasticsearch.Serverless/Elastic.Clients.Elasticsearch.Serverless.csproj
  src/Elastic.Clients.Elasticsearch.Serverless/packages.lock.json
  src/Elastic.Clients.Elasticsearch.Shared/Core/Configuration/ElasticsearchClientSettings.cs
  src/Elastic.Clients.Elasticsearch/Client/ElasticsearchClient.cs
  src/Elastic.Clients.Elasticsearch/Elastic.Clients.Elasticsearch.csproj
  src/Elastic.Clients.Elasticsearch/packages.lock.json
  src/Playground/Playground.csproj
  src/Playground/Program.cs
  src/Playground/packages.lock.json
  tests/Tests.ClusterLauncher/packages.lock.json
  tests/Tests.Core/Client/FixedResponseClient.cs
  tests/Tests.Core/Extensions/TestConfigurationExtensions.cs
  tests/Tests.Core/Serialization/SerializationTester.cs
  tests/Tests.Core/packages.lock.json
  tests/Tests.Domain/Project.cs
  tests/Tests.Domain/packages.lock.json
  tests/Tests/ClientConcepts/HighLevel/Indexing/IndexingDocuments.doc.cs
  tests/Tests/ClientConcepts/HighLevel/Inference/IndexNameInference.doc.cs
  tests/Tests/ClientConcepts/HighLevel/Serialization/CustomSerialization.doc.cs
  tests/Tests/Document/Multiple/Bulk/BulkResponseParstingTests.cs
  tests/Tests/Document/Multiple/Bulk/BulkSourceDeserialize.cs
  tests/Tests/Document/Multiple/BulkAll/BulkAllRetryTests.cs
  tests/Tests/Documentation/ClientConcepts/Serialization/CustomSerializationTests.cs
  tests/Tests/Documentation/DocumentationTestBase.cs
  tests/Tests/Documentation/Usage/CrudExamplesTests.cs
  tests/Tests/Serialization/DefaultSourceSerializerTests.cs
  tests/Tests/Tests.csproj
  tests/Tests/packages.lock.json
Labels: dependencies, 8.x, backport 8.12, backport 8.13, v8.12.1
