Repository elastic/elasticsearch-net, pull requests merged in 2025-04, with the labels that each got.

#8486 Fix serialization of `Names`
  src/Elastic.Clients.Elasticsearch/_Shared/Core/UrlParameters/Name/Names.cs
Labels: 8.x, Category: Bug, Area: Client, backport 8.17, backport 8.x

#8490 [Docs] Restore troubleshooting content
  docs/reference/images/elasticsearch-client-net-api-capture-requests-localhost.png
  docs/reference/images/elasticsearch-client-net-api-capture-requests-remotehost.png
  docs/reference/images/elasticsearch-client-net-api-inspect-requests.png
  docs/reference/toc.yml
  docs/reference/troubleshoot/audit-trail.md
  docs/reference/troubleshoot/debug-information.md
  docs/reference/troubleshoot/debug-mode.md
  docs/reference/troubleshoot/debugging.md
  docs/reference/troubleshoot/index.md
  docs/reference/troubleshoot/logging-with-fiddler.md
  docs/reference/troubleshoot/logging-with-onrequestcompleted.md
  docs/reference/troubleshoot/logging.md
Labels: Area: Documentation, backport 9.0, 9.x

#8492 fix doc build
  docs/release-notes/breaking-changes.md
  docs/release-notes/index.md
Labels: backport 9.0

#8495 [DOCS] Specifies no known issue and deprecations for 9.0.0
  docs/release-notes/deprecations.md
  docs/release-notes/known-issues.md
Labels: Area: Documentation, skip-backport, 9.x

#8497 Address 9.0-preview feedback
  docs/release-notes/breaking-changes.md
  docs/release-notes/index.md
  docs/release-notes/known-issues.md
  src/Elastic.Clients.Elasticsearch/_Generated/Client/ElasticsearchClient.Cluster.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Client/ElasticsearchClient.Indices.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Client/ElasticsearchClient.Ml.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Client/ElasticsearchClient.Nodes.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Client/ElasticsearchClient.SearchableSnapshots.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Client/ElasticsearchClient.Security.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Client/ElasticsearchClient.Sql.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Client/ElasticsearchClient.TextStructure.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Client/ElasticsearchClient.g.cs
  src/Elastic.Clients.Elasticsearch/_Shared/Types/QueryDsl/RangeQuery.cs
Labels: backport 9.0, 9.x

#8498 [docs] Fix image paths for docs-assembler
  docs/reference/getting-started.md
  docs/reference/troubleshoot/logging-with-fiddler.md
Labels: Area: Documentation, backport 9.0

#8504 feat: add issue template for es 9.x client
  .github/ISSUE_TEMPLATE/bug-report-for-version-9-x.md
  .github/ISSUE_TEMPLATE/config.yml
Labels: skip-backport

#8505 9.0.1 fixes
  src/Elastic.Clients.Elasticsearch/_Generated/Api/MachineLearning/GetDataFrameAnalyticsStatsRequest.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/MachineLearning/GetDatafeedStatsRequest.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/MachineLearning/GetJobStatsRequest.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Core/RankEval/RankEvalMetricDiscountedCumulativeGain.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Core/RankEval/RankEvalMetricMeanReciprocalRank.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Core/RankEval/RankEvalMetricPrecision.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Core/RankEval/RankEvalMetricRecall.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Core/Search/InnerHits.g.cs
  src/Elastic.Clients.Elasticsearch/_Shared/Api/IndexManagement/GetAliasResponse.cs
Labels: Category: Bug, backport 9.0, 9.x
