Repository elastic/elasticsearch-net, pull requests merged in 2025-05, with the labels that each got.

#8530 Add (experimental) native AOT support
  src/Elastic.Clients.Elasticsearch/Elastic.Clients.Elasticsearch.csproj
  src/Elastic.Clients.Elasticsearch/_Shared/Api/SearchRequest.cs
  src/Elastic.Clients.Elasticsearch/_Shared/Client/ElasticsearchClient.Esql.cs
  src/Elastic.Clients.Elasticsearch/_Shared/Core/DateTime/DateMath/DateMath.cs
  src/Elastic.Clients.Elasticsearch/_Shared/Core/DateTime/DateMath/DateMathTime.cs
  src/Elastic.Clients.Elasticsearch/_Shared/Core/EnumValue.cs
  src/Elastic.Clients.Elasticsearch/_Shared/Core/Extensions/Extensions.cs
  src/Elastic.Clients.Elasticsearch/_Shared/Core/Extensions/TypeExtensions.cs
  src/Elastic.Clients.Elasticsearch/_Shared/Core/Infer/DynamicPropertyAccessor.cs
  src/Elastic.Clients.Elasticsearch/_Shared/Core/Infer/Id/IdResolver.cs
  src/Elastic.Clients.Elasticsearch/_Shared/Core/Infer/Id/IdsConverter.cs
  src/Elastic.Clients.Elasticsearch/_Shared/Core/Infer/Inferrer.cs
  src/Elastic.Clients.Elasticsearch/_Shared/Core/Infer/JoinFieldConverter.cs
  src/Elastic.Clients.Elasticsearch/_Shared/Core/Infer/RoutingResolver.cs
  src/Elastic.Clients.Elasticsearch/_Shared/Core/LazyJson.cs
  src/Elastic.Clients.Elasticsearch/_Shared/Core/UrlParameters/DataStreamNames/DataStreamName.cs
  src/Elastic.Clients.Elasticsearch/_Shared/Core/UrlParameters/DataStreamNames/DataStreamNames.cs
  src/Elastic.Clients.Elasticsearch/_Shared/Core/UrlParameters/Name/Name.cs
  src/Elastic.Clients.Elasticsearch/_Shared/Core/UrlParameters/Username/Username.cs
  src/Elastic.Clients.Elasticsearch/_Shared/Helpers/BulkAllObservable.cs
  src/Elastic.Clients.Elasticsearch/_Shared/Next/JsonReaderExtensions.cs
  src/Elastic.Clients.Elasticsearch/_Shared/Next/JsonSerializerOptionsExtensions.cs
  src/Elastic.Clients.Elasticsearch/_Shared/Serialization/DefaultRequestResponseSerializer.cs
  src/Elastic.Clients.Elasticsearch/_Shared/Serialization/DefaultSourceSerializer.cs
  src/Elastic.Clients.Elasticsearch/_Shared/Serialization/StringAliasConverter.cs
  src/Elastic.Clients.Elasticsearch/_Shared/Types/Aggregations/BucketsPath.cs
  src/Elastic.Clients.Elasticsearch/_Shared/Types/Aggregations/TermsExclude.cs
  src/Elastic.Clients.Elasticsearch/_Shared/Types/Aggregations/TermsInclude.cs
  src/Elastic.Clients.Elasticsearch/_Shared/Types/Core/Bulk/BulkUpdateBody.cs
  src/Elastic.Clients.Elasticsearch/_Shared/Types/Core/Bulk/ScriptedBulkUpdateBody.cs
  src/Elastic.Clients.Elasticsearch/_Shared/Types/Mapping/Properties.cs
  src/Elastic.Clients.Elasticsearch/_Shared/Types/Slices.cs
  src/Elastic.Clients.Elasticsearch/_Shared/Types/Sql/SqlRow.cs
  src/Elastic.Clients.Elasticsearch/_Shared/Types/Sql/SqlValue.cs
  src/Playground/Playground.csproj
Labels: Category: Feature, Area: Client, backport 9.0

#8527 [docs] Add `products` to `docset.yml`
  docs/docset.yml
Labels: Area: Documentation, skip-backport

#8532 Regenerate client
  src/Elastic.Clients.Elasticsearch/_Generated/Api/IndexManagement/DeleteTemplateRequest.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/IndexManagement/GetTemplateRequest.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/IndexManagement/PutTemplateRequest.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Api/Inference/PutJinaaiResponse.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Client/ElasticsearchClient.Indices.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Core/Search/ShardProfile.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Enums/Enums.Inference.g.cs
  src/Elastic.Clients.Elasticsearch/_Generated/Types/Snapshot/SnapshotShardFailure.g.cs
Labels: backport 9.0, 9.x

#8534 Update compatibility section in README
  README.md
Labels: backport 9.0

#8537 Update documentation
  README.md
  docs/reference/_options_on_elasticsearchclientsettings.md
  docs/reference/aggregations.md
  docs/reference/configuration.md
  docs/reference/connecting.md
  docs/reference/examples.md
  docs/reference/getting-started.md
  docs/reference/index.md
  docs/reference/installation.md
  docs/reference/mappings.md
  docs/reference/migration-guide.md
  docs/reference/query.md
  docs/reference/recommendations.md
  docs/reference/serialization.md
  docs/reference/source-serialization.md
  docs/reference/toc.yml
  docs/reference/using-net-client.md
Labels: Area: Documentation, Category: Enhancement, backport 9.0, 9.x

#8549 Update `Elastic.Transport`
  src/Elastic.Clients.Elasticsearch/Elastic.Clients.Elasticsearch.csproj
  src/Playground/Playground.csproj
Labels: 8.x, Area: Transport, Category: Bug, backport 8.19, backport 9.0, 9.x
