Repository elastic/elasticsearch-net, pull requests merged in 2025-03, with the labels that each got.

#8478 [docs] Miscellaneous docs clean up
  docs/docset.yml
  docs/reference/getting-started.md
  docs/reference/images/create-api-key.png
  docs/reference/images/es-endpoint.jpg
Labels: Area: Documentation, backport 9.0

#8480 Updates navigation titles and descriptions for release notes
  docs/release-notes/breaking-changes.md
  docs/release-notes/deprecations.md
  docs/release-notes/index.md
  docs/release-notes/known-issues.md
Labels: Area: Documentation, skip-backport

#8482 [docs] Add missing mapped pages
  docs/release-notes/breaking-changes.md
Labels: Area: Documentation
